/*
 * Book Vault Quiz — Obsidian Plugin
 * ---------------------------------------------------------------------------
 * Parses Quiz.md files, renders interactive multiple-choice quizzes with
 * real-time scoring, tracks per-book attempt history, and shows a vault-wide
 * progress dashboard via the `book-vault-quiz-dashboard` code block.
 *
 * Quiz.md format expected (generated by automation/engines/quiz.py):
 *
 *   ```quiz
 *   book: Make-It-Stick
 *   title: Make It Stick Quiz
 *   ---
 *   Q1. What does retrieval practice do?
 *   A) Strengthens memory through effortful recall
 *   B) Works best when combined with re-reading
 *   C) Is only effective for factual knowledge
 *   D) Has no effect on long-term retention
 *   ANSWER: A
 *   EXPLANATION: Retrieval practice strengthens the neural pathways...
 *
 *   Q2. ...
 *   ```
 *
 * Also renders `book-vault-quiz-dashboard` blocks as a full progress table.
 */

const DEFAULT_DATA = { attempts: {} };

class BookVaultQuizPlugin extends Plugin {

  async onload() {
    await this.loadData_();

    // ── Render interactive quiz blocks ──────────────────────────────────────
    this.registerMarkdownCodeBlockProcessor("quiz", (source, el, ctx) => {
      this.renderQuiz(source.trim(), el, ctx);
    });

    // ── Render interactive flashcard decks ──────────────────────────────────
    this.registerMarkdownCodeBlockProcessor("flashcards", (source, el, ctx) => {
      this.renderFlashcards(source.trim(), el, ctx);
    });

    // ── Render dashboard blocks ─────────────────────────────────────────────
    this.registerMarkdownCodeBlockProcessor("book-vault-quiz-dashboard", (source, el, ctx) => {
      this.renderDashboard(el);
    });

    // ── Ribbon icon to open dashboard ───────────────────────────────────────
    this.addRibbonIcon("graduation-cap", "Book Vault Quiz Dashboard", () => {
      this.openDashboardNote();
    });

    // ── Command: open dashboard ─────────────────────────────────────────────
    this.addCommand({
      id: "open-quiz-dashboard",
      name: "Open Quiz Dashboard",
      callback: () => this.openDashboardNote(),
    });

    // ── Command: reset all scores ───────────────────────────────────────────
    this.addCommand({
      id: "reset-quiz-scores",
      name: "Reset All Quiz Scores",
      callback: async () => {
        this.pluginData.attempts = {};
        await this.saveData_(this.pluginData);
        new Notice("All quiz scores have been reset.");
      },
    });

    console.log("Book Vault Quiz plugin loaded.");
  }

  onunload() {
    console.log("Book Vault Quiz plugin unloaded.");
  }

  // ── Data persistence ───────────────────────────────────────────────────────

  async loadData_() {
    const saved = await this.loadData();
    this.pluginData = Object.assign({}, DEFAULT_DATA, saved || {});
    if (!this.pluginData.attempts) this.pluginData.attempts = {};
  }

  async saveData_(data) {
    this.pluginData = data;
    await this.saveData(data);
  }

  // ── Quiz parser ────────────────────────────────────────────────────────────

  parseQuiz(source) {
    const lines = source.split("\n");
    let bookSlug = "";
    let quizTitle = "";
    let inHeader = true;

    const questions = [];
    let current = null;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();

      // Header section (before first blank line or first Q)
      if (inHeader) {
        if (line.startsWith("book:")) { bookSlug = line.replace("book:", "").trim(); continue; }
        if (line.startsWith("title:")) { quizTitle = line.replace("title:", "").trim(); continue; }
        if (line === "---" || /^Q\d+\./.test(line)) { inHeader = false; }
        if (inHeader) continue;
      }

      // Question line: Q1. text  or  ## Q1. text
      if (/^(##\s*)?Q\d+[.)]\s+/.test(line)) {
        if (current) questions.push(current);
        current = {
          text: line.replace(/^(##\s*)?Q\d+[.)]\s+/, "").trim(),
          options: [],
          answer: "",
          explanation: "",
        };
        continue;
      }

      if (!current) continue;

      // Option line: A) text  or  A. text  or  - A) text
      const optMatch = line.match(/^[-–]?\s*([A-D])[.)]\s+(.+)/);
      if (optMatch) {
        current.options.push({ label: optMatch[1], text: optMatch[2].trim() });
        continue;
      }

      // Answer line
      if (/^ANSWER\s*:/i.test(line)) {
        current.answer = line.replace(/^ANSWER\s*:\s*/i, "").trim().toUpperCase();
        continue;
      }

      // Explanation line
      if (/^EXPLANATION\s*:/i.test(line)) {
        current.explanation = line.replace(/^EXPLANATION\s*:\s*/i, "").trim();
        continue;
      }
    }

    if (current) questions.push(current);
    return { bookSlug, quizTitle: quizTitle || bookSlug || "Quiz", questions };
  }

  // ── Quiz renderer ──────────────────────────────────────────────────────────

  renderQuiz(source, container, ctx) {
    const { bookSlug, quizTitle, questions } = this.parseQuiz(source);

    if (questions.length === 0) {
      container.createEl("p", {
        text: "⚠️ No questions found. Check the Quiz.md format.",
        cls: "bvq-error",
      });
      return;
    }

    container.addClass("bvq-container");

    // Header
    const header = container.createEl("div", { cls: "bvq-header" });
    header.createEl("h2", { text: `📝 ${quizTitle}`, cls: "bvq-title" });
    const meta = header.createEl("div", { cls: "bvq-meta" });
    meta.createEl("span", { text: `${questions.length} questions`, cls: "bvq-badge" });

    // State
    const state = {
      answered: new Array(questions.length).fill(null),   // null | 'A'|'B'|'C'|'D'
      revealed: new Array(questions.length).fill(false),
      submitted: false,
    };

    // Score bar (shown after submit)
    const scoreBar = container.createEl("div", { cls: "bvq-scorebar bvq-hidden" });

    // Questions
    const qContainer = container.createEl("div", { cls: "bvq-questions" });

    questions.forEach((q, qi) => {
      const qEl = qContainer.createEl("div", { cls: "bvq-question" });

      // Question text
      qEl.createEl("p", {
        text: `${qi + 1}. ${q.text}`,
        cls: "bvq-question-text",
      });

      // Options
      const optList = qEl.createEl("div", { cls: "bvq-options" });
      q.options.forEach((opt) => {
        const btn = optList.createEl("button", {
          cls: "bvq-option",
          attr: { "data-qi": qi, "data-label": opt.label },
        });
        btn.createEl("span", { text: `${opt.label})`, cls: "bvq-opt-label" });
        btn.createEl("span", { text: ` ${opt.text}`, cls: "bvq-opt-text" });

        btn.addEventListener("click", () => {
          if (state.submitted) return;
          // Deselect others
          optList.querySelectorAll(".bvq-option").forEach((b) => b.removeClass("bvq-selected"));
          btn.addClass("bvq-selected");
          state.answered[qi] = opt.label;
        });
      });

      // Explanation (hidden until reveal)
      if (q.explanation) {
        const expEl = qEl.createEl("div", { cls: "bvq-explanation bvq-hidden" });
        expEl.createEl("strong", { text: "💡 " });
        expEl.appendText(q.explanation);
        state[`exp_${qi}`] = expEl;
      }
    });

    // Submit / Retry buttons
    const actions = container.createEl("div", { cls: "bvq-actions" });
    const submitBtn = actions.createEl("button", { text: "✅ Submit Quiz", cls: "bvq-btn bvq-btn-primary" });
    const retryBtn = actions.createEl("button", { text: "🔄 Retry", cls: "bvq-btn bvq-btn-secondary bvq-hidden" });

    submitBtn.addEventListener("click", async () => {
      // Mark unanswered
      const unanswered = state.answered.filter((a) => a === null).length;
      if (unanswered > 0) {
        new Notice(`Please answer all questions. ${unanswered} remaining.`);
        return;
      }

      state.submitted = true;
      submitBtn.addClass("bvq-hidden");
      retryBtn.removeClass("bvq-hidden");

      // Score
      let correct = 0;
      questions.forEach((q, qi) => {
        const isCorrect = state.answered[qi] === q.answer;
        if (isCorrect) correct++;

        // Color options
        qContainer.querySelectorAll(`[data-qi="${qi}"]`).forEach((btn) => {
          const lbl = btn.getAttribute("data-label");
          if (lbl === q.answer) btn.addClass("bvq-correct");
          else if (lbl === state.answered[qi]) btn.addClass("bvq-wrong");
          btn.setAttribute("disabled", "true");
        });

        // Show explanation
        if (state[`exp_${qi}`]) state[`exp_${qi}`].removeClass("bvq-hidden");
      });

      const pct = Math.round((correct / questions.length) * 100);
      const grade = pct >= 90 ? "🏆 Excellent" : pct >= 70 ? "✅ Good" : pct >= 50 ? "⚠️ Needs Work" : "❌ Review Required";

      // Score bar
      scoreBar.empty();
      scoreBar.removeClass("bvq-hidden");
      const scoreText = scoreBar.createEl("div", { cls: "bvq-score-text" });
      scoreText.createEl("span", { text: `${grade} — `, cls: "bvq-grade" });
      scoreText.createEl("strong", { text: `${correct} / ${questions.length} correct (${pct}%)` });

      const barOuter = scoreBar.createEl("div", { cls: "bvq-bar-outer" });
      const barInner = barOuter.createEl("div", {
        cls: `bvq-bar-inner ${pct >= 70 ? "bvq-bar-pass" : "bvq-bar-fail"}`,
      });
      barInner.style.width = `${pct}%`;

      // Persist
      const slug = bookSlug || (ctx.sourcePath || "unknown").split("/").slice(-2, -1)[0];
      const now = new Date().toISOString();
      if (!this.pluginData.attempts[slug]) this.pluginData.attempts[slug] = [];
      this.pluginData.attempts[slug].push({
        date: now,
        score: correct,
        total: questions.length,
        pct,
        file: ctx.sourcePath,
      });
      await this.saveData_(this.pluginData);

      // Scroll to score
      scoreBar.scrollIntoView({ behavior: "smooth" });
    });

    retryBtn.addEventListener("click", () => {
      // Full re-render
      container.empty();
      this.renderQuiz(source, container, ctx);
    });
  }

  // ── Dashboard renderer ─────────────────────────────────────────────────────

  renderDashboard(container) {
    container.addClass("bvq-dashboard");
    container.createEl("h2", { text: "📊 Quiz Progress Dashboard", cls: "bvq-dash-title" });

    const attempts = this.pluginData.attempts || {};
    const slugs = Object.keys(attempts).sort();

    if (slugs.length === 0) {
      container.createEl("p", { text: "No quiz attempts yet. Open a Quiz.md file and take your first quiz!", cls: "bvq-empty" });
      return;
    }

    // Summary stats
    let totalAttempts = 0;
    let totalCorrect = 0;
    let totalQ = 0;
    slugs.forEach((slug) => {
      attempts[slug].forEach((a) => {
        totalAttempts++;
        totalCorrect += a.score;
        totalQ += a.total;
      });
    });
    const overallPct = totalQ > 0 ? Math.round((totalCorrect / totalQ) * 100) : 0;

    const stats = container.createEl("div", { cls: "bvq-dash-stats" });
    const statItems = [
      { label: "Books Quizzed", value: slugs.length },
      { label: "Total Attempts", value: totalAttempts },
      { label: "Overall Score", value: `${overallPct}%` },
      { label: "Questions Answered", value: totalQ },
    ];
    statItems.forEach((s) => {
      const card = stats.createEl("div", { cls: "bvq-stat-card" });
      card.createEl("div", { text: String(s.value), cls: "bvq-stat-value" });
      card.createEl("div", { text: s.label, cls: "bvq-stat-label" });
    });

    // Per-book table
    const table = container.createEl("table", { cls: "bvq-dash-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    ["Book", "Attempts", "Best Score", "Last Score", "Last Attempt"].forEach((h) => {
      headerRow.createEl("th", { text: h });
    });

    const tbody = table.createEl("tbody");
    slugs.forEach((slug) => {
      const bookAttempts = attempts[slug];
      const best = Math.max(...bookAttempts.map((a) => a.pct));
      const last = bookAttempts[bookAttempts.length - 1];
      const lastDate = new Date(last.date).toLocaleDateString();
      const badgeClass = last.pct >= 70 ? "bvq-badge-pass" : "bvq-badge-fail";

      const row = tbody.createEl("tr");
      row.createEl("td", { text: slug.replace(/-/g, " "), cls: "bvq-book-name" });
      row.createEl("td", { text: String(bookAttempts.length) });
      row.createEl("td", { text: `${best}%`, cls: best >= 70 ? "bvq-pass" : "bvq-fail" });
      const lastTd = row.createEl("td");
      lastTd.createEl("span", { text: `${last.pct}%`, cls: `bvq-badge ${badgeClass}` });
      row.createEl("td", { text: lastDate, cls: "bvq-date" });
    });

    // Reset button
    const resetBtn = container.createEl("button", { text: "🗑️ Reset All Scores", cls: "bvq-btn bvq-btn-danger" });
    resetBtn.addEventListener("click", async () => {
      if (confirm("Reset all quiz scores? This cannot be undone.")) {
        this.pluginData.attempts = {};
        await this.saveData_(this.pluginData);
        container.empty();
        this.renderDashboard(container);
        new Notice("All scores reset.");
      }
    });
  }

  // ── Flashcard Deck Renderer ────────────────────────────────────────────────
  parseFlashcards(source) {
    const cards = [];
    const lines = source.split(/\r?\n/);
    let currentQ = "";
    let currentA = "";

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      if (!line) continue;

      // Format 1: Front :: Back
      if (line.includes("::")) {
        const parts = line.split("::");
        if (parts.length >= 2) {
          cards.push({
            q: parts[0].trim().replace(/^[Q0-9.:\s-]+/i, ""),
            a: parts.slice(1).join("::").trim().replace(/^[A0-9.:\s-]+/i, ""),
          });
          continue;
        }
      }

      // Format 2: Q: ... / A: ...
      if (/^Q(?:uestion)?\s*[\d.:-]*\s*(.+)/i.test(line)) {
        if (currentQ && currentA) {
          cards.push({ q: currentQ, a: currentA });
          currentQ = "";
          currentA = "";
        }
        currentQ = line.replace(/^Q(?:uestion)?\s*[\d.:-]*\s*/i, "").trim();
      } else if (/^A(?:nswer)?\s*[\d.:-]*\s*(.+)/i.test(line)) {
        currentA = line.replace(/^A(?:nswer)?\s*[\d.:-]*\s*/i, "").trim();
      } else if (currentA) {
        currentA += " " + line;
      } else if (currentQ) {
        currentQ += " " + line;
      }
    }

    if (currentQ && currentA) {
      cards.push({ q: currentQ, a: currentA });
    }

    return cards;
  }

  renderFlashcards(source, container, ctx) {
    container.empty();
    const cards = this.parseFlashcards(source);

    if (cards.length === 0) {
      container.createEl("p", { text: "⚠️ No flashcards found in block. Use 'Q: ... \\n A: ...' or 'Front :: Back' format." });
      return;
    }

    let currentIndex = 0;
    let isFlipped = false;
    let masteredCount = 0;

    const deckEl = container.createEl("div", { cls: "bvf-container" });

    // Header
    const header = deckEl.createEl("div", { cls: "bvf-header" });
    const titleEl = header.createEl("h3", { text: "🧠 Active Recall Flashcards", cls: "bvf-title" });
    const counterEl = header.createEl("span", { text: `Card 1 / ${cards.length}`, cls: "bvf-counter" });

    // Progress Bar
    const progressTrack = deckEl.createEl("div", { cls: "bvf-progress-track" });
    const progressBar = progressTrack.createEl("div", { cls: "bvf-progress-fill" });
    progressBar.style.width = `${(1 / cards.length) * 100}%`;

    // Card Body
    const cardEl = deckEl.createEl("div", { cls: "bvf-card" });
    const cardContent = cardEl.createEl("div", { cls: "bvf-card-content" });
    const cardLabel = cardContent.createEl("div", { text: "QUESTION", cls: "bvf-card-label" });
    const cardText = cardContent.createEl("div", { text: cards[0].q, cls: "bvf-card-text" });
    const hintEl = cardContent.createEl("div", { text: "👆 Click to reveal answer", cls: "bvf-card-hint" });

    const updateCard = () => {
      isFlipped = false;
      const card = cards[currentIndex];
      counterEl.textContent = `Card ${currentIndex + 1} / ${cards.length}`;
      progressBar.style.width = `${((currentIndex + 1) / cards.length) * 100}%`;

      cardEl.classList.remove("bvf-flipped");
      cardLabel.textContent = "QUESTION";
      cardLabel.className = "bvf-card-label";
      cardText.textContent = card.q;
      hintEl.textContent = "👆 Click card or Spacebar to reveal answer";
    };

    const flipCard = () => {
      isFlipped = !isFlipped;
      const card = cards[currentIndex];
      if (isFlipped) {
        cardEl.classList.add("bvf-flipped");
        cardLabel.textContent = "ANSWER";
        cardLabel.className = "bvf-card-label bvf-label-answer";
        cardText.textContent = card.a;
        hintEl.textContent = "👆 Click card to flip back";
      } else {
        cardEl.classList.remove("bvf-flipped");
        cardLabel.textContent = "QUESTION";
        cardLabel.className = "bvf-card-label";
        cardText.textContent = card.q;
        hintEl.textContent = "👆 Click card to reveal answer";
      }
    };

    cardEl.addEventListener("click", flipCard);

    // Controls
    const controls = deckEl.createEl("div", { cls: "bvf-controls" });
    const prevBtn = controls.createEl("button", { text: "⬅ Previous", cls: "bvf-btn bvf-btn-secondary" });
    const flipBtn = controls.createEl("button", { text: "🔄 Flip Card", cls: "bvf-btn bvf-btn-accent" });
    const nextBtn = controls.createEl("button", { text: "Next ➡", cls: "bvf-btn bvf-btn-secondary" });

    prevBtn.addEventListener("click", () => {
      if (currentIndex > 0) {
        currentIndex--;
        updateCard();
      }
    });

    flipBtn.addEventListener("click", flipCard);

    nextBtn.addEventListener("click", () => {
      if (currentIndex < cards.length - 1) {
        currentIndex++;
        updateCard();
      } else {
        // Finish deck
        cardLabel.textContent = "🎉 DECK COMPLETED";
        cardLabel.className = "bvf-card-label bvf-label-finish";
        cardText.textContent = `You reviewed all ${cards.length} cards in this deck!`;
        hintEl.textContent = "";
        flipBtn.style.display = "none";
        nextBtn.textContent = "🔄 Review Again";
        nextBtn.onclick = () => {
          currentIndex = 0;
          flipBtn.style.display = "";
          nextBtn.textContent = "Next ➡";
          updateCard();
        };
      }
    });
  }

  async openDashboardNote() {
    const dashPath = "Quiz-Dashboard.md";
    let file = this.app.vault.getAbstractFileByPath(dashPath);
    if (!file) {
      file = await this.app.vault.create(dashPath, "# 📊 Book Vault Quiz Dashboard\n\n```book-vault-quiz-dashboard\n```\n");
    }
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(file);
  }
}

module.exports = BookVaultQuizPlugin;
