from __future__ import annotations

import argparse
import contextlib
import os
import re
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from ..core.config import ConfigurationError, ROOT, load_settings
from ..core.length import length_label, word_bounds
from ..core.manifest import category_folder, load_manifest
from ..core.validate import validate_note
from ..research.research import load_research, save_research, search_book, source_bundle
from .llm_client import build_providers, configure_limiter, generate_markdown
from .prompts import TEMPLATE_VERSION, build_audio_tts_prompt, build_modular_reading_prompt


def _pillar_dirs() -> dict[str, str]:
    """Pillar display name -> md folder (generated by automation/curriculum.py)."""
    try:
        from ..core.taxonomy import PILLAR_DIRS

    except ImportError as exc:
        raise SystemExit(
            "automation/taxonomy.py is missing — run `python -m automation.curriculum` first."
        ) from exc
    return {name: f"md/{folder}" for name, folder in PILLAR_DIRS.items()}


LOCK_PATH = ROOT / "automation" / ".pipeline.lock"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate researched book notes with Zen, NVIDIA, or g4f from Python.")
    parser.add_argument("--manifest", type=Path, default=ROOT / "automation" / "manifest.csv")
    parser.add_argument("--slug")
    parser.add_argument("--limit", type=int, default=None, help="Number of PENDING books to process per run (defaults to worker count).")
    parser.add_argument("--workers", type=int, default=None, help="Parallel worker threads (default: PIPELINE_WORKERS, 1 = sequential).")

    parser.add_argument("--force", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--no-web", action="store_true", help="Create a draft without web research.")
    parser.add_argument(
        "--loop",
        action="store_true",
        help="Keep running until the manifest has no pending books (reloads the manifest each pass).",
    )
    return parser.parse_args()


def target_path(book: dict[str, str]) -> Path:
    try:
        folder = _pillar_dirs()[book["pillar"]]
    except KeyError as exc:
        raise ValueError(f"No pillar-folder mapping for {book['pillar']}") from exc
    return ROOT / folder / category_folder(book["pillar"], book["category"]) / book["slug"]


def complete(path: Path) -> bool:
    if path.is_dir():
        readme = path / "README.md"
        audio = path / "Audio-Listening-Edition.md"
        return readme.exists() and audio.exists()
    if path.is_file():
        return bool(re.search(r"^status:\s*complete\s*$", path.read_text(encoding="utf-8"), re.M))
    return False


def is_pending(book: dict[str, str], force: bool) -> bool:
    return force or not complete(target_path(book))


def navigation_for(book: dict[str, str], books: list[dict[str, str]]) -> dict[str, str]:
    """Build the previous / pillar / next wikilink lines for a book."""
    pillar_folder = _pillar_dirs()[book["pillar"]]
    pillar_label = book["pillar"].replace(";", ",")
    pillar_link = f"[[{pillar_folder}/README|{pillar_label}]]"
    same = [b for b in books if b["pillar"] == book["pillar"]]
    index = next(i for i, b in enumerate(same) if b["slug"] == book["slug"])
    prev = same[index - 1] if index > 0 else None
    nxt = same[index + 1] if index < len(same) - 1 else None
    return {
        "prev": f"[[{prev['slug']}/README|{prev['title']}]]" if prev else pillar_link,
        "category": pillar_link,
        "next": f"[[{nxt['slug']}/README|{nxt['title']}]]" if nxt else pillar_link,
    }


def _clean_markdown(text: str) -> str:
    """Ensure output is pure Markdown without outer wrapping fences."""
    text = text.strip()
    if text.startswith("```markdown"):
        text = text[11:].lstrip("\r\n")
        if text.endswith("```"):
            text = text[:-3].rstrip()
    elif text.startswith("```md"):
        text = text[5:].lstrip("\r\n")
        if text.endswith("```"):
            text = text[:-3].rstrip()
    elif text.startswith("```") and not text.startswith("```mermaid") and not text.startswith("---"):
        text = text[3:].lstrip("\r\n")
        if text.endswith("```"):
            text = text[:-3].rstrip()
    return text.rstrip() + "\n"


def _unpack_files(raw_text: str, default_name: str = "README.md") -> dict[str, str]:
    """Parse multi-file output formatted with === FILE: name.md === markers."""
    pattern = re.compile(r"^===\s*FILE:\s*([^\s=]+)\s*===\s*$", re.MULTILINE)
    matches = list(pattern.finditer(raw_text))
    if not matches:
        return {default_name: raw_text}
    files: dict[str, str] = {}
    for i, match in enumerate(matches):
        filename = match.group(1).strip()
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(raw_text)
        files[filename] = raw_text[start:end].strip()
    return files




def _pid_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False


def _recorded_holder(path: Path) -> int | None:
    """Read the holder PID from the first line of a lock file."""
    try:
        first = path.read_text(encoding="ascii").splitlines()[0].strip()
        return int(first) if first.isdigit() else None
    except (OSError, ValueError, IndexError):
        return None


@contextlib.contextmanager
def pipeline_lock(path: Path = LOCK_PATH):
    """Prevent two pipeline instances from generating the same book twice.

    The lock file records the holder PID. OS-level locks release automatically
    when the holder process dies; the PID check additionally breaks a stale
    lock if the recorded holder is no longer alive, so long-running automation
    can always resume after crashes.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    handle = None

    def _acquire() -> bool:
        nonlocal handle
        if sys.platform.startswith("win"):
            import msvcrt

            h = open(path, "a+b")
            try:
                if h.seek(0, os.SEEK_END) == 0:
                    h.write(b"0")
                    h.flush()
                h.seek(0)
                msvcrt.locking(h.fileno(), msvcrt.LK_NBLCK, 1)
            except OSError:
                h.close()
                return False
            h.seek(0)
            h.write(f"{os.getpid()}\n".encode("ascii"))
            h.flush()
            handle = h  # left open; released in _release()
            return True
        else:
            import fcntl

            h = open(path, "w")
            try:
                fcntl.flock(h, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except OSError:
                h.close()
                return False
            h.seek(0)
            h.write(f"{os.getpid()}\n")
            h.flush()
            handle = h
            return True

    def _release() -> None:
        nonlocal handle
        if handle is None:
            return
        try:
            if sys.platform.startswith("win"):
                import msvcrt

                handle.seek(0)
                msvcrt.locking(handle.fileno(), msvcrt.LK_UNLCK, 1)
        except OSError:
            pass
        try:
            handle.close()
        except OSError:
            pass
        handle = None

    for attempt in range(2):
        if _acquire():
            break
        holder = _recorded_holder(path)
        if holder is not None and not _pid_alive(holder):
            print(f"  STALE LOCK: removing lock from dead PID {holder}.", flush=True)
            try:
                path.unlink()
            except OSError:
                pass
            if attempt == 0:
                continue
        raise SystemExit(f"  ERROR: another pipeline instance is running (lock held by PID {holder}). {path}")
    try:
        yield
    finally:
        _release()


def _words(text: str) -> int:
    return len(re.findall(r"\b[\w’'-]+\b", text))


def process_one(book: dict[str, str], all_books: list[dict[str, str]], args: argparse.Namespace, rel_map: dict[str, set[str]], worker: int = 0) -> None:
    settings = load_settings()
    destination = target_path(book)
    say = lambda msg: print(f"[w{worker}] {msg}", flush=True)
    if complete(destination) and not args.force:
        say(f"  SKIP: already complete -> {destination.relative_to(ROOT)}")
        return

    from ..core.graph import format_graph_context

    graph_context = format_graph_context(book, all_books, rel_map=rel_map)


    # Content-adaptive length: the summary target follows the book's own
    # profile (book type, priority, difficulty, pillar) instead of one
    # fixed gate for everything.
    min_words, max_words = word_bounds(book)

    # ---- Step 1: web research -------------------------------------------------
    say(f"  [1/4] research: searching the web for '{book['title']}' by {book['author']}")
    sources = []
    search_retries = 3
    for search_attempt in range(search_retries):
        try:
            sources = search_book(book, settings)
            save_research(ROOT / "automation" / "research" / f"{book['slug']}.json", book, sources)
            say(f"        sources kept: {len(sources)} (deduplicated, publisher/author sites first)")
            break
        except Exception as exc:  # retry the whole research block
            if search_attempt < search_retries - 1:
                import time
                wait = 3 * (2 ** search_attempt)
                say(f"        RESEARCH FAILED (attempt {search_attempt + 1}/{search_retries}): {exc}")
                say(f"        retrying research in {wait}s...")
                time.sleep(wait)
            else:
                if not args.no_web:
                    say(f"        RESEARCH FAILED after {search_retries} attempts: {exc}")
                    say("        skipping this book; the run continues with the next one.")
                    return
                say(f"        OFFLINE DRAFT: {exc}")

    # ---- Step 2: Dual-Edition Generation ---------------------------------------
    prompt_book = dict(book)
    prompt_book["category"] = book["category"].replace(";", ",")
    nav = navigation_for(book, all_books)
    say(f"  [2/3] generating dual-edition summary (reading + audio TTS)")

    from .prompts import build_modular_reading_prompt, build_audio_tts_prompt

    # 1. Modular Reading Edition
    try:
        reading_raw = generate_markdown(
            settings,
            build_modular_reading_prompt(
                prompt_book,
                source_bundle(sources) if sources else "No web sources available.",
                args.no_web,
                nav=nav,
                graph=graph_context,
                min_words=min_words,
                max_words=max_words,
            ),
            cache_key=f"book-reading-{book['slug']}-{TEMPLATE_VERSION}",
        )
        files = _unpack_files(reading_raw, default_name="README.md")
    except Exception as exc:
        say(f"        GENERATION FAILED (reading edition): {exc}")
        return

    # 2. Audio Listening Edition
    try:
        audio_raw = generate_markdown(
            settings,
            build_audio_tts_prompt(
                prompt_book,
                source_bundle(sources) if sources else "No web sources available.",
            ),
            cache_key=f"book-audio-{book['slug']}-{TEMPLATE_VERSION}",
        )
        files["Audio-Listening-Edition.md"] = audio_raw
    except Exception as exc:
        say(f"        AUDIO TTS NOTE: {exc} (saving reading edition)")

    # ---- Step 3: Atomic Multi-File Write ---------------------------------------
    destination.mkdir(parents=True, exist_ok=True)
    total_words = 0
    for filename, text in files.items():
        clean = _clean_markdown(text)
        out_file = destination / filename
        tmp_file = destination / f"{filename}.tmp"
        tmp_file.write_text(clean, encoding="utf-8")
        tmp_file.replace(out_file)
        total_words += _words(clean)

    say(f"  [3/3] WROTE {len(files)} files to {destination.relative_to(ROOT)} ({total_words} total words across Reading & Audio editions)")



def run() -> int:

    args = parse_args()
    settings = load_settings()
    if args.dry_run:
        books = load_manifest(args.manifest)
        if args.slug:
            books = [book for book in books if book["slug"] == args.slug]
        pending = [book for book in books if is_pending(book, args.force)]
        print(f"Manifest rows: {len(books)} | Pending: {len(pending)}")
        for book in books:
            state = "SKIP" if book not in pending else "PLAN"
            lo, hi = word_bounds(book)
            print(f"{state} {book['title']} -> {target_path(book).relative_to(ROOT)} [{lo}-{hi} words]")
        print("DRY RUN: no API calls made.")
        return 0

    workers = max(1, args.workers or settings.pipeline_workers)
    configure_limiter(settings.llm_calls_per_minute)

    with pipeline_lock():
        providers = build_providers(settings)
        chain = " -> ".join(f"{p.label} ({p.model})" for p in providers)
        print("=" * 70, flush=True)
        print("PIPELINE START", flush=True)
        print(f"  manifest   : {args.manifest}", flush=True)
        print(f"  providers  : {chain} + g4f auto (last resort)", flush=True)
        print(f"  length     : content-adaptive per book (type/priority/difficulty), 1500–15000 words", flush=True)
        print(f"  workers    : {workers} thread(s) — shared rate cap {settings.llm_calls_per_minute} calls/min, no artificial sleeps", flush=True)
        print(f"  backoff    : exponential + jitter on every 429/5xx/network error", flush=True)
        print(f"  loop mode  : {'yes (continuous, no sleep between passes)' if args.loop else 'no (single pass)'}", flush=True)
        print("=" * 70, flush=True)

        all_manifest_books = load_manifest(args.manifest)
        from ..core.graph import related_map
        print("  precomputing knowledge-graph map (outgoing + incoming links)...", flush=True)

        rel_map = related_map(all_manifest_books)
        print(f"  graph ready: {sum(len(v) for v in rel_map.values())} total edges across {len(rel_map)} books", flush=True)

        while True:
            books = load_manifest(args.manifest)
            if args.slug:
                books = [book for book in books if book["slug"] == args.slug]
            pending = [book for book in books if is_pending(book, args.force)]
            if not pending:
                print("ALL MANIFEST BOOKS COMPLETE. Nothing left to generate.", flush=True)
                return 0
            batch_size = args.limit if args.limit is not None else (workers if (args.loop or workers > 1) else 1)
            selected = pending[: max(1, batch_size)]
            print(f"\nPASS: {len(selected)} book(s) to process ({len(pending)} pending of {len(books)} total)", flush=True)

            if workers > 1:
                with ThreadPoolExecutor(max_workers=workers, thread_name_prefix="book") as pool:
                    futures = {}
                    for index, book in enumerate(selected, start=1):
                        print(f"\n--- BOOK {index}/{len(selected)} | #{book['number']} | {book['title']} | {book['pillar']} > {book['category']} ---", flush=True)
                        futures[pool.submit(process_one, book, books, args, rel_map, index)] = book
                    for future in as_completed(futures):
                        book = futures[future]
                        try:
                            future.result()
                        except Exception as exc:
                            print(f"[main] WORKER ERROR for {book['slug']}: {exc}", flush=True)
            else:
                for index, book in enumerate(selected, start=1):
                    print(f"\n--- BOOK {index}/{len(selected)} | #{book['number']} | {book['title']} | {book['pillar']} > {book['category']} ---", flush=True)
                    process_one(book, books, args, rel_map, 0)
            if not args.loop:
                return 0
            print("\nNext pass starts immediately (no artificial sleep; Ctrl-C to stop cleanly).", flush=True)


if __name__ == "__main__":
    try:
        raise SystemExit(run())
    except ConfigurationError as exc:
        raise SystemExit(f"CONFIGURATION ERROR: {exc}")
