from __future__ import annotations

# Domain 03: Psychology & Human Behavior (180 books: #0311–#0490)
BOOKS_03 = [
    # -------------------------------------------------------------------------
    # LEVEL 2: 01. COGNITIVE PSYCHOLOGY (45 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: THINKING (15 books)
    # LEVEL 4: Judgment (5 books)
    {"title": "Judgment Under Uncertainty: Heuristics and Biases", "author": "Daniel Kahneman; Paul Slovic; Amos Tversky", "first_published": "1982", "latest_published": "1982", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Judgment", "slug": "Judgment-Under-Uncertainty"},
    {"title": "Choices, Values, and Frames", "author": "Daniel Kahneman; Amos Tversky", "first_published": "2000", "latest_published": "2000", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Judgment", "slug": "Choices-Values-and-Frames"},
    {"title": "Simple Heuristics That Make Us Smart", "author": "Gerd Gigerenzer; Peter M. Todd", "first_published": "1999", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Judgment", "slug": "Simple-Heuristics-That-Make-Us-Smart"},
    {"title": "Gut Feelings: The Intelligence of the Unconscious", "author": "Gerd Gigerenzer", "first_published": "2007", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Judgment", "slug": "Gut-Feelings"},
    {"title": "Blink: The Power of Thinking Without Thinking", "author": "Malcolm Gladwell", "first_published": "2005", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Judgment", "slug": "Blink-Gladwell"},

    # LEVEL 4: Reasoning (5 books)
    {"title": "The Psychology of Proof: Deductive Reasoning in Human Thinking", "author": "Lance J. Rips", "first_published": "1994", "latest_published": "1994", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Reasoning", "slug": "The-Psychology-of-Proof"},
    {"title": "How We Reason", "author": "Philip N. Johnson-Laird", "first_published": "2006", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Reasoning", "slug": "How-We-Reason"},
    {"title": "Mental Models: Towards a Cognitive Science of Language, Inference, and Consciousness", "author": "Philip N. Johnson-Laird", "first_published": "1983", "latest_published": "1983", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Reasoning", "slug": "Mental-Models-Johnson-Laird"},
    {"title": "The Knowledge Illusion: Why We Never Think Alone", "author": "Steven Sloman; Philip Fernbach", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Reasoning", "slug": "The-Knowledge-Illusion"},
    {"title": "May Contain Lies: How Stories, Statistics, and Studies Exploit Our Biases", "author": "Alex Edmans", "first_published": "2024", "latest_published": "2024", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Reasoning", "slug": "May-Contain-Lies"},

    # LEVEL 4: Problem Solving (5 books)
    {"title": "How to Solve It: A New Aspect of Mathematical Method", "author": "George Pólya", "first_published": "1945", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Problem Solving", "slug": "How-to-Solve-It"},
    {"title": "Conceptual Blockbusting: A Guide to Better Ideas", "author": "James L. Adams", "first_published": "1974", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Problem Solving", "slug": "Conceptual-Blockbusting"},
    {"title": "The Psychology of Problem Solving: Theory and Practice", "author": "Janet E. Davidson; Robert J. Sternberg", "first_published": "2003", "latest_published": "2003", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Problem Solving", "slug": "The-Psychology-of-Problem-Solving"},
    {"title": "Subtract: The Untapped Science of Less", "author": "Leidy Klotz", "first_published": "2021", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Problem Solving", "slug": "Subtract-Klotz"},
    {"title": "Cracked It!: How to Solve Big Problems and Sell Solutions Like Top Strategy Consultants", "author": "Bernard Garrette; Corey Phelps; Olivier Sibony", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Problem Solving", "slug": "Cracked-It"},

    # LEVEL 3: MEMORY & ATTENTION (15 books)
    # LEVEL 4: Human Memory (5 books)
    {"title": "The Seven Sins of Memory: How the Mind Forgets and Remembers", "author": "Daniel L. Schacter", "first_published": "2001", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Memory", "slug": "The-Seven-Sins-of-Memory"},
    {"title": "Searching for Memory: The Brain, the Mind, and the Past", "author": "Daniel L. Schacter", "first_published": "1996", "latest_published": "1997", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Memory", "slug": "Searching-for-Memory"},
    {"title": "Memory: Foundations and Applications", "author": "Bennett L. Schwartz", "first_published": "2010", "latest_published": "2020", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Memory", "slug": "Memory-Schwartz"},
    {"title": "Working Memory, Thought, and Action", "author": "Alan Baddeley", "first_published": "2007", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Memory", "slug": "Working-Memory-Baddeley"},
    {"title": "The Memory Arts: A Practical Guide to Ancient Mnemotechnics", "author": "Sarah Craske", "first_published": "2018", "latest_published": "2020", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Memory", "slug": "The-Memory-Arts"},

    # LEVEL 4: Attention (5 books)
    {"title": "Attention and Effort", "author": "Daniel Kahneman", "first_published": "1973", "latest_published": "1973", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attention", "slug": "Attention-and-Effort"},
    {"title": "Focus: The Hidden Driver of Excellence", "author": "Daniel Goleman", "first_published": "2013", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attention", "slug": "Focus-Goleman"},
    {"title": "The Attentive Brain", "author": "Raja Parasuraman", "first_published": "1998", "latest_published": "2000", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attention", "slug": "The-Attentive-Brain"},
    {"title": "Attention: Theory and Practice", "author": "Addie Johnson; Robert W. Proctor", "first_published": "2004", "latest_published": "2004", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attention", "slug": "Attention-Johnson-Proctor"},
    {"title": "The World Beyond Your Head: On Becoming an Individual in an Age of Distraction", "author": "Matthew B. Crawford", "first_published": "2015", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attention", "slug": "The-World-Beyond-Your-Head"},

    # LEVEL 4: Cognitive Load (5 books)
    {"title": "Cognitive Load Theory", "author": "John Sweller; Paul Ayres; Slava Kalyuga", "first_published": "2011", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Load", "slug": "Cognitive-Load-Theory"},
    {"title": "Efficiency in Learning: Evidence-Based Guidelines to Manage Cognitive Load", "author": "Ruth Colvin Clark; Frank Nguyen; John Sweller", "first_published": "2005", "latest_published": "2006", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Load", "slug": "Efficiency-in-Learning"},
    {"title": "The Extended Mind: The Power of Thinking Outside the Brain", "author": "Annie Murphy Paul", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Load", "slug": "The-Extended-Mind"},
    {"title": "Supersizing the Mind: Embodiment, Action, and Cognitive Extension", "author": "Andy Clark", "first_published": "2008", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Load", "slug": "Supersizing-the-Mind"},
    {"title": "Mind in Motion: How Action Shapes Thought", "author": "Barbara Tversky", "first_published": "2019", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Load", "slug": "Mind-in-Motion"},

    # LEVEL 3: PERCEPTION & CONSCIOUSNESS (15 books)
    # LEVEL 4: Perception (5 books)
    {"title": "The Case Against Reality: Why Evolution Hid the Truth from Our Eyes", "author": "Donald Hoffman", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Perception", "slug": "The-Case-Against-Reality"},
    {"title": "Being You: A New Science of Consciousness", "author": "Anil Seth", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Perception", "slug": "Being-You"},
    {"title": "Phantoms in the Brain: Probing the Mysteries of the of the Human Mind", "author": "V.S. Ramachandran; Sandra Blakeslee", "first_published": "1998", "latest_published": "1999", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Perception", "slug": "Phantoms-in-the-Brain"},
    {"title": "The Tell-Tale Brain: A Neuroscientist's Quest for What Makes Us Human", "author": "V.S. Ramachandran", "first_published": "2011", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Perception", "slug": "The-Tell-Tale-Brain"},
    {"title": "The Man Who Mistook His Wife for a Hat and Other Clinical Tales", "author": "Oliver Sacks", "first_published": "1985", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Perception", "slug": "The-Man-Who-Mistook-His-Wife-for-a-Hat"},

    # LEVEL 4: Consciousness (5 books)
    {"title": "Consciousness Explained", "author": "Daniel C. Dennett", "first_published": "1991", "latest_published": "1992", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consciousness", "slug": "Consciousness-Explained"},
    {"title": "The Conscious Mind: In Search of a Fundamental Theory", "author": "David J. Chalmers", "first_published": "1996", "latest_published": "1997", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consciousness", "slug": "The-Conscious-Mind"},
    {"title": "Kinds of Minds: Toward an Understanding of Consciousness", "author": "Daniel C. Dennett", "first_published": "1996", "latest_published": "1997", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consciousness", "slug": "Kinds-of-Minds-Dennett"},
    {"title": "Consciousness and the Brain: Deciphering How the Brain Codes Our Thoughts", "author": "Stanislas Dehaene", "first_published": "2014", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consciousness", "slug": "Consciousness-and-the-Brain"},
    {"title": "The Feeling of What Happens: Body and Emotion in the Making of Consciousness", "author": "Antonio Damasio", "first_published": "1999", "latest_published": "2000", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consciousness", "slug": "The-Feeling-of-What-Happens"},

    # LEVEL 4: Mental Representation (5 books)
    {"title": "Surfing Uncertainty: Prediction, Action, and the Embodied Mind", "author": "Andy Clark", "first_published": "2015", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mental Representation", "slug": "Surfing-Uncertainty"},
    {"title": "The Experience Machine: How Our Minds Predict and Shape Reality", "author": "Andy Clark", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mental Representation", "slug": "The-Experience-Machine"},
    {"title": "Surfaces and Essences: Analogy as the Fuel and Fire of Thinking", "author": "Douglas Hofstadter; Emmanuel Sander", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mental Representation", "slug": "Surfaces-and-Essences"},
    {"title": "Metaphors We Live By", "author": "George Lakoff; Mark Johnson", "first_published": "1980", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mental Representation", "slug": "Metaphors-We-Live-By"},
    {"title": "Women, Fire, and Dangerous Things: What Categories Reveal About the Mind", "author": "George Lakoff", "first_published": "1987", "latest_published": "1990", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mental Representation", "slug": "Women-Fire-and-Dangerous-Things"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 02. SOCIAL PSYCHOLOGY (35 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: GROUPS (10 books)
    # LEVEL 4: Group Behavior (5 books)
    {"title": "The Wisdom of Crowds", "author": "James Surowiecki", "first_published": "2004", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Group Behavior", "slug": "The-Wisdom-of-Crowds"},
    {"title": "Groupthink: Psychological Studies of Policy Decisions and Fiascoes", "author": "Irving L. Janis", "first_published": "1972", "latest_published": "1982", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Group Behavior", "slug": "Groupthink-Janis"},
    {"title": "The Lucifer Effect: Understanding How Good People Turn Evil", "author": "Philip Zimbardo", "first_published": "2007", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Group Behavior", "slug": "The-Lucifer-Effect"},
    {"title": "Extraordinary Popular Delusions and the Madness of Crowds", "author": "Charles Mackay", "first_published": "1841", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Group Behavior", "slug": "Extraordinary-Popular-Delusions"},
    {"title": "The Crowd: A Study of the Popular Mind", "author": "Gustave Le Bon", "first_published": "1895", "latest_published": "2002", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Group Behavior", "slug": "The-Crowd-Le-Bon"},

    # LEVEL 4: Social Identity (5 books)
    {"title": "The Righteous Mind: Why Good People Are Divided by Politics and Religion", "author": "Jonathan Haidt", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Identity", "slug": "The-Righteous-Mind"},
    {"title": "Us and Them: Understanding Your Tribal Mind", "author": "David Berreby", "first_published": "2005", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Identity", "slug": "Us-and-Them"},
    {"title": "Whistling Vivaldi: How Stereotypes Affect Us and What We Can Do", "author": "Claude M. Steele", "first_published": "2010", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Identity", "slug": "Whistling-Vivaldi"},
    {"title": "The Social Animal: The Hidden Sources of Love, Character, and Achievement", "author": "David Brooks", "first_published": "2011", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Identity", "slug": "The-Social-Animal-Brooks"},
    {"title": "Tribes: We Need You to Lead Us", "author": "Seth Godin", "first_published": "2008", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Identity", "slug": "Tribes-Godin"},

    # LEVEL 3: SOCIAL INFLUENCE (15 books)
    # LEVEL 4: Conformity (5 books)
    {"title": "Obedience to Authority: An Experimental View", "author": "Stanley Milgram", "first_published": "1974", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conformity", "slug": "Obedience-to-Authority"},
    {"title": "The Social Animal", "author": "Elliot Aronson; Joshua Aronson", "first_published": "1972", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conformity", "slug": "The-Social-Animal-Aronson"},
    {"title": "Conformity: The Power of Social Influences", "author": "Cass R. Sunstein", "first_published": "2019", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conformity", "slug": "Conformity-Sunstein"},
    {"title": "The Asch Experiments: Studies of Independence and Conformity", "author": "Solomon E. Asch", "first_published": "1956", "latest_published": "1956", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conformity", "slug": "The-Asch-Experiments"},
    {"title": "Originals: How Non-Conformists Move the World", "author": "Adam Grant", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conformity", "slug": "Originals-Grant"},

    # LEVEL 4: Authority (5 books)
    {"title": "The Anatomy of Power", "author": "John Kenneth Galbraith", "first_published": "1983", "latest_published": "1985", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Authority", "slug": "The-Anatomy-of-Power-Galbraith"},
    {"title": "The Moral Arc: How Science Makes Us Better People", "author": "Michael Shermer", "first_published": "2015", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Authority", "slug": "The-Moral-Arc-Shermer"},
    {"title": "The Status Game: On Social Position and How We Use It", "author": "Will Storr", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Authority", "slug": "The-Status-Game-Storr"},
    {"title": "The Power Paradox: How We Gain and Lose Influence", "author": "Dacher Keltner", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Authority", "slug": "The-Power-Paradox-Keltner"},
    {"title": "Status: Why We Seek It, How It Shapes Our Lives", "author": "Cecilia L. Ridgeway", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Authority", "slug": "Status-Ridgeway"},

    # LEVEL 4: Persuasion (5 books)
    {"title": "Methods of Persuasion: How to Use Psychology to Influence Human Behavior", "author": "Nick Kolenda", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Persuasion", "slug": "Methods-of-Persuasion-Kolenda"},
    {"title": "Winning the Room: The Art of Pitching and Presentation", "author": "Peter Coughter", "first_published": "2012", "latest_published": "2012", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Persuasion", "slug": "Winning-the-Room"},
    {"title": "Win Bigly: Persuasion in a World Where Facts Don't Matter", "author": "Scott Adams", "first_published": "2017", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Persuasion", "slug": "Win-Bigly"},
    {"title": "The Influential Mind: What the Brain Reveals About Our Power to Change Others", "author": "Tali Sharot", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Persuasion", "slug": "The-Influential-Mind"},
    {"title": "The Optimism Bias: A Tour of the Irrationally Positive Brain", "author": "Tali Sharot", "first_published": "2011", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Persuasion", "slug": "The-Optimism-Bias"},

    # LEVEL 3: HUMAN RELATIONSHIPS (10 books)
    # LEVEL 4: Attraction & Connection (5 books)
    {"title": "Attached: The New Science of Adult Attachment and How It Can Help You Find—and Keep—Love", "author": "Amir Levine; Rachel Heller", "first_published": "2010", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attraction & Connection", "slug": "Attached"},
    {"title": "Hold Me Tight: Seven Conversations for a Lifetime of Love", "author": "Sue Johnson", "first_published": "2008", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attraction & Connection", "slug": "Hold-Me-Tight"},
    {"title": "The Seven Principles for Making Marriage Work", "author": "John M. Gottman; Nan Silver", "first_published": "1999", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attraction & Connection", "slug": "The-Seven-Principles-for-Making-Marriage-Work"},
    {"title": "Mating in Captivity: Unlocking Erotic Intelligence", "author": "Esther Perel", "first_published": "2006", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attraction & Connection", "slug": "Mating-in-Captivity"},
    {"title": "The State of Affairs: Rethinking Infidelity", "author": "Esther Perel", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attraction & Connection", "slug": "The-State-of-Affairs"},

    # LEVEL 4: Cooperation & Competition (5 books)
    {"title": "The Evolution of Cooperation", "author": "Robert Axelrod", "first_published": "1984", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cooperation & Competition", "slug": "The-Evolution-of-Cooperation"},
    {"title": "SuperCooperators: Altruism, Evolution, and Why We Need Each Other to Succeed", "author": "Martin A. Nowak; Roger Highfield", "first_published": "2011", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cooperation & Competition", "slug": "SuperCooperators"},
    {"title": "Give and Take: Why Helping Others Drives Our Success", "author": "Adam Grant", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cooperation & Competition", "slug": "Give-and-Take"},
    {"title": "A Cooperative Species: Human Reciprocity and Its Evolution", "author": "Samuel Bowles; Herbert Gintis", "first_published": "2011", "latest_published": "2013", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cooperation & Competition", "slug": "A-Cooperative-Species"},
    {"title": "The Origins of Virtue: Human Instincts and the Evolution of Cooperation", "author": "Matt Ridley", "first_published": "1996", "latest_published": "1998", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cooperation & Competition", "slug": "The-Origins-of-Virtue-Ridley"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 03. MOTIVATION & BEHAVIOR (40 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: MOTIVATION (15 books)
    # LEVEL 4: Goals (5 books)
    {"title": "Drive: The Surprising Truth About What Motivates Us", "author": "Daniel H. Pink", "first_published": "2009", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Goals", "slug": "Drive-Pink"},
    {"title": "Measure What Matters: How Google, Bono, and the Gates Foundation Rock the World with OKRs", "author": "John Doerr", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Goals", "slug": "Measure-What-Matters"},
    {"title": "Succeed: How We Can Reach Our Goals", "author": "Heidi Grant Halvorson", "first_published": "2010", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Goals", "slug": "Succeed-Halvorson"},
    {"title": "Nine Things Successful People Do Differently", "author": "Heidi Grant Halvorson", "first_published": "2011", "latest_published": "2012", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Goals", "slug": "Nine-Things-Successful-People-Do-Differently"},
    {"title": "Rethinking Positive Thinking: Inside the New Science of Motivation", "author": "Gabriele Oettingen", "first_published": "2014", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Goals", "slug": "Rethinking-Positive-Thinking"},

    # LEVEL 4: Incentives (5 books)
    {"title": "Freakonomics: A Rogue Economist Explores the Hidden Side of Everything", "author": "Steven D. Levitt; Stephen J. Dubner", "first_published": "2005", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives", "slug": "Freakonomics"},
    {"title": "SuperFreakonomics: Global Cooling, Patriotic Prostitutes, and Why Suicide Bombers Should Buy Life Insurance", "author": "Steven D. Levitt; Stephen J. Dubner", "first_published": "2009", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives", "slug": "SuperFreakonomics"},
    {"title": "Think Like a Freak: The Authors of Freakonomics Offer to Retrain Your Brain", "author": "Steven D. Levitt; Stephen J. Dubner", "first_published": "2014", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives", "slug": "Think-Like-a-Freak"},
    {"title": "The Why Axis: Hidden Motives and the Undiscovered Economics of Everyday Life", "author": "Uri Gneezy; John A. List", "first_published": "2013", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives", "slug": "The-Why-Axis"},
    {"title": "Mixed Signals: How Incentives Really Work", "author": "Uri Gneezy", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives", "slug": "Mixed-Signals"},

    # LEVEL 4: Drive & Motivation (5 books)
    {"title": "The Molecule of More: How a Single Chemical in Your Brain Drives Love, Sex, and Creativity", "author": "Daniel Z. Lieberman; Michael E. Long", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Drive & Motivation", "slug": "The-Molecule-of-More"},
    {"title": "Dopamine Nation: Finding Balance in the Age of Indulgence", "author": "Anna Lembke", "first_published": "2021", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Drive & Motivation", "slug": "Dopamine-Nation"},
    {"title": "The Willpower Instinct: How Self-Control Works, Why It Matters, and What You Can Do to Get More of It", "author": "Kelly McGonigal", "first_published": "2011", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Drive & Motivation", "slug": "The-Willpower-Instinct"},
    {"title": "Self-Determination Theory: Basic Psychological Needs in Motivation, Development, and Wellness", "author": "Richard M. Ryan; Edward L. Deci", "first_published": "2017", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Drive & Motivation", "slug": "Self-Determination-Theory"},
    {"title": "Intrinsic Motivation and Self-Determination in Human Behavior", "author": "Edward L. Deci; Richard M. Ryan", "first_published": "1985", "latest_published": "1985", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Drive & Motivation", "slug": "Intrinsic-Motivation"},

    # LEVEL 3: HABITS (15 books)
    # LEVEL 4: Habit Loops (5 books)
    {"title": "Habit Changers: 81 Game-Changing Mantras to Mindfully Realize Your Goals", "author": "M.J. Ryan", "first_published": "2016", "latest_published": "2016", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Loops", "slug": "Habit-Changers"},
    {"title": "Habits of a Happy Brain: Retrain Your Brain to Boost Your Serotonin, Dopamine, Oxytocin, & Endorphin Levels", "author": "Loretta Graziano Breuning", "first_published": "2015", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Loops", "slug": "Habits-of-a-Happy-Brain"},
    {"title": "Making Habits, Breaking Habits: Why We Do Things, Why We Don't, and How to Make Any Change Stick", "author": "Jeremy Dean", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Loops", "slug": "Making-Habits-Breaking-Habits"},
    {"title": "Rewire: Change Your Brain to Break Bad Habits, Overcome Addictions, Conquer Self-Destructive Behavior", "author": "Richard O'Connor", "first_published": "2014", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Loops", "slug": "Rewire-OConnor"},
    {"title": "The Here-and-Now Habit: How Mindfulness Can Help You Break Unhealthy Habits Once and for All", "author": "Hugh G. Byrne", "first_published": "2016", "latest_published": "2016", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Loops", "slug": "The-Here-and-Now-Habit"},

    # LEVEL 4: Habit Tracking (5 books)
    {"title": "The Habit Blueprint: 15 Simple Steps to Transform Your Life", "author": "Patrik Edblad", "first_published": "2016", "latest_published": "2016", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Tracking", "slug": "The-Habit-Blueprint"},
    {"title": "Better Than Before: What I Learned About Making and Breaking Habits", "author": "Gretchen Rubin", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Tracking", "slug": "Better-Than-Before"},
    {"title": "Elastic Habits: How to Create Smarter Habits That Adapt to Your Day", "author": "Stephen Guise", "first_published": "2019", "latest_published": "2019", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Tracking", "slug": "Elastic-Habits"},
    {"title": "Superhuman by Habit: A Guide to Becoming the Best Possible Version of Yourself", "author": "Tynan", "first_published": "2014", "latest_published": "2014", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Tracking", "slug": "Superhuman-by-Habit"},
    {"title": "The Now Habit: A Strategic Program for Overcoming Procrastination and Enjoying Guilt-Free Play", "author": "Neil Fiore", "first_published": "1988", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Tracking", "slug": "The-Now-Habit"},

    # LEVEL 4: Behavioral Momentum (5 books)
    {"title": "The Little Book of Big Change: The No-Willpower Approach to Breaking Any Habit", "author": "Amy Johnson", "first_published": "2016", "latest_published": "2016", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Momentum", "slug": "The-Little-Book-of-Big-Change"},
    {"title": "Stick with It: A Scientifically Proven Process for Changing Your Life-for Good", "author": "Sean D. Young", "first_published": "2017", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Momentum", "slug": "Stick-with-It"},
    {"title": "The Craving Mind: From Cigarettes to Smartphones to Love – Why We Get Hooked and How We Can Break Bad Habits", "author": "Judson Brewer", "first_published": "2017", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Momentum", "slug": "The-Craving-Mind"},
    {"title": "Unwinding Anxiety: New Science Shows How to Break the Cycles of Worry and Fear to Heal Your Mind", "author": "Judson Brewer", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Momentum", "slug": "Unwinding-Anxiety-Brewer"},
    {"title": "The Hunger Habit: Why We Eat When We're Not Hungry and How to Stop", "author": "Judson Brewer", "first_published": "2024", "latest_published": "2024", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Momentum", "slug": "The-Hunger-Habit-Brewer"},

    # LEVEL 3: SELF-CONTROL (10 books)
    # LEVEL 4: Ego Depletion (5 books)
    {"title": "Willpower: Rediscovering the Greatest Human Strength", "author": "Roy F. Baumeister; John Tierney", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ego Depletion", "slug": "Willpower-Baumeister"},
    {"title": "The Marshmallow Test: Mastering Self-Control", "author": "Walter Mischel", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ego Depletion", "slug": "The-Marshmallow-Test"},
    {"title": "Self-Regulation and Executive Function: Challenges and Opportunities", "author": "Roy F. Baumeister; Kathleen D. Vohs", "first_published": "2016", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ego Depletion", "slug": "Self-Regulation-Baumeister"},
    {"title": "Temptation: Finding Self-Control in an Age of Excess", "author": "Daniel Akst", "first_published": "2011", "latest_published": "2011", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ego Depletion", "slug": "Temptation-Akst"},
    {"title": "The Science of Self-Discipline: The Willpower, Mental Toughness, and Self-Control to Resist Temptation and Achieve Your Goals", "author": "Peter Hollins", "first_published": "2017", "latest_published": "2019", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ego Depletion", "slug": "The-Science-of-Self-Discipline"},

    # LEVEL 4: Impulse Management (5 books)
    {"title": "The Power of Fifty Bits: The New Science of Turning Good Intentions into Positive Results", "author": "Bob Nease", "first_published": "2016", "latest_published": "2016", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Impulse Management", "slug": "The-Power-of-Fifty-Bits"},
    {"title": "Stop Overthinking: 23 Techniques to Relieve Stress, Stop Negative Spirals, Declutter Your Mind, and Focus on the Present", "author": "Nick Trenton", "first_published": "2021", "latest_published": "2021", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Impulse Management", "slug": "Stop-Overthinking-Trenton"},
    {"title": "Master Your Emotions: A Practical Guide to Overcome Negativity and Better Manage Your Feelings", "author": "Thibaut Meurisse", "first_published": "2018", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Impulse Management", "slug": "Master-Your-Emotions-Meurisse"},
    {"title": "Self-Discipline: The Art of Mental Toughness", "author": "Brian Cagneey", "first_published": "2016", "latest_published": "2016", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Impulse Management", "slug": "Self-Discipline-Cagneey"},
    {"title": "Mindful Self-Discipline: Accelerate Your Growth and Become Who You Want to Be", "author": "Giovanni Dienstmann", "first_published": "2021", "latest_published": "2021", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Impulse Management", "slug": "Mindful-Self-Discipline"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 04. PERSONALITY & EMOTION (50 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: PERSONALITY (15 books)
    # LEVEL 4: Personality Models (5 books)
    {"title": "Personality: What Makes You the Way You Are", "author": "Daniel Nettle", "first_published": "2007", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personality Models", "slug": "Personality-Nettle"},
    {"title": "Quiet: The Power of Introverts in a World That Can't Stop Talking", "author": "Susan Cain", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personality Models", "slug": "Quiet-Susan-Cain"},
    {"title": "Bittersweet: How Sorrow and Longing Make Us Whole", "author": "Susan Cain", "first_published": "2022", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personality Models", "slug": "Bittersweet-Susan-Cain"},
    {"title": "Me, Myself, and Us: The Science of Personality and the Art of Well-Being", "author": "Brian R. Little", "first_published": "2014", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personality Models", "slug": "Me-Myself-and-Us"},
    {"title": "The Owner's Manual for the Brain: Everyday Applications from Mind-Brain Research", "author": "Pierce J. Howard", "first_published": "1994", "latest_published": "2014", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personality Models", "slug": "The-Owners-Manual-for-the-Brain"},

    # LEVEL 4: Individual Differences (5 books)
    {"title": "Blueprint: How DNA Makes Us Who We Are", "author": "Robert Plomin", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Individual Differences", "slug": "Blueprint-Plomin"},
    {"title": "The Nurture Assumption: Why Children Turn Out the Way They Do", "author": "Judith Rich Harris", "first_published": "1998", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Individual Differences", "slug": "The-Nurture-Assumption"},
    {"title": "No Two Alike: Human Nature and Human Individuality", "author": "Judith Rich Harris", "first_published": "2006", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Individual Differences", "slug": "No-Two-Alike"},
    {"title": "The Blank Slate: The Modern Denial of Human Nature", "author": "Steven Pinker", "first_published": "2002", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Individual Differences", "slug": "The-Blank-Slate"},
    {"title": "Innate: How the Wiring of Our Brains Shapes Who We Are", "author": "Kevin J. Mitchell", "first_published": "2018", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Individual Differences", "slug": "Innate-Mitchell"},

    # LEVEL 4: Identity (5 books)
    {"title": "Self Comes to Mind: Constructing the Conscious Brain", "author": "Antonio Damasio", "first_published": "2010", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Identity", "slug": "Self-Comes-to-Mind"},
    {"title": "The Ego Trick: What Does It Mean to Be You?", "author": "Julian Baggini", "first_published": "2011", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Identity", "slug": "The-Ego-Trick"},
    {"title": "The Self Illusion: How the Social Brain Creates Identity", "author": "Bruce Hood", "first_published": "2012", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Identity", "slug": "The-Self-Illusion"},
    {"title": "Strangers to Ourselves: Discovering the Adaptive Unconscious", "author": "Timothy D. Wilson", "first_published": "2002", "latest_published": "2004", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Identity", "slug": "Strangers-to-Ourselves"},
    {"title": "Redirect: The Surprising New Science of Psychological Change", "author": "Timothy D. Wilson", "first_published": "2011", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Identity", "slug": "Redirect-Wilson"},

    # LEVEL 3: EMOTION (15 books)
    # LEVEL 4: Emotional Regulation (5 books)
    {"title": "Chatter: The Voice in Our Head, Why It Matters, and How to Harness It", "author": "Ethan Kross", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Emotional Regulation", "slug": "Chatter-Kross"},
    {"title": "How Emotions Are Made: The Secret Life of the Brain", "author": "Lisa Feldman Barrett", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Emotional Regulation", "slug": "How-Emotions-Are-Made"},
    {"title": "Seven and a Half Lessons About the Brain", "author": "Lisa Feldman Barrett", "first_published": "2020", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Emotional Regulation", "slug": "Seven-and-a-Half-Lessons-About-the-Brain"},
    {"title": "Descartes' Error: Emotion, Reason, and the Human Brain", "author": "Antonio Damasio", "first_published": "1994", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Emotional Regulation", "slug": "Descartes-Error"},
    {"title": "Looking for Spinoza: Joy, Sorrow, and the Feeling Brain", "author": "Antonio Damasio", "first_published": "2003", "latest_published": "2003", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Emotional Regulation", "slug": "Looking-for-Spinoza"},

    # LEVEL 4: Fear & Anxiety Concepts (5 books)
    {"title": "Anxious: Using the Brain to Understand and Treat Fear and Anxiety", "author": "Joseph LeDoux", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Fear & Anxiety Concepts", "slug": "Anxious-LeDoux"},
    {"title": "The Emotional Brain: The Mysterious Underpinnings of Emotional Life", "author": "Joseph LeDoux", "first_published": "1996", "latest_published": "1998", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Fear & Anxiety Concepts", "slug": "The-Emotional-Brain"},
    {"title": "My Age of Anxiety: Fear, Hope, Dread, and the Search for Peace of Mind", "author": "Scott Stossel", "first_published": "2014", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Fear & Anxiety Concepts", "slug": "My-Age-of-Anxiety"},
    {"title": "The Body Keeps the Score: Brain, Mind, and Body in the Healing of Trauma", "author": "Bessel van der Kolk", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Fear & Anxiety Concepts", "slug": "The-Body-Keeps-the-Score"},
    {"title": "When the Body Says No: The Cost of Hidden Stress", "author": "Gabor Maté", "first_published": "2003", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Fear & Anxiety Concepts", "slug": "When-the-Body-Says-No"},

    # LEVEL 4: Happiness & Positive Emotion (5 books)
    {"title": "The Happiness Hypothesis: Finding Modern Truth in Ancient Wisdom", "author": "Jonathan Haidt", "first_published": "2006", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Happiness & Positive Emotion", "slug": "The-Happiness-Hypothesis"},
    {"title": "Stumbling on Happiness", "author": "Daniel Gilbert", "first_published": "2006", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Happiness & Positive Emotion", "slug": "Stumbling-on-Happiness"},
    {"title": "Authentic Happiness: Using the New Positive Psychology to Realize Your Potential for Lasting Fulfillment", "author": "Martin E.P. Seligman", "first_published": "2002", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Happiness & Positive Emotion", "slug": "Authentic-Happiness"},
    {"title": "Flourish: A Visionary New Understanding of Happiness and Well-being", "author": "Martin E.P. Seligman", "first_published": "2011", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Happiness & Positive Emotion", "slug": "Flourish-Seligman"},
    {"title": "The How of Happiness: A Scientific Approach to Getting the Life You Want", "author": "Sonja Lyubomirsky", "first_published": "2007", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Happiness & Positive Emotion", "slug": "The-How-of-Happiness"},

    # LEVEL 3: EVOLUTIONARY PSYCHOLOGY (15 books)
    # LEVEL 4: Cooperation (5 books)
    {"title": "The Selfish Gene", "author": "Richard Dawkins", "first_published": "1976", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cooperation", "slug": "The-Selfish-Gene"},
    {"title": "Unto Others: The Evolution and Psychology of Unselfish Behavior", "author": "Elliott Sober; David Sloan Wilson", "first_published": "1998", "latest_published": "1999", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cooperation", "slug": "Unto-Others-Sober-Wilson"},
    {"title": "Darwin's Dangerous Idea: Evolution and the Meanings of Life", "author": "Daniel C. Dennett", "first_published": "1995", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cooperation", "slug": "Darwins-Dangerous-Idea-Dennett"},
    {"title": "Mutual Aid: A Factor of Evolution", "author": "Peter Kropotkin", "first_published": "1902", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cooperation", "slug": "Mutual-Aid"},
    {"title": "Moral Origins: The Evolution of Virtue, Altruism, and Shame", "author": "Christopher Boehm", "first_published": "2012", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cooperation", "slug": "Moral-Origins"},

    # LEVEL 4: Competition (5 books)
    {"title": "The Red Queen: Sex and the Evolution of Human Nature", "author": "Matt Ridley", "first_published": "1993", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competition", "slug": "The-Red-Queen"},
    {"title": "The Moral Animal: Why We Are the Way We Are: The New Science of Evolutionary Psychology", "author": "Robert Wright", "first_published": "1994", "latest_published": "1995", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competition", "slug": "The-Moral-Animal"},
    {"title": "Hierarchy in the Forest: The Evolution of Egalitarian Behavior", "author": "Christopher Boehm", "first_published": "1999", "latest_published": "2001", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competition", "slug": "Hierarchy-in-the-Forest"},
    {"title": "War, Peace, and Human Nature: The Convergence of Evolutionary and Cultural Views", "author": "Douglas P. Fry", "first_published": "2013", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competition", "slug": "War-Peace-and-Human-Nature-Fry"},
    {"title": "The Secret of Our Success: How Culture Is Driving Human Evolution", "author": "Joseph Henrich", "first_published": "2015", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competition", "slug": "The-Secret-of-Our-Success-Henrich"},

    # LEVEL 4: Human Evolution (5 books)
    {"title": "The Bonobo and the Atheist: In Search of Humanism Among the Primates", "author": "Frans de Waal", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Evolution", "slug": "The-Bonobo-and-the-Atheist-de-Waal"},
    {"title": "Blueprint: The Evolutionary Origins of a Good Society", "author": "Nicholas A. Christakis", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Evolution", "slug": "Blueprint-Evolutionary-Origins-Christakis"},
    {"title": "Different: Gender Through the Eyes of a Primatologist", "author": "Frans de Waal", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Evolution", "slug": "Different-de-Waal"},
    {"title": "The Third Chimpanzee: The Evolution and Future of the Human Animal", "author": "Jared Diamond", "first_published": "1991", "latest_published": "2006", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Evolution", "slug": "The-Third-Chimpanzee"},
    {"title": "Kindred: Neanderthal Life, Love, Death and Art", "author": "Rebecca Wragg Sykes", "first_published": "2020", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Evolution", "slug": "Kindred-Sykes"},

    # LEVEL 3: APPLIED BEHAVIORAL SCIENCE (15 books)
    # LEVEL 4: Choice Architecture (5 books)
    {"title": "The Smarter Screen: What Your Business Can Learn from the Way We Think, Talk, and Buy Online", "author": "Shlomo Benartzi; Jonah Lehrer", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Choice Architecture", "slug": "The-Smarter-Screen"},
    {"title": "The Art of Choosing", "author": "Sheena Iyengar", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Choice Architecture", "slug": "The-Art-of-Choosing"},
    {"title": "The Paradox of Choice: Why More Is Less", "author": "Barry Schwartz", "first_published": "2004", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Choice Architecture", "slug": "The-Paradox-of-Choice"},
    {"title": "Nudge: The Final Edition", "author": "Richard H. Thaler; Cass R. Sunstein", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Choice Architecture", "slug": "Nudge-Final-Edition"},
    {"title": "Look Both Ways: How to Bring Choice Architecture into the Real World", "author": "Ruth Schmidt", "first_published": "2022", "latest_published": "2022", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Choice Architecture", "slug": "Look-Both-Ways"},

    # LEVEL 4: Incentive Systems (5 books)
    {"title": "Carrots and Sticks: Unlock the Power of Incentives to Get Things Done", "author": "Ian Ayres", "first_published": "2010", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentive Systems", "slug": "Carrots-and-Sticks"},
    {"title": "Punished by Rewards: The Trouble with Gold Stars, Incentive Plans, A's, Praise, and Other Bribes", "author": "Alfie Kohn", "first_published": "1993", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentive Systems", "slug": "Punished-by-Rewards"},
    {"title": "Payoff: The Hidden Logic That Shapes Our Motivations", "author": "Dan Ariely", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentive Systems", "slug": "Payoff-Ariely"},
    {"title": "The Honest Truth About Dishonesty: How We Lie to Everyone—Especially Ourselves", "author": "Dan Ariely", "first_published": "2012", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentive Systems", "slug": "The-Honest-Truth-About-Dishonesty"},
    {"title": "Irrationally Yours: On Missing Socks, Pickup Lines, and Other Existential Puzzles", "author": "Dan Ariely", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentive Systems", "slug": "Irrationally-Yours-Ariely"},

    # LEVEL 4: Applied Behavioral Change (5 books)
    {"title": "Inside the Nudge Unit: How Small Changes Can Make a Big Difference", "author": "David Halpern", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Applied Behavioral Change", "slug": "Inside-the-Nudge-Unit"},
    {"title": "Think Small: The Surprisingly Simple Ways to Reach Big Goals", "author": "Owain Service; Rory Gallagher", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Applied Behavioral Change", "slug": "Think-Small"},
    {"title": "Behavioral Science in Practice", "author": "Liam Delaney", "first_published": "2021", "latest_published": "2021", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Applied Behavioral Change", "slug": "Behavioral-Science-in-Practice"},
    {"title": "Engaged: Designing for Behavior Change", "author": "Amy Bucher", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Applied Behavioral Change", "slug": "Engaged-Bucher"},
    {"title": "Design for How People Think: Using Brain Science to Build Better Products", "author": "John Whalen", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Applied Behavioral Change", "slug": "Design-for-How-People-Think"},
]
