from __future__ import annotations

# Domain 06: Economics, Business & Entrepreneurship (220 books: #0821–#1040)
BOOKS_06 = [
    # -------------------------------------------------------------------------
    # LEVEL 2: 01. ECONOMICS (70 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: MICROECONOMICS (20 books)
    # LEVEL 4: Incentives (5 books)
    {"title": "Basic Economics: A Common Sense Guide to the Economy", "author": "Thomas Sowell", "first_published": "2000", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives", "slug": "Basic-Economics-Sowell"},
    {"title": "Economics in One Lesson", "author": "Henry Hazlitt", "first_published": "1946", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives", "slug": "Economics-in-One-Lesson"},
    {"title": "The Armchair Economist: Economics and Everyday Life", "author": "Steven E. Landsburg", "first_published": "1993", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives", "slug": "The-Armchair-Economist"},
    {"title": "The Undercover Economist", "author": "Tim Harford", "first_published": "2005", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives", "slug": "The-Undercover-Economist"},
    {"title": "The Logic of Life: The Rational Economics of an Irrational World", "author": "Tim Harford", "first_published": "2008", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives", "slug": "The-Logic-of-Life"},

    # LEVEL 4: Markets (5 books)
    {"title": "The Wealth of Nations", "author": "Adam Smith", "first_published": "1776", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Markets", "slug": "The-Wealth-of-Nations"},
    {"title": "Reinventing the Bazaar: A Natural History of Markets", "author": "John McMillan", "first_published": "2002", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Markets", "slug": "Reinventing-the-Bazaar"},
    {"title": "Who Gets What — and Why: The New Economics of Matchmaking and Market Design", "author": "Alvin E. Roth", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Markets", "slug": "Who-Gets-What-and-Why"},
    {"title": "Free to Choose: A Personal Statement", "author": "Milton Friedman; Rose Friedman", "first_published": "1980", "latest_published": "1990", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Markets", "slug": "Free-to-Choose"},
    {"title": "Capitalism and Freedom", "author": "Milton Friedman", "first_published": "1962", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Markets", "slug": "Capitalism-and-Freedom"},

    # LEVEL 4: Competition (5 books)
    {"title": "The Road to Serfdom", "author": "Friedrich A. Hayek", "first_published": "1944", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competition", "slug": "The-Road-to-Serfdom"},
    {"title": "Individualism and Economic Order", "author": "Friedrich A. Hayek", "first_published": "1948", "latest_published": "1980", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competition", "slug": "Individualism-and-Economic-Order"},
    {"title": "Human Action: A Treatise on Economics", "author": "Ludwig von Mises", "first_published": "1949", "latest_published": "1998", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competition", "slug": "Human-Action"},
    {"title": "The Use of Knowledge in Society", "author": "Friedrich A. Hayek", "first_published": "1945", "latest_published": "1945", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competition", "slug": "The-Use-of-Knowledge-in-Society"},
    {"title": "The Anti-Capitalistic Mentality", "author": "Ludwig von Mises", "first_published": "1956", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competition", "slug": "The-Anti-Capitalistic-Mentality"},

    # LEVEL 4: Pricing (5 books)
    {"title": "Confessions of the Pricing Man: How Price Affects Everything", "author": "Hermann Simon", "first_published": "2015", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pricing", "slug": "Confessions-of-the-Pricing-Man"},
    {"title": "Priceless: The Myth of Fair Value (and How to Take Advantage of It)", "author": "William Poundstone", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pricing", "slug": "Priceless-Poundstone"},
    {"title": "The Strategy and Tactics of Pricing: A Guide to Growing More Profitably", "author": "Thomas T. Nagle; Georg Müller", "first_published": "1987", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pricing", "slug": "The-Strategy-and-Tactics-of-Pricing"},
    {"title": "Smart Pricing: How Google, Priceline, and Leading Businesses Use Pricing Innovation for Profitablity", "author": "Jagmohan Raju; Z. John Zhang", "first_published": "2010", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pricing", "slug": "Smart-Pricing"},
    {"title": "The Truth About Pricing: How to Apply Behavioral Economics So Customers Buy", "author": "Melina Palmer", "first_published": "2024", "latest_published": "2024", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pricing", "slug": "The-Truth-About-Pricing-Palmer"},

    # LEVEL 3: MACROECONOMICS (25 books)
    # LEVEL 4: Money & Banking (5 books)
    {"title": "The General Theory of Employment, Interest, and Money", "author": "John Maynard Keynes", "first_published": "1936", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Money & Banking", "slug": "The-General-Theory-of-Employment-Interest-and-Money"},
    {"title": "A Monetary History of the United States, 1867-1960", "author": "Milton Friedman; Anna Jacobson Schwartz", "first_published": "1963", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Money & Banking", "slug": "A-Monetary-History-of-the-United-States"},
    {"title": "The Courage to Act: A Memoir of a Crisis and Its Aftermath", "author": "Ben S. Bernanke", "first_published": "2015", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Money & Banking", "slug": "The-Courage-to-Act"},
    {"title": "21st Century Monetary Policy: The Federal Reserve from the Great Inflation to COVID-19", "author": "Ben S. Bernanke", "first_published": "2022", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Money & Banking", "slug": "21st-Century-Monetary-Policy"},
    {"title": "The Money Machine: How the City Really Works", "author": "Philip Coggan", "first_published": "1986", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Money & Banking", "slug": "The-Money-Machine-Coggan"},

    # LEVEL 4: Inflation (5 books)
    {"title": "When Money Dies: The Nightmare of the Weimar Hyper-inflation", "author": "Adam Fergusson", "first_published": "1975", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Inflation", "slug": "When-Money-Dies"},
    {"title": "Dying of Money: Lessons of the Great German and American Inflations", "author": "Jens O. Parsson", "first_published": "1974", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Inflation", "slug": "Dying-of-Money"},
    {"title": "The Great Inflation: The Rebirth of Modern Central Banking", "author": "Michael D. Bordo; Athanasios Orphanides", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Inflation", "slug": "The-Great-Inflation"},
    {"title": "Paper Money", "author": "George J.W. Goodman (Adam Smith)", "first_published": "1981", "latest_published": "1982", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Inflation", "slug": "Paper-Money-Adam-Smith"},
    {"title": "Inflation: What It Is, Why It's Bad, and How to Fix It", "author": "Steve Forbes; Nathan Lewis; Elizabeth Ames", "first_published": "2022", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Inflation", "slug": "Inflation-Forbes"},

    # LEVEL 4: Business Cycles (5 books)
    {"title": "Stabilizing an Unstable Economy", "author": "Hyman P. Minsky", "first_published": "1986", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Cycles", "slug": "Stabilizing-an-Unstable-Economy"},
    {"title": "Can \"It\" Happen Again?: Essays on Instability and Finance", "author": "Hyman P. Minsky", "first_published": "1982", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Cycles", "slug": "Can-It-Happen-Again"},
    {"title": "Business Cycles: A Theoretical, Historical, and Statistical Analysis of the Capitalist Process", "author": "Joseph A. Schumpeter", "first_published": "1939", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Cycles", "slug": "Business-Cycles-Schumpeter"},
    {"title": "Good Economics for Hard Times", "author": "Abhijit V. Banerjee; Esther Duflo", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Cycles", "slug": "Good-Economics-for-Hard-Times"},
    {"title": "Economics for the Common Good", "author": "Jean Tirole", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Cycles", "slug": "Economics-for-the-Common-Good"},

    # LEVEL 4: Government & Fiscal Policy (5 books)
    {"title": "The Deficit Myth: Modern Monetary Theory and the Birth of the People's Economy", "author": "Stephanie Kelton", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Government & Fiscal Policy", "slug": "The-Deficit-Myth"},
    {"title": "The Public Wealth of Nations: How Management of Public Assets Can Boost or Bust Economic Growth", "author": "Dag Detter; Stefan Fölster", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Government & Fiscal Policy", "slug": "The-Public-Wealth-of-Nations"},
    {"title": "The Entrepreneurial State: Debunking Public vs. Private Sector Myths", "author": "Mariana Mazzucato", "first_published": "2013", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Government & Fiscal Policy", "slug": "The-Entrepreneurial-State"},
    {"title": "The Value of Everything: Making and Taking in the Global Economy", "author": "Mariana Mazzucato", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Government & Fiscal Policy", "slug": "The-Value-of-Everything"},
    {"title": "Mission Economy: A Moonshot Guide to Changing Capitalism", "author": "Mariana Mazzucato", "first_published": "2021", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Government & Fiscal Policy", "slug": "Mission-Economy"},

    # LEVEL 4: International Economics (5 books)
    {"title": "The Globalization Paradox: Democracy and the Future of the World Economy", "author": "Dani Rodrik", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "International Economics", "slug": "The-Globalization-Paradox"},
    {"title": "Straight Talk on Trade: Ideas for a Sane World Economy", "author": "Dani Rodrik", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "International Economics", "slug": "Straight-Talk-on-Trade"},
    {"title": "Globalization and Its Discontents", "author": "Joseph E. Stiglitz", "first_published": "2002", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "International Economics", "slug": "Globalization-and-Its-Discontents"},
    {"title": "The Great Convergence: Information Technology and the New Globalization", "author": "Richard Baldwin", "first_published": "2016", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "International Economics", "slug": "The-Great-Convergence"},
    {"title": "The Globotics Upheaval: Globalization, Robotics, and the Future of Work", "author": "Richard Baldwin", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "International Economics", "slug": "The-Globotics-Upheaval"},

    # LEVEL 3: BEHAVIORAL ECONOMICS (15 books)
    # LEVEL 4: Economic Decision-Making (5 books)
    {"title": "Misbehaving: The Making of Behavioral Economics", "author": "Richard H. Thaler", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Economic Decision-Making", "slug": "Misbehaving-Thaler-Econ"},
    {"title": "The Winner's Curse: Paradoxes and Anomalies of Economic Life", "author": "Richard H. Thaler", "first_published": "1992", "latest_published": "1994", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Economic Decision-Making", "slug": "The-Winners-Curse"},
    {"title": "Quasi Rational Economics", "author": "Richard H. Thaler", "first_published": "1991", "latest_published": "1994", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Economic Decision-Making", "slug": "Quasi-Rational-Economics"},
    {"title": "Behavioral Economics", "author": "Edward Cartwright", "first_published": "2011", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Economic Decision-Making", "slug": "Behavioral-Economics-Cartwright"},
    {"title": "An Introduction to Behavioral Economics", "author": "Nick Wilkinson; Matthias Klaes", "first_published": "2007", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Economic Decision-Making", "slug": "Introduction-to-Behavioral-Economics"},

    # LEVEL 4: Incentives & Choice (5 books)
    {"title": "Scarcity: Why Having Too Little Means So Much", "author": "Sendhil Mullainathan; Eldar Shafir", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives & Choice", "slug": "Scarcity-Mullainathan"},
    {"title": "Dollars and Sense: How We Misthink Money and How to Spend Smarter", "author": "Dan Ariely; Jeff Kreisler", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives & Choice", "slug": "Dollars-and-Sense"},
    {"title": "Alchemy: The Dark Art and Curious Science of Creating Magic in Brands, Business, and Life", "author": "Rory Sutherland", "first_published": "2019", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives & Choice", "slug": "Alchemy-Sutherland"},
    {"title": "Choice Factory: 25 Behavioural Biases That Influence What We Buy", "author": "Richard Shotton", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives & Choice", "slug": "Choice-Factory"},
    {"title": "The Illusion of Choice: 16½ Psychological Biases That Influence What We Buy", "author": "Richard Shotton", "first_published": "2023", "latest_published": "2023", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Incentives & Choice", "slug": "The-Illusion-of-Choice"},

    # LEVEL 4: Behavioral Markets (5 books)
    {"title": "Finance and the Good Society", "author": "Robert J. Shiller", "first_published": "2012", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Markets", "slug": "Finance-and-the-Good-Society"},
    {"title": "The Subprime Solution: How Today's Global Financial Crisis Happened, and What to Do about It", "author": "Robert J. Shiller", "first_published": "2008", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Markets", "slug": "The-Subprime-Solution"},
    {"title": "The New Financial Order: Risk in the 21st Century", "author": "Robert J. Shiller", "first_published": "2003", "latest_published": "2004", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Markets", "slug": "The-New-Financial-Order"},
    {"title": "Market Sense and Nonsense: How the Markets Really Work (and How They Don't)", "author": "Jack D. Schwager", "first_published": "2012", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Markets", "slug": "Market-Sense-and-Nonsense"},
    {"title": "Hedge Hogs: The Cowboy Traders Behind Wall Street's Largest Hedge Fund Disaster", "author": "Barbara T. Dreyfuss", "first_published": "2013", "latest_published": "2013", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Markets", "slug": "Hedge-Hogs"},

    # LEVEL 3: DEVELOPMENT ECONOMICS (10 books)
    # LEVEL 4: Poverty & Development (5 books)
    {"title": "Poor Economics: A Radical Rethinking of the Way to Fight Global Poverty", "author": "Abhijit V. Banerjee; Esther Duflo", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Poverty & Development", "slug": "Poor-Economics"},
    {"title": "Development as Freedom", "author": "Amartya Sen", "first_published": "1999", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Poverty & Development", "slug": "Development-as-Freedom"},
    {"title": "The Bottom Billion: Why the Poorest Countries are Failing and What Can Be Done About It", "author": "Paul Collier", "first_published": "2007", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Poverty & Development", "slug": "The-Bottom-Billion"},
    {"title": "The End of Poverty: Economic Possibilities for Our Time", "author": "Jeffrey D. Sachs", "first_published": "2005", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Poverty & Development", "slug": "The-End-of-Poverty"},
    {"title": "The White Man's Burden: Why the West's Efforts to Aid the Rest Have Done So Much Ill and So Little Good", "author": "William Easterly", "first_published": "2006", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Poverty & Development", "slug": "The-White-Mans-Burden"},

    # LEVEL 4: Institutions & Growth (5 books)
    {"title": "Why Nations Fail: The Origins of Power, Prosperity, and Poverty", "author": "Daron Acemoglu; James A. Robinson", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Institutions & Growth", "slug": "Why-Nations-Fail"},
    {"title": "The Narrow Corridor: States, Societies, and the Fate of Liberty", "author": "Daron Acemoglu; James A. Robinson", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Institutions & Growth", "slug": "The-Narrow-Corridor"},
    {"title": "Power and Progress: Our Thousand-Year Struggle Over Technology and Prosperity", "author": "Daron Acemoglu; Simon Johnson", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Institutions & Growth", "slug": "Power-and-Progress"},
    {"title": "Institutions, Institutional Change and Economic Performance", "author": "Douglass C. North", "first_published": "1990", "latest_published": "1990", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Institutions & Growth", "slug": "Institutions-Institutional-Change-North"},
    {"title": "The Mystery of Capital: Why Capitalism Triumphs in the West and Fails Everywhere Else", "author": "Hernando de Soto", "first_published": "2000", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Institutions & Growth", "slug": "The-Mystery-of-Capital"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 02. BUSINESS (60 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: BUSINESS STRATEGY (20 books)
    # LEVEL 4: Competitive Strategy (5 books)
    {"title": "Good Strategy Bad Strategy: The Difference and Why It Matters", "author": "Richard P. Rumelt", "first_published": "2011", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competitive Strategy", "slug": "Good-Strategy-Bad-Strategy"},
    {"title": "The Crux: How Leaders Become Strategists", "author": "Richard P. Rumelt", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competitive Strategy", "slug": "The-Crux-Rumelt"},
    {"title": "Playing to Win: How Strategy Really Works", "author": "A.G. Lafley; Roger L. Martin", "first_published": "2013", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competitive Strategy", "slug": "Playing-to-Win"},
    {"title": "Blue Ocean Strategy: How to Create Uncontested Market Space and Make the Competition Irrelevant", "author": "W. Chan Kim; Renée Mauborgne", "first_published": "2005", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competitive Strategy", "slug": "Blue-Ocean-Strategy"},
    {"title": "Blue Ocean Shift: Beyond Competing - Proven Steps to Inspire Confidence and Seize New Growth", "author": "W. Chan Kim; Renée Mauborgne", "first_published": "2017", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competitive Strategy", "slug": "Blue-Ocean-Shift"},

    # LEVEL 4: Business Models (5 books)
    {"title": "Business Model Generation: A Handbook for Visionaries, Game Changers, and Challengers", "author": "Alexander Osterwalder; Yves Pigneur", "first_published": "2010", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Models", "slug": "Business-Model-Generation"},
    {"title": "Value Proposition Design: How to Create Products and Services Customers Want", "author": "Alexander Osterwalder; Yves Pigneur; Gregory Bernarda; Alan Smith", "first_published": "2014", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Models", "slug": "Value-Proposition-Design"},
    {"title": "Testing Business Ideas: A Field Guide for Rapid Experimentation", "author": "David J. Bland; Alexander Osterwalder", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Models", "slug": "Testing-Business-Ideas"},
    {"title": "The Invincible Company: How to Constantly Reinvent Your Organization with Inspiration From the World's Best Business Models", "author": "Alexander Osterwalder; Yves Pigneur; Fred Etiemble; Alan Smith", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Models", "slug": "The-Invincible-Company"},
    {"title": "Reinventing Your Business Model: How to Seize the White Space for Transformative Growth", "author": "Mark W. Johnson", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Models", "slug": "Reinventing-Your-Business-Model"},

    # LEVEL 4: Strategic Advantage (5 books)
    {"title": "The Innovator's Dilemma: When New Technologies Cause Great Firms to Fail", "author": "Clayton M. Christensen", "first_published": "1997", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Advantage", "slug": "The-Innovators-Dilemma"},
    {"title": "The Innovator's Solution: Creating and Sustaining Successful Growth", "author": "Clayton M. Christensen; Michael E. Raynor", "first_published": "2003", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Advantage", "slug": "The-Innovators-Solution"},
    {"title": "Competing Against Luck: The Story of Innovation and Customer Choice", "author": "Clayton M. Christensen; Taddy Hall; Karen Dillon; David S. Duncan", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Advantage", "slug": "Competing-Against-Luck"},
    {"title": "Crossing the Chasm: Marketing and Selling Disruptive Products to Mainstream Customers", "author": "Geoffrey A. Moore", "first_published": "1991", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Advantage", "slug": "Crossing-the-Chasm"},
    {"title": "Inside the Tornado: Strategies for Developing, Leveraging, and Surviving Hypergrowth Markets", "author": "Geoffrey A. Moore", "first_published": "1995", "latest_published": "2004", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Advantage", "slug": "Inside-the-Tornado"},

    # LEVEL 4: Industry Analysis (5 books)
    {"title": "Modern Monopolies: What It Takes to Dominate the 21st-Century Economy", "author": "Alex Moazed; Nicholas L. Johnson", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industry Analysis", "slug": "Modern-Monopolies"},
    {"title": "Platform Revolution: How Networked Markets Are Transforming the Economy and How to Make Them Work for You", "author": "Geoffrey G. Parker; Marshall W. Van Alstyne; Sangeet Paul Choudary", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industry Analysis", "slug": "Platform-Revolution"},
    {"title": "Matchmakers: The New Economics of Multisided Platforms", "author": "David S. Evans; Richard Schmalensee", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industry Analysis", "slug": "Matchmakers-Evans"},
    {"title": "The Business of Platforms: Strategy in the Age of Digital Competition, Innovation, and Power", "author": "Michael A. Cusumano; Annabelle Gawer; David B. Yoffie", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industry Analysis", "slug": "The-Business-of-Platforms"},
    {"title": "Platform Scale: How an Emerging Business Model Helps Startups Build Large Empires with Minimum Investment", "author": "Sangeet Paul Choudary", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industry Analysis", "slug": "Platform-Scale"},

    # LEVEL 3: MANAGEMENT (20 books)
    # LEVEL 4: Organizations (5 books)
    {"title": "High Output Management", "author": "Andrew S. Grove", "first_published": "1983", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizations", "slug": "High-Output-Management"},
    {"title": "Only the Paranoid Survive: How to Exploit the Crisis Points That Challenge Every Company", "author": "Andrew S. Grove", "first_published": "1996", "latest_published": "1999", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizations", "slug": "Only-the-Paranoid-Survive"},
    {"title": "The Effective Executive: The Definitive Guide to Getting the Right Things Done", "author": "Peter F. Drucker", "first_published": "1967", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizations", "slug": "The-Effective-Executive"},
    {"title": "Management: Tasks, Responsibilities, Practices", "author": "Peter F. Drucker", "first_published": "1973", "latest_published": "1993", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizations", "slug": "Management-Drucker"},
    {"title": "The Essential Drucker", "author": "Peter F. Drucker", "first_published": "2001", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizations", "slug": "The-Essential-Drucker"},

    # LEVEL 4: Execution (5 books)
    {"title": "Execution: The Discipline of Getting Things Done", "author": "Larry Bossidy; Ram Charan", "first_published": "2002", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Execution", "slug": "Execution-Bossidy"},
    {"title": "The 4 Disciplines of Execution: Achieving Your Wildly Important Goals", "author": "Chris McChesney; Sean Covey; Jim Huling", "first_published": "2012", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Execution", "slug": "The-4-Disciplines-of-Execution"},
    {"title": "Great by Choice: Uncertainty, Chaos, and Luck—Why Some Thrive Despite Them All", "author": "Jim Collins; Morten T. Hansen", "first_published": "2011", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Execution", "slug": "Great-by-Choice"},
    {"title": "Good to Great: Why Some Companies Make the Leap... and Others Don't", "author": "Jim Collins", "first_published": "2001", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Execution", "slug": "Good-to-Great"},
    {"title": "Built to Last: Successful Habits of Visionary Companies", "author": "Jim Collins; Jerry I. Porras", "first_published": "1994", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Execution", "slug": "Built-to-Last"},

    # LEVEL 4: Operations (5 books)
    {"title": "The Goal: A Process of Ongoing Improvement", "author": "Eliyahu M. Goldratt; Jeff Cox", "first_published": "1984", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Operations", "slug": "The-Goal-Goldratt"},
    {"title": "The Phoenix Project: A Novel About IT, DevOps, and Helping Your Business Win", "author": "Gene Kim; Kevin Behr; George Spafford", "first_published": "2013", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Operations", "slug": "The-Phoenix-Project"},
    {"title": "The Unicorn Project: A Novel about Developers, Digital Disruption, and Thriving in the Age of Data", "author": "Gene Kim", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Operations", "slug": "The-Unicorn-Project"},
    {"title": "The Toyota Way: 14 Management Principles from the World's Greatest Manufacturer", "author": "Jeffrey K. Liker", "first_published": "2004", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Operations", "slug": "The-Toyota-Way"},
    {"title": "Lean Thinking: Banish Waste and Create Wealth in Your Corporation", "author": "James P. Womack; Daniel T. Jones", "first_published": "1996", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Operations", "slug": "Lean-Thinking"},

    # LEVEL 4: Organizational Culture (5 books)
    {"title": "No Rules Rules: Netflix and the Culture of Reinvention", "author": "Reed Hastings; Erin Meyer", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizational Culture", "slug": "No-Rules-Rules"},
    {"title": "Creativity, Inc.: Overcoming the Unseen Forces That Stand in the Way of True Inspiration", "author": "Ed Catmull; Amy Wallace", "first_published": "2014", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizational Culture", "slug": "Creativity-Inc"},
    {"title": "Work Rules!: Insights from Inside Google That Will Transform How You Live and Lead", "author": "Laszlo Bock", "first_published": "2015", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizational Culture", "slug": "Work-Rules"},
    {"title": "The Culture Code: The Secrets of Highly Successful Groups", "author": "Daniel Coyle", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizational Culture", "slug": "The-Culture-Code"},
    {"title": "Delivering Happiness: A Path to Profits, Passion, and Purpose", "author": "Tony Hsieh", "first_published": "2010", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizational Culture", "slug": "Delivering-Happiness"},

    # LEVEL 3: MARKETING (20 books)
    # LEVEL 4: Customer Psychology (5 books)
    {"title": "Buyology: Truth and Lies About Why We Buy", "author": "Martin Lindstrom", "first_published": "2008", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Psychology", "slug": "Buyology"},
    {"title": "Small Data: The Tiny Clues That Uncover Huge Trends", "author": "Martin Lindstrom", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Psychology", "slug": "Small-Data"},
    {"title": "Brandwashed: Tricks Companies Use to Manipulate Our Minds and Persuade Us to Buy", "author": "Martin Lindstrom", "first_published": "2011", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Psychology", "slug": "Brandwashed"},
    {"title": "Decoded: The Science of Why We Buy", "author": "Phil Barden", "first_published": "2013", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Psychology", "slug": "Decoded-Barden"},
    {"title": "Neuromarketing: Understanding the Buy Buttons in Your Customer's Brain", "author": "Patrick Renvoise; Christophe Morin", "first_published": "2002", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Psychology", "slug": "Neuromarketing-Renvoise"},

    # LEVEL 4: Branding (5 books)
    {"title": "Building a StoryBrand: Clarify Your Message So Customers Will Listen", "author": "Donald Miller", "first_published": "2017", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Branding", "slug": "Building-a-StoryBrand"},
    {"title": "Marketing Made Simple: A Step-by-Step StoryBrand Guide for Any Business", "author": "Donald Miller; J.J. Peterson", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Branding", "slug": "Marketing-Made-Simple"},
    {"title": "Positioning: The Battle for Your Mind", "author": "Al Ries; Jack Trout", "first_published": "1981", "latest_published": "2001", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Branding", "slug": "Positioning-The-Battle-for-Your-Mind"},
    {"title": "The 22 Immutable Laws of Marketing: Violate Them at Your Own Risk!", "author": "Al Ries; Jack Trout", "first_published": "1993", "latest_published": "1994", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Branding", "slug": "The-22-Immutable-Laws-of-Marketing"},
    {"title": "The 22 Immutable Laws of Branding", "author": "Al Ries; Laura Ries", "first_published": "1998", "latest_published": "2002", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Branding", "slug": "The-22-Immutable-Laws-of-Branding"},

    # LEVEL 4: Distribution (5 books)
    {"title": "Traction: How Any Startup Can Achieve Explosive Customer Growth", "author": "Gabriel Weinberg; Justin Mares", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distribution", "slug": "Traction-Weinberg"},
    {"title": "Hacking Growth: How Today's Fastest-Growing Companies Drive Breakout Success", "author": "Sean Ellis; Morgan Brown", "first_published": "2017", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distribution", "slug": "Hacking-Growth"},
    {"title": "Growth Hacker Marketing: A Primer on the Future of PR, Marketing, and Advertising", "author": "Ryan Holiday", "first_published": "2013", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distribution", "slug": "Growth-Hacker-Marketing"},
    {"title": "Product-Led Growth: How to Build a Product That Sells Itself", "author": "Wes Bush", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distribution", "slug": "Product-Led-Growth"},
    {"title": "Product-Led Onboarding: How to Turn Users into Lifelong Customers", "author": "Ramli John; Wes Bush", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distribution", "slug": "Product-Led-Onboarding"},

    # LEVEL 4: Marketing Strategy (5 books)
    {"title": "This Is Marketing: You Can't Be Seen Until You Learn to See", "author": "Seth Godin", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Marketing Strategy", "slug": "This-Is-Marketing"},
    {"title": "Purple Cow: Transform Your Business by Being Remarkable", "author": "Seth Godin", "first_published": "2003", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Marketing Strategy", "slug": "Purple-Cow"},
    {"title": "Permission Marketing: Turning Strangers Into Friends And Friends Into Customers", "author": "Seth Godin", "first_published": "1999", "latest_published": "1999", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Marketing Strategy", "slug": "Permission-Marketing"},
    {"title": "All Marketers Are Liars: The Underground Classic That Explains How Marketing Really Works--and Why Authenticity Is the Best Marketing of All", "author": "Seth Godin", "first_published": "2005", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Marketing Strategy", "slug": "All-Marketers-Are-Liars"},
    {"title": "Linchpin: Are You Indispensable?", "author": "Seth Godin", "first_published": "2010", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Marketing Strategy", "slug": "Linchpin-Godin"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 03. ENTREPRENEURSHIP & STARTUPS (55 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: STARTUP FOUNDATIONS (20 books)
    # LEVEL 4: Opportunity Identification (5 books)
    {"title": "The Lean Startup: How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses", "author": "Eric Ries", "first_published": "2011", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Opportunity Identification", "slug": "The-Lean-Startup"},
    {"title": "The Startup Way: How Modern Companies Use Entrepreneurial Management to Transform Culture and Drive Long-Term Growth", "author": "Eric Ries", "first_published": "2017", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Opportunity Identification", "slug": "The-Startup-Way"},
    {"title": "The Four Steps to the Epiphany: Successful Strategies for Products that Win", "author": "Steve Blank", "first_published": "2005", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Opportunity Identification", "slug": "The-Four-Steps-to-the-Epiphany"},
    {"title": "The Startup Owner's Manual: The Step-By-Step Guide for Building a Great Company", "author": "Steve Blank; Bob Dorf", "first_published": "2012", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Opportunity Identification", "slug": "The-Startup-Owners-Manual"},
    {"title": "Disciplined Entrepreneurship: 24 Steps to a Successful Startup", "author": "Bill Aulet", "first_published": "2013", "latest_published": "2024", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Opportunity Identification", "slug": "Disciplined-Entrepreneurship"},

    # LEVEL 4: Customer Discovery (5 books)
    {"title": "The Mom Test: How to Talk to Customers & Learn If Your Business Is a Good Idea When Everyone Is Lying to You", "author": "Rob Fitzpatrick", "first_published": "2013", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Discovery", "slug": "The-Mom-Test"},
    {"title": "Talking to Humans: Success Starts with Understanding Your Customers", "author": "Giff Constable; Frank Rimalovski", "first_published": "2014", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Discovery", "slug": "Talking-to-Humans"},
    {"title": "Testing with Humans: How to Run Experiments with Real People", "author": "Giff Constable; Frank Rimalovski", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Discovery", "slug": "Testing-with-Humans"},
    {"title": "Deploy Empathy: A Practical Guide to Interviewing Customers", "author": "Michele Hansen", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Discovery", "slug": "Deploy-Empathy"},
    {"title": "Continuous Discovery Habits: Discover Products that Create Customer Value and Business Value", "author": "Teresa Torres", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Discovery", "slug": "Continuous-Discovery-Habits"},

    # LEVEL 4: Validation (5 books)
    {"title": "Sprint: How to Solve Big Problems and Test New Ideas in Just Five Days", "author": "Jake Knapp; John Zeratsky; Braden Kowitz", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Validation", "slug": "Sprint-Knapp"},
    {"title": "Running Lean: Iterate from Plan A to a Plan That Works", "author": "Ash Maurya", "first_published": "2012", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Validation", "slug": "Running-Lean"},
    {"title": "Scaling Lean: Mastering the Key Metrics for Startup Growth", "author": "Ash Maurya", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Validation", "slug": "Scaling-Lean"},
    {"title": "Lean Analytics: Use Data to Build a Better Startup Faster", "author": "Alistair Croll; Benjamin Yoskovitz", "first_published": "2013", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Validation", "slug": "Lean-Analytics"},
    {"title": "Lean Customer Development: Building Products Your Customers Will Buy", "author": "Cindy Alvarez", "first_published": "2014", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Validation", "slug": "Lean-Customer-Development"},

    # LEVEL 4: Product-Market Fit (5 books)
    {"title": "The Lean Product Playbook: How to Innovate with Minimum Viable Products and Rapid Customer Feedback", "author": "Dan Olsen", "first_published": "2015", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product-Market Fit", "slug": "The-Lean-Product-Playbook"},
    {"title": "Founding Sales: The Early Stage Go-to-Market Handbook", "author": "Peter R. Kazanjy", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product-Market Fit", "slug": "Founding-Sales"},
    {"title": "Obviously Awesome: How to Nail Product Positioning so Customers Get It, Buy It, Love It", "author": "April Dunford", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product-Market Fit", "slug": "Obviously-Awesome"},
    {"title": "Sales Pitch: How to Craft a Story to Stand Out and Win", "author": "April Dunford", "first_published": "2023", "latest_published": "2023", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product-Market Fit", "slug": "Sales-Pitch-Dunford"},
    {"title": "The Right It: Why So Many Ideas Fail and How to Make Sure Yours Succeed", "author": "Alberto Savoia", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product-Market Fit", "slug": "The-Right-It"},

    # LEVEL 3: PRODUCT (15 books)
    # LEVEL 4: Product Management (5 books)
    {"title": "Inspired: How to Create Tech Products Customers Love", "author": "Marty Cagan", "first_published": "2008", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product Management", "slug": "Inspired-Cagan"},
    {"title": "Empowered: Ordinary People, Extraordinary Products", "author": "Marty Cagan; Chris Jones", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product Management", "slug": "Empowered-Cagan"},
    {"title": "Transformed: Moving to the Product Operating Model", "author": "Marty Cagan; Jon Moore", "first_published": "2024", "latest_published": "2024", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product Management", "slug": "Transformed-Cagan"},
    {"title": "Escaping the Build Trap: How Effective Product Management Creates Real Value", "author": "Melissa Perri", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product Management", "slug": "Escaping-the-Build-Trap"},
    {"title": "Cracking the PM Interview: How to Land a Product Manager Job in Technology", "author": "Gayle Laakmann McDowell; Jackie Bavaro", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product Management", "slug": "Cracking-the-PM-Interview"},

    # LEVEL 4: Product Design (5 books)
    {"title": "Don't Make Me Think, Revisited: A Common Sense Approach to Web Usability", "author": "Steve Krug", "first_published": "2000", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product Design", "slug": "Dont-Make-Me-Think"},
    {"title": "Rocket Surgery Made Easy: The Do-It-Yourself Guide to Finding and Fixing Usability Problems", "author": "Steve Krug", "first_published": "2009", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product Design", "slug": "Rocket-Surgery-Made-Easy"},
    {"title": "About Face: The Essentials of Interaction Design", "author": "Alan Cooper; Robert Reimann; David Cronin; Christopher Noessel", "first_published": "1995", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product Design", "slug": "About-Face-Cooper"},
    {"title": "The Inmates Are Running the Asylum: Why High Tech Products Drive Us Crazy and How to Restore the Sanity", "author": "Alan Cooper", "first_published": "1999", "latest_published": "2004", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product Design", "slug": "The-Inmates-Are-Running-the-Asylum"},
    {"title": "Refactoring UI", "author": "Adam Wathan; Steve Schoger", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Product Design", "slug": "Refactoring-UI"},

    # LEVEL 4: Customer Experience (5 books)
    {"title": "The Effortless Experience: Conquering the New Battleground for Customer Loyalty", "author": "Matthew Dixon; Nick Toman; Rick DeLisi", "first_published": "2013", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Experience", "slug": "The-Effortless-Experience"},
    {"title": "The Challenger Sale: Taking Control of the Customer Conversation", "author": "Matthew Dixon; Brent Adamson", "first_published": "2011", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Experience", "slug": "The-Challenger-Sale"},
    {"title": "The Challenger Customer: Selling to the Hidden Influencer Who Can Multiply Your Results", "author": "Brent Adamson; Matthew Dixon; Pat Spenner; Nick Toman", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Experience", "slug": "The-Challenger-Customer"},
    {"title": "The JOLT Effect: How High Performers Overcome Customer Indecision", "author": "Matthew Dixon; Ted McKenna", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Experience", "slug": "The-JOLT-Effect"},
    {"title": "Winning on Purpose: The Unbeatable Strategy of Loving Customers", "author": "Fred Reichheld", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Customer Experience", "slug": "Winning-on-Purpose"},

    # LEVEL 3: GROWTH (20 books)
    # LEVEL 4: Growth Strategy (5 books)
    {"title": "Blitzscaling: The Lightning-Fast Path to Building Massively Valuable Companies", "author": "Reid Hoffman; Chris Yeh", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Growth Strategy", "slug": "Blitzscaling"},
    {"title": "High Growth Handbook: Scaling Startups from 10 to 10,000 People", "author": "Elad Gil", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Growth Strategy", "slug": "High-Growth-Handbook"},
    {"title": "Scaling Up: How a Few Companies Make It... and Why the Rest Don't", "author": "Verne Harnish", "first_published": "2014", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Growth Strategy", "slug": "Scaling-Up-Harnish"},
    {"title": "Mastering the Rockefeller Habits: What You Must Do to Increase the Value of Your Fast-Growth Firm", "author": "Verne Harnish", "first_published": "2002", "latest_published": "2002", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Growth Strategy", "slug": "Mastering-the-Rockefeller-Habits"},
    {"title": "Traction: Get a Grip on Your Business", "author": "Gino Wickman", "first_published": "2007", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Growth Strategy", "slug": "Traction-Wickman"},

    # LEVEL 4: Distribution (5 books)
    {"title": "Predictable Revenue: Turn Your Business Into A Sales Machine with the $100 Million Best Practices of Salesforce.com", "author": "Aaron Ross; Marylou Tyler", "first_published": "2011", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distribution", "slug": "Predictable-Revenue"},
    {"title": "From Impossible to Inevitable: How Hyper-Growth Companies Create Predictable Revenue", "author": "Aaron Ross; Jason Lemkin", "first_published": "2016", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distribution", "slug": "From-Impossible-to-Inevitable"},
    {"title": "The Sales Acceleration Formula: Using Data, Technology, and Inbound Selling to go from $0 to $100 Million", "author": "Mark Roberge", "first_published": "2015", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distribution", "slug": "The-Sales-Acceleration-Formula"},
    {"title": "Inbound Marketing: Get Found Using Google, Social Media, and Blogs", "author": "Brian Halligan; Dharmesh Shah", "first_published": "2009", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distribution", "slug": "Inbound-Marketing"},
    {"title": "Fanatical Prospecting: The Ultimate Guide to Opening Sales Conversations and Filling the Pipeline", "author": "Jeb Blount", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distribution", "slug": "Fanatical-Prospecting"},

    # LEVEL 4: Scaling (5 books)
    {"title": "The E-Myth Revisited: Why Most Small Businesses Don't Work and What to Do About It", "author": "Michael E. Gerber", "first_published": "1995", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Scaling", "slug": "The-E-Myth-Revisited"},
    {"title": "E-Myth Mastery: The Seven Essential Disciplines for Building a World Class Company", "author": "Michael E. Gerber", "first_published": "2005", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Scaling", "slug": "E-Myth-Mastery"},
    {"title": "Rework", "author": "Jason Fried; David Heinemeier Hansson", "first_published": "2010", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Scaling", "slug": "Rework"},
    {"title": "Remote: Office Not Required", "author": "Jason Fried; David Heinemeier Hansson", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Scaling", "slug": "Remote-Fried-Hansson"},
    {"title": "It Doesn't Have to Be Crazy at Work", "author": "Jason Fried; David Heinemeier Hansson", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Scaling", "slug": "It-Doesnt-Have-to-Be-Crazy-at-Work"},

    # LEVEL 4: Network Effects (5 books)
    {"title": "The Cold Start Problem: How to Start and Scale Network Effects", "author": "Andrew Chen", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Network Effects", "slug": "The-Cold-Start-Problem"},
    {"title": "Information Rules: A Strategic Guide to the Network Economy", "author": "Carl Shapiro; Hal R. Varian", "first_published": "1998", "latest_published": "1999", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Network Effects", "slug": "Information-Rules"},
    {"title": "New Rules for the New Economy: 10 Radical Strategies for a Connected World", "author": "Kevin Kelly", "first_published": "1998", "latest_published": "1999", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Network Effects", "slug": "New-Rules-for-the-New-Economy"},
    {"title": "Networks, Crowds, and Markets: Reasoning About a Highly Connected World", "author": "David Easley; Jon Kleinberg", "first_published": "2010", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Network Effects", "slug": "Networks-Crowds-and-Markets"},
    {"title": "Connected: The Surprising Power of Our Social Networks and How They Shape Our Lives", "author": "Nicholas A. Christakis; James H. Fowler", "first_published": "2009", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Network Effects", "slug": "Connected-Christakis"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 04. LEADERSHIP (35 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: PEOPLE LEADERSHIP (15 books)
    # LEVEL 4: Managing People (5 books)
    {"title": "The Making of a Manager: What to Do When Everyone Looks to You", "author": "Julie Zhuo", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Managing People", "slug": "The-Making-of-a-Manager"},
    {"title": "First, Break All the Rules: What the World's Greatest Managers Do Differently", "author": "Marcus Buckingham; Curt Coffman", "first_published": "1999", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Managing People", "slug": "First-Break-All-the-Rules"},
    {"title": "The One Minute Manager", "author": "Kenneth Blanchard; Spencer Johnson", "first_published": "1982", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Managing People", "slug": "The-One-Minute-Manager"},
    {"title": "Nine Lies About Work: A Freethinking Leader's Guide to the Real World", "author": "Marcus Buckingham; Ashley Goodall", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Managing People", "slug": "Nine-Lies-About-Work"},
    {"title": "Help Them Grow or Watch Them Go: Career Conversations Organizations Need and Employees Want", "author": "Beverly Kaye; Julie Winkle Giulioni", "first_published": "2012", "latest_published": "2019", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Managing People", "slug": "Help-Them-Grow-or-Watch-Them-Go"},

    # LEVEL 4: Feedback & Coaching (5 books)
    {"title": "The Coaching Habit: Say Less, Ask More & Change the Way You Lead Forever", "author": "Michael Bungay Stanier", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Feedback & Coaching", "slug": "The-Coaching-Habit"},
    {"title": "The Advice Trap: Be Humble, Stay Curious & Change the Way You Lead Forever", "author": "Michael Bungay Stanier", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Feedback & Coaching", "slug": "The-Advice-Trap"},
    {"title": "Coaching Questions: A Coach's Guide to Powerful Asking Skills", "author": "Tony Stoltzfus", "first_published": "2008", "latest_published": "2008", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Feedback & Coaching", "slug": "Coaching-Questions-Stoltzfus"},
    {"title": "Coaching for Performance: The Principles and Practice of Coaching and Leadership", "author": "John Whitmore", "first_published": "1992", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Feedback & Coaching", "slug": "Coaching-for-Performance"},
    {"title": "Trillion Dollar Coach: The Leadership Playbook of Silicon Valley's Bill Campbell", "author": "Eric Schmidt; Jonathan Rosenberg; Alan Eagle", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Feedback & Coaching", "slug": "Trillion-Dollar-Coach"},

    # LEVEL 4: Building Teams (5 books)
    {"title": "The Five Dysfunctions of a Team: A Leadership Fable", "author": "Patrick Lencioni", "first_published": "2002", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Teams", "slug": "The-Five-Dysfunctions-of-a-Team"},
    {"title": "The Advantage: Why Organizational Health Trumps Everything Else in Business", "author": "Patrick Lencioni", "first_published": "2012", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Teams", "slug": "The-Advantage-Lencioni"},
    {"title": "The Ideal Team Player: How to Recognize and Cultivate The Three Essential Virtues", "author": "Patrick Lencioni", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Teams", "slug": "The-Ideal-Team-Player"},
    {"title": "Leaders Eat Last: Why Some Teams Pull Together and Others Don't", "author": "Simon Sinek", "first_published": "2014", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Teams", "slug": "Leaders-Eat-Last"},
    {"title": "Team of Teams: New Rules of Engagement for a Complex World", "author": "Stanley McChrystal; Tantum Collins; David Silverman", "first_published": "2015", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Teams", "slug": "Team-of-Teams"},

    # LEVEL 3: STRATEGIC LEADERSHIP (20 books)
    # LEVEL 4: Strategic Decisions (5 books)
    {"title": "Leadership Strategy and Tactics: Field Manual", "author": "Jocko Willink", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Decisions", "slug": "Leadership-Strategy-and-Tactics"},
    {"title": "Extreme Ownership: How U.S. Navy SEALs Lead and Win", "author": "Jocko Willink; Leif Babin", "first_published": "2015", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Decisions", "slug": "Extreme-Ownership"},
    {"title": "The Dichotomy of Leadership: Balancing the Challenges of Extreme Ownership to Lead and Win", "author": "Jocko Willink; Leif Babin", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Decisions", "slug": "The-Dichotomy-of-Leadership"},
    {"title": "The Score Takes Care of Itself: My Philosophy of Leadership", "author": "Bill Walsh; Steve Jamison; Craig Walsh", "first_published": "2009", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Decisions", "slug": "The-Score-Takes-Care-of-Itself"},
    {"title": "Turn the Ship Around!: A True Story of Turning Followers into Leaders", "author": "L. David Marquet", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Decisions", "slug": "Turn-the-Ship-Around"},

    # LEVEL 4: Organizational Power (5 books)
    {"title": "Managing with Power: Politics and Influence in Organizations", "author": "Jeffrey Pfeffer", "first_published": "1992", "latest_published": "1994", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizational Power", "slug": "Managing-with-Power"},
    {"title": "Leadership BS: Fixing Workplaces and Careers One Truth at a Time", "author": "Jeffrey Pfeffer", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizational Power", "slug": "Leadership-BS"},
    {"title": "Dying for a Paycheck: How Modern Management Harms Employee Health and Company Performance", "author": "Jeffrey Pfeffer", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizational Power", "slug": "Dying-for-a-Paycheck"},
    {"title": "The Knowing-Doing Gap: How Smart Companies Turn Knowledge into Action", "author": "Jeffrey Pfeffer; Robert I. Sutton", "first_published": "1999", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizational Power", "slug": "The-Knowing-Doing-Gap"},
    {"title": "Hard Facts, Dangerous Half-Truths, and Total Nonsense: Profiting from Evidence-Based Management", "author": "Jeffrey Pfeffer; Robert I. Sutton", "first_published": "2006", "latest_published": "2006", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Organizational Power", "slug": "Hard-Facts-Dangerous-Half-Truths"},

    # LEVEL 4: Leadership Under Uncertainty (5 books)
    {"title": "Leadership in Turbulent Times", "author": "Doris Kearns Goodwin", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Leadership Under Uncertainty", "slug": "Leadership-in-Turbulent-Times"},
    {"title": "Team of Rivals: The Political Genius of Abraham Lincoln", "author": "Doris Kearns Goodwin", "first_published": "2005", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Leadership Under Uncertainty", "slug": "Team-of-Rivals"},
    {"title": "The Splendid and the Vile: A Saga of Churchill, Family, and Defiance During the Blitz", "author": "Erik Larson", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Leadership Under Uncertainty", "slug": "The-Splendid-and-the-Vile"},
    {"title": "Churchill: Walking with Destiny", "author": "Andrew Roberts", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Leadership Under Uncertainty", "slug": "Churchill-Roberts"},
    {"title": "Leadership: Six Studies in World Strategy", "author": "Henry Kissinger", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Leadership Under Uncertainty", "slug": "Leadership-Kissinger"},

    # LEVEL 4: Crisis Leadership (5 books)
    {"title": "Forged in Crisis: The Power of Courageous Leadership in Turbulent Times", "author": "Nancy Koehn", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Crisis Leadership", "slug": "Forged-in-Crisis"},
    {"title": "Shackleton's Way: Leadership Lessons from the Great Antarctic Explorer", "author": "Margot Morrell; Stephanie Capparell", "first_published": "2001", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Crisis Leadership", "slug": "Shackletons-Way"},
    {"title": "Lead from the Future: How to Turn Visionary Thinking Into Breakthrough Growth", "author": "Mark W. Johnson; Josh Suskewicz", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Crisis Leadership", "slug": "Lead-from-the-Future"},
    {"title": "The Infinite Game", "author": "Simon Sinek", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Crisis Leadership", "slug": "The-Infinite-Game"},
    {"title": "Dare to Lead: Brave Work. Tough Conversations. Whole Hearts.", "author": "Brené Brown", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Crisis Leadership", "slug": "Dare-to-Lead"},
]
