from __future__ import annotations

# Domain 13: Biography, Memoir & Lives (70 books: #1931–#2000)
BOOKS_13 = [
    # -------------------------------------------------------------------------
    # LEVEL 2: 01. INNOVATORS & BUILDERS (25 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: TECH & INDUSTRY FOUNDERS (15 books)
    # LEVEL 4: Modern Tech Founders (5 books)
    {"title": "Steve Jobs", "author": "Walter Isaacson", "first_published": "2011", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Tech Founders", "slug": "Steve-Jobs-Isaacson"},
    {"title": "Elon Musk", "author": "Walter Isaacson", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Tech Founders", "slug": "Elon-Musk-Isaacson"},
    {"title": "Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future", "author": "Ashlee Vance", "first_published": "2015", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Tech Founders", "slug": "Elon-Musk-Ashlee-Vance"},
    {"title": "The Everything Store: Jeff Bezos and the Age of Amazon", "author": "Brad Stone", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Tech Founders", "slug": "The-Everything-Store-Brad-Stone"},
    {"title": "Amazon Unbound: Jeff Bezos and the Invention of a Global Empire", "author": "Brad Stone", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Tech Founders", "slug": "Amazon-Unbound-Brad-Stone"},

    # LEVEL 4: Industrial Pioneers (5 books)
    {"title": "Titan: The Life of John D. Rockefeller, Sr.", "author": "Ron Chernow", "first_published": "1998", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industrial Pioneers", "slug": "Titan-Ron-Chernow"},
    {"title": "The First Tycoon: The Epic Life of Cornelius Vanderbilt", "author": "T.J. Stiles", "first_published": "2009", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industrial Pioneers", "slug": "The-First-Tycoon-Stiles"},
    {"title": "Andrew Carnegie", "author": "David Nasaw", "first_published": "2006", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industrial Pioneers", "slug": "Andrew-Carnegie-Nasaw"},
    {"title": "The Patriarch: The Remarkable Life and Turbulent Times of Joseph P. Kennedy", "author": "David Nasaw", "first_published": "2012", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industrial Pioneers", "slug": "The-Patriarch-Nasaw"},
    {"title": "Morgan: American Financier", "author": "Jean Strouse", "first_published": "1999", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industrial Pioneers", "slug": "Morgan-American-Financier-Strouse"},

    # LEVEL 4: Startup Creators (5 books)
    {"title": "The Upstarts: How Uber, Airbnb, and the Killer Companies of the New Silicon Valley Are Changing the World", "author": "Brad Stone", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Startup Creators", "slug": "The-Upstarts-Brad-Stone"},
    {"title": "Super Pumped: The Battle for Uber", "author": "Mike Isaac", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Startup Creators", "slug": "Super-Pumped-Mike-Isaac"},
    {"title": "Bad Blood: Secrets and Lies in a Silicon Valley Startup", "author": "John Carreyrou", "first_published": "2018", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Startup Creators", "slug": "Bad-Blood-Carreyrou"},
    {"title": "Going Infinite: The Rise and Fall of a New Tycoon", "author": "Michael Lewis", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Startup Creators", "slug": "Going-Infinite-Michael-Lewis"},
    {"title": "The New New Thing: A Silicon Valley Story", "author": "Michael Lewis", "first_published": "1999", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Startup Creators", "slug": "The-New-New-Thing-Lewis"},

    # LEVEL 3: SCIENTIFIC PIONEERS (10 books)
    # LEVEL 4: Physicists & Mathematicians (5 books)
    {"title": "American Prometheus: The Triumph and Tragedy of J. Robert Oppenheimer", "author": "Kai Bird; Martin J. Sherwin", "first_published": "2005", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Physicists & Mathematicians", "slug": "American-Prometheus"},
    {"title": "\"Surely You're Joking, Mr. Feynman!\": Adventures of a Curious Character", "author": "Richard P. Feynman; Ralph Leighton", "first_published": "1985", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Physicists & Mathematicians", "slug": "Surely-Youre-Joking-Mr-Feynman"},
    {"title": "\"What Do You Care What Other People Think?\": Further Adventures of a Curious Character", "author": "Richard P. Feynman; Ralph Leighton", "first_published": "1988", "latest_published": "2001", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Physicists & Mathematicians", "slug": "What-Do-You-Care-What-Other-People-Think"},
    {"title": "A Beautiful Mind: The Life of Mathematical Genius and Nobel Laureate John Nash", "author": "Sylvia Nasar", "first_published": "1998", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Physicists & Mathematicians", "slug": "A-Beautiful-Mind-Nasar"},
    {"title": "The Man Who Knew Infinity: A Life of the Genius Ramanujan", "author": "Robert Kanigel", "first_published": "1991", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Physicists & Mathematicians", "slug": "The-Man-Who-Knew-Infinity-Kanigel"},

    # LEVEL 4: Naturalists & Explorers (5 books)
    {"title": "The Invention of Nature: Alexander von Humboldt's New World", "author": "Andrea Wulf", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Naturalists & Explorers", "slug": "The-Invention-of-Nature-Wulf"},
    {"title": "Magnificent Rebels: The First Romantics and the Invention of the Self", "author": "Andrea Wulf", "first_published": "2022", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Naturalists & Explorers", "slug": "Magnificent-Rebels-Wulf"},
    {"title": "The Man Who Found Time: James Hutton and the Discovery of the Earth's Antiquity", "author": "Jack Repcheck", "first_published": "2003", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Naturalists & Explorers", "slug": "The-Man-Who-Found-Time"},
    {"title": "Darwin: The Life of a Tormented Evolutionist", "author": "Adrian Desmond; James R. Moore", "first_published": "1991", "latest_published": "1994", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Naturalists & Explorers", "slug": "Darwin-Desmond-Moore"},
    {"title": "Longitude: The True Story of a Lone Genius Who Solved the Greatest Scientific Problem of His Time", "author": "Dava Sobel", "first_published": "1995", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Naturalists & Explorers", "slug": "Longitude-Dava-Sobel"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 02. THINKERS & PHILOSOPHERS (15 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: INTELLECTUAL GIANTS (15 books)
    # LEVEL 4: Ancient & Modern Thinkers (5 books)
    {"title": "Leonardo da Vinci", "author": "Walter Isaacson", "first_published": "2017", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient & Modern Thinkers", "slug": "Leonardo-da-Vinci-Isaacson"},
    {"title": "Benjamin Franklin: An American Life", "author": "Walter Isaacson", "first_published": "2003", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient & Modern Thinkers", "slug": "Benjamin-Franklin-Isaacson"},
    {"title": "The Autobiography of Benjamin Franklin", "author": "Benjamin Franklin", "first_published": "1791", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient & Modern Thinkers", "slug": "The-Autobiography-of-Benjamin-Franklin"},
    {"title": "Montaigne", "author": "Stefan Zweig", "first_published": "1942", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient & Modern Thinkers", "slug": "Montaigne-Stefan-Zweig"},
    {"title": "How to Live: Or A Life of Montaigne in One Question and Twenty Attempts at an Answer", "author": "Sarah Bakewell", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient & Modern Thinkers", "slug": "How-to-Live-Sarah-Bakewell"},

    # LEVEL 4: Political Theorists (5 books)
    {"title": "At the Existentialist Café: Freedom, Being, and Apricot Cocktails", "author": "Sarah Bakewell", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Political Theorists", "slug": "At-the-Existentialist-Cafe"},
    {"title": "Humanly Possible: Seven Hundred Years of Humanist Freethinking, Inquiry, and Hope", "author": "Sarah Bakewell", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Political Theorists", "slug": "Humanly-Possible-Bakewell"},
    {"title": "Karl Marx: Greatness and Illusion", "author": "Gareth Stedman Jones", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Political Theorists", "slug": "Karl-Marx-Stedman-Jones"},
    {"title": "Hannah Arendt: A Life in Dark Times", "author": "Anne C. Heller", "first_published": "2015", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Political Theorists", "slug": "Hannah-Arendt-Heller"},
    {"title": "Isaiah Berlin: A Life", "author": "Michael Ignatieff", "first_published": "1998", "latest_published": "1999", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Political Theorists", "slug": "Isaiah-Berlin-Ignatieff"},

    # LEVEL 4: Writers & Essayists (5 books)
    {"title": "George Orwell: A Life", "author": "Bernard Crick", "first_published": "1980", "latest_published": "1992", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Writers & Essayists", "slug": "George-Orwell-Bernard-Crick"},
    {"title": "Orwell: The Life", "author": "D.J. Taylor", "first_published": "2003", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Writers & Essayists", "slug": "Orwell-The-Life-Taylor"},
    {"title": "Tolstoy: A Life", "author": "Rosamund Bartlett", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Writers & Essayists", "slug": "Tolstoy-A-Life-Bartlett"},
    {"title": "Dostoevsky: A Writer in His Time", "author": "Joseph Frank", "first_published": "2009", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Writers & Essayists", "slug": "Dostoevsky-Joseph-Frank"},
    {"title": "The World of Yesterday: Memoires of a European", "author": "Stefan Zweig", "first_published": "1942", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Writers & Essayists", "slug": "The-World-of-Yesterday-Zweig"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 03. LEADERS & STATESPEOPLE (15 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: POLITICAL LEADERS (15 books)
    # LEVEL 4: Transformational Leaders (5 books)
    {"title": "Alexander Hamilton", "author": "Ron Chernow", "first_published": "2004", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Transformational Leaders", "slug": "Alexander-Hamilton-Chernow"},
    {"title": "Washington: A Life", "author": "Ron Chernow", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Transformational Leaders", "slug": "Washington-A-Life-Chernow"},
    {"title": "Grant", "author": "Ron Chernow", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Transformational Leaders", "slug": "Grant-Ron-Chernow"},
    {"title": "Lincoln", "author": "David Herbert Donald", "first_published": "1995", "latest_published": "1996", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Transformational Leaders", "slug": "Lincoln-Donald"},
    {"title": "The Path to Power (The Years of Lyndon Johnson, Vol. 1)", "author": "Robert A. Caro", "first_published": "1982", "latest_published": "1990", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Transformational Leaders", "slug": "The-Path-to-Power-Caro"},

    # LEVEL 4: War Leaders (5 books)
    {"title": "Means of Ascent (The Years of Lyndon Johnson, Vol. 2)", "author": "Robert A. Caro", "first_published": "1990", "latest_published": "1991", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "War Leaders", "slug": "Means-of-Ascent-Caro"},
    {"title": "Master of the Senate (The Years of Lyndon Johnson, Vol. 3)", "author": "Robert A. Caro", "first_published": "2002", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "War Leaders", "slug": "Master-of-the-Senate-Caro"},
    {"title": "The Passage of Power (The Years of Lyndon Johnson, Vol. 4)", "author": "Robert A. Caro", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "War Leaders", "slug": "The-Passage-of-Power-Caro"},
    {"title": "The Power Broker: Robert Moses and the Fall of New York", "author": "Robert A. Caro", "first_published": "1974", "latest_published": "1975", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "War Leaders", "slug": "The-Power-Broker-Caro"},
    {"title": "Working: Researching, Interviewing, Writing", "author": "Robert A. Caro", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "War Leaders", "slug": "Working-Robert-Caro"},

    # LEVEL 4: Modern Statespeople (5 books)
    {"title": "Long Walk to Freedom: The Autobiography of Nelson Mandela", "author": "Nelson Mandela", "first_published": "1994", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Statespeople", "slug": "Long-Walk-to-Freedom-Mandela"},
    {"title": "Gandhi: The Years That Changed the World, 1914-1948", "author": "Ramachandra Guha", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Statespeople", "slug": "Gandhi-The-Years-That-Changed-the-World"},
    {"title": "Gandhi Before India", "author": "Ramachandra Guha", "first_published": "2013", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Statespeople", "slug": "Gandhi-Before-India-Guha"},
    {"title": "India After Gandhi: The History of the World's Largest Democracy", "author": "Ramachandra Guha", "first_published": "2007", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Statespeople", "slug": "India-After-Gandhi-Guha"},
    {"title": "From Third World to First: The Singapore Story: 1965-2000", "author": "Lee Kuan Yew", "first_published": "2000", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Statespeople", "slug": "From-Third-World-to-First-Lee-Kuan-Yew"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 04. REMARKABLE LIVES & MEMOIRS (15 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: RESILIENCE & ADVENTURE (15 books)
    # LEVEL 4: Survival & Exploration (5 books)
    {"title": "Endurance: Shackleton's Incredible Voyage", "author": "Alfred Lansing", "first_published": "1959", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Survival & Exploration", "slug": "Endurance-Alfred-Lansing"},
    {"title": "Into Thin Air: A Personal Account of the Mt. Everest Disaster", "author": "Jon Krakauer", "first_published": "1997", "latest_published": "1999", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Survival & Exploration", "slug": "Into-Thin-Air-Krakauer"},
    {"title": "Into the Wild", "author": "Jon Krakauer", "first_published": "1996", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Survival & Exploration", "slug": "Into-the-Wild-Krakauer"},
    {"title": "Under the Banner of Heaven: A Story of Violent Faith", "author": "Jon Krakauer", "first_published": "2003", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Survival & Exploration", "slug": "Under-the-Banner-of-Heaven"},
    {"title": "The River of Doubt: Theodore Roosevelt's Darkest Journey", "author": "Candice Millard", "first_published": "2005", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Survival & Exploration", "slug": "The-River-of-Doubt-Millard"},

    # LEVEL 4: Creative Lives (5 books)
    {"title": "Destiny of the Republic: A Tale of Madness, Medicine and the Murder of a President", "author": "Candice Millard", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Creative Lives", "slug": "Destiny-of-the-Republic-Millard"},
    {"title": "Hero of the Empire: The Boer War, a Daring Escape, and the Making of Winston Churchill", "author": "Candice Millard", "first_published": "2016", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Creative Lives", "slug": "Hero-of-the-Empire-Millard"},
    {"title": "Born a Crime: Stories from a South African Childhood", "author": "Trevor Noah", "first_published": "2016", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Creative Lives", "slug": "Born-a-Crime-Trevor-Noah"},
    {"title": "Educated: A Memoir", "author": "Tara Westover", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Creative Lives", "slug": "Educated-Tara-Westover"},
    {"title": "When Breath Becomes Air", "author": "Paul Kalanithi", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Creative Lives", "slug": "When-Breath-Becomes-Air-Kalanithi"},

    # LEVEL 4: Personal Journeys (5 books)
    {"title": "Wild: From Lost to Found on the Pacific Crest Trail", "author": "Cheryl Strayed", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Journeys", "slug": "Wild-Cheryl-Strayed"},
    {"title": "The Glass Castle: A Memoir", "author": "Jeannette Walls", "first_published": "2005", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Journeys", "slug": "The-Glass-Castle-Walls"},
    {"title": "The Last Lecture", "author": "Randy Pausch; Jeffrey Zaslow", "first_published": "2008", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Journeys", "slug": "The-Last-Lecture-Pausch"},
    {"title": "Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson", "author": "Mitch Albom", "first_published": "1997", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Journeys", "slug": "Tuesdays-with-Morrie-Albom"},
    {"title": "A Walk in the Woods: Rediscovering America on the Appalachian Trail", "author": "Bill Bryson", "first_published": "1998", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Journeys", "slug": "A-Walk-in-the-Woods-Bryson"},
]
