# Canonical 2,000-book curriculum — entries 001-400 (transcribed from the master list).
# Tuple: (number, priority, category_key, subcategory, title, author)
# Priority: S = foundational, A = highly recommended, B = expansion/reference.

CURRICULUM = [
("001", "S", "Learning", "Learning Science", "Make It Stick", "Peter C. Brown; Henry L. Roediger III; Mark A. McDaniel"),
("002", "S", "Learning", "Learning Science", "A Mind for Numbers", "Barbara Oakley"),
("003", "S", "Learning", "Learning Science", "Ultralearning", "Scott Young"),
("004", "S", "Learning", "Learning Science", "Peak", "Anders Ericsson; Robert Pool"),
("005", "S", "Learning", "Learning Science", "Range", "David Epstein"),
("006", "A", "Learning", "Learning Science", "How We Learn", "Benedict Carey"),
("007", "A", "Learning", "Learning Science", "Limitless", "Jim Kwik"),
("008", "A", "Learning", "Memory", "Moonwalking with Einstein", "Joshua Foer"),
("009", "A", "Learning", "Memory", "Remember It!", "Nelson Dellis"),
("010", "A", "Learning", "Study Skills", "How to Become a Straight-A Student", "Cal Newport"),
("011", "S", "Learning", "Focus", "Deep Work", "Cal Newport"),
("012", "A", "Learning", "Focus", "Indistractable", "Nir Eyal"),
("013", "A", "Learning", "Focus", "Stolen Focus", "Johann Hari"),
("014", "S", "Learning", "Time", "Four Thousand Weeks", "Oliver Burkeman"),
("015", "A", "Learning", "Productivity", "Getting Things Done", "David Allen"),
("016", "A", "Learning", "Productivity", "The ONE Thing", "Gary Keller"),
("017", "A", "Learning", "Productivity", "Essentialism", "Greg McKeown"),
("018", "A", "Learning", "Productivity", "Make Time", "Jake Knapp; John Zeratsky"),
("019", "A", "Learning", "Habits", "Atomic Habits", "James Clear"),
("020", "A", "Learning", "Habits", "Tiny Habits", "BJ Fogg"),
("021", "A", "Learning", "Practice", "The Talent Code", "Daniel Coyle"),
("022", "A", "Learning", "Practice", "The Little Book of Talent", "Daniel Coyle"),
("023", "A", "Learning", "Expertise", "The Art of Learning", "Josh Waitzkin"),
("024", "A", "Learning", "Metacognition", "Thinking About Thinking", "Peter Hollins"),
("025", "A", "Learning", "Reading", "How to Read a Book", "Mortimer J. Adler; Charles Van Doren"),
("026", "A", "Learning", "Reading", "The Well-Educated Mind", "Susan Wise Bauer"),
("027", "B", "Learning", "Study Skills", "The Study Skills Handbook", "Stella Cottrell"),
("028", "A", "Learning", "Writing", "The Craft of Research", "Wayne C. Booth et al."),
("029", "A", "Learning", "Research", "Research Design", "John W. Creswell"),
("030", "A", "Learning", "Knowledge", "Building a Second Brain", "Tiago Forte"),
("031", "A", "Learning", "Notes", "How to Take Smart Notes", "Sönke Ahrens"),
("032", "B", "Learning", "Knowledge", "The Organized Mind", "Daniel J. Levitin"),
("033", "A", "Learning", "Curiosity", "Curious", "Ian Leslie"),
("034", "A", "Learning", "Mastery", "Mastery", "Robert Greene"),
("035", "A", "Learning", "Motivation", "Drive", "Daniel H. Pink"),
("036", "A", "Learning", "Motivation", "Grit", "Angela Duckworth"),
("037", "A", "Learning", "Mindset", "Mindset", "Carol Dweck"),
("038", "B", "Learning", "Expertise", "Talent Is Overrated", "Geoff Colvin"),
("039", "B", "Learning", "Education", "What the Best College Teachers Do", "Ken Bain"),
("040", "B", "Learning", "Education", "The End of Education", "Neil Postman"),
("041", "S", "Thinking", "Cognitive Bias", "Thinking, Fast and Slow", "Daniel Kahneman"),
("042", "S", "Thinking", "Rationality", "The Scout Mindset", "Julia Galef"),
("043", "S", "Thinking", "Forecasting", "Superforecasting", "Philip Tetlock; Dan Gardner"),
("044", "S", "Thinking", "Decision Making", "Thinking in Bets", "Annie Duke"),
("045", "A", "Thinking", "Decision Making", "How to Decide", "Annie Duke"),
("046", "A", "Thinking", "Decision Making", "Quit", "Annie Duke"),
("047", "S", "Thinking", "Mental Models", "Seeking Wisdom", "Peter Bevelin"),
("048", "A", "Thinking", "Mental Models", "The Great Mental Models, Vol. 1", "Shane Parrish"),
("049", "A", "Thinking", "Mental Models", "The Great Mental Models, Vol. 2", "Shane Parrish"),
("050", "A", "Thinking", "Mental Models", "The Great Mental Models, Vol. 3", "Shane Parrish"),
("051", "S", "Thinking", "Probability", "Fooled by Randomness", "Nassim Nicholas Taleb"),
("052", "S", "Thinking", "Uncertainty", "The Black Swan", "Nassim Nicholas Taleb"),
("053", "A", "Thinking", "Risk", "Antifragile", "Nassim Nicholas Taleb"),
("054", "A", "Thinking", "Incentives", "Skin in the Game", "Nassim Nicholas Taleb"),
("055", "S", "Thinking", "Judgment", "Noise", "Daniel Kahneman; Olivier Sibony; Cass Sunstein"),
("056", "A", "Thinking", "Decision Making", "Decisive", "Chip Heath; Dan Heath"),
("057", "A", "Thinking", "Measurement", "How to Measure Anything", "Douglas Hubbard"),
("058", "S", "Thinking", "Prediction", "The Signal and the Noise", "Nate Silver"),
("059", "S", "Thinking", "Bias", "Mistakes Were Made (But Not by Me)", "Carol Tavris; Elliot Aronson"),
("060", "A", "Thinking", "Rationality", "Rationality", "Steven Pinker"),
("061", "B", "Thinking", "Bias", "The Art of Thinking Clearly", "Rolf Dobelli"),
("062", "A", "Thinking", "Logic", "The Demon-Haunted World", "Carl Sagan"),
("063", "A", "Thinking", "Skepticism", "The Skeptics' Guide to the Universe", "Steven Novella et al."),
("064", "A", "Thinking", "Critical Thinking", "Asking the Right Questions", "M. Neil Browne; Stuart Keeley"),
("065", "A", "Thinking", "Logic", "Being Logical", "D.Q. McInerny"),
("066", "S", "Thinking", "Logic", "The Art of Reasoning", "David Kelley"),
("067", "A", "Thinking", "Bayesian Thinking", "The Theory That Would Not Die", "Sharon Bertsch McGrayne"),
("068", "A", "Thinking", "Probability", "Against the Gods", "Peter L. Bernstein"),
("069", "B", "Thinking", "Game Theory", "The Art of Strategy", "Avinash Dixit; Barry Nalebuff"),
("070", "S", "Thinking", "Uncertainty", "Judgment Under Uncertainty", "Daniel Kahneman; Paul Slovic; Amos Tversky"),
("071", "S", "Psychology", "Social Influence", "Influence", "Robert Cialdini"),
("072", "A", "Psychology", "Persuasion", "Pre-Suasion", "Robert Cialdini"),
("073", "S", "Psychology", "Behavior", "Behave", "Robert Sapolsky"),
("074", "A", "Psychology", "Motivation", "The Molecule of More", "Daniel Lieberman; Michael Long"),
("075", "A", "Psychology", "Addiction", "Dopamine Nation", "Anna Lembke"),
("076", "S", "Psychology", "Happiness", "The Happiness Hypothesis", "Jonathan Haidt"),
("077", "S", "Psychology", "Morality", "The Righteous Mind", "Jonathan Haidt"),
("078", "A", "Psychology", "Irrationality", "Predictably Irrational", "Dan Ariely"),
("079", "A", "Psychology", "Choice", "The Paradox of Choice", "Barry Schwartz"),
("080", "A", "Psychology", "Self-Deception", "The Elephant in the Brain", "Kevin Simler; Robin Hanson"),
("081", "A", "Psychology", "Social Psychology", "The Social Animal", "Elliot Aronson"),
("082", "A", "Psychology", "Neuroscience", "The Man Who Mistook His Wife for a Hat", "Oliver Sacks"),
("083", "A", "Psychology", "Cognitive Dissonance", "The Undoing Project", "Michael Lewis"),
("084", "A", "Psychology", "Happiness", "Stumbling on Happiness", "Daniel Gilbert"),
("085", "A", "Psychology", "Emotion", "Emotional Intelligence", "Daniel Goleman"),
("086", "A", "Psychology", "Emotion", "Emotional Agility", "Susan David"),
("087", "A", "Psychology", "Relationships", "Attached", "Amir Levine; Rachel Heller"),
("088", "A", "Psychology", "Personality", "Quiet", "Susan Cain"),
("089", "A", "Psychology", "Personality", "The Personality Puzzle", "David Funder"),
("090", "B", "Psychology", "Transactional Analysis", "Games People Play", "Eric Berne"),
("091", "S", "Math", "Intuition", "How Not to Be Wrong", "Jordan Ellenberg"),
("092", "A", "Math", "Appreciation", "The Joy of x", "Steven Strogatz"),
("093", "A", "Math", "Calculus", "Infinite Powers", "Steven Strogatz"),
("094", "S", "Math", "Linear Algebra", "Introduction to Linear Algebra", "Gilbert Strang"),
("095", "A", "Math", "Linear Algebra", "Linear Algebra Done Right", "Sheldon Axler"),
("096", "S", "Math", "ML Math", "Mathematics for Machine Learning", "Marc Peter Deisenroth; A. Aldo Faisal; Cheng Soon Ong"),
("097", "A", "Math", "Problem Solving", "How to Solve It", "George Pólya"),
("098", "S", "Math", "Problem Solving", "Problem-Solving Strategies", "Arthur Engel"),
("099", "A", "Math", "Discrete Math", "Concrete Mathematics", "Ronald Graham; Donald Knuth; Oren Patashnik"),
("100", "A", "Math", "Proofs", "How to Prove It", "Daniel Velleman"),
("101", "A", "Math", "Proofs", "Book of Proof", "Richard Hammack"),
("102", "S", "Math", "Mathematical Thinking", "Mathematics and Plausible Reasoning", "George Pólya"),
("103", "B", "Math", "History", "Journey Through Genius", "William Dunham"),
("104", "B", "Math", "Infinity", "The Infinite Book", "John D. Barrow"),
("105", "S", "Math", "Computation", "Gödel, Escher, Bach", "Douglas Hofstadter"),
("106", "A", "Math", "Logic", "Logicomix", "Apostolos Doxiadis; Christos Papadimitriou"),
("107", "A", "Math", "Complexity", "Complexity", "Melanie Mitchell"),
("108", "A", "Math", "Networks", "Linked", "Albert-László Barabási"),
("109", "B", "Math", "Beauty", "The Music of the Primes", "Marcus du Sautoy"),
("110", "B", "Math", "Mathematics", "The Princeton Companion to Mathematics", "Timothy Gowers"),
("111", "S", "Statistics", "Intuition", "The Art of Statistics", "David Spiegelhalter"),
("112", "A", "Statistics", "Introduction", "Naked Statistics", "Charles Wheelan"),
("113", "S", "Statistics", "Probability", "Introduction to Probability", "Joseph K. Blitzstein; Jessica Hwang"),
("114", "S", "Statistics", "Data Science", "Practical Statistics for Data Scientists", "Peter Bruce; Andrew Bruce; Peter Gedeck"),
("115", "A", "Statistics", "Bayesian", "Think Bayes", "Allen Downey"),
("116", "A", "Statistics", "Statistics", "Think Stats", "Allen Downey"),
("117", "S", "Statistics", "ML", "An Introduction to Statistical Learning", "Gareth James; Daniela Witten; Trevor Hastie; Robert Tibshirani"),
("118", "S", "Statistics", "Advanced ML", "The Elements of Statistical Learning", "Trevor Hastie; Robert Tibshirani; Jerome Friedman"),
("119", "S", "Statistics", "Statistics", "All of Statistics", "Larry Wasserman"),
("120", "A", "Statistics", "Data", "Statistics Done Wrong", "Alex Reinhart"),
("121", "A", "Statistics", "Visualization", "Storytelling with Data", "Cole Nussbaumer Knaflic"),
("122", "A", "Statistics", "Visualization", "Fundamentals of Data Visualization", "Claus O. Wilke"),
("123", "A", "Statistics", "Bayesian", "Statistical Rethinking", "Richard McElreath"),
("124", "A", "Statistics", "Bayesian", "Doing Bayesian Data Analysis", "John Kruschke"),
("125", "S", "Statistics", "Probability", "Probability Theory: The Logic of Science", "E.T. Jaynes"),
("126", "B", "Statistics", "Reference", "Bayesian Data Analysis", "Andrew Gelman et al."),
("127", "A", "Statistics", "Causality", "The Book of Why", "Judea Pearl; Dana Mackenzie"),
("128", "S", "Statistics", "Causality", "Causal Inference: The Mixtape", "Scott Cunningham"),
("129", "A", "Statistics", "Experimentation", "Trustworthy Online Controlled Experiments", "Ron Kohavi; Diane Tang; Ya Xu"),
("130", "B", "Statistics", "Data Analysis", "Data Analysis Using Regression and Multilevel Models", "Andrew Gelman; Jennifer Hill; Aki Vehtari"),
("131", "S", "Science", "Scientific Method", "The Structure of Scientific Revolutions", "Thomas Kuhn"),
("132", "S", "Science", "Falsification", "The Logic of Scientific Discovery", "Karl Popper"),
("133", "A", "Science", "Research", "The Craft of Scientific Writing", "Michael Alley"),
("134", "A", "Science", "Research", "How to Write and Publish a Scientific Paper", "Barbara Gastel; Robert Day"),
("135", "A", "Science", "Evidence", "Calling Bullshit", "Carl Bergstrom; Jevin West"),
("136", "A", "Science", "Evidence", "Bad Science", "Ben Goldacre"),
("137", "A", "Science", "Medicine", "Bad Pharma", "Ben Goldacre"),
("138", "A", "Science", "Experiments", "The Design of Experiments", "Ronald Fisher"),
("139", "A", "Science", "Research", "Research Methods in Psychology", "John J. Shaughnessy et al."),
("140", "A", "Science", "Philosophy", "What Is This Thing Called Science?", "Alan Chalmers"),
("141", "S", "Science", "Knowledge", "The Beginning of Infinity", "David Deutsch"),
("142", "A", "Science", "Progress", "The Knowledge Machine", "Michael Strevens"),
("143", "A", "Science", "Discovery", "The Structure of Scientific Revolutions", "Thomas Kuhn"),
("144", "B", "Science", "Sociology", "Science in Action", "Bruno Latour"),
("145", "A", "Science", "Thinking", "The Scientist in the Crib", "Alison Gopnik; Andrew Meltzoff; Patricia Kuhl"),
("146", "B", "Science", "History", "The Making of the Atomic Bomb", "Richard Rhodes"),
("147", "A", "Science", "Information", "The Information", "James Gleick"),
("148", "A", "Science", "Chaos", "Chaos", "James Gleick"),
("149", "A", "Science", "Complexity", "Scale", "Geoffrey West"),
("150", "S", "Science", "Overview", "A Short History of Nearly Everything", "Bill Bryson"),
("151", "S", "CS", "Algorithms", "Grokking Algorithms", "Aditya Bhargava"),
("152", "S", "CS", "Algorithms", "The Algorithm Design Manual", "Steven Skiena"),
("153", "S", "CS", "Algorithms", "Introduction to Algorithms", "Thomas Cormen; Charles Leiserson; Ronald Rivest; Clifford Stein"),
("154", "A", "CS", "Algorithms", "Algorithms", "Robert Sedgewick; Kevin Wayne"),
("155", "A", "CS", "Problem Solving", "Competitive Programming", "Steven Halim; Felix Halim"),
("156", "S", "CS", "Systems", "Computer Systems: A Programmer's Perspective", "Randal Bryant; David O'Hallaron"),
("157", "S", "CS", "Operating Systems", "Operating Systems: Three Easy Pieces", "Remzi Arpaci-Dusseau; Andrea Arpaci-Dusseau"),
("158", "A", "CS", "Operating Systems", "Modern Operating Systems", "Andrew Tanenbaum"),
("159", "S", "CS", "Networking", "Computer Networking: A Top-Down Approach", "James Kurose; Keith Ross"),
("160", "S", "CS", "Databases", "Database System Concepts", "Abraham Silberschatz; Henry Korth; S. Sudarshan"),
("161", "S", "CS", "Theory", "Introduction to the Theory of Computation", "Michael Sipser"),
("162", "S", "CS", "Compilers", "Crafting Interpreters", "Robert Nystrom"),
("163", "A", "CS", "Compilers", "Compilers: Principles, Techniques, and Tools", "Alfred Aho; Monica Lam; Ravi Sethi; Jeffrey Ullman"),
("164", "S", "CS", "Distributed Systems", "Designing Data-Intensive Applications", "Martin Kleppmann"),
("165", "A", "CS", "Architecture", "Computer Architecture: A Quantitative Approach", "John Hennessy; David Patterson"),
("166", "A", "CS", "Security", "Computer Security", "Dieter Gollmann"),
("167", "A", "CS", "Cryptography", "Serious Cryptography", "Jean-Philippe Aumasson"),
("168", "A", "CS", "Cryptography", "The Code Book", "Simon Singh"),
("169", "B", "CS", "History", "Code", "Charles Petzold"),
("170", "S", "CS", "Computing", "The Art of Computer Programming, Vol. 1", "Donald Knuth"),
("171", "S", "Software", "Craft", "The Pragmatic Programmer", "Andrew Hunt; David Thomas"),
("172", "A", "Software", "Code Quality", "Clean Code", "Robert C. Martin"),
("173", "S", "Software", "Programming", "Code Complete", "Steve McConnell"),
("174", "S", "Software", "Refactoring", "Refactoring", "Martin Fowler"),
("175", "S", "Software", "Legacy", "Working Effectively with Legacy Code", "Michael Feathers"),
("176", "A", "Software", "Design", "A Philosophy of Software Design", "John Ousterhout"),
("177", "S", "Software", "Architecture", "Fundamentals of Software Architecture", "Mark Richards; Neal Ford"),
("178", "S", "Software", "Architecture", "Software Architecture: The Hard Parts", "Neal Ford; Mark Richards; Pramod Sadalage; Zhamak Dehghani"),
("179", "A", "Software", "DDD", "Domain-Driven Design", "Eric Evans"),
("180", "A", "Software", "Patterns", "Design Patterns", "Erich Gamma; Richard Helm; Ralph Johnson; John Vlissides"),
("181", "A", "Software", "Patterns", "Head First Design Patterns", "Eric Freeman; Elisabeth Robson"),
("182", "S", "Software", "Reliability", "Release It!", "Michael Nygard"),
("183", "S", "Software", "Engineering", "Software Engineering at Google", "Titus Winters; Tom Manshreck; Hyrum Wright"),
("184", "S", "Software", "DevOps", "Accelerate", "Nicole Forsgren; Jez Humble; Gene Kim"),
("185", "A", "Software", "DevOps", "The DevOps Handbook", "Gene Kim et al."),
("186", "A", "Software", "Delivery", "Continuous Delivery", "Jez Humble; David Farley"),
("187", "A", "Software", "Testing", "Working Effectively with Unit Tests", "Jay Fields"),
("188", "A", "Software", "Testing", "Growing Object-Oriented Software, Guided by Tests", "Steve Freeman; Nat Pryce"),
("189", "A", "Software", "Career", "The Clean Coder", "Robert C. Martin"),
("190", "B", "Software", "Projects", "Peopleware", "Tom DeMarco; Timothy Lister"),
("191", "S", "Systems", "Databases", "Database Internals", "Alex Petrov"),
("192", "A", "Systems", "SQL", "SQL Antipatterns", "Bill Karwin"),
("193", "A", "Systems", "SQL", "SQL Performance Explained", "Markus Winand"),
("194", "A", "Systems", "Distributed Systems", "Designing Distributed Systems", "Brendan Burns"),
("195", "S", "Systems", "Reliability", "Site Reliability Engineering", "Betsy Beyer et al. (Google)"),
("196", "A", "Systems", "Reliability", "The Site Reliability Workbook", "Betsy Beyer et al. (Google)"),
("197", "A", "Systems", "Microservices", "Building Microservices", "Sam Newman"),
("198", "A", "Systems", "Architecture", "Monolith to Microservices", "Sam Newman"),
("199", "A", "Systems", "Kubernetes", "Kubernetes Up & Running", "Brendan Burns; Joe Beda; Kelsey Hightower"),
("200", "A", "Systems", "Networking", "TCP/IP Illustrated, Vol. 1", "W. Richard Stevens"),
("201", "A", "Systems", "Linux", "The Linux Programming Interface", "Michael Kerrisk"),
("202", "A", "Systems", "Linux", "How Linux Works", "Brian Ward"),
("203", "A", "Systems", "Distributed Systems", "Distributed Systems", "Maarten van Steen; Andrew Tanenbaum"),
("204", "A", "Systems", "Cloud", "Cloud Native Patterns", "Cornelia Davis"),
("205", "A", "Systems", "Architecture", "Building Evolutionary Architectures", "Neal Ford; Rebecca Parsons; Patrick Kua"),
("206", "B", "Systems", "Observability", "Observability Engineering", "Charity Majors; Liz Fong-Jones; George Miranda"),
("207", "A", "Systems", "APIs", "API Design Patterns", "JJ Geewax"),
("208", "A", "Systems", "Security", "Web Application Security", "Andrew Hoffman"),
("209", "A", "Systems", "Security", "Threat Modeling", "Adam Shostack"),
("210", "B", "Systems", "Performance", "Systems Performance", "Brendan Gregg"),
("211", "S", "AI", "Overview", "The Hundred-Page Machine Learning Book", "Andriy Burkov"),
("212", "S", "AI", "Applied ML", "Hands-On Machine Learning", "Aurélien Géron"),
("213", "S", "AI", "Theory", "Artificial Intelligence: A Modern Approach", "Stuart Russell; Peter Norvig"),
("214", "S", "AI", "ML Theory", "Pattern Recognition and Machine Learning", "Christopher Bishop"),
("215", "S", "AI", "Deep Learning", "Deep Learning", "Ian Goodfellow; Yoshua Bengio; Aaron Courville"),
("216", "A", "AI", "Deep Learning", "Deep Learning with Python", "François Chollet"),
("217", "A", "AI", "Deep Learning", "Dive into Deep Learning", "Aston Zhang; Zachary Lipton; Mu Li; Alexander Smola"),
("218", "S", "AI", "Probabilistic ML", "Probabilistic Machine Learning: An Introduction", "Kevin Murphy"),
("219", "A", "AI", "Probabilistic ML", "Probabilistic Machine Learning: Advanced Topics", "Kevin Murphy"),
("220", "S", "AI", "Reinforcement Learning", "Reinforcement Learning", "Richard Sutton; Andrew Barto"),
("221", "S", "AI", "NLP", "Speech and Language Processing", "Dan Jurafsky; James Martin"),
("222", "A", "AI", "Transformers", "Natural Language Processing with Transformers", "Lewis Tunstall; Leandro von Werra; Thomas Wolf"),
("223", "A", "AI", "LLMs", "Hands-On Large Language Models", "Jay Alammar; Maarten Grootendorst"),
("224", "A", "AI", "LLMs", "Build a Large Language Model (From Scratch)", "Sebastian Raschka"),
("225", "A", "AI", "Generative AI", "Generative Deep Learning", "David Foster"),
("226", "S", "AI", "ML Systems", "Designing Machine Learning Systems", "Chip Huyen"),
("227", "A", "AI", "AI Engineering", "AI Engineering", "Chip Huyen"),
("228", "A", "AI", "ML Engineering", "Machine Learning Engineering", "Andriy Burkov"),
("229", "A", "AI", "Production", "Building Machine Learning Powered Applications", "Emmanuel Ameisen"),
("230", "A", "AI", "Interpretability", "Interpretable Machine Learning", "Christoph Molnar"),
("231", "A", "AI", "MLOps", "Introducing MLOps", "Mark Treveil et al."),
("232", "A", "AI", "PyTorch", "Deep Learning with PyTorch", "Eli Stevens; Luca Antiga; Thomas Viehmann"),
("233", "A", "AI", "LLM Engineering", "LLM Engineer's Handbook", "Paul Iusztin; Maxime Labonne"),
("234", "A", "AI", "RAG", "RAG-Driven Generative AI", "Denis Rothman"),
("235", "A", "AI", "Agents", "AI Agents in Action", "Micheal Lanham"),
("236", "A", "AI", "Agentic Systems", "Building Agentic AI Systems", "Biswas; Talukdar"),
("237", "S", "AI", "Safety", "Human Compatible", "Stuart Russell"),
("238", "S", "AI", "Safety", "Superintelligence", "Nick Bostrom"),
("239", "S", "AI", "Alignment", "The Alignment Problem", "Brian Christian"),
("240", "A", "AI", "Society", "Co-Intelligence", "Ethan Mollick"),
("241", "S", "Communication", "Nonfiction", "On Writing Well", "William Zinsser"),
("242", "S", "Communication", "Style", "The Sense of Style", "Steven Pinker"),
("243", "S", "Communication", "Clarity", "Style: Lessons in Clarity and Grace", "Joseph Williams"),
("244", "A", "Communication", "Practical", "Everybody Writes", "Ann Handley"),
("245", "A", "Communication", "Story", "Storyworthy", "Matthew Dicks"),
("246", "S", "Communication", "Ideas", "Made to Stick", "Chip Heath; Dan Heath"),
("247", "S", "Communication", "Business", "The Pyramid Principle", "Barbara Minto"),
("248", "S", "Communication", "Negotiation", "Never Split the Difference", "Chris Voss"),
("249", "S", "Communication", "Negotiation", "Getting to Yes", "Roger Fisher; William Ury; Bruce Patton"),
("250", "S", "Communication", "Difficult Talks", "Difficult Conversations", "Douglas Stone; Bruce Patton; Sheila Heen"),
("251", "A", "Communication", "Conflict", "Crucial Conversations", "Kerry Patterson et al."),
("252", "A", "Communication", "Empathy", "Nonviolent Communication", "Marshall Rosenberg"),
("253", "A", "Communication", "Rhetoric", "Thank You for Arguing", "Jay Heinrichs"),
("254", "A", "Communication", "Speaking", "Talk Like TED", "Carmine Gallo"),
("255", "A", "Communication", "Presentations", "Resonate", "Nancy Duarte"),
("256", "A", "Communication", "Presentations", "slide:ology", "Nancy Duarte"),
("257", "A", "Communication", "Advertising", "Ogilvy on Advertising", "David Ogilvy"),
("258", "A", "Communication", "Copywriting", "Scientific Advertising", "Claude Hopkins"),
("259", "A", "Communication", "Copywriting", "Breakthrough Advertising", "Eugene Schwartz"),
("260", "B", "Communication", "Communication", "Words That Work", "Frank Luntz"),
("261", "S", "Personal Development", "Effectiveness", "The 7 Habits of Highly Effective People", "Stephen Covey"),
("262", "S", "Personal Development", "Career", "So Good They Can't Ignore You", "Cal Newport"),
("263", "A", "Personal Development", "Career", "Designing Your Life", "Bill Burnett; Dave Evans"),
("264", "A", "Personal Development", "Career", "The Startup of You", "Reid Hoffman; Ben Casnocha"),
("265", "A", "Personal Development", "Career", "The Almanack of Naval Ravikant", "Eric Jorgenson"),
("266", "A", "Personal Development", "Execution", "The War of Art", "Steven Pressfield"),
("267", "A", "Personal Development", "Execution", "Do the Work", "Steven Pressfield"),
("268", "A", "Personal Development", "Flow", "Flow", "Mihaly Csikszentmihalyi"),
("269", "A", "Personal Development", "Resilience", "The Obstacle Is the Way", "Ryan Holiday"),
("270", "A", "Personal Development", "Resilience", "Ego Is the Enemy", "Ryan Holiday"),
("271", "A", "Personal Development", "Stoicism", "Stillness Is the Key", "Ryan Holiday"),
("272", "A", "Personal Development", "Confidence", "The Confidence Gap", "Russ Harris"),
("273", "A", "Personal Development", "Courage", "Feel the Fear and Do It Anyway", "Susan Jeffers"),
("274", "A", "Personal Development", "Habits", "The Power of Habit", "Charles Duhigg"),
("275", "A", "Personal Development", "Life Design", "Designing Your Work Life", "Bill Burnett; Dave Evans"),
("276", "B", "Personal Development", "Simplicity", "Essentialism", "Greg McKeown"),
("277", "A", "Personal Development", "Discipline", "Discipline Equals Freedom", "Jocko Willink"),
("278", "B", "Personal Development", "Resilience", "The Comfort Crisis", "Michael Easter"),
("279", "A", "Personal Development", "Meaning", "Man's Search for Meaning", "Viktor Frankl"),
("280", "A", "Personal Development", "Life", "The Good Life", "Robert Waldinger; Marc Schulz"),
("281", "A", "Decision Making", "Creativity", "The Creative Act", "Rick Rubin"),
("282", "A", "Decision Making", "Creativity", "Steal Like an Artist", "Austin Kleon"),
("283", "A", "Decision Making", "Creativity", "Show Your Work!", "Austin Kleon"),
("284", "A", "Decision Making", "Creativity", "Keep Going", "Austin Kleon"),
("285", "S", "Decision Making", "Innovation", "The Innovator's Dilemma", "Clayton Christensen"),
("286", "A", "Decision Making", "Innovation", "The Innovator's Solution", "Clayton Christensen; Michael Raynor"),
("287", "A", "Decision Making", "Innovation", "Where Good Ideas Come From", "Steven Johnson"),
("288", "A", "Decision Making", "Innovation", "The Medici Effect", "Frans Johansson"),
("289", "A", "Decision Making", "Design Thinking", "The Design of Everyday Things", "Don Norman"),
("290", "A", "Decision Making", "Design", "Don't Make Me Think", "Steve Krug"),
("291", "A", "Decision Making", "Product", "Inspired", "Marty Cagan"),
("292", "A", "Decision Making", "Product", "Empowered", "Marty Cagan; Chris Jones"),
("293", "A", "Decision Making", "Product", "Escaping the Build Trap", "Melissa Perri"),
("294", "A", "Decision Making", "Product", "Hooked", "Nir Eyal"),
("295", "A", "Decision Making", "Innovation", "Competing Against Luck", "Clayton Christensen et al."),
("296", "A", "Decision Making", "Strategy", "Good Strategy Bad Strategy", "Richard Rumelt"),
("297", "S", "Decision Making", "Strategy", "Playing to Win", "A.G. Lafley; Roger Martin"),
("298", "A", "Decision Making", "Strategy", "The Strategy Paradox", "Michael Raynor"),
("299", "A", "Decision Making", "Design", "Sprint", "Jake Knapp; John Zeratsky; Braden Kowitz"),
("300", "A", "Decision Making", "Problem Solving", "Lateral Thinking", "Edward de Bono"),
("301", "S", "Finance", "Behavior", "The Psychology of Money", "Morgan Housel"),
("302", "S", "Finance", "Personal Finance", "I Will Teach You to Be Rich", "Ramit Sethi"),
("303", "S", "Finance", "FIRE", "Your Money or Your Life", "Vicki Robin; Joe Dominguez"),
("304", "S", "Finance", "Saving", "Just Keep Buying", "Nick Maggiulli"),
("305", "S", "Finance", "FIRE", "The Simple Path to Wealth", "JL Collins"),
("306", "A", "Finance", "Wealth", "The Millionaire Next Door", "Thomas Stanley; William Danko"),
("307", "A", "Finance", "Wealth", "The Next Millionaires Next Door", "Sarah Stanley Fallaw"),
("308", "A", "Finance", "Life", "Die With Zero", "Bill Perkins"),
("309", "A", "Finance", "Simplicity", "The Index Card", "Helaine Olen; Harold Pollack"),
("310", "A", "Finance", "Behavior", "The Behavior Gap", "Carl Richards"),
("311", "A", "Finance", "Investing", "The Bogleheads' Guide to Investing", "Taylor Larimore; Mel Lindauer; Michael LeBoeuf"),
("312", "A", "Finance", "FIRE", "Financial Freedom", "Grant Sabatier"),
("313", "A", "Finance", "FIRE", "Quit Like a Millionaire", "Kristy Shen; Bryce Leung"),
("314", "B", "Finance", "Debt", "The Total Money Makeover", "Dave Ramsey"),
("315", "A", "Finance", "Household Finance", "The Financial Diaries", "Jonathan Morduch; Rachel Schneider"),
("316", "B", "Finance", "Wealth", "The Richest Man in Babylon", "George Clason"),
("317", "A", "Finance", "Psychology", "Happy Money", "Elizabeth Dunn; Michael Norton"),
("318", "A", "Finance", "Behavior", "The Latte Factor", "David Bach"),
("319", "B", "Finance", "Retirement", "How Much Money Do I Need to Retire?", "Todd Tresidder"),
("320", "A", "Finance", "India", "Let's Talk Money", "Monika Halan"),
("321", "S", "Investing", "Value", "The Intelligent Investor", "Benjamin Graham"),
("322", "S", "Investing", "Indexing", "The Little Book of Common Sense Investing", "John Bogle"),
("323", "S", "Investing", "Markets", "A Random Walk Down Wall Street", "Burton Malkiel"),
("324", "S", "Investing", "Stocks", "One Up On Wall Street", "Peter Lynch"),
("325", "A", "Investing", "Stocks", "Beating the Street", "Peter Lynch"),
("326", "S", "Investing", "Growth", "Common Stocks and Uncommon Profits", "Philip Fisher"),
("327", "S", "Investing", "Risk", "The Most Important Thing", "Howard Marks"),
("328", "A", "Investing", "Cycles", "Mastering the Market Cycle", "Howard Marks"),
("329", "S", "Investing", "Value", "Security Analysis", "Benjamin Graham; David Dodd"),
("330", "S", "Investing", "Mental Models", "Poor Charlie's Almanack", "Charles T. Munger"),
("331", "S", "Investing", "Buffett", "The Essays of Warren Buffett", "Lawrence Cunningham"),
("332", "A", "Investing", "Buffett", "The Warren Buffett Way", "Robert Hagstrom"),
("333", "A", "Investing", "Value", "Margin of Safety", "Seth Klarman"),
("334", "A", "Investing", "Allocation", "The Four Pillars of Investing", "William Bernstein"),
("335", "A", "Investing", "Allocation", "The Intelligent Asset Allocator", "William Bernstein"),
("336", "A", "Investing", "Mutual Funds", "Common Sense on Mutual Funds", "John Bogle"),
("337", "A", "Investing", "Behavioral", "The Little Book of Behavioral Investing", "James Montier"),
("338", "S", "Investing", "Risk", "Against the Gods", "Peter Bernstein"),
("339", "A", "Investing", "Quant", "A Man for All Markets", "Edward Thorp"),
("340", "A", "Investing", "Capital", "Capital Returns", "Edward Chancellor"),
("341", "S", "Economics", "Introduction", "Economics in One Lesson", "Henry Hazlitt"),
("342", "S", "Economics", "Introduction", "Basic Economics", "Thomas Sowell"),
("343", "S", "Economics", "Intuition", "The Undercover Economist", "Tim Harford"),
("344", "A", "Economics", "Introduction", "Naked Economics", "Charles Wheelan"),
("345", "A", "Economics", "Incentives", "Freakonomics", "Steven Levitt; Stephen Dubner"),
("346", "S", "Economics", "Development", "Poor Economics", "Abhijit Banerjee; Esther Duflo"),
("347", "A", "Economics", "Development", "Good Economics for Hard Times", "Abhijit Banerjee; Esther Duflo"),
("348", "S", "Economics", "Institutions", "Why Nations Fail", "Daron Acemoglu; James Robinson"),
("349", "S", "Economics", "Institutions", "The Narrow Corridor", "Daron Acemoglu; James Robinson"),
("350", "S", "Economics", "History", "The Ascent of Money", "Niall Ferguson"),
("351", "S", "Economics", "Crises", "Lords of Finance", "Liaquat Ahamed"),
("352", "S", "Economics", "Crises", "This Time Is Different", "Carmen Reinhart; Kenneth Rogoff"),
("353", "S", "Economics", "Crises", "Manias, Panics, and Crashes", "Charles Kindleberger"),
("354", "A", "Economics", "Debt", "Debt: The First 5,000 Years", "David Graeber"),
("355", "S", "Economics", "Interest Rates", "The Price of Time", "Edward Chancellor"),
("356", "A", "Economics", "Inequality", "Capital in the Twenty-First Century", "Thomas Piketty"),
("357", "A", "Economics", "History", "The Wealth of Nations", "Adam Smith"),
("358", "A", "Economics", "Political Economy", "The Road to Serfdom", "Friedrich Hayek"),
("359", "A", "Economics", "Economic History", "The Great Transformation", "Karl Polanyi"),
("360", "B", "Economics", "Intuition", "The Armchair Economist", "Steven Landsburg"),
("361", "S", "Business", "Management", "High Output Management", "Andrew Grove"),
("362", "S", "Business", "Management", "The Effective Executive", "Peter Drucker"),
("363", "S", "Business", "Management", "The Practice of Management", "Peter Drucker"),
("364", "S", "Business", "Management", "Good to Great", "Jim Collins"),
("365", "A", "Business", "Management", "Built to Last", "Jim Collins; Jerry Porras"),
("366", "A", "Business", "Management", "Great by Choice", "Jim Collins; Morten Hansen"),
("367", "S", "Business", "Strategy", "Good Strategy Bad Strategy", "Richard Rumelt"),
("368", "A", "Business", "Strategy", "Blue Ocean Strategy", "W. Chan Kim; Renée Mauborgne"),
("369", "S", "Business", "Operations", "The Goal", "Eliyahu Goldratt"),
("370", "S", "Business", "Operations", "The Toyota Way", "Jeffrey Liker"),
("371", "A", "Business", "Management", "Measure What Matters", "John Doerr"),
("372", "A", "Business", "Management", "Working Backwards", "Colin Bryar; Bill Carr"),
("373", "S", "Business", "Business History", "Business Adventures", "John Brooks"),
("374", "A", "Business", "Business", "The Personal MBA", "Josh Kaufman"),
("375", "A", "Business", "Management", "Management", "Peter Drucker"),
("376", "A", "Business", "Capital Allocation", "The Outsiders", "William Thorndike"),
("377", "A", "Business", "Companies", "The Everything Store", "Brad Stone"),
("378", "A", "Business", "Companies", "The Upstarts", "Brad Stone"),
("379", "B", "Business", "Management", "Principles", "Ray Dalio"),
("380", "A", "Business", "Management", "Turn the Ship Around!", "L. David Marquet"),
("381", "S", "Entrepreneurship", "Startups", "The Lean Startup", "Eric Ries"),
("382", "S", "Entrepreneurship", "Startups", "Zero to One", "Peter Thiel"),
("383", "S", "Entrepreneurship", "Startups", "The Hard Thing About Hard Things", "Ben Horowitz"),
("384", "S", "Entrepreneurship", "Startups", "The Mom Test", "Rob Fitzpatrick"),
("385", "S", "Entrepreneurship", "Entrepreneurship", "The E-Myth Revisited", "Michael Gerber"),
("386", "A", "Entrepreneurship", "Entrepreneurship", "The $100 Startup", "Chris Guillebeau"),
("387", "A", "Entrepreneurship", "Entrepreneurship", "Company of One", "Paul Jarvis"),
("388", "S", "Entrepreneurship", "Startups", "The Startup Owner's Manual", "Steve Blank; Bob Dorf"),
("389", "S", "Entrepreneurship", "Customer Development", "The Four Steps to the Epiphany", "Steve Blank"),
("390", "S", "Entrepreneurship", "Technology", "Crossing the Chasm", "Geoffrey Moore"),
("391", "S", "Entrepreneurship", "Networks", "The Cold Start Problem", "Andrew Chen"),
("392", "A", "Entrepreneurship", "Founders", "The Founder's Dilemmas", "Noam Wasserman"),
("393", "A", "Entrepreneurship", "Scaling", "Blitzscaling", "Reid Hoffman; Chris Yeh"),
("394", "A", "Entrepreneurship", "Startups", "Lost and Founder", "Rand Fishkin"),
("395", "A", "Entrepreneurship", "Startups", "That Will Never Work", "Marc Randolph"),
("396", "A", "Entrepreneurship", "Startups", "The Art of the Start 2.0", "Guy Kawasaki"),
("397", "A", "Entrepreneurship", "Business", "Rework", "Jason Fried; David Heinemeier Hansson"),
("398", "A", "Entrepreneurship", "Product", "Lean Analytics", "Alistair Croll; Benjamin Yoskovitz"),
("399", "A", "Entrepreneurship", "Growth", "Hacking Growth", "Sean Ellis; Morgan Brown"),
("400", "A", "Entrepreneurship", "Entrepreneurship", "The Entrepreneurial Mindset", "Rita McGrath"),
]
