# Canonical 2,000-book curriculum — entries 401-800 (transcribed from the master list).
# Tuple: (number, priority, category_key, subcategory, title, author)
# Priority: S = foundational, A = highly recommended, B = expansion/reference.

CURRICULUM = [
("401", "S", "Leadership", "Leadership", "Turn the Ship Around!", "L. David Marquet"),
("402", "S", "Leadership", "Management", "Radical Candor", "Kim Scott"),
("403", "S", "Leadership", "Culture", "The Culture Code", "Daniel Coyle"),
("404", "S", "Leadership", "Leadership", "Creativity, Inc.", "Ed Catmull"),
("405", "A", "Leadership", "Culture", "No Rules Rules", "Reed Hastings; Erin Meyer"),
("406", "A", "Leadership", "Leadership", "Multipliers", "Liz Wiseman"),
("407", "A", "Leadership", "Leadership", "Extreme Ownership", "Jocko Willink; Leif Babin"),
("408", "A", "Leadership", "Teams", "The Five Dysfunctions of a Team", "Patrick Lencioni"),
("409", "A", "Leadership", "Leadership", "Dare to Lead", "Brené Brown"),
("410", "A", "Leadership", "Leadership", "Leadership on the Line", "Ronald Heifetz; Marty Linsky"),
("411", "A", "Leadership", "Organizations", "Team of Teams", "Stanley McChrystal et al."),
("412", "A", "Leadership", "Leadership", "The Leadership Challenge", "James Kouzes; Barry Posner"),
("413", "A", "Leadership", "Management", "First, Break All the Rules", "Marcus Buckingham; Curt Coffman"),
("414", "A", "Leadership", "Culture", "Powerful", "Patty McCord"),
("415", "B", "Leadership", "Organizations", "Reinventing Organizations", "Frederic Laloux"),
("416", "A", "Leadership", "Teams", "The Fearless Organization", "Amy Edmondson"),
("417", "A", "Leadership", "Management", "The Making of a Manager", "Julie Zhuo"),
("418", "A", "Leadership", "Management", "High Growth Handbook", "Elad Gil"),
("419", "B", "Leadership", "Leadership", "Leadership Strategy and Tactics", "Jocko Willink"),
("420", "A", "Leadership", "Organizations", "The Infinite Game", "Simon Sinek"),
("421", "S", "Health", "Health", "Outlive", "Peter Attia; Bill Gifford"),
("422", "A", "Health", "Sleep", "Why We Sleep", "Matthew Walker"),
("423", "A", "Health", "Exercise", "Exercised", "Daniel Lieberman"),
("424", "A", "Health", "Exercise", "Spark", "John Ratey"),
("425", "A", "Health", "Movement", "Built to Move", "Kelly Starrett; Juliet Starrett"),
("426", "A", "Health", "Movement", "The Joy of Movement", "Kelly McGonigal"),
("427", "A", "Health", "Sports Science", "The Sports Gene", "David Epstein"),
("428", "A", "Health", "Nutrition", "In Defense of Food", "Michael Pollan"),
("429", "A", "Health", "Nutrition", "Food Rules", "Michael Pollan"),
("430", "B", "Health", "Longevity", "Lifespan", "David Sinclair"),
("431", "A", "Health", "Metabolism", "Good Energy", "Casey Means"),
("432", "A", "Health", "Habits", "The Power of Habit", "Charles Duhigg"),
("433", "A", "Health", "Mental Health", "Feeling Good", "David Burns"),
("434", "A", "Health", "CBT", "Mind Over Mood", "Dennis Greenberger; Christine Padesky"),
("435", "A", "Health", "Stress", "Why Zebras Don't Get Ulcers", "Robert Sapolsky"),
("436", "A", "Health", "Breath", "Breath", "James Nestor"),
("437", "B", "Health", "Health", "The Body Keeps the Score", "Bessel van der Kolk"),
("438", "A", "Health", "Relationships", "The Seven Principles for Making Marriage Work", "John Gottman"),
("439", "A", "Health", "Happiness", "The How of Happiness", "Sonja Lyubomirsky"),
("440", "A", "Health", "Nutrition", "Eat, Drink, and Be Healthy", "Walter Willett"),
("441", "S", "Biology", "Evolution", "The Selfish Gene", "Richard Dawkins"),
("442", "S", "Biology", "Evolution", "The Blind Watchmaker", "Richard Dawkins"),
("443", "S", "Biology", "Genetics", "The Gene", "Siddhartha Mukherjee"),
("444", "S", "Biology", "Medicine", "The Emperor of All Maladies", "Siddhartha Mukherjee"),
("445", "S", "Biology", "Ethics", "The Immortal Life of Henrietta Lacks", "Rebecca Skloot"),
("446", "S", "Biology", "Evolution", "On the Origin of Species", "Charles Darwin"),
("447", "A", "Biology", "Evolution", "Why Evolution Is True", "Jerry Coyne"),
("448", "A", "Biology", "Biology", "The Vital Question", "Nick Lane"),
("449", "A", "Biology", "Biology", "Life Ascending", "Nick Lane"),
("450", "A", "Biology", "Human Body", "The Body", "Bill Bryson"),
("451", "A", "Biology", "Biology", "The Song of the Cell", "Siddhartha Mukherjee"),
("452", "A", "Biology", "Evolution", "The Red Queen", "Matt Ridley"),
("453", "S", "Biology", "Ecology", "The Sixth Extinction", "Elizabeth Kolbert"),
("454", "A", "Biology", "Biology", "Entangled Life", "Merlin Sheldrake"),
("455", "A", "Biology", "Genetics", "The Gene Machine", "Bonnie Bassler"),
("456", "A", "Biology", "Neuroscience", "Principles of Neural Science", "Eric Kandel et al."),
("457", "B", "Biology", "Neuroscience", "Behave", "Robert Sapolsky"),
("458", "A", "Biology", "Biology", "The Extended Phenotype", "Richard Dawkins"),
("459", "B", "Biology", "Medicine", "The Laws of Medicine", "Siddhartha Mukherjee"),
("460", "A", "Biology", "Life", "What Is Life?", "Paul Nurse"),
("461", "S", "Physics", "Physics", "Six Easy Pieces", "Richard Feynman"),
("462", "A", "Physics", "Physics", "Six Not-So-Easy Pieces", "Richard Feynman"),
("463", "S", "Physics", "Cosmology", "A Brief History of Time", "Stephen Hawking"),
("464", "S", "Physics", "Astronomy", "Cosmos", "Carl Sagan"),
("465", "S", "Physics", "Astronomy", "Pale Blue Dot", "Carl Sagan"),
("466", "S", "Physics", "Physics", "The Feynman Lectures on Physics, Vol. 1", "Richard Feynman et al."),
("467", "A", "Physics", "Physics", "The Elegant Universe", "Brian Greene"),
("468", "S", "Physics", "Physics", "The Fabric of the Cosmos", "Brian Greene"),
("469", "A", "Physics", "Cosmology", "The Hidden Reality", "Brian Greene"),
("470", "A", "Physics", "Physics", "Seven Brief Lessons on Physics", "Carlo Rovelli"),
("471", "A", "Physics", "Physics", "Reality Is Not What It Seems", "Carlo Rovelli"),
("472", "A", "Physics", "Cosmology", "The Grand Design", "Stephen Hawking; Leonard Mlodinow"),
("473", "A", "Physics", "Quantum", "Something Deeply Hidden", "Sean Carroll"),
("474", "A", "Physics", "Universe", "The Biggest Ideas in the Universe", "Sean Carroll"),
("475", "A", "Physics", "Time", "The Order of Time", "Carlo Rovelli"),
("476", "S", "Physics", "Physics", "The Fabric of Reality", "David Deutsch"),
("477", "A", "Physics", "Quantum", "Quantum", "Manjit Kumar"),
("478", "B", "Physics", "Physics", "QED", "Richard Feynman"),
("479", "A", "Physics", "Astronomy", "Astrophysics for People in a Hurry", "Neil deGrasse Tyson"),
("480", "A", "Physics", "Cosmology", "The End of Everything", "Katie Mack"),
("481", "S", "History", "History", "The Lessons of History", "Will Durant; Ariel Durant"),
("482", "S", "History", "Civilization", "Guns, Germs, and Steel", "Jared Diamond"),
("483", "A", "History", "Civilization", "Collapse", "Jared Diamond"),
("484", "S", "History", "Human History", "Sapiens", "Yuval Noah Harari"),
("485", "S", "History", "Anthropology", "The Dawn of Everything", "David Graeber; David Wengrow"),
("486", "A", "History", "World History", "The Silk Roads", "Peter Frankopan"),
("487", "S", "History", "Economic History", "The Great Divergence", "Kenneth Pomeranz"),
("488", "S", "History", "WWII", "The Rise and Fall of the Third Reich", "William Shirer"),
("489", "S", "History", "Europe", "Postwar", "Tony Judt"),
("490", "S", "History", "US History", "The Power Broker", "Robert Caro"),
("491", "S", "History", "Leadership", "Team of Rivals", "Doris Kearns Goodwin"),
("492", "A", "History", "History", "The Wright Brothers", "David McCullough"),
("493", "S", "History", "Power", "The Rise and Fall of the Great Powers", "Paul Kennedy"),
("494", "A", "History", "US History", "A People's History of the United States", "Howard Zinn"),
("495", "S", "History", "Civilization", "The Story of Civilization", "Will Durant; Ariel Durant"),
("496", "A", "History", "Ancient History", "SPQR", "Mary Beard"),
("497", "A", "History", "Rome", "Rubicon", "Tom Holland"),
("498", "A", "History", "History", "The Guns of August", "Barbara Tuchman"),
("499", "A", "History", "History", "The Sleepwalkers", "Christopher Clark"),
("500", "S", "History", "History", "The Making of the Modern World", "Robert B. Marks"),
("501", "S", "India", "India", "India After Gandhi", "Ramachandra Guha"),
("502", "S", "India", "India", "The Argumentative Indian", "Amartya Sen"),
("503", "S", "India", "India", "The Discovery of India", "Jawaharlal Nehru"),
("504", "S", "India", "India History", "The Anarchy", "William Dalrymple"),
("505", "A", "India", "India", "The Idea of India", "Sunil Khilnani"),
("506", "S", "India", "Ancient India", "The Wonder That Was India", "A.L. Basham"),
("507", "S", "India", "India History", "India: A History", "John Keay"),
("508", "A", "India", "Mughal India", "The Last Mughal", "William Dalrymple"),
("509", "A", "India", "Colonialism", "Inglorious Empire", "Shashi Tharoor"),
("510", "A", "India", "Colonialism", "An Era of Darkness", "Shashi Tharoor"),
("511", "A", "India", "India History", "The Ivory Throne", "Manu S. Pillai"),
("512", "A", "India", "India History", "False Allies", "Manu S. Pillai"),
("513", "A", "India", "Society", "India Moving", "Chinmay Tumbe"),
("514", "S", "India", "Constitution", "Working a Democratic Constitution", "Granville Austin et al."),
("515", "S", "India", "Constitution", "The Indian Constitution: Cornerstone of a Nation", "Granville Austin"),
("516", "A", "India", "Economics", "India Unbound", "Gurcharan Das"),
("517", "A", "India", "Economics", "The Elephant Paradigm", "Gurcharan Das"),
("518", "A", "India", "Society", "Everybody Loves a Good Drought", "P. Sainath"),
("519", "A", "India", "Modern India", "India Since Independence", "Bipan Chandra et al."),
("520", "A", "India", "Ancient India", "Early India", "Romila Thapar"),
("521", "S", "Sociology", "Anthropology", "The WEIRDest People in the World", "Joseph Henrich"),
("522", "S", "Sociology", "Sociology", "Bowling Alone", "Robert Putnam"),
("523", "S", "Sociology", "Sociology", "The Presentation of Self in Everyday Life", "Erving Goffman"),
("524", "S", "Sociology", "Inequality", "Evicted", "Matthew Desmond"),
("525", "A", "Sociology", "Inequality", "The Spirit Level", "Richard Wilkinson; Kate Pickett"),
("526", "S", "Sociology", "Violence", "The Better Angels of Our Nature", "Steven Pinker"),
("527", "A", "Sociology", "Progress", "Enlightenment Now", "Steven Pinker"),
("528", "S", "Sociology", "Global Development", "Factfulness", "Hans Rosling"),
("529", "B", "Sociology", "Society", "The Tipping Point", "Malcolm Gladwell"),
("530", "B", "Sociology", "Success", "Outliers", "Malcolm Gladwell"),
("531", "A", "Sociology", "Anthropology", "The World Until Yesterday", "Jared Diamond"),
("532", "A", "Sociology", "Status", "The Status Game", "Will Storr"),
("533", "A", "Sociology", "Development", "The Nurture Assumption", "Judith Rich Harris"),
("534", "S", "Sociology", "Inequality", "Capital and Ideology", "Thomas Piketty"),
("535", "A", "Sociology", "Society", "The Lonely Century", "Noreena Hertz"),
("536", "A", "Sociology", "Networks", "Connected", "Nicholas Christakis; James Fowler"),
("537", "A", "Sociology", "Culture", "The Culture Map", "Erin Meyer"),
("538", "A", "Sociology", "Cities", "The Death and Life of Great American Cities", "Jane Jacobs"),
("539", "A", "Sociology", "Society", "The True Believer", "Eric Hoffer"),
("540", "A", "Sociology", "Sociology", "Distinction", "Pierre Bourdieu"),
("541", "S", "Politics", "Politics", "The Dictator's Handbook", "Bruce Bueno de Mesquita; Alastair Smith"),
("542", "S", "Politics", "Political Order", "The Origins of Political Order", "Francis Fukuyama"),
("543", "S", "Politics", "Political Order", "Political Order and Political Decay", "Francis Fukuyama"),
("544", "S", "Politics", "Politics", "The End of History and the Last Man", "Francis Fukuyama"),
("545", "S", "Politics", "Democracy", "Democracy in America", "Alexis de Tocqueville"),
("546", "S", "Politics", "Liberty", "On Liberty", "John Stuart Mill"),
("547", "S", "Politics", "US Politics", "The Federalist Papers", "Alexander Hamilton; James Madison; John Jay"),
("548", "S", "Politics", "Justice", "Justice", "Michael Sandel"),
("549", "S", "Politics", "Political Philosophy", "The Republic", "Plato"),
("550", "S", "Politics", "Law", "The Constitution of India", "Government of India"),
("551", "A", "Politics", "Politics", "Why We're Polarized", "Ezra Klein"),
("552", "A", "Politics", "Democracy", "How Democracies Die", "Steven Levitsky; Daniel Ziblatt"),
("553", "A", "Politics", "Institutions", "The Logic of Political Survival", "Bruce Bueno de Mesquita et al."),
("554", "A", "Politics", "Government", "Seeing Like a State", "James C. Scott"),
("555", "A", "Politics", "Law", "The Rule of Law", "Tom Bingham"),
("556", "A", "Politics", "Politics", "The Road to Unfreedom", "Timothy Snyder"),
("557", "A", "Politics", "Democracy", "The People vs. Democracy", "Yascha Mounk"),
("558", "B", "Politics", "Politics", "Politics", "Aristotle"),
("559", "A", "Politics", "Governance", "The Fifth Risk", "Michael Lewis"),
("560", "A", "Politics", "Institutions", "Why Nations Fail", "Daron Acemoglu; James Robinson"),
("561", "S", "Power", "Power", "The Prince", "Niccolò Machiavelli"),
("562", "S", "Power", "Strategy", "The Art of War", "Sun Tzu"),
("563", "S", "Power", "Strategy", "On War", "Carl von Clausewitz"),
("564", "S", "Power", "Strategy", "The Strategy of Conflict", "Thomas Schelling"),
("565", "A", "Power", "Strategy", "The 33 Strategies of War", "Robert Greene"),
("566", "A", "Power", "Diplomacy", "Diplomacy", "Henry Kissinger"),
("567", "A", "Power", "Geography", "Prisoners of Geography", "Tim Marshall"),
("568", "S", "Power", "Geography", "The Revenge of Geography", "Robert Kaplan"),
("569", "S", "Power", "Geopolitics", "The Tragedy of Great Power Politics", "John Mearsheimer"),
("570", "A", "Power", "World Order", "The Changing World Order", "Ray Dalio"),
("571", "A", "Power", "Geopolitics", "The Grand Chessboard", "Zbigniew Brzezinski"),
("572", "A", "Power", "Geopolitics", "The World", "Richard Haass"),
("573", "A", "Power", "Strategy", "Strategy: A History", "Lawrence Freedman"),
("574", "A", "Power", "Power", "Power: Why Some People Have It and Others Don't", "Jeffrey Pfeffer"),
("575", "A", "Power", "Power", "The 48 Laws of Power", "Robert Greene"),
("576", "B", "Power", "War", "The Face of Battle", "John Keegan"),
("577", "A", "Power", "China", "The Party and the People", "Bruce Dickson"),
("578", "A", "Power", "Russia", "Putin's World", "Angela Stent"),
("579", "A", "Power", "Geopolitics", "The New Map", "Daniel Yergin"),
("580", "A", "Power", "International Relations", "The Hell of Good Intentions", "Stephen Walt"),
("581", "S", "Philosophy", "Stoicism", "Meditations", "Marcus Aurelius"),
("582", "S", "Philosophy", "Stoicism", "Letters from a Stoic", "Seneca"),
("583", "S", "Philosophy", "Stoicism", "Discourses", "Epictetus"),
("584", "S", "Philosophy", "Ethics", "Nicomachean Ethics", "Aristotle"),
("585", "S", "Philosophy", "Philosophy", "The Republic", "Plato"),
("586", "S", "Philosophy", "Philosophy", "Beyond Good and Evil", "Friedrich Nietzsche"),
("587", "S", "Philosophy", "Philosophy", "On the Genealogy of Morality", "Friedrich Nietzsche"),
("588", "A", "Philosophy", "Existentialism", "The Myth of Sisyphus", "Albert Camus"),
("589", "S", "Philosophy", "Philosophy", "The Problems of Philosophy", "Bertrand Russell"),
("590", "S", "Philosophy", "Philosophy", "A History of Western Philosophy", "Bertrand Russell"),
("591", "S", "Philosophy", "Meaning", "Man's Search for Meaning", "Viktor Frankl"),
("592", "S", "Philosophy", "Eastern Philosophy", "Tao Te Ching", "Lao Tzu"),
("593", "S", "Philosophy", "Indian Philosophy", "Bhagavad Gita", "traditional"),
("594", "A", "Philosophy", "Philosophy", "The Consolation of Philosophy", "Boethius"),
("595", "A", "Philosophy", "Ethics", "The Elements of Moral Philosophy", "James Rachels"),
("596", "A", "Philosophy", "Ethics", "Practical Ethics", "Peter Singer"),
("597", "A", "Philosophy", "Philosophy", "Sophie's World", "Jostein Gaarder"),
("598", "A", "Philosophy", "Philosophy", "The Story of Philosophy", "Will Durant"),
("599", "A", "Philosophy", "Philosophy", "Justice", "Michael Sandel"),
("600", "A", "Philosophy", "Meaning", "The Denial of Death", "Ernest Becker"),
("601", "S", "Technology", "AI Future", "Life 3.0", "Max Tegmark"),
("602", "S", "Technology", "AI Safety", "Superintelligence", "Nick Bostrom"),
("603", "S", "Technology", "AI Safety", "Human Compatible", "Stuart Russell"),
("604", "S", "Technology", "AI Alignment", "The Alignment Problem", "Brian Christian"),
("605", "A", "Technology", "Technology", "The Coming Wave", "Mustafa Suleyman; Michael Bhaskar"),
("606", "A", "Technology", "AI", "Co-Intelligence", "Ethan Mollick"),
("607", "S", "Technology", "AI Economics", "Power and Prediction", "Ajay Agrawal; Joshua Gans; Avi Goldfarb"),
("608", "S", "Technology", "AI Economics", "Prediction Machines", "Ajay Agrawal; Joshua Gans; Avi Goldfarb"),
("609", "S", "Technology", "Technology", "The Second Machine Age", "Erik Brynjolfsson; Andrew McAfee"),
("610", "S", "Technology", "Technology", "The Master Switch", "Tim Wu"),
("611", "S", "Technology", "Computing History", "The Innovators", "Walter Isaacson"),
("612", "A", "Technology", "Biotechnology", "The Code Breaker", "Walter Isaacson"),
("613", "B", "Technology", "Future", "The Future Is Faster Than You Think", "Peter Diamandis; Steven Kotler"),
("614", "S", "Technology", "Technology Society", "The Age of Surveillance Capitalism", "Shoshana Zuboff"),
("615", "S", "Technology", "Technology Economics", "Technological Revolutions and Financial Capital", "Carlota Perez"),
("616", "A", "Technology", "Automation", "Rise of the Robots", "Martin Ford"),
("617", "A", "Technology", "Future", "The Singularity Is Nearer", "Ray Kurzweil"),
("618", "A", "Technology", "Technology", "The Industries of the Future", "Alec Ross"),
("619", "A", "Technology", "Computing", "The Cathedral and the Bazaar", "Eric Raymond"),
("620", "A", "Technology", "Open Source", "The Innovator's Hypothesis", "Michael Raynor"),
("621", "S", "Biography", "Biography", "Steve Jobs", "Walter Isaacson"),
("622", "S", "Biography", "Investing", "The Snowball", "Alice Schroeder"),
("623", "S", "Biography", "Business", "Shoe Dog", "Phil Knight"),
("624", "S", "Biography", "Investing", "A Man for All Markets", "Edward Thorp"),
("625", "A", "Biography", "Business", "The Ride of a Lifetime", "Robert Iger"),
("626", "S", "Biography", "Business", "Made in America", "Sam Walton"),
("627", "A", "Biography", "Business", "Grinding It Out", "Ray Kroc"),
("628", "A", "Biography", "Business", "The Everything Store", "Brad Stone"),
("629", "A", "Biography", "Biography", "Elon Musk", "Walter Isaacson"),
("630", "S", "Biography", "Biography", "Leonardo da Vinci", "Walter Isaacson"),
("631", "S", "Biography", "Biography", "Einstein", "Walter Isaacson"),
("632", "S", "Biography", "Biography", "Benjamin Franklin: An American Life", "Walter Isaacson"),
("633", "S", "Biography", "Memoir", "Long Walk to Freedom", "Nelson Mandela"),
("634", "S", "Biography", "Memoir", "The Diary of a Young Girl", "Anne Frank"),
("635", "S", "Biography", "Science", "Surely You're Joking, Mr. Feynman!", "Richard Feynman"),
("636", "A", "Biography", "Science", "What Do You Care What Other People Think?", "Richard Feynman"),
("637", "S", "Biography", "Biography", "The Autobiography of Benjamin Franklin", "Benjamin Franklin"),
("638", "S", "Biography", "Business", "Titan", "Ron Chernow"),
("639", "S", "Biography", "Biography", "Alexander Hamilton", "Ron Chernow"),
("640", "S", "Biography", "Biography", "Grant", "Ron Chernow"),
("641", "A", "AI", "History", "The Master Algorithm", "Pedro Domingos"),
("642", "A", "AI", "Society", "The AI Revolution in Medicine", "Eric Topol"),
("643", "A", "AI", "Agents", "Artificial Intelligence: A Guide for Thinking Humans", "Melanie Mitchell"),
("644", "A", "AI", "Intelligence", "The Quest for Artificial Intelligence", "Nils Nilsson"),
("645", "A", "AI", "Deep Learning", "Grokking Deep Learning", "Andrew Trask"),
("646", "A", "AI", "PyTorch", "Machine Learning with PyTorch and Scikit-Learn", "Sebastian Raschka et al."),
("647", "A", "AI", "Data", "Python Data Science Handbook", "Jake VanderPlas"),
("648", "A", "AI", "Data", "Effective Pandas", "Matt Harrison"),
("649", "A", "AI", "Data", "Data Science from Scratch", "Joel Grus"),
("650", "A", "AI", "ML", "Machine Learning Yearning", "Andrew Ng"),
("651", "A", "Security", "Foundations", "The Web Application Hacker's Handbook", "Dafydd Stuttard; Marcus Pinto"),
("652", "A", "Security", "Engineering", "Security Engineering", "Ross Anderson"),
("653", "A", "Security", "Web", "Web Hacking 101", "Peter Yaworski"),
("654", "A", "Security", "Cryptography", "Cryptography Engineering", "Niels Ferguson; Bruce Schneier; Tadayoshi Kohno"),
("655", "A", "Security", "Privacy", "Permanent Record", "Edward Snowden"),
("656", "A", "Security", "Privacy", "Data and Goliath", "Bruce Schneier"),
("657", "A", "Security", "Internet", "Future Crimes", "Marc Goodman"),
("658", "A", "Security", "Psychology", "Social Engineering", "Christopher Hadnagy"),
("659", "A", "Security", "Threats", "The Art of Deception", "Kevin Mitnick"),
("660", "A", "Security", "History", "Ghost in the Wires", "Kevin Mitnick"),
("661", "A", "Web", "JavaScript", "Eloquent JavaScript", "Marijn Haverbeke"),
("662", "A", "Web", "JavaScript", "You Don't Know JS Yet", "Kyle Simpson"),
("663", "A", "Web", "TypeScript", "Effective TypeScript", "Dan Vanderkam"),
("664", "A", "Web", "Node", "Node.js Design Patterns", "Mario Casciaro; Luciano Mammino"),
("665", "A", "Web", "Frontend", "Refactoring UI", "Adam Wathan; Steve Schoger"),
("666", "A", "Web", "UX", "Don't Make Me Think, Revisited", "Steve Krug"),
("667", "A", "Web", "UX", "About Face", "Alan Cooper et al."),
("668", "A", "Web", "APIs", "Web API Design", "Brian Mulloy"),
("669", "A", "Web", "Performance", "High Performance Browser Networking", "Ilya Grigorik"),
("670", "A", "Web", "Web", "Designing Web APIs", "Brenda Jin; Saurabh Sahni; Amir Shevat"),
("671", "A", "Cloud", "AWS", "AWS Certified Solutions Architect Study Guide", "Ben Piper; David Clinton"),
("672", "A", "Cloud", "Architecture", "Cloud Architecture Patterns", "Bill Wilder"),
("673", "A", "Cloud", "Distributed", "Building Secure and Reliable Systems", "Google SRE team"),
("674", "A", "Cloud", "Reliability", "Seeking SRE", "David Blank-Edelman; Betsy Beyer et al."),
("675", "A", "Cloud", "Kubernetes", "Kubernetes Patterns", "Bilgin Ibryam; Roland Huß"),
("676", "A", "Cloud", "Containers", "Docker Deep Dive", "Nigel Poulton"),
("677", "A", "Cloud", "Infrastructure", "Terraform: Up & Running", "Yevgeniy Brikman"),
("678", "A", "Cloud", "Observability", "Distributed Systems Observability", "Cindy Sridharan"),
("679", "A", "Cloud", "Serverless", "Serverless Architectures on AWS", "Peter Sbarski"),
("680", "B", "Cloud", "FinOps", "Cloud FinOps", "J.R. Storment; Mike Fuller"),
("681", "A", "Data Engineering", "Data Engineering", "Fundamentals of Data Engineering", "Joe Reis; Matt Housley"),
("682", "A", "Data Engineering", "Data Engineering", "Designing Event-Driven Systems", "Ben Stopford"),
("683", "A", "Data Engineering", "Data Engineering", "Streaming Systems", "Tyler Akidau; Slava Chernyak; Reuven Lax"),
("684", "A", "Data Engineering", "Data Engineering", "Kafka: The Definitive Guide", "Neha Narkhede; Gwen Shapira; Todd Palino"),
("685", "A", "Data Engineering", "Data Engineering", "Learning Spark", "Jules Damji; Brooke Wenig; Tathagata Das; Denny Lee"),
("686", "A", "Data Engineering", "Data Engineering", "The Data Warehouse Toolkit", "Ralph Kimball; Margy Ross"),
("687", "A", "Data Engineering", "Data Engineering", "Building a Data Lakehouse", "Bill Inmon; Mary Levins; Ranjeet Srivastava"),
("688", "A", "Data Engineering", "Data Engineering", "Data Mesh", "Zhamak Dehghani"),
("689", "A", "Data Engineering", "Data Engineering", "Data Pipelines Pocket Reference", "James Densmore"),
("690", "B", "Data Engineering", "Data Engineering", "Data Management at Scale", "Piethein Strengholt"),
("691", "A", "Product", "Analytics", "Lean Analytics", "Alistair Croll; Benjamin Yoskovitz"),
("692", "A", "Product", "Metrics", "Escaping the Build Trap", "Melissa Perri"),
("693", "A", "Product", "Growth", "Product-Led Growth", "Wes Bush"),
("694", "A", "Product", "Strategy", "The Lean Product Playbook", "Dan Olsen"),
("695", "A", "Product", "Discovery", "Continuous Discovery Habits", "Teresa Torres"),
("696", "A", "Product", "UX", "The Mom Test", "Rob Fitzpatrick"),
("697", "A", "Product", "Strategy", "Obviously Awesome", "April Dunford"),
("698", "A", "Product", "Pricing", "Monetizing Innovation", "Madhavan Ramanujam; Georg Tacke"),
("699", "A", "Product", "Marketplace", "The Cold Start Problem", "Andrew Chen"),
("700", "A", "Product", "Product", "The Innovator's DNA", "Jeff Dyer; Hal Gregersen; Clayton Christensen"),
("701", "A", "Marketing", "Marketing", "This Is Marketing", "Seth Godin"),
("702", "A", "Marketing", "Marketing", "Positioning", "Al Ries; Jack Trout"),
("703", "A", "Marketing", "Marketing", "Alchemy", "Rory Sutherland"),
("704", "A", "Marketing", "Marketing", "Contagious", "Jonah Berger"),
("705", "A", "Marketing", "Marketing", "Building a StoryBrand", "Donald Miller"),
("706", "A", "Marketing", "Marketing", "Traction", "Gabriel Weinberg; Justin Mares"),
("707", "A", "Marketing", "Marketing", "Permission Marketing", "Seth Godin"),
("708", "A", "Marketing", "Marketing", "Purple Cow", "Seth Godin"),
("709", "A", "Marketing", "Marketing", "Cashvertising", "Drew Eric Whitman"),
("710", "A", "Marketing", "Marketing", "Tested Advertising Methods", "John Caples"),
("711", "A", "Sales", "Sales", "SPIN Selling", "Neil Rackham"),
("712", "A", "Sales", "Sales", "The Challenger Sale", "Brent Adamson; Matthew Dixon"),
("713", "A", "Sales", "Sales", "To Sell Is Human", "Daniel Pink"),
("714", "A", "Sales", "Sales", "Fanatical Prospecting", "Jeb Blount"),
("715", "A", "Sales", "Sales", "The Psychology of Selling", "Brian Tracy"),
("716", "A", "Sales", "Sales", "Gap Selling", "Keenan"),
("717", "A", "Sales", "Sales", "The Qualified Sales Leader", "John McMahon"),
("718", "A", "Sales", "Sales", "Let's Get Real or Let's Not Play", "Mahan Khalsa"),
("719", "A", "Sales", "Sales", "New Sales. Simplified.", "Mike Weinberg"),
("720", "B", "Sales", "Sales", "Influence Is Your Superpower", "Zoe Chance"),
("721", "A", "Accounting", "Accounting", "Financial Intelligence", "Karen Berman; Joe Knight"),
("722", "A", "Accounting", "Accounting", "Accounting Made Simple", "Mike Piper"),
("723", "A", "Finance", "Corporate", "Investment Banking", "Joshua Rosenbaum; Joshua Pearl"),
("724", "A", "Finance", "Valuation", "Valuation", "Tim Koller; Marc Goedhart; David Wessels"),
("725", "A", "Finance", "Valuation", "Damodaran on Valuation", "Aswath Damodaran"),
("726", "A", "Finance", "Corporate", "Applied Corporate Finance", "Aswath Damodaran"),
("727", "A", "Finance", "Accounting", "Quality of Earnings", "Thornton O'Glove"),
("728", "A", "Finance", "Fraud", "Financial Shenanigans", "Howard Schilit; Jeremy Perler"),
("729", "A", "Finance", "Capital", "Capital Allocators", "Ted Seides"),
("730", "A", "Finance", "Private Equity", "The Masters of Private Equity", "David Finkel; Claudio Feser"),
("731", "A", "Investing", "Quant", "Advances in Financial Machine Learning", "Marcos López de Prado"),
("732", "A", "Investing", "Quant", "Machine Learning for Asset Managers", "Marcos López de Prado"),
("733", "A", "Investing", "Trading", "Algorithmic Trading", "Ernest Chan"),
("734", "A", "Investing", "Trading", "Quantitative Trading", "Ernest Chan"),
("735", "A", "Investing", "Markets", "Market Wizards", "Jack Schwager"),
("736", "A", "Investing", "Markets", "The New Market Wizards", "Jack Schwager"),
("737", "A", "Investing", "Trading", "Reminiscences of a Stock Operator", "Edwin Lefèvre"),
("738", "A", "Investing", "Behavioral", "The Psychology of Trading", "Brett Steenbarger"),
("739", "A", "Investing", "Risk", "The Failure of Risk Management", "Douglas Hubbard"),
("740", "A", "Investing", "Bubbles", "Devil Take the Hindmost", "Edward Chancellor"),
("741", "A", "Economics", "Macro", "Macroeconomics", "Olivier Blanchard"),
("742", "A", "Economics", "Micro", "Intermediate Microeconomics", "Hal Varian"),
("743", "A", "Economics", "Development", "Development as Freedom", "Amartya Sen"),
("744", "A", "Economics", "Trade", "The Worldly Philosophers", "Robert Heilbroner"),
("745", "A", "Economics", "Inequality", "The Great Leveler", "Walter Scheidel"),
("746", "A", "Economics", "Growth", "Why Nations Fail", "Daron Acemoglu; James Robinson"),
("747", "A", "Economics", "India", "The Billionaire Raj", "James Crabtree"),
("748", "A", "Economics", "India", "Whole Numbers and Half Truths", "Rukmini S"),
("749", "A", "Economics", "China", "Red Flags", "George Magnus"),
("750", "A", "Economics", "Globalization", "The World Is Flat", "Thomas Friedman"),
("751", "A", "Philosophy", "Logic", "A Rulebook for Arguments", "Anthony Weston"),
("752", "A", "Philosophy", "Mind", "Consciousness Explained", "Daniel Dennett"),
("753", "A", "Philosophy", "Mind", "The Conscious Mind", "David Chalmers"),
("754", "A", "Philosophy", "Mind", "Being You", "Anil Seth"),
("755", "A", "Philosophy", "Ethics", "The Expanding Circle", "Peter Singer"),
("756", "A", "Philosophy", "Free Will", "Determined", "Robert Sapolsky"),
("757", "A", "Philosophy", "Free Will", "Free Will", "Sam Harris"),
("758", "A", "Philosophy", "Knowledge", "Knowledge and Its Limits", "Timothy Williamson"),
("759", "A", "Philosophy", "Language", "Philosophical Investigations", "Ludwig Wittgenstein"),
("760", "A", "Philosophy", "Logic", "Tractatus Logico-Philosophicus", "Ludwig Wittgenstein"),
("761", "A", "History", "Ancient", "The Histories", "Herodotus"),
("762", "A", "History", "Ancient", "The Peloponnesian War", "Thucydides"),
("763", "A", "History", "Rome", "The Twelve Caesars", "Suetonius"),
("764", "A", "History", "Rome", "The History of the Decline and Fall of the Roman Empire", "Edward Gibbon"),
("765", "A", "History", "Medieval", "The Crusades", "Thomas Asbridge"),
("766", "A", "History", "Renaissance", "The Renaissance", "Paul Johnson"),
("767", "A", "History", "Europe", "The Pursuit of Power", "Richard J. Evans"),
("768", "A", "History", "Britain", "The English and Their History", "Robert Tombs"),
("769", "A", "History", "China", "The Search for Modern China", "Jonathan Spence"),
("770", "A", "History", "Japan", "A Modern History of Japan", "Andrew Gordon"),
("771", "A", "India", "Ancient", "The Penguin History of Early India", "Romila Thapar"),
("772", "A", "India", "Medieval", "A History of Medieval India", "Satish Chandra"),
("773", "A", "India", "Modern", "India's Struggle for Independence", "Bipan Chandra et al."),
("774", "A", "India", "Politics", "The Great Indian Middle Class", "Pavan K. Varma"),
("775", "A", "India", "Economy", "India Grows at Night", "Gurcharan Das"),
("776", "A", "India", "Society", "Price of the Modi Years", "Aakar Patel"),
("777", "A", "India", "Constitution", "The Indian Constitution: Cornerstone of a Nation", "Granville Austin"),
("778", "A", "India", "Judiciary", "The Court and the Constitution of India: Summits and Shallows", "O. Chinnappa Reddy"),
("779", "A", "India", "Business", "The Tata Story", "Peter Casey"),
("780", "A", "India", "Business", "The Creation of Wealth: The Tatas from the 19th to the 21st Century", "R. M. Lala"),
("781", "A", "Geopolitics", "China", "The Hundred-Year Marathon", "Michael Pillsbury"),
("782", "A", "Geopolitics", "China", "The Third Revolution", "Elizabeth Economy"),
("783", "A", "Geopolitics", "Russia", "The New Tsar", "Steven Lee Myers"),
("784", "A", "Geopolitics", "Middle East", "The New Arabs", "Marwan Muasher"),
("785", "A", "Geopolitics", "India", "The India Way: Strategies for an Uncertain World", "S. Jaishankar"),
("786", "A", "Geopolitics", "War", "The Future of Power", "Joseph Nye"),
("787", "A", "Geopolitics", "Power", "Soft Power", "Joseph Nye"),
("788", "A", "Geopolitics", "Strategy", "The Future of War", "Lawrence Freedman"),
("789", "A", "Geopolitics", "International Relations", "The Anarchical Society", "Hedley Bull"),
("790", "A", "Geopolitics", "World Order", "World Order", "Henry Kissinger"),
("791", "A", "Sociology", "Networks", "Six Degrees", "Duncan Watts"),
("792", "A", "Sociology", "Culture", "The Culture Map", "Erin Meyer"),
("793", "A", "Sociology", "Institutions", "The Logic of Collective Action", "Mancur Olson"),
("794", "A", "Sociology", "Society", "The Great Society", "Amity Shlaes"),
("795", "A", "Sociology", "Inequality", "The Color of Law", "Richard Rothstein"),
("796", "A", "Sociology", "Cities", "Triumph of the City", "Edward Glaeser"),
("797", "A", "Sociology", "Urbanism", "Order Without Design", "Alain Bertaud"),
("798", "A", "Sociology", "Population", "Empty Planet", "Darrell Bricker; John Ibbitson"),
("799", "A", "Sociology", "Demography", "The Great Demographic Reversal", "Charles Goodhart; Manoj Pradhan"),
("800", "A", "Sociology", "Population", "Factfulness", "Hans Rosling"),
]
