from __future__ import annotations

# Domain 09: Philosophy, Ethics & Decision-Making (130 books: #1331–#1460)
BOOKS_09 = [
    # -------------------------------------------------------------------------
    # LEVEL 2: 01. CLASSICAL & MODERN PHILOSOPHY (40 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: ANCIENT PHILOSOPHY (15 books)
    # LEVEL 4: Greek Philosophy (5 books)
    {"title": "The Republic", "author": "Plato", "first_published": "-375", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Greek Philosophy", "slug": "The-Republic-Plato"},
    {"title": "Nicomachean Ethics", "author": "Aristotle", "first_published": "-340", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Greek Philosophy", "slug": "Nicomachean-Ethics"},
    {"title": "The Trial and Death of Socrates", "author": "Plato", "first_published": "-399", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Greek Philosophy", "slug": "The-Trial-and-Death-of-Socrates"},
    {"title": "The Symposium", "author": "Plato", "first_published": "-385", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Greek Philosophy", "slug": "The-Symposium-Plato"},
    {"title": "Politics", "author": "Aristotle", "first_published": "-335", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Greek Philosophy", "slug": "Politics-Aristotle"},

    # LEVEL 4: Roman Stoicism (5 books)
    {"title": "Meditations", "author": "Marcus Aurelius", "first_published": "180", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Roman Stoicism", "slug": "Meditations-Marcus-Aurelius"},
    {"title": "Letters from a Stoic", "author": "Lucius Annaeus Seneca", "first_published": "65", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Roman Stoicism", "slug": "Letters-from-a-Stoic-Seneca"},
    {"title": "Discourses and Selected Writings", "author": "Epictetus", "first_published": "108", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Roman Stoicism", "slug": "Discourses-Epictetus"},
    {"title": "On the Shortness of Life", "author": "Lucius Annaeus Seneca", "first_published": "49", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Roman Stoicism", "slug": "On-the-Shortness-of-Life-Seneca"},
    {"title": "The Inner Citadel: The Meditations of Marcus Aurelius", "author": "Pierre Hadot", "first_published": "1998", "latest_published": "2001", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Roman Stoicism", "slug": "The-Inner-Citadel-Hadot"},

    # LEVEL 4: Eastern Philosophy (5 books)
    {"title": "Tao Te Ching", "author": "Laozi", "first_published": "-400", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Eastern Philosophy", "slug": "Tao-Te-Ching"},
    {"title": "The Analects", "author": "Confucius", "first_published": "-479", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Eastern Philosophy", "slug": "The-Analects-Confucius"},
    {"title": "The Bhagavad Gita", "author": "Vyasa (Eknath Easwaran Trans.)", "first_published": "-200", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Eastern Philosophy", "slug": "The-Bhagavad-Gita"},
    {"title": "Zhuangzi: The Essential Writings", "author": "Zhuangzi (Brook Ziporyn Trans.)", "first_published": "-300", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Eastern Philosophy", "slug": "Zhuangzi-Essential-Writings"},
    {"title": "Zen Mind, Beginner's Mind", "author": "Shunryu Suzuki", "first_published": "1970", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Eastern Philosophy", "slug": "Zen-Mind-Beginners-Mind"},

    # LEVEL 3: MODERN PHILOSOPHY (15 books)
    # LEVEL 4: Enlightenment Philosophy (5 books)
    {"title": "Meditations on First Philosophy", "author": "René Descartes", "first_published": "1641", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Enlightenment Philosophy", "slug": "Meditations-on-First-Philosophy"},
    {"title": "An Enquiry Concerning Human Understanding", "author": "David Hume", "first_published": "1748", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Enlightenment Philosophy", "slug": "An-Enquiry-Concerning-Human-Understanding"},
    {"title": "Critique of Pure Reason", "author": "Immanuel Kant", "first_published": "1781", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Enlightenment Philosophy", "slug": "Critique-of-Pure-Reason"},
    {"title": "Ethics", "author": "Baruch Spinoza", "first_published": "1677", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Enlightenment Philosophy", "slug": "Ethics-Spinoza"},
    {"title": "An Essay Concerning Human Understanding", "author": "John Locke", "first_published": "1689", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Enlightenment Philosophy", "slug": "An-Essay-Concerning-Human-Understanding"},

    # LEVEL 4: Existentialism (5 books)
    {"title": "Beyond Good and Evil: Prelude to a Philosophy of the Future", "author": "Friedrich Nietzsche", "first_published": "1886", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Existentialism", "slug": "Beyond-Good-and-Evil"},
    {"title": "Thus Spoke Zarathustra", "author": "Friedrich Nietzsche", "first_published": "1883", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Existentialism", "slug": "Thus-Spoke-Zarathustra"},
    {"title": "Being and Nothingness: An Essay on Phenomenological Ontology", "author": "Jean-Paul Sartre", "first_published": "1943", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Existentialism", "slug": "Being-and-Nothingness"},
    {"title": "The Myth of Sisyphus", "author": "Albert Camus", "first_published": "1942", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Existentialism", "slug": "The-Myth-of-Sisyphus"},
    {"title": "Fear and Trembling", "author": "Søren Kierkegaard", "first_published": "1843", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Existentialism", "slug": "Fear-and-Trembling"},

    # LEVEL 4: Pragmatism (5 books)
    {"title": "Pragmatism: A New Name for Some Old Ways of Thinking", "author": "William James", "first_published": "1907", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pragmatism", "slug": "Pragmatism-James"},
    {"title": "The Will to Believe and Other Essays in Popular Philosophy", "author": "William James", "first_published": "1897", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pragmatism", "slug": "The-Will-to-Believe"},
    {"title": "Democracy and Education: An Introduction to the Philosophy of Education", "author": "John Dewey", "first_published": "1916", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pragmatism", "slug": "Democracy-and-Education-Dewey"},
    {"title": "Philosophy and the Mirror of Nature", "author": "Richard Rorty", "first_published": "1979", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pragmatism", "slug": "Philosophy-and-the-Mirror-of-Nature"},
    {"title": "Contingency, Irony, and Solidarity", "author": "Richard Rorty", "first_published": "1989", "latest_published": "1989", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pragmatism", "slug": "Contingency-Irony-and-Solidarity"},

    # LEVEL 3: EPISTEMOLOGY (10 books)
    # LEVEL 4: Nature of Knowledge (5 books)
    {"title": "The Problems of Philosophy", "author": "Bertrand Russell", "first_published": "1912", "latest_published": "2001", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nature of Knowledge", "slug": "The-Problems-of-Philosophy"},
    {"title": "A History of Western Philosophy", "author": "Bertrand Russell", "first_published": "1945", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nature of Knowledge", "slug": "A-History-of-Western-Philosophy-Russell"},
    {"title": "Tractatus Logico-Philosophicus", "author": "Ludwig Wittgenstein", "first_published": "1921", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nature of Knowledge", "slug": "Tractatus-Logico-Philosophicus"},
    {"title": "Philosophical Investigations", "author": "Ludwig Wittgenstein", "first_published": "1953", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nature of Knowledge", "slug": "Philosophical-Investigations"},
    {"title": "Epistemology: A Contemporary Introduction to the Theory of Knowledge", "author": "Robert Audi", "first_published": "1998", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nature of Knowledge", "slug": "Epistemology-Audi"},

    # LEVEL 4: Truth & Reality (5 books)
    {"title": "Truth and Truthfulness: An Essay in Genealogy", "author": "Bernard Williams", "first_published": "2002", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Truth & Reality", "slug": "Truth-and-Truthfulness-Williams"},
    {"title": "On Bullshit", "author": "Harry G. Frankfurt", "first_published": "2005", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Truth & Reality", "slug": "On-Bullshit"},
    {"title": "The View from Nowhere", "author": "Thomas Nagel", "first_published": "1986", "latest_published": "1989", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Truth & Reality", "slug": "The-View-from-Nowhere"},
    {"title": "Mortal Questions", "author": "Thomas Nagel", "first_published": "1979", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Truth & Reality", "slug": "Mortal-Questions-Nagel"},
    {"title": "Mind and Cosmos: Why the Materialist Neo-Darwinian Conception of Nature Is Almost Certainly False", "author": "Thomas Nagel", "first_published": "2012", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Truth & Reality", "slug": "Mind-and-Cosmos"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 02. ETHICS & MORAL PHILOSOPHY (35 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: MORAL THEORIES (15 books)
    # LEVEL 4: Utilitarianism (5 books)
    {"title": "Utilitarianism", "author": "John Stuart Mill", "first_published": "1861", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Utilitarianism", "slug": "Utilitarianism-Mill"},
    {"title": "On Liberty", "author": "John Stuart Mill", "first_published": "1859", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Utilitarianism", "slug": "On-Liberty-Mill"},
    {"title": "Practical Ethics", "author": "Peter Singer", "first_published": "1979", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Utilitarianism", "slug": "Practical-Ethics-Singer"},
    {"title": "Animal Liberation: The Definitive Classic of the Animal Movement", "author": "Peter Singer", "first_published": "1975", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Utilitarianism", "slug": "Animal-Liberation-Singer"},
    {"title": "The Life You Can Save: Acting Now to End World Poverty", "author": "Peter Singer", "first_published": "2009", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Utilitarianism", "slug": "The-Life-You-Can-Save"},

    # LEVEL 4: Deontology & Virtue (5 books)
    {"title": "Groundwork of the Metaphysics of Morals", "author": "Immanuel Kant", "first_published": "1785", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deontology & Virtue", "slug": "Groundwork-of-the-Metaphysics-of-Morals"},
    {"title": "After Virtue: A Study in Moral Theory", "author": "Alasdair MacIntyre", "first_published": "1981", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deontology & Virtue", "slug": "After-Virtue"},
    {"title": "Whose Justice? Which Rationality?", "author": "Alasdair MacIntyre", "first_published": "1988", "latest_published": "1989", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deontology & Virtue", "slug": "Whose-Justice-Which-Rationality"},
    {"title": "The Sovereignty of Good", "author": "Iris Murdoch", "first_published": "1970", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deontology & Virtue", "slug": "The-Sovereignty-of-Good"},
    {"title": "Natural Goodness", "author": "Philippa Foot", "first_published": "2001", "latest_published": "2003", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deontology & Virtue", "slug": "Natural-Goodness-Foot"},

    # LEVEL 4: Modern Moral Philosophy (5 books)
    {"title": "Reasons and Persons", "author": "Derek Parfit", "first_published": "1984", "latest_published": "1986", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Moral Philosophy", "slug": "Reasons-and-Persons"},
    {"title": "On What Matters: Volume 1", "author": "Derek Parfit", "first_published": "2011", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Moral Philosophy", "slug": "On-What-Matters-Vol-1"},
    {"title": "On What Matters: Volume 2", "author": "Derek Parfit", "first_published": "2011", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Moral Philosophy", "slug": "On-What-Matters-Vol-2"},
    {"title": "What We Owe to Each Other", "author": "T.M. Scanlon", "first_published": "1998", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Moral Philosophy", "slug": "What-We-Owe-to-Each-Other"},
    {"title": "Moral Thinking: Its Levels, Method, and Point", "author": "R.M. Hare", "first_published": "1981", "latest_published": "1982", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Moral Philosophy", "slug": "Moral-Thinking-Hare"},

    # LEVEL 3: APPLIED ETHICS (10 books)
    # LEVEL 4: Bioethics & Tech Ethics (5 books)
    {"title": "Principles of Biomedical Ethics", "author": "Tom L. Beauchamp; James F. Childress", "first_published": "1979", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bioethics & Tech Ethics", "slug": "Principles-of-Biomedical-Ethics"},
    {"title": "The Case Against Perfection: Ethics in the Age of Genetic Engineering", "author": "Michael J. Sandel", "first_published": "2007", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bioethics & Tech Ethics", "slug": "The-Case-Against-Perfection"},
    {"title": "Technology and the Virtues: A Philosophical Guide to a Future Worth Wanting", "author": "Shannon Vallor", "first_published": "2016", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bioethics & Tech Ethics", "slug": "Technology-and-the-Virtues"},
    {"title": "Future Morality: 12 Decisions We Need to Make About the Future of the Human Race", "author": "David Edmonds", "first_published": "2023", "latest_published": "2023", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bioethics & Tech Ethics", "slug": "Future-Morality-Edmonds"},
    {"title": "Would You Kill the Fat Man?: The Trolley Problem and What Your Answer Tells Us about Right and Wrong", "author": "David Edmonds", "first_published": "2013", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bioethics & Tech Ethics", "slug": "Would-You-Kill-the-Fat-Man"},

    # LEVEL 4: Social Ethics (5 books)
    {"title": "Justice: What's the Right Thing to Do?", "author": "Michael J. Sandel", "first_published": "2009", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Ethics", "slug": "Justice-Sandel"},
    {"title": "What Money Can't Buy: The Moral Limits of Markets", "author": "Michael J. Sandel", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Ethics", "slug": "What-Money-Cant-Buy"},
    {"title": "The Tyranny of Merit: What's Become of the Common Good?", "author": "Michael J. Sandel", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Ethics", "slug": "The-Tyranny-of-Merit"},
    {"title": "Just Babies: The Origins of Good and Evil", "author": "Paul Bloom", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Ethics", "slug": "Just-Babies-Bloom"},
    {"title": "Moral Tribes: Emotion, Reason, and the Gap Between Us and Them", "author": "Joshua Greene", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Ethics", "slug": "Moral-Tribes-Greene"},

    # LEVEL 3: MEANING & GOOD LIFE (10 books)
    # LEVEL 4: The Good Life (5 books)
    {"title": "A Guide to the Good Life: The Ancient Art of Stoic Joy", "author": "William B. Irvine", "first_published": "2008", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "The Good Life", "slug": "A-Guide-to-the-Good-Life"},
    {"title": "The Stoic Challenge: A Philosopher's Guide to Becoming Tougher, Calmer, and More Resilient", "author": "William B. Irvine", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "The Good Life", "slug": "The-Stoic-Challenge"},
    {"title": "The Art of Living: The Classical Manual on Virtue, Happiness, and Effectiveness", "author": "Epictetus; Sharon Lebell", "first_published": "1995", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "The Good Life", "slug": "The-Art-of-Living-Epictetus"},
    {"title": "How to Be a Stoic: Using Ancient Philosophy to Live a Modern Life", "author": "Massimo Pigliucci", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "The Good Life", "slug": "How-to-Be-a-Stoic"},
    {"title": "A Field Guide to a Happy Life: 53 Brief Lessons for Living", "author": "Massimo Pigliucci", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "The Good Life", "slug": "A-Field-Guide-to-a-Happy-Life"},

    # LEVEL 4: Meaning of Life (5 books)
    {"title": "The Will to Meaning: Foundations and Applications of Logotherapy", "author": "Viktor E. Frankl", "first_published": "1969", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Meaning of Life", "slug": "The-Will-to-Meaning-Frankl"},
    {"title": "The Meaning of Things: Applying Philosophy to Life", "author": "A.C. Grayling", "first_published": "2001", "latest_published": "2002", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Meaning of Life", "slug": "The-Meaning-of-Things-Grayling"},
    {"title": "Philosophy for Life and Other Dangerous Situations: Ancient Philosophy for Modern Problems", "author": "Jules Evans", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Meaning of Life", "slug": "Philosophy-for-Life"},
    {"title": "Every Time I Find the Meaning of Life, They Change It: Wisdom of the Great Philosophers on How to Live", "author": "Daniel Klein", "first_published": "2015", "latest_published": "2016", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Meaning of Life", "slug": "Every-Time-I-Find-the-Meaning-of-Life"},
    {"title": "Life Is Hard: How Philosophy Can Help Us Find Our Way", "author": "Kieran Setiya", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Meaning of Life", "slug": "Life-Is-Hard-Setiya"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 03. DECISION-MAKING & PRACTICAL RATIONALITY (30 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: RATIONAL DECISION MAKING (15 books)
    # LEVEL 4: Decision Theory (5 books)
    {"title": "Decisive: How to Make Better Choices in Life and Work", "author": "Chip Heath; Dan Heath", "first_published": "2013", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decision Theory", "slug": "Decisive-Heath"},
    {"title": "Smart Choices: A Practical Guide to Making Better Decisions", "author": "John S. Hammond; Ralph L. Keeney; Howard Raiffa", "first_published": "1999", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decision Theory", "slug": "Smart-Choices"},
    {"title": "Value-Focused Thinking: A Path to Creative Decisionmaking", "author": "Ralph L. Keeney", "first_published": "1992", "latest_published": "1996", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decision Theory", "slug": "Value-Focused-Thinking"},
    {"title": "Decisions with Multiple Objectives: Preferences and Value Trade-Offs", "author": "Ralph L. Keeney; Howard Raiffa", "first_published": "1976", "latest_published": "1993", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decision Theory", "slug": "Decisions-with-Multiple-Objectives"},
    {"title": "The Art of Decision Making: How We Move from Indecision to Smart Action", "author": "Joseph Bikart", "first_published": "2019", "latest_published": "2019", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decision Theory", "slug": "The-Art-of-Decision-Making-Bikart"},

    # LEVEL 4: Cognitive Bias in Decisions (5 books)
    {"title": "Noise: A Flaw in Human Judgment", "author": "Daniel Kahneman; Olivier Sibony; Cass R. Sunstein", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Bias in Decisions", "slug": "Noise-Kahneman"},
    {"title": "You're About to Make a Terrible Mistake!: How Biases Distort Decision-Making and What You Can Do to Fight Them", "author": "Olivier Sibony", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Bias in Decisions", "slug": "Youre-About-to-Make-a-Terrible-Mistake"},
    {"title": "The Thinker's Toolkit: 14 Powerful Techniques for Problem Solving", "author": "Morgan D. Jones", "first_published": "1995", "latest_published": "1998", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Bias in Decisions", "slug": "The-Thinkers-Toolkit"},
    {"title": "Seeing What Others Don't: The Remarkable Ways We Gain Insights", "author": "Gary Klein", "first_published": "2013", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Bias in Decisions", "slug": "Seeing-What-Others-Dont-Klein"},
    {"title": "Streetlights and Shadows: Searching for the Keys to Adaptive Decision Making", "author": "Gary Klein", "first_published": "2009", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Bias in Decisions", "slug": "Streetlights-and-Shadows"},

    # LEVEL 4: Probabilistic Decisions (5 books)
    {"title": "Thinking in Bets: Making Smarter Decisions When You Don't Have All the Facts", "author": "Annie Duke", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Probabilistic Decisions", "slug": "Thinking-in-Bets"},
    {"title": "How to Decide: Simple Tools for Making Better Choices", "author": "Annie Duke", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Probabilistic Decisions", "slug": "How-to-Decide-Duke"},
    {"title": "Decisions, Decisions: How to Get It Right Every Time", "author": "Robert H. Frank", "first_published": "2008", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Probabilistic Decisions", "slug": "Decisions-Decisions-Frank"},
    {"title": "Superforecasting: The Art and Science of Prediction", "author": "Philip E. Tetlock; Dan Gardner", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Probabilistic Decisions", "slug": "Superforecasting"},
    {"title": "Expert Political Judgment: How Good Is It? How Can We Know?", "author": "Philip E. Tetlock", "first_published": "2005", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Probabilistic Decisions", "slug": "Expert-Political-Judgment"},

    # LEVEL 3: MENTAL MODELS & FRAMEWORKS (15 books)
    # LEVEL 4: Systems Decisions (5 books)
    {"title": "The Great Mental Models Volume 1: General Thinking Concepts", "author": "Shane Parrish; Rhiannon Beaubien", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Systems Decisions", "slug": "The-Great-Mental-Models-Vol-1"},
    {"title": "The Great Mental Models Volume 2: Physics, Chemistry and Biology", "author": "Shane Parrish; Rhiannon Beaubien", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Systems Decisions", "slug": "The-Great-Mental-Models-Vol-2"},
    {"title": "The Great Mental Models Volume 3: Systems and Mathematics", "author": "Shane Parrish; Rhiannon Beaubien", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Systems Decisions", "slug": "The-Great-Mental-Models-Vol-3"},
    {"title": "Clear Thinking: Turning Ordinary Moments into Extraordinary Results", "author": "Shane Parrish", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Systems Decisions", "slug": "Clear-Thinking-Parrish"},
    {"title": "Super Thinking: The Big Book of Mental Models", "author": "Gabriel Weinberg; Lauren McCann", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Systems Decisions", "slug": "Super-Thinking"},

    # LEVEL 4: Strategic Heuristics (5 books)
    {"title": "Simple Rules: How to Thrive in a Complex World", "author": "Donald Sull; Kathleen M. Eisenhardt", "first_published": "2015", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Heuristics", "slug": "Simple-Rules"},
    {"title": "Simply Rational: Decision Making in the Real World", "author": "Gerd Gigerenzer", "first_published": "2015", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Heuristics", "slug": "Simply-Rational-Gigerenzer"},
    {"title": "Bounded Rationality: The Adaptive Toolbox", "author": "Gerd Gigerenzer; Reinhard Selten", "first_published": "2001", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Heuristics", "slug": "Bounded-Rationality-Gigerenzer"},
    {"title": "Calculated Risks: How to Know When Numbers Deceive You", "author": "Gerd Gigerenzer", "first_published": "2002", "latest_published": "2003", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Heuristics", "slug": "Calculated-Risks"},
    {"title": "Heuristics: How to Make Decisions Without Math", "author": "Gerd Gigerenzer; Peter M. Todd", "first_published": "2011", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Heuristics", "slug": "Heuristics-Gigerenzer"},

    # LEVEL 4: Long-Term Decisions (5 books)
    {"title": "The Clock of the Long Now: Time and Responsibility", "author": "Stewart Brand", "first_published": "1999", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Decisions", "slug": "The-Clock-of-the-Long-Now"},
    {"title": "Longpath: Becoming the Great Ancestors Our Future Needs", "author": "Ari Wallach", "first_published": "2022", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Decisions", "slug": "Longpath-Wallach"},
    {"title": "Farsighted: How We Make the Decisions That Matter the Most", "author": "Steven Johnson", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Decisions", "slug": "Farsighted-Johnson"},
    {"title": "The Scout Mindset: Why Some People See Things Clearly and Others Don't", "author": "Julia Galef", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Decisions", "slug": "The-Scout-Mindset-Decisions"},
    {"title": "Algorithms to Live By: The Computer Science of Human Decisions", "author": "Brian Christian; Tom Griffiths", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Decisions", "slug": "Algorithms-to-Live-By-Phil"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 04. POLITICAL PHILOSOPHY (25 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: JUSTICE & RIGHTS (10 books)
    # LEVEL 4: Theories of Justice (5 books)
    {"title": "A Theory of Justice", "author": "John Rawls", "first_published": "1971", "latest_published": "1999", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Theories of Justice", "slug": "A-Theory-of-Justice-Rawls"},
    {"title": "Political Liberalism", "author": "John Rawls", "first_published": "1993", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Theories of Justice", "slug": "Political-Liberalism"},
    {"title": "Justice as Fairness: A Restatement", "author": "John Rawls", "first_published": "2001", "latest_published": "2001", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Theories of Justice", "slug": "Justice-as-Fairness"},
    {"title": "The Idea of Justice", "author": "Amartya Sen", "first_published": "2009", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Theories of Justice", "slug": "The-Idea-of-Justice-Sen"},
    {"title": "Spheres of Justice: A Defense of Pluralism and Equality", "author": "Michael Walzer", "first_published": "1983", "latest_published": "1984", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Theories of Justice", "slug": "Spheres-of-Justice"},

    # LEVEL 4: Human Rights & Freedom (5 books)
    {"title": "Anarchy, State, and Utopia", "author": "Robert Nozick", "first_published": "1974", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Rights & Freedom", "slug": "Anarchy-State-and-Utopia"},
    {"title": "Two Concepts of Liberty", "author": "Isaiah Berlin", "first_published": "1958", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Rights & Freedom", "slug": "Two-Concepts-of-Liberty"},
    {"title": "The Crooked Timber of Humanity: Chapters in the History of Ideas", "author": "Isaiah Berlin", "first_published": "1990", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Rights & Freedom", "slug": "The-Crooked-Timber-of-Humanity"},
    {"title": "Taking Rights Seriously", "author": "Ronald Dworkin", "first_published": "1977", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Rights & Freedom", "slug": "Taking-Rights-Seriously"},
    {"title": "Justice for Hedgehogs", "author": "Ronald Dworkin", "first_published": "2011", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Rights & Freedom", "slug": "Justice-for-Hedgehogs-Dworkin"},

    # LEVEL 3: GOVERNANCE & POWER (15 books)
    # LEVEL 4: Political Order (5 books)
    {"title": "Leviathan", "author": "Thomas Hobbes", "first_published": "1651", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Political Order", "slug": "Leviathan-Hobbes"},
    {"title": "Two Treatises of Government", "author": "John Locke", "first_published": "1689", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Political Order", "slug": "Two-Treatises-of-Government"},
    {"title": "The Social Contract", "author": "Jean-Jacques Rousseau", "first_published": "1762", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Political Order", "slug": "The-Social-Contract-Rousseau"},
    {"title": "The Spirit of the Laws", "author": "Montesquieu", "first_published": "1748", "latest_published": "1989", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Political Order", "slug": "The-Spirit-of-the-Laws"},
    {"title": "The Prince", "author": "Niccolò Machiavelli", "first_published": "1532", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Political Order", "slug": "The-Prince-Machiavelli"},

    # LEVEL 4: Liberty & State (5 books)
    {"title": "The Constitution of Liberty", "author": "Friedrich A. Hayek", "first_published": "1960", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Liberty & State", "slug": "The-Constitution-of-Liberty"},
    {"title": "Law, Legislation and Liberty, Volume 1: Rules and Order", "author": "Friedrich A. Hayek", "first_published": "1973", "latest_published": "1983", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Liberty & State", "slug": "Law-Legislation-and-Liberty-Vol-1"},
    {"title": "Law, Legislation and Liberty, Volume 2: The Mirage of Social Justice", "author": "Friedrich A. Hayek", "first_published": "1976", "latest_published": "1983", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Liberty & State", "slug": "Law-Legislation-and-Liberty-Vol-2"},
    {"title": "The Open Society and Its Enemies", "author": "Karl Popper", "first_published": "1945", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Liberty & State", "slug": "The-Open-Society-and-Its-Enemies"},
    {"title": "The Poverty of Historicism", "author": "Karl Popper", "first_published": "1957", "latest_published": "2002", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Liberty & State", "slug": "The-Poverty-of-Historicism"},

    # LEVEL 4: Democracy & Institutions (5 books)
    {"title": "Democracy in America", "author": "Alexis de Tocqueville", "first_published": "1835", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Democracy & Institutions", "slug": "Democracy-in-America-Tocqueville"},
    {"title": "The Federalist Papers", "author": "Alexander Hamilton; James Madison; John Jay", "first_published": "1788", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Democracy & Institutions", "slug": "The-Federalist-Papers"},
    {"title": "Reflections on the Revolution in France", "author": "Edmund Burke", "first_published": "1790", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Democracy & Institutions", "slug": "Reflections-on-the-Revolution-in-France"},
    {"title": "On Revolution", "author": "Hannah Arendt", "first_published": "1963", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Democracy & Institutions", "slug": "On-Revolution-Arendt"},
    {"title": "The Human Condition", "author": "Hannah Arendt", "first_published": "1958", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Democracy & Institutions", "slug": "The-Human-Condition-Arendt"},
]
