from __future__ import annotations

# Domain 12: Society, Politics, Law & Public Policy (100 books: #1831–#1930)
BOOKS_12 = [
    # -------------------------------------------------------------------------
    # LEVEL 2: 01. POLITICAL SYSTEMS & GOVERNANCE (35 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: DEMOCRATIC INSTITUTIONS (15 books)
    # LEVEL 4: Democratic Health (5 books)
    {"title": "How Democracies Die", "author": "Steven Levitsky; Daniel Ziblatt", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Democratic Health", "slug": "How-Democracies-Die"},
    {"title": "Tyranny of the Minority: Why American Democracy Reached the Breaking Point", "author": "Steven Levitsky; Daniel Ziblatt", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Democratic Health", "slug": "Tyranny-of-the-Minority"},
    {"title": "The Twilight of Democracy: The Seductive Lure of Authoritarianism", "author": "Anne Applebaum", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Democratic Health", "slug": "Twilight-of-Democracy-Applebaum"},
    {"title": "On Tyranny: Twenty Lessons from the Twentieth Century", "author": "Timothy Snyder", "first_published": "2017", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Democratic Health", "slug": "On-Tyranny-Snyder"},
    {"title": "The Road to Unfreedom: Russia, Europe, America", "author": "Timothy Snyder", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Democratic Health", "slug": "The-Road-to-Unfreedom"},

    # LEVEL 4: Authoritarianism & Populism (5 books)
    {"title": "The People vs. Democracy: Why Our Freedom Is in Danger and How to Save It", "author": "Yascha Mounk", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Authoritarianism & Populism", "slug": "The-People-vs-Democracy"},
    {"title": "The Great Experiment: Why Diverse Democracies Fall Apart and How They Can Endure", "author": "Yascha Mounk", "first_published": "2022", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Authoritarianism & Populism", "slug": "The-Great-Experiment-Mounk"},
    {"title": "Autocracy, Inc.: The Dictators Who Want to Run the World", "author": "Anne Applebaum", "first_published": "2024", "latest_published": "2024", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Authoritarianism & Populism", "slug": "Autocracy-Inc-Applebaum"},
    {"title": "Strongmen: Mussolini to the Present", "author": "Ruth Ben-Ghiat", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Authoritarianism & Populism", "slug": "Strongmen-Ben-Ghiat"},
    {"title": "Surviving Autocracy", "author": "Masha Gessen", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Authoritarianism & Populism", "slug": "Surviving-Autocracy-Gessen"},

    # LEVEL 4: Voting & Elections (5 books)
    {"title": "Why We're Polarized", "author": "Ezra Klein", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Voting & Elections", "slug": "Why-Were-Polarized-Klein"},
    {"title": "It's Even Worse Than It Looks: How the American Constitutional System Collided With the New Politics of Extremism", "author": "Thomas E. Mann; Norman J. Ornstein", "first_published": "2012", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Voting & Elections", "slug": "Its-Even-Worse-Than-It-Looks"},
    {"title": "Give Us the Ballot: The Modern Struggle for Voting Rights in America", "author": "Ari Berman", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Voting & Elections", "slug": "Give-Us-the-Ballot-Berman"},
    {"title": "Uncivil Agreement: How Politics Became Our Identity", "author": "Lilliana Mason", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Voting & Elections", "slug": "Uncivil-Agreement-Mason"},
    {"title": "One Person, No Vote: How Voter Suppression Is Destroying Our Democracy", "author": "Carol Anderson", "first_published": "2018", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Voting & Elections", "slug": "One-Person-No-Vote"},

    # LEVEL 3: POLITICAL ECONOMY (10 books)
    # LEVEL 4: State & Economy (5 books)
    {"title": "Capital in the Twenty-First Century", "author": "Thomas Piketty", "first_published": "2013", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "State & Economy", "slug": "Capital-in-the-Twenty-First-Century"},
    {"title": "Capital and Ideology", "author": "Thomas Piketty", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "State & Economy", "slug": "Capital-and-Ideology-Piketty"},
    {"title": "A Brief History of Equality", "author": "Thomas Piketty", "first_published": "2021", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "State & Economy", "slug": "A-Brief-History-of-Equality-Piketty"},
    {"title": "The Great Transformation: The Political and Economic Origins of Our Time", "author": "Karl Polanyi", "first_published": "1944", "latest_published": "2001", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "State & Economy", "slug": "The-Great-Transformation-Polanyi"},
    {"title": "The Fatal Conceit: The Errors of Socialism", "author": "Friedrich A. Hayek", "first_published": "1988", "latest_published": "1991", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "State & Economy", "slug": "The-Fatal-Conceit-Hayek"},

    # LEVEL 4: Wealth & Power (5 books)
    {"title": "Dark Money: The Hidden History of the Billionaires Behind the Rise of the Radical Right", "author": "Jane Mayer", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Wealth & Power", "slug": "Dark-Money-Jane-Mayer"},
    {"title": "Winner-Take-All Politics: How Washington Made the Rich Richer--and Turned Its Back on the Middle Class", "author": "Jacob S. Hacker; Paul Pierson", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Wealth & Power", "slug": "Winner-Take-All-Politics"},
    {"title": "Let Them Eat Tweets: How the Right Rules in an Age of Extreme Inequality", "author": "Jacob S. Hacker; Paul Pierson", "first_published": "2020", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Wealth & Power", "slug": "Let-Them-Eat-Tweets"},
    {"title": "Democracy in Chains: The Deep History of the Radical Right's Stealth Plan for America", "author": "Nancy MacLean", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Wealth & Power", "slug": "Democracy-in-Chains-MacLean"},
    {"title": "The Triumph of Injustice: How the Rich Dodge Taxes and How to Make Them Pay", "author": "Emmanuel Saez; Gabriel Zucman", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Wealth & Power", "slug": "The-Triumph-of-Injustice"},

    # LEVEL 3: PUBLIC POLICY (10 books)
    # LEVEL 4: Policy Design (5 books)
    {"title": "A Practical Guide for Policy Analysis: The Eightfold Path to More Effective Problem Solving", "author": "Eugene Bardach; Eric M. Patashnik", "first_published": "2000", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Policy Design", "slug": "A-Practical-Guide-for-Policy-Analysis"},
    {"title": "Policy Paradox: The Art of Political Decision Making", "author": "Deborah Stone", "first_published": "1988", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Policy Design", "slug": "Policy-Paradox-Stone"},
    {"title": "Agendas, Alternatives, and Public Policies", "author": "John W. Kingdon", "first_published": "1984", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Policy Design", "slug": "Agendas-Alternatives-and-Public-Policies"},
    {"title": "Show Me the Evidence: Obama's Fight for Rigor and Results in Social Policy", "author": "Ron Haskins; Greg Margolis", "first_published": "2014", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Policy Design", "slug": "Show-Me-the-Evidence"},
    {"title": "The Logic of Collective Action: Public Goods and the Theory of Groups", "author": "Mancur Olson", "first_published": "1965", "latest_published": "1971", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Policy Design", "slug": "The-Logic-of-Collective-Action-Olson"},

    # LEVEL 4: Regulation & Lawmaking (5 books)
    {"title": "Nudge: Improving Decisions About Health, Wealth, and Happiness", "author": "Richard H. Thaler; Cass R. Sunstein", "first_published": "2008", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Regulation & Lawmaking", "slug": "Nudge-Thaler-Sunstein"},
    {"title": "Simpler: The Future of Government", "author": "Cass R. Sunstein", "first_published": "2013", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Regulation & Lawmaking", "slug": "Simpler-Sunstein"},
    {"title": "The Cost-Benefit Revolution", "author": "Cass R. Sunstein", "first_published": "2018", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Regulation & Lawmaking", "slug": "The-Cost-Benefit-Revolution"},
    {"title": "Sludge: Bureaucrats, Law, and the Hidden Tax of Paperwork", "author": "Cass R. Sunstein", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Regulation & Lawmaking", "slug": "Sludge-Sunstein"},
    {"title": "Administrative Law and Regulatory Policy: Problems, Text, and Cases", "author": "Stephen G. Breyer; Richard B. Stewart; Cass R. Sunstein; Adrian Vermeule", "first_published": "1979", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Regulation & Lawmaking", "slug": "Administrative-Law-and-Regulatory-Policy"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 02. LAW & JURISPRUDENCE (35 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: LEGAL PHILOSOPHY (10 books)
    # LEVEL 4: Jurisprudence (5 books)
    {"title": "The Concept of Law", "author": "H.L.A. Hart", "first_published": "1961", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Jurisprudence", "slug": "The-Concept-of-Law-Hart"},
    {"title": "The Morality of Law", "author": "Lon L. Fuller", "first_published": "1964", "latest_published": "1969", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Jurisprudence", "slug": "The-Morality-of-Law-Fuller"},
    {"title": "Law's Empire", "author": "Ronald Dworkin", "first_published": "1986", "latest_published": "1986", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Jurisprudence", "slug": "Laws-Empire-Society"},
    {"title": "Justice in Robes", "author": "Ronald Dworkin", "first_published": "2006", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Jurisprudence", "slug": "Justice-in-Robes-Dworkin"},
    {"title": "Pure Theory of Law", "author": "Hans Kelsen", "first_published": "1934", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Jurisprudence", "slug": "Pure-Theory-of-Law-Kelsen"},

    # LEVEL 4: Constitutional Law (5 books)
    {"title": "The Words That Made Us: America's Constitutional Conversation, 1760-1840", "author": "Akhil Reed Amar", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Constitutional Law", "slug": "The-Words-That-Made-Us-Amar"},
    {"title": "The Bill of Rights: Creation and Reconstruction", "author": "Akhil Reed Amar", "first_published": "1998", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Constitutional Law", "slug": "The-Bill-of-Rights-Amar"},
    {"title": "Making Our Democracy Work: A Judge's View", "author": "Stephen Breyer", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Constitutional Law", "slug": "Making-Our-Democracy-Work-Breyer"},
    {"title": "Reading Law: The Interpretation of Legal Texts", "author": "Antonin Scalia; Bryan A. Garner", "first_published": "2012", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Constitutional Law", "slug": "Reading-Law-Scalia"},
    {"title": "A Matter of Interpretation: Federal Courts and the Law", "author": "Antonin Scalia", "first_published": "1997", "latest_published": "1998", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Constitutional Law", "slug": "A-Matter-of-Interpretation-Scalia"},

    # LEVEL 3: LAW & SOCIETY (15 books)
    # LEVEL 4: Justice Systems (5 books)
    {"title": "Just Mercy: A Story of Justice and Redemption", "author": "Bryan Stevenson", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Justice Systems", "slug": "Just-Mercy-Stevenson"},
    {"title": "The New Jim Crow: Mass Incarceration in the Age of Colorblindness", "author": "Michelle Alexander", "first_published": "2010", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Justice Systems", "slug": "The-New-Jim-Crow"},
    {"title": "Charged: The New Movement to Transform American Prosecution and End Mass Incarceration", "author": "Emily Bazelon", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Justice Systems", "slug": "Charged-Bazelon"},
    {"title": "Usual Cruelty: The Complicity of Lawyers in the Criminal Injustice System", "author": "Alec Karakatsanis", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Justice Systems", "slug": "Usual-Cruelty-Karakatsanis"},
    {"title": "Gideon's Trumpet", "author": "Anthony Lewis", "first_published": "1964", "latest_published": "1989", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Justice Systems", "slug": "Gideons-Trumpet-Lewis"},

    # LEVEL 4: Criminal Justice (5 books)
    {"title": "Punishment and Inequality in America", "author": "Bruce Western", "first_published": "2006", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Criminal Justice", "slug": "Punishment-and-Inequality-in-America"},
    {"title": "Locking Up Our Own: Crime and Punishment in Black America", "author": "James Forman Jr.", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Criminal Justice", "slug": "Locking-Up-Our-Own-Forman"},
    {"title": "Bleeding Out: The Devastating Consequences of Urban Violence--and a Bold New Plan for Peace in the Streets", "author": "Thomas Abt", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Criminal Justice", "slug": "Bleeding-Out-Abt"},
    {"title": "The Collapse of American Criminal Justice", "author": "William J. Stuntz", "first_published": "2011", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Criminal Justice", "slug": "The-Collapse-of-American-Criminal-Justice"},
    {"title": "In Cold Blood", "author": "Truman Capote", "first_published": "1966", "latest_published": "1994", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Criminal Justice", "slug": "In-Cold-Blood-Capote"},

    # LEVEL 4: Civil Rights & Liberties (5 books)
    {"title": "Freedom for the Thought That We Hate: A Biography of the First Amendment", "author": "Anthony Lewis", "first_published": "2007", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civil Rights & Liberties", "slug": "Freedom-for-the-Thought-That-We-Hate"},
    {"title": "The Color of Law: A Forgotten History of How Our Government Segregated America", "author": "Richard Rothstein", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civil Rights & Liberties", "slug": "The-Color-of-Law-Rothstein"},
    {"title": "Just Action: How to Challenge Segregation Enacted Under the Color of Law", "author": "Richard Rothstein; Leah Rothstein", "first_published": "2023", "latest_published": "2023", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civil Rights & Liberties", "slug": "Just-Action-Rothstein"},
    {"title": "My Beloved World", "author": "Sonia Sotomayor", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civil Rights & Liberties", "slug": "My-Beloved-World-Sotomayor"},
    {"title": "Notorious RBG: The Life and Times of Ruth Bader Ginsburg", "author": "Irin Carmon; Shana Knizhnik", "first_published": "2015", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civil Rights & Liberties", "slug": "Notorious-RBG"},

    # LEVEL 3: INTERNATIONAL LAW (10 books)
    # LEVEL 4: Global Governance (5 books)
    {"title": "The Internationalists: How a Radical Plan to Outlaw War Remade the World", "author": "Oona A. Hathaway; Scott J. Shapiro", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Governance", "slug": "The-Internationalists-Hathaway"},
    {"title": "Governing the World: The History of an Idea, 1815 to the Present", "author": "Mark Mazower", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Governance", "slug": "Governing-the-World-Mazower"},
    {"title": "No Enchanted Palace: The End of Empire and the Ideological Origins of the United Nations", "author": "Mark Mazower", "first_published": "2009", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Governance", "slug": "No-Enchanted-Palace"},
    {"title": "The Parliament of Man: The Past, Present, and Future of the United Nations", "author": "Paul Kennedy", "first_published": "2006", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Governance", "slug": "The-Parliament-of-Man-Kennedy"},
    {"title": "International Law: A Very Short Introduction", "author": "Vaughan Lowe", "first_published": "2007", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Governance", "slug": "International-Law-Lowe"},

    # LEVEL 4: Human Rights Law (5 books)
    {"title": "A Problem from Hell: America and the Age of Genocide", "author": "Samantha Power", "first_published": "2002", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Rights Law", "slug": "A-Problem-from-Hell-Power"},
    {"title": "The Last Utopia: Human Rights in History", "author": "Samuel Moyn", "first_published": "2010", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Rights Law", "slug": "The-Last-Utopia-Moyn"},
    {"title": "Not Enough: Human Rights in an Unequal World", "author": "Samuel Moyn", "first_published": "2018", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Rights Law", "slug": "Not-Enough-Moyn"},
    {"title": "Humane: How the United States Abandoned Peace and Reinvented War", "author": "Samuel Moyn", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Rights Law", "slug": "Humane-Moyn"},
    {"title": "East West Street: On the Origins of Genocide and Crimes Against Humanity", "author": "Philippe Sands", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Rights Law", "slug": "East-West-Street-Sands"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 03. SOCIAL STRUCTURE & POLICY (30 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: INEQUALITY & CLASS (15 books)
    # LEVEL 4: Economic Inequality (5 books)
    {"title": "Evicted: Poverty and Profit in the American City", "author": "Matthew Desmond", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Economic Inequality", "slug": "Evicted-Matthew-Desmond"},
    {"title": "Poverty, by America", "author": "Matthew Desmond", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Economic Inequality", "slug": "Poverty-by-America-Desmond"},
    {"title": "The Price of Inequality: How Today's Divided Society Endangers Our Future", "author": "Joseph E. Stiglitz", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Economic Inequality", "slug": "The-Price-of-Inequality-Stiglitz"},
    {"title": "People, Power, and Profits: Progressive Capitalism for an Age of Discontent", "author": "Joseph E. Stiglitz", "first_published": "2019", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Economic Inequality", "slug": "People-Power-and-Profits-Stiglitz"},
    {"title": "The Great Escape: Health, Wealth, and the Origins of Inequality", "author": "Angus Deaton", "first_published": "2013", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Economic Inequality", "slug": "The-Great-Escape-Deaton"},

    # LEVEL 4: Social Mobility (5 books)
    {"title": "Deaths of Despair and the Future of Capitalism", "author": "Anne Case; Angus Deaton", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Mobility", "slug": "Deaths-of-Despair-Case-Deaton"},
    {"title": "Our Kids: The American Dream in Crisis", "author": "Robert D. Putnam", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Mobility", "slug": "Our-Kids-Putnam"},
    {"title": "Bowling Alone: The Collapse and Revival of American Community", "author": "Robert D. Putnam", "first_published": "2000", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Mobility", "slug": "Bowling-Alone-Putnam"},
    {"title": "The Upswing: How America Came Together a Century Ago and How We Can Do It Again", "author": "Robert D. Putnam; Shaylyn Romney Garrett", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Mobility", "slug": "The-Upswing-Putnam"},
    {"title": "Dream Hoarders: How the American Upper Middle Class Is Leaving Everyone Else in the Dust", "author": "Richard V. Reeves", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Mobility", "slug": "Dream-Hoarders-Reeves"},

    # LEVEL 4: Poverty Policy (5 books)
    {"title": "Nickel and Dimed: On (Not) Getting By in America", "author": "Barbara Ehrenreich", "first_published": "2001", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Poverty Policy", "slug": "Nickel-and-Dimed-Ehrenreich"},
    {"title": "Bait and Switch: The (Futile) Pursuit of the American Dream", "author": "Barbara Ehrenreich", "first_published": "2005", "latest_published": "2006", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Poverty Policy", "slug": "Bait-and-Switch-Ehrenreich"},
    {"title": "Bright-Sided: How the Relentless Promotion of Positive Thinking Has Undermined America", "author": "Barbara Ehrenreich", "first_published": "2009", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Poverty Policy", "slug": "Bright-Sided-Ehrenreich"},
    {"title": "$2.00 a Day: Living on Almost Nothing in America", "author": "Kathryn J. Edin; H. Luke Shaefer", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Poverty Policy", "slug": "2-Dollars-a-Day-Edin"},
    {"title": "Promises I Can Keep: Why Poor Women Put Motherhood Before Marriage", "author": "Kathryn Edin; Maria J. Kefalas", "first_published": "2005", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Poverty Policy", "slug": "Promises-I-Can-Keep-Edin"},

    # LEVEL 3: MODERN INSTITUTIONS (15 books)
    # LEVEL 4: Education Systems (5 books)
    {"title": "The Death and Life of the Great American School System: How Testing and Choice Are Undermining Education", "author": "Diane Ravitch", "first_published": "2010", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Education Systems", "slug": "The-Death-and-Life-of-the-Great-American-School-System"},
    {"title": "Reign of Error: The Hoax of the Privatization Movement and the Danger to America's Public Schools", "author": "Diane Ravitch", "first_published": "2013", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Education Systems", "slug": "Reign-of-Error-Ravitch"},
    {"title": "The Smartest Kids in the World: And How They Got That Way", "author": "Amanda Ripley", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Education Systems", "slug": "The-Smartest-Kids-in-the-World"},
    {"title": "Creative Schools: The Grassroots Revolution That's Transforming Education", "author": "Ken Robinson; Lou Aronica", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Education Systems", "slug": "Creative-Schools-Robinson"},
    {"title": "The Case Against Education: Why the Education System Is a Waste of Time and Money", "author": "Bryan Caplan", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Education Systems", "slug": "The-Case-Against-Education"},

    # LEVEL 4: Healthcare Systems (5 books)
    {"title": "The Healing of America: A Global Quest for Better, Cheaper, and Fairer Health Care", "author": "T.R. Reid", "first_published": "2009", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Healthcare Systems", "slug": "The-Healing-of-America-Reid"},
    {"title": "An American Sickness: How Healthcare Became Big Business and How You Can Take It Back", "author": "Elisabeth Rosenthal", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Healthcare Systems", "slug": "An-American-Sickness-Rosenthal"},
    {"title": "Better: A Surgeon's Notes on Performance", "author": "Atul Gawande", "first_published": "2007", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Healthcare Systems", "slug": "Better-Atul-Gawande"},
    {"title": "Being Mortal: Medicine and What Matters in the End", "author": "Atul Gawande", "first_published": "2014", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Healthcare Systems", "slug": "Being-Mortal-Society"},
    {"title": "Complications: A Surgeon's Notes on an Imperfect Science", "author": "Atul Gawande", "first_published": "2002", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Healthcare Systems", "slug": "Complications-Gawande"},

    # LEVEL 4: Urban Policy (5 books)
    {"title": "The Death and Life of Great American Cities", "author": "Jane Jacobs", "first_published": "1961", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Urban Policy", "slug": "The-Death-and-Life-of-Great-American-Cities"},
    {"title": "The Economy of Cities", "author": "Jane Jacobs", "first_published": "1969", "latest_published": "1970", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Urban Policy", "slug": "The-Economy-of-Cities"},
    {"title": "Triumph of the City: How Our Greatest Invention Makes Us Richer, Smarter, Greener, Healthier, and Happier", "author": "Edward Glaeser", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Urban Policy", "slug": "Triumph-of-the-City-Glaeser"},
    {"title": "Survival of the City: Living and Thriving in an Age of Isolation", "author": "Edward Glaeser; David Cutler", "first_published": "2021", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Urban Policy", "slug": "Survival-of-the-City"},
    {"title": "Happy City: Transforming Our Lives Through Urban Design", "author": "Charles Montgomery", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Urban Policy", "slug": "Happy-City-Montgomery"},
]
