from __future__ import annotations

# Domain 01: Learning, Thinking & Knowledge (180 books: #0001–#0180)
BOOKS_01 = [
    # -------------------------------------------------------------------------
    # LEVEL 2: 01. LEARNING SCIENCE (45 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: HOW LEARNING WORKS (15 books)
    # LEVEL 4: Memory & Retention (5 books)
    {"title": "Make It Stick: The Science of Successful Learning", "author": "Peter C. Brown; Henry L. Roediger III; Mark A. McDaniel", "first_published": "2014", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Memory & Retention", "slug": "Make-It-Stick"},
    {"title": "How We Learn: The Surprising Truth About When, Where, and Why It Happens", "author": "Benedict Carey", "first_published": "2014", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Memory & Retention", "slug": "How-We-Learn"},
    {"title": "Moonwalking with Einstein: The Art and Science of Remembering Everything", "author": "Joshua Foer", "first_published": "2011", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Memory & Retention", "slug": "Moonwalking-with-Einstein"},
    {"title": "The Memory Illusion: Remembering, Forgetting, and the Science of False Memory", "author": "Julia Shaw", "first_published": "2016", "latest_published": "2017", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Memory & Retention", "slug": "The-Memory-Illusion"},
    {"title": "Remember: The Science of Memory and the Art of Forgetting", "author": "Lisa Genova", "first_published": "2021", "latest_published": "2022", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Memory & Retention", "slug": "Remember"},

    # LEVEL 4: Retrieval Practice (5 books)
    {"title": "Powerful Teaching: Unleash the Science of Learning", "author": "Pooja K. Agarwal; Patrice M. Bain", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Retrieval Practice", "slug": "Powerful-Teaching"},
    {"title": "Small Teaching: Everyday Lessons from the Science of Learning", "author": "James M. Lang", "first_published": "2016", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Retrieval Practice", "slug": "Small-Teaching"},
    {"title": "Understanding How We Learn: A Visual Guide", "author": "Yana Weinstein; Megan Sumeracki; Oliver Caviglioli", "first_published": "2018", "latest_published": "2019", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Retrieval Practice", "slug": "Understanding-How-We-Learn"},
    {"title": "Learning and Memory: From Brain to Behavior", "author": "Mark A. Gluck; Eduardo Mercado; Catherine E. Myers", "first_published": "2007", "latest_published": "2019", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Retrieval Practice", "slug": "Learning-and-Memory"},
    {"title": "The Science of Learning: 99 Studies That Every Teacher Needs to Know", "author": "Edward Watson; Bradley Busch", "first_published": "2019", "latest_published": "2021", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Retrieval Practice", "slug": "The-Science-of-Learning"},

    # LEVEL 4: Spaced Learning (5 books)
    {"title": "A Mind for Numbers: How to Excel at Math and Science", "author": "Barbara Oakley", "first_published": "2014", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Spaced Learning", "slug": "A-Mind-for-Numbers"},
    {"title": "How Learning Works: 7 Research-Based Principles for Smart Teaching", "author": "Susan A. Ambrose; Michael W. Bridges; Michele DiPietro", "first_published": "2010", "latest_published": "2023", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Spaced Learning", "slug": "How-Learning-Works"},
    {"title": "Learning as a Generative Activity: Eight Learning Strategies that Promote Understanding", "author": "Logan Fiorella; Richard E. Mayer", "first_published": "2015", "latest_published": "2015", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Spaced Learning", "slug": "Learning-as-a-Generative-Activity"},
    {"title": "The Principles of Psychology", "author": "William James", "first_published": "1890", "latest_published": "2012", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Spaced Learning", "slug": "The-Principles-of-Psychology"},
    {"title": "Memory: A Contribution to Experimental Psychology", "author": "Hermann Ebbinghaus", "first_published": "1885", "latest_published": "2013", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Spaced Learning", "slug": "Memory-Ebbinghaus"},

    # LEVEL 3: SKILL ACQUISITION (15 books)
    # LEVEL 4: Deliberate Practice (5 books)
    {"title": "Peak: Secrets from the New Science of Expertise", "author": "Anders Ericsson; Robert Pool", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deliberate Practice", "slug": "Peak"},
    {"title": "Talent Is Overrated: What Really Separates World-Class Performers from Everybody Else", "author": "Geoff Colvin", "first_published": "2008", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deliberate Practice", "slug": "Talent-Is-Overrated"},
    {"title": "The Talent Code: Greatness Isn't Born. It's Grown. Here's How.", "author": "Daniel Coyle", "first_published": "2009", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deliberate Practice", "slug": "The-Talent-Code"},
    {"title": "The Little Book of Talent: 52 Tips for Improving Your Skills", "author": "Daniel Coyle", "first_published": "2012", "latest_published": "2012", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deliberate Practice", "slug": "The-Little-Book-of-Talent"},
    {"title": "The Cambridge Handbook of Expertise and Expert Performance", "author": "K. Anders Ericsson", "first_published": "2006", "latest_published": "2018", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deliberate Practice", "slug": "Cambridge-Handbook-of-Expertise"},

    # LEVEL 4: Feedback Loops (5 books)
    {"title": "Thanks for the Feedback: The Science and Art of Receiving Feedback Well", "author": "Douglas Stone; Sheila Heen", "first_published": "2014", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Feedback Loops", "slug": "Thanks-for-the-Feedback"},
    {"title": "The Feedback Imperative: How to Give Everyday Feedback to Speed Up Your Team's Success", "author": "Anna Carroll", "first_published": "2014", "latest_published": "2014", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Feedback Loops", "slug": "The-Feedback-Imperative"},
    {"title": "Radical Candor: Be a Kick-Ass Boss Without Losing Your Humanity", "author": "Kim Scott", "first_published": "2017", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Feedback Loops", "slug": "Radical-Candor"},
    {"title": "Feedback That Works: How to Build and Deliver Your Message", "author": "Sloan R. Weitzel", "first_published": "2000", "latest_published": "2007", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Feedback Loops", "slug": "Feedback-That-Works"},
    {"title": "The Power of Feedback", "author": "John Hattie; Helen Timperley", "first_published": "2007", "latest_published": "2007", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Feedback Loops", "slug": "The-Power-of-Feedback"},

    # LEVEL 4: Building Expertise (5 books)
    {"title": "Mastery", "author": "Robert Greene", "first_published": "2012", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Expertise", "slug": "Mastery-Greene"},
    {"title": "Range: Why Generalists Triumph in a Specialized World", "author": "David Epstein", "first_published": "2019", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Expertise", "slug": "Range"},
    {"title": "The Art of Learning: An Inner Journey to Optimal Performance", "author": "Josh Waitzkin", "first_published": "2007", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Expertise", "slug": "The-Art-of-Learning"},
    {"title": "Expert: Understanding the Path to Mastery", "author": "Roger Kneebone", "first_published": "2020", "latest_published": "2021", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Expertise", "slug": "Expert-Kneebone"},
    {"title": "Sources of Power: How People Make Decisions", "author": "Gary Klein", "first_published": "1998", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Expertise", "slug": "Sources-of-Power"},

    # LEVEL 3: META-LEARNING (15 books)
    # LEVEL 4: Learning How to Learn (5 books)
    {"title": "Ultralearning: Master Hard Skills, Outsmart the Competition, and Accelerate Your Career", "author": "Scott H. Young", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Learning How to Learn", "slug": "Ultralearning"},
    {"title": "Learn Like a Pro: Science-Based Tools to Become Better at Anything", "author": "Barbara Oakley; Olav Schewe", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Learning How to Learn", "slug": "Learn-Like-a-Pro"},
    {"title": "Mindshift: Break Through Obstacles to Learning and Discover Your Hidden Potential", "author": "Barbara Oakley", "first_published": "2017", "latest_published": "2017", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Learning How to Learn", "slug": "Mindshift"},
    {"title": "Limitless: Upgrade Your Brain, Learn Anything Faster, and Unlock Your Exceptional Life", "author": "Jim Kwik", "first_published": "2020", "latest_published": "2023", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Learning How to Learn", "slug": "Limitless"},
    {"title": "How We Learn: The New Science of Education and the Brain", "author": "Stanislas Dehaene", "first_published": "2020", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Learning How to Learn", "slug": "How-We-Learn-Dehaene"},

    # LEVEL 4: Accelerated Learning (5 books)
    {"title": "The First 20 Hours: How to Learn Anything... Fast!", "author": "Josh Kaufman", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Accelerated Learning", "slug": "The-First-20-Hours"},
    {"title": "Accelerated Learning for the 21st Century", "author": "Colin Rose; Malcolm J. Nicholl", "first_published": "1997", "latest_published": "1998", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Accelerated Learning", "slug": "Accelerated-Learning-21st-Century"},
    {"title": "Mastery: The Keys to Success and Long-Term Fulfillment", "author": "George Leonard", "first_published": "1992", "latest_published": "1992", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Accelerated Learning", "slug": "Mastery-Leonard"},
    {"title": "Super Reading: How to Read Faster and Retain More", "author": "Ron Cole", "first_published": "2018", "latest_published": "2020", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Accelerated Learning", "slug": "Super-Reading"},
    {"title": "The 4-Hour Chef: The Simple Path to Cooking Like a Pro, Learning Anything, and Living the Good Life", "author": "Timothy Ferriss", "first_published": "2012", "latest_published": "2012", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Accelerated Learning", "slug": "The-4-Hour-Chef"},

    # LEVEL 4: Self-Directed Learning (5 books)
    {"title": "How to Become a Straight-A Student", "author": "Cal Newport", "first_published": "2006", "latest_published": "2006", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Self-Directed Learning", "slug": "How-to-Become-a-Straight-A-Student"},
    {"title": "The Self-Directed Learning Handbook", "author": "Maurice Gibbons", "first_published": "2002", "latest_published": "2002", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Self-Directed Learning", "slug": "The-Self-Directed-Learning-Handbook"},
    {"title": "Deschooling Society", "author": "Ivan Illich", "first_published": "1971", "latest_published": "2002", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Self-Directed Learning", "slug": "Deschooling-Society"},
    {"title": "The Modern Scholar: How to Learn on Your Own", "author": "Blake Boles", "first_published": "2014", "latest_published": "2015", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Self-Directed Learning", "slug": "The-Modern-Scholar"},
    {"title": "Self-Directed Learner: The Path to Lifelong Education", "author": "Peter Hollins", "first_published": "2020", "latest_published": "2020", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Self-Directed Learning", "slug": "Self-Directed-Learner"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 02. CRITICAL THINKING & REASONING (45 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: LOGIC (15 books)
    # LEVEL 4: Formal Reasoning (5 books)
    {"title": "Introduction to Logic", "author": "Irving M. Copi; Carl Cohen; Victor Rodych", "first_published": "1953", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Formal Reasoning", "slug": "Introduction-to-Logic"},
    {"title": "Logic: The Basics", "author": "JC Beall", "first_published": "2010", "latest_published": "2017", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Formal Reasoning", "slug": "Logic-The-Basics"},
    {"title": "A Rulebook for Arguments", "author": "Anthony Weston", "first_published": "1987", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Formal Reasoning", "slug": "A-Rulebook-for-Arguments"},
    {"title": "Logicomix: An Epic Search for Truth", "author": "Apostolos Doxiadis; Christos Papadimitriou", "first_published": "2009", "latest_published": "2009", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Formal Reasoning", "slug": "Logicomix"},
    {"title": "Gödel, Escher, Bach: An Eternal Golden Braid", "author": "Douglas Hofstadter", "first_published": "1979", "latest_published": "1999", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Formal Reasoning", "slug": "Godel-Escher-Bach"},

    # LEVEL 4: Informal Logic (5 books)
    {"title": "Asking the Right Questions: A Guide to Critical Thinking", "author": "M. Neil Browne; Stuart M. Keeley", "first_published": "1981", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Informal Logic", "slug": "Asking-the-Right-Questions"},
    {"title": "Attacking Faulty Reasoning: A Practical Guide to Fallacy-Free Arguments", "author": "T. Edward Damer", "first_published": "1980", "latest_published": "2012", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Informal Logic", "slug": "Attacking-Faulty-Reasoning"},
    {"title": "Good Thinking: Seven Powerful Ideas That Influence the Way We Think", "author": "Guy P. Harrison", "first_published": "2015", "latest_published": "2015", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Informal Logic", "slug": "Good-Thinking"},
    {"title": "The Art of Reasoning: An Introduction to Logic and Critical Thinking", "author": "David Kelley", "first_published": "1988", "latest_published": "2013", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Informal Logic", "slug": "The-Art-of-Reasoning"},
    {"title": "Thinking from A to Z", "author": "Nigel Warburton", "first_published": "1996", "latest_published": "2007", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Informal Logic", "slug": "Thinking-from-A-to-Z"},

    # LEVEL 4: Logical Fallacies (5 books)
    {"title": "Logically Fallacious: The Ultimate Collection of Over 300 Logical Fallacies", "author": "Bo Bennett", "first_published": "2012", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Logical Fallacies", "slug": "Logically-Fallacious"},
    {"title": "An Illustrated Book of Bad Arguments", "author": "Ali Almossawi", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Logical Fallacies", "slug": "An-Illustrated-Book-of-Bad-Arguments"},
    {"title": "Crimes Against Logic: Exposing the Bogus Arguments of Politicians, Priests, Journalists, and Other Serial Offenders", "author": "Jamie Whyte", "first_published": "2004", "latest_published": "2005", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Logical Fallacies", "slug": "Crimes-Against-Logic"},
    {"title": "How to Win Every Argument: The Use and Abuse of Logic", "author": "Madsen Pirie", "first_published": "2006", "latest_published": "2015", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Logical Fallacies", "slug": "How-to-Win-Every-Argument"},
    {"title": "Bad Arguments: 100 of the Most Important Fallacies in Western Philosophy", "author": "Robert Arp; Steven Barbone; Michael Bruce", "first_published": "2018", "latest_published": "2019", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Logical Fallacies", "slug": "Bad-Arguments-Arp"},

    # LEVEL 3: DECISION-MAKING (15 books)
    # LEVEL 4: Mental Models (5 books)
    {"title": "Poor Charlie's Almanack: The Essential Wit and Wisdom of Charles T. Munger", "author": "Charles T. Munger; Peter D. Kaufman", "first_published": "2005", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mental Models", "slug": "Poor-Charlies-Almanack"},
    {"title": "Seeking Wisdom: From Darwin to Munger", "author": "Peter Bevelin", "first_published": "2003", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mental Models", "slug": "Seeking-Wisdom-Bevelin"},
    {"title": "All I Want To Know Is Where I'm Going To Die So I'll Never Go There: Buffett & Munger - A Study in Simplicity and Uncommon, Common Sense", "author": "Peter Bevelin", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mental Models", "slug": "All-I-Want-To-Know-Bevelin"},
    {"title": "Mental Models: 30 Thinking Tools that Separate the Average From the Exceptional", "author": "Peter Hollins", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mental Models", "slug": "Mental-Models-Peter-Hollins"},
    {"title": "The Model Thinker: What You Need to Know to Make Data Work for You", "author": "Scott E. Page", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mental Models", "slug": "The-Model-Thinker"},

    # LEVEL 4: Judgment Under Uncertainty (5 books)
    {"title": "Thinking, Fast and Slow", "author": "Daniel Kahneman", "first_published": "2011", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Judgment Under Uncertainty", "slug": "Thinking-Fast-and-Slow"},
    {"title": "Judgment in Managerial Decision Making", "author": "Max H. Bazerman; Don A. Moore", "first_published": "1986", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Judgment Under Uncertainty", "slug": "Judgment-in-Managerial-Decision-Making"},
    {"title": "The Undoing Project: A Friendship That Changed Our Minds", "author": "Michael Lewis", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Judgment Under Uncertainty", "slug": "The-Undoing-Project"},
    {"title": "Blindspot: Hidden Biases of Good People", "author": "Mahzarin R. Banaji; Anthony G. Greenwald", "first_published": "2013", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Judgment Under Uncertainty", "slug": "Blindspot"},
    {"title": "The Invisible Gorilla: How Our Intuitions Deceive Us", "author": "Christopher Chabris; Daniel Simons", "first_published": "2010", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Judgment Under Uncertainty", "slug": "The-Invisible-Gorilla"},

    # LEVEL 4: Decision Frameworks (5 books)
    {"title": "Decision Traps: Ten Barriers to Brilliant Decision-Making and How to Overcome Them", "author": "J. Edward Russo; Paul J.H. Schoemaker", "first_published": "1989", "latest_published": "1990", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decision Frameworks", "slug": "Decision-Traps-Russo"},
    {"title": "The Success Equation: Untangling Skill and Luck in Business, Sports, and Investing", "author": "Michael J. Mauboussin", "first_published": "2012", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decision Frameworks", "slug": "The-Success-Equation-Mauboussin"},
    {"title": "Think Twice: Harnessing the Power of Counterintuition", "author": "Michael J. Mauboussin", "first_published": "2009", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decision Frameworks", "slug": "Think-Twice-Mauboussin"},
    {"title": "More Than You Know: Finding Financial Wisdom in Unconventional Places", "author": "Michael J. Mauboussin", "first_published": "2006", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decision Frameworks", "slug": "More-Than-You-Know-Mauboussin"},
    {"title": "Rationality for Mortals: How People Cope with Uncertainty", "author": "Gerd Gigerenzer", "first_published": "2008", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decision Frameworks", "slug": "Rationality-for-Mortals-Gigerenzer"},

    # LEVEL 3: COGNITIVE BIASES & RATIONALITY (15 books)
    # LEVEL 4: Cognitive Biases (5 books)
    {"title": "Heuristics and Biases: The Psychology of Intuitive Judgment", "author": "Thomas Gilovich; Dale Griffin; Daniel Kahneman", "first_published": "2002", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Biases", "slug": "Heuristics-and-Biases-Gilovich"},
    {"title": "The Art of Thinking Clearly", "author": "Rolf Dobelli", "first_published": "2011", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Biases", "slug": "The-Art-of-Thinking-Clearly"},
    {"title": "Predictably Irrational: The Hidden Forces That Shape Our Decisions", "author": "Dan Ariely", "first_published": "2008", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Biases", "slug": "Predictably-Irrational"},
    {"title": "The Upside of Irrationality: The Unexpected Benefits of Defying Logic", "author": "Dan Ariely", "first_published": "2010", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Biases", "slug": "The-Upside-of-Irrationality"},
    {"title": "You Are Not So Smart: Why You Have Too Many Friends on Facebook, Why Your Memory Is Mostly Fiction, and 46 Other Ways You're Deluding Yourself", "author": "David McRaney", "first_published": "2011", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cognitive Biases", "slug": "You-Are-Not-So-Smart"},

    # LEVEL 4: Debiasing (5 books)
    {"title": "Think Again: The Power of Knowing What You Don't Know", "author": "Adam Grant", "first_published": "2021", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Debiasing", "slug": "Think-Again"},
    {"title": "Mistakes Were Made (but Not by Me): Why We Justify Foolish Beliefs, Bad Decisions, and Hurtful Acts", "author": "Carol Tavris; Elliot Aronson", "first_published": "2007", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Debiasing", "slug": "Mistakes-Were-Made"},
    {"title": "Mindware: Tools for Smart Thinking", "author": "Richard E. Nisbett", "first_published": "2015", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Debiasing", "slug": "Mindware"},
    {"title": "How Minds Change: The Surprising Science of Belief, Opinion, and Persuasion", "author": "David McRaney", "first_published": "2022", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Debiasing", "slug": "How-Minds-Change-McRaney"},
    {"title": "The Intelligence Trap: Revolutionise Your Thinking and Make Wiser Decisions", "author": "David Robson", "first_published": "2019", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Debiasing", "slug": "The-Intelligence-Trap-Robson"},

    # LEVEL 4: Rational Thinking (5 books)
    {"title": "Rationality: What It Is, Why It Seems Scarce, Why It Matters", "author": "Steven Pinker", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Rational Thinking", "slug": "Rationality-Pinker"},
    {"title": "The Enigma of Reason", "author": "Hugo Mercier; Dan Sperber", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Rational Thinking", "slug": "The-Enigma-of-Reason"},
    {"title": "What Intelligence Tests Miss: The Psychology of Rational Thought", "author": "Keith E. Stanovich", "first_published": "2009", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Rational Thinking", "slug": "What-Intelligence-Tests-Miss"},
    {"title": "The Rationality Quotient: Toward a Test of Rational Thinking", "author": "Keith E. Stanovich; Richard F. West; Maggie E. Toplak", "first_published": "2016", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Rational Thinking", "slug": "The-Rationality-Quotient"},
    {"title": "The Demon-Haunted World: Science as a Candle in the Dark", "author": "Carl Sagan", "first_published": "1995", "latest_published": "1997", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Rational Thinking", "slug": "The-Demon-Haunted-World"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 03. KNOWLEDGE MANAGEMENT (40 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: NOTE-TAKING (15 books)
    # LEVEL 4: Personal Knowledge Management (5 books)
    {"title": "Building a Second Brain: A Proven Method to Organize Your Digital Life and Unlock Your Creative Potential", "author": "Tiago Forte", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Knowledge Management", "slug": "Building-a-Second-Brain"},
    {"title": "How to Take Smart Notes: One Simple Technique to Boost Writing, Learning and Thinking", "author": "Sönke Ahrens", "first_published": "2017", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Knowledge Management", "slug": "How-to-Take-Smart-Notes"},
    {"title": "The PARA Method: Simplify, Organize, and Master Your Digital Life", "author": "Tiago Forte", "first_published": "2023", "latest_published": "2023", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Knowledge Management", "slug": "The-PARA-Method"},
    {"title": "Digital Zettelkasten: Principles, Methods, & Examples", "author": "David Kadavy", "first_published": "2021", "latest_published": "2021", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Knowledge Management", "slug": "Digital-Zettelkasten"},
    {"title": "Antinet Zettelkasten: A Knowledge System That Will Maximize Your Intellect", "author": "Scott P. Scheper", "first_published": "2022", "latest_published": "2022", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Knowledge Management", "slug": "Antinet-Zettelkasten"},

    # LEVEL 4: Zettelkasten (5 books)
    {"title": "Communicating with Slip Boxes", "author": "Niklas Luhmann", "first_published": "1981", "latest_published": "1992", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Zettelkasten", "slug": "Communicating-with-Slip-Boxes"},
    {"title": "Zettelkasten: The Ultimate Guide to Note-Taking and Knowledge Management", "author": "Christian Tietze; Sascha Fast", "first_published": "2020", "latest_published": "2023", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Zettelkasten", "slug": "Zettelkasten-Guide"},
    {"title": "The Card Catalog: Books, Cards, and Literary Treasures", "author": "The Library of Congress; Peter Devereaux", "first_published": "2017", "latest_published": "2017", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Zettelkasten", "slug": "The-Card-Catalog"},
    {"title": "Index, A History of the: A Bookish Adventure", "author": "Dennis Duncan", "first_published": "2021", "latest_published": "2022", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Zettelkasten", "slug": "Index-A-History-of-the"},
    {"title": "Paper Machines: About Cards & Catalogs, 1548-1929", "author": "Markus Krajewski", "first_published": "2002", "latest_published": "2011", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Zettelkasten", "slug": "Paper-Machines"},

    # LEVEL 4: Connected Notes (5 books)
    {"title": "As We May Think", "author": "Vannevar Bush", "first_published": "1945", "latest_published": "1996", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Connected Notes", "slug": "As-We-May-Think"},
    {"title": "Literary Machines: The Report on, and of, Project Xanadu", "author": "Theodor Holm Nelson", "first_published": "1981", "latest_published": "1993", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Connected Notes", "slug": "Literary-Machines"},
    {"title": "Augmenting Human Intellect: A Conceptual Framework", "author": "Douglas C. Engelbart", "first_published": "1962", "latest_published": "2000", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Connected Notes", "slug": "Augmenting-Human-Intellect"},
    {"title": "Tools for Thought: The History and Future of Mind-Expanding Technology", "author": "Howard Rheingold", "first_published": "1985", "latest_published": "2000", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Connected Notes", "slug": "Tools-for-Thought"},
    {"title": "The Idea Factory: Bell Labs and the Great Age of American Innovation", "author": "Jon Gertner", "first_published": "2012", "latest_published": "2013", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Connected Notes", "slug": "The-Idea-Factory"},

    # LEVEL 3: INFORMATION MANAGEMENT (15 books)
    # LEVEL 4: Information Filtering (5 books)
    {"title": "The Information: A History, a Theory, a Flood", "author": "James Gleick", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Information Filtering", "slug": "The-Information"},
    {"title": "Too Much to Know: Managing Scholarly Information before the Modern Age", "author": "Ann M. Blair", "first_published": "2010", "latest_published": "2011", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Information Filtering", "slug": "Too-Much-to-Know"},
    {"title": "Information Overload: Why it Matters and How to Tackle It", "author": "David Shenk", "first_published": "1997", "latest_published": "1998", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Information Filtering", "slug": "Information-Overload"},
    {"title": "Infomagical: How to Take Control of Your Information Diet", "author": "Manoush Zomorodi", "first_published": "2017", "latest_published": "2017", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Information Filtering", "slug": "Infomagical"},
    {"title": "Data Smog: Surviving the Information Glut", "author": "David Shenk", "first_published": "1997", "latest_published": "1998", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Information Filtering", "slug": "Data-Smog"},

    # LEVEL 4: Digital Organization (5 books)
    {"title": "Organizing Solutions for People with ADHD", "author": "Susan C. Pinsky", "first_published": "2006", "latest_published": "2017", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Organization", "slug": "Organizing-Solutions-ADHD"},
    {"title": "The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing", "author": "Marie Kondo", "first_published": "2011", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Organization", "slug": "The-Life-Changing-Magic-of-Tidying-Up"},
    {"title": "Work Clean: The Life-Changing Power of Mise-en-Place to Organize Your Life, Work, and Mind", "author": "Dan Charnas", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Organization", "slug": "Work-Clean"},
    {"title": "Remix: Making Art and Commerce Thrive in the Hybrid Economy", "author": "Lawrence Lessig", "first_published": "2008", "latest_published": "2009", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Organization", "slug": "Remix-Lessig"},
    {"title": "Everything Is Miscellaneous: The Power of the New Digital Disorder", "author": "David Weinberger", "first_published": "2007", "latest_published": "2008", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Organization", "slug": "Everything-Is-Miscellaneous"},

    # LEVEL 4: Knowledge Retrieval (5 books)
    {"title": "Information Architecture: For the Web and Beyond", "author": "Louis Rosenfeld; Peter Morville; Jorge Arango", "first_published": "1998", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Knowledge Retrieval", "slug": "Information-Architecture"},
    {"title": "Search Patterns: Design for Discovery", "author": "Peter Morville; Jeffery Callender", "first_published": "2010", "latest_published": "2010", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Knowledge Retrieval", "slug": "Search-Patterns"},
    {"title": "Ambient Findability: What We Find Changes Who We Become", "author": "Peter Morville", "first_published": "2005", "latest_published": "2005", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Knowledge Retrieval", "slug": "Ambient-Findability"},
    {"title": "Intertwingled: Information Changes Everything", "author": "Peter Morville", "first_published": "2014", "latest_published": "2014", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Knowledge Retrieval", "slug": "Intertwingled"},
    {"title": "Designing the Search Experience: The Information Architecture of Discovery", "author": "Tony Russell-Rose; Tyler Tate", "first_published": "2012", "latest_published": "2013", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Knowledge Retrieval", "slug": "Designing-the-Search-Experience"},

    # LEVEL 3: THINKING THROUGH WRITING (10 books)
    # LEVEL 4: Writing to Clarify Thought (5 books)
    {"title": "Writing to Learn", "author": "William Zinsser", "first_published": "1988", "latest_published": "1993", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Writing to Clarify Thought", "slug": "Writing-to-Learn"},
    {"title": "The Sense of Style: The Thinking Person's Guide to Writing in the 21st Century", "author": "Steven Pinker", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Writing to Clarify Thought", "slug": "The-Sense-of-Style"},
    {"title": "Writing Without Teachers", "author": "Peter Elbow", "first_published": "1973", "latest_published": "1998", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Writing to Clarify Thought", "slug": "Writing-Without-Teachers"},
    {"title": "The Elements of Eloquence: How to Turn the Perfect English Phrase", "author": "Mark Forsyth", "first_published": "2013", "latest_published": "2014", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Writing to Clarify Thought", "slug": "The-Elements-of-Eloquence"},
    {"title": "Clear and Simple as the Truth: Writing Classic Prose", "author": "Francis-Noël Thomas; Mark Turner", "first_published": "1994", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Writing to Clarify Thought", "slug": "Clear-and-Simple-as-the-Truth"},

    # LEVEL 4: Synthesis & Idea Creation (5 books)
    {"title": "Where Good Ideas Come From: The Natural History of Innovation", "author": "Steven Johnson", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Synthesis & Idea Creation", "slug": "Where-Good-Ideas-Come-From"},
    {"title": "A Technique for Producing Ideas", "author": "James Webb Young", "first_published": "1940", "latest_published": "2003", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Synthesis & Idea Creation", "slug": "A-Technique-for-Producing-Ideas"},
    {"title": "The Art of Thought", "author": "Graham Wallas", "first_published": "1926", "latest_published": "2014", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Synthesis & Idea Creation", "slug": "The-Art-of-Thought"},
    {"title": "Borrowing Brilliance: The Six Steps to Business Innovation by Building on the Ideas of Others", "author": "David Kord Murray", "first_published": "2009", "latest_published": "2010", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Synthesis & Idea Creation", "slug": "Borrowing-Brilliance"},
    {"title": "Steal Like an Artist: 10 Things Nobody Told You About Being Creative", "author": "Austin Kleon", "first_published": "2012", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Synthesis & Idea Creation", "slug": "Steal-Like-an-Artist"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 04. PRODUCTIVITY & FOCUS (50 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: FOCUS & ATTENTION (15 books)
    # LEVEL 4: Deep Work (5 books)
    {"title": "Deep Work: Rules for Focused Success in a Distracted World", "author": "Cal Newport", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deep Work", "slug": "Deep-Work"},
    {"title": "Digital Minimalism: Choosing a Focused Life in a Noisy World", "author": "Cal Newport", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deep Work", "slug": "Digital-Minimalism"},
    {"title": "So Good They Can't Ignore You: Why Skills Trump Passion in the Quest for Work You Love", "author": "Cal Newport", "first_published": "2012", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deep Work", "slug": "So-Good-They-Cant-Ignore-You"},
    {"title": "A World Without Email: Reimagining Work in an Age of Communication Overload", "author": "Cal Newport", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deep Work", "slug": "A-World-Without-Email"},
    {"title": "Slow Productivity: The Lost Art of Accomplishment Without Burnout", "author": "Cal Newport", "first_published": "2024", "latest_published": "2024", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Deep Work", "slug": "Slow-Productivity"},

    # LEVEL 4: Attention Management (5 books)
    {"title": "Stolen Focus: Why You Can't Pay Attention—and How to Think Deeply Again", "author": "Johann Hari", "first_published": "2022", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attention Management", "slug": "Stolen-Focus"},
    {"title": "The Shallows: What the Internet Is Doing to Our Brains", "author": "Nicholas Carr", "first_published": "2010", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attention Management", "slug": "The-Shallows"},
    {"title": "Hyperfocus: How to Be More Productive in a World of Distraction", "author": "Chris Bailey", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attention Management", "slug": "Hyperfocus"},
    {"title": "Attention Span: A Groundbreaking Way to Restore Balance, Happiness and Productivity", "author": "Gloria Mark", "first_published": "2023", "latest_published": "2023", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attention Management", "slug": "Attention-Span"},
    {"title": "The Distracted Mind: Ancient Brains in a High-Tech World", "author": "Adam Gazzaley; Larry D. Rosen", "first_published": "2016", "latest_published": "2017", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Attention Management", "slug": "The-Distracted-Mind"},

    # LEVEL 4: Distraction Management (5 books)
    {"title": "Indistractable: How to Control Your Attention and Choose Your Life", "author": "Nir Eyal; Julie Li", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distraction Management", "slug": "Indistractable"},
    {"title": "Make Time: How to Focus on What Matters Every Day", "author": "Jake Knapp; John Zeratsky", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distraction Management", "slug": "Make-Time"},
    {"title": "Stand Out of Our Light: Freedom and Resistance in the Attention Economy", "author": "James Williams", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distraction Management", "slug": "Stand-Out-of-Our-Light"},
    {"title": "Irresistible: The Rise of Addictive Technology and the Business of Keeping Us Hooked", "author": "Adam Alter", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distraction Management", "slug": "Irresistible-Alter"},
    {"title": "Ten Arguments for Deleting Your Social Media Accounts Right Now", "author": "Jaron Lanier", "first_published": "2018", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distraction Management", "slug": "Ten-Arguments-for-Deleting-Social-Media"},

    # LEVEL 3: HABITS & BEHAVIOR (20 books)
    # LEVEL 4: Habit Formation (5 books)
    {"title": "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones", "author": "James Clear", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Formation", "slug": "Atomic-Habits"},
    {"title": "The Power of Habit: Why We Do What We Do in Life and Business", "author": "Charles Duhigg", "first_published": "2012", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Formation", "slug": "The-Power-of-Habit"},
    {"title": "Tiny Habits: The Small Changes That Change Everything", "author": "B.J. Fogg", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Formation", "slug": "Tiny-Habits"},
    {"title": "Mini Habits: Smaller Habits, Bigger Results", "author": "Stephen Guise", "first_published": "2013", "latest_published": "2013", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Formation", "slug": "Mini-Habits"},
    {"title": "Good Habits, Bad Habits: The Science of Making Positive Changes That Stick", "author": "Wendy Wood", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Habit Formation", "slug": "Good-Habits-Bad-Habits"},

    # LEVEL 4: Behavior Change (5 books)
    {"title": "Switch: How to Change Things When Change Is Hard", "author": "Chip Heath; Dan Heath", "first_published": "2010", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavior Change", "slug": "Switch"},
    {"title": "How to Change: The Science of Getting from Where You Are to Where You Want to Be", "author": "Katy Milkman", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavior Change", "slug": "How-to-Change"},
    {"title": "Triggers: Creating Behavior That Lasts—Becoming the Person You Want to Be", "author": "Marshall Goldsmith; Mark Reiter", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavior Change", "slug": "Triggers"},
    {"title": "Change Anything: The New Science of Personal Success", "author": "Kerry Patterson; Joseph Grenny; David Maxfield", "first_published": "2011", "latest_published": "2012", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavior Change", "slug": "Change-Anything"},
    {"title": "Hooked: How to Build Habit-Forming Products", "author": "Nir Eyal", "first_published": "2014", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavior Change", "slug": "Hooked"},

    # LEVEL 4: Environment Design (5 books)
    {"title": "Willpower Doesn't Work: Discover the Hidden Keys to Success", "author": "Benjamin Hardy", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environment Design", "slug": "Willpower-Doesnt-Work"},
    {"title": "Drunk Tank Pink: And Other Unexpected Forces That Shape How We Think, Feel, and Behave", "author": "Adam Alter", "first_published": "2013", "latest_published": "2014", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environment Design", "slug": "Drunk-Tank-Pink"},
    {"title": "The Design of Everyday Things", "author": "Don Norman", "first_published": "1988", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environment Design", "slug": "The-Design-of-Everyday-Things"},
    {"title": "Joyful: The Surprising Power of Ordinary Things to Create Extraordinary Happiness", "author": "Ingrid Fetell Lee", "first_published": "2018", "latest_published": "2019", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environment Design", "slug": "Joyful"},
    {"title": "Welcome to Your World: How the Built Environment Shapes Our Lives", "author": "Sarah Williams Goldhagen", "first_published": "2017", "latest_published": "2017", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environment Design", "slug": "Welcome-to-Your-World"},

    # LEVEL 4: Consistency & Discipline (5 books)
    {"title": "Grit: The Power of Passion and Perseverance", "author": "Angela Duckworth", "first_published": "2016", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consistency & Discipline", "slug": "Grit"},
    {"title": "The Compound Effect: Jumpstart Your Income, Your Life, Your Success", "author": "Darren Hardy", "first_published": "2010", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consistency & Discipline", "slug": "The-Compound-Effect"},
    {"title": "The Slight Edge: Turning Simple Disciplines into Massive Success and Happiness", "author": "Jeff Olson", "first_published": "2005", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consistency & Discipline", "slug": "The-Slight-Edge"},
    {"title": "Discipline Equals Freedom: Field Manual", "author": "Jocko Willink", "first_published": "2017", "latest_published": "2020", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consistency & Discipline", "slug": "Discipline-Equals-Freedom"},
    {"title": "Discipline Is Destiny: The Power of Self-Control", "author": "Ryan Holiday", "first_published": "2022", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consistency & Discipline", "slug": "Discipline-Is-Destiny"},

    # LEVEL 3: PERSONAL SYSTEMS (15 books)
    # LEVEL 4: Time Management (5 books)
    {"title": "Four Thousand Weeks: Time Management for Mortals", "author": "Oliver Burkeman", "first_published": "2021", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Time Management", "slug": "Four-Thousand-Weeks"},
    {"title": "168 Hours: You Have More Time Than You Think", "author": "Laura Vanderkam", "first_published": "2010", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Time Management", "slug": "168-Hours"},
    {"title": "The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change", "author": "Stephen R. Covey", "first_published": "1989", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Time Management", "slug": "The-7-Habits-of-Highly-Effective-People"},
    {"title": "First Things First", "author": "Stephen R. Covey; A. Roger Merrill; Rebecca R. Merrill", "first_published": "1994", "latest_published": "1999", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Time Management", "slug": "First-Things-First"},
    {"title": "Time Smart: How to Reclaim Your Time and Live a Happier Life", "author": "Ashley Whillans", "first_published": "2020", "latest_published": "2020", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Time Management", "slug": "Time-Smart"},

    # LEVEL 4: Task Management (5 books)
    {"title": "Getting Things Done: The Art of Stress-Free Productivity", "author": "David Allen", "first_published": "2001", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Task Management", "slug": "Getting-Things-Done"},
    {"title": "The Bullet Journal Method: Track the Past, Order the Present, Design the Future", "author": "Ryder Carroll", "first_published": "2018", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Task Management", "slug": "The-Bullet-Journal-Method"},
    {"title": "The Checklist Manifesto: How to Get Things Right", "author": "Atul Gawande", "first_published": "2009", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Task Management", "slug": "The-Checklist-Manifesto"},
    {"title": "Eat That Frog!: 21 Great Ways to Stop Procrastinating and Get More Done in Less Time", "author": "Brian Tracy", "first_published": "2001", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Task Management", "slug": "Eat-That-Frog"},
    {"title": "Personal Kanban: Mapping Work | Navigating Life", "author": "Jim Benson; Tonianne DeMaria Barry", "first_published": "2011", "latest_published": "2011", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Task Management", "slug": "Personal-Kanban"},

    # LEVEL 4: Energy Management (5 books)
    {"title": "The Power of Full Engagement: Managing Energy, Not Time, Is the Key to High Performance and Personal Renewal", "author": "Jim Loehr; Tony Schwartz", "first_published": "2003", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Energy Management", "slug": "The-Power-of-Full-Engagement"},
    {"title": "Why We Sleep: Unlocking the Power of Sleep and Dreams", "author": "Matthew Walker", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Energy Management", "slug": "Why-We-Sleep"},
    {"title": "When: The Scientific Secrets of Perfect Timing", "author": "Daniel H. Pink", "first_published": "2018", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Energy Management", "slug": "When-Pink"},
    {"title": "Rest: Why You Get More Done When You Work Less", "author": "Alex Soojung-Kim Pang", "first_published": "2016", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Energy Management", "slug": "Rest-Pang"},
    {"title": "Peak Performance: Elevate Your Game, Avoid Burnout, and Thrive with the New Science of Success", "author": "Brad Stulberg; Steve Magness", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Energy Management", "slug": "Peak-Performance-Stulberg"},
]
