from __future__ import annotations

# Domain 02: Communication, Writing & Social Intelligence (130 books: #0181–#0310)
BOOKS_02 = [
    # -------------------------------------------------------------------------
    # LEVEL 2: 01. WRITING (40 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: CLEAR WRITING (15 books)
    # LEVEL 4: Clarity (5 books)
    {"title": "On Writing Well: The Classic Guide to Writing Nonfiction", "author": "William Zinsser", "first_published": "1976", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Clarity", "slug": "On-Writing-Well"},
    {"title": "The Elements of Style", "author": "William Strunk Jr.; E.B. White", "first_published": "1918", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Clarity", "slug": "The-Elements-of-Style"},
    {"title": "Style: Lessons in Clarity and Grace", "author": "Joseph M. Williams; Joseph Bizup", "first_published": "1981", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Clarity", "slug": "Style-Lessons-in-Clarity-and-Grace"},
    {"title": "Several Short Sentences About Writing", "author": "Verlyn Klinkenborg", "first_published": "2012", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Clarity", "slug": "Several-Short-Sentences-About-Writing"},
    {"title": "Bird by Bird: Some Instructions on Writing and Life", "author": "Anne Lamott", "first_published": "1994", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Clarity", "slug": "Bird-by-Bird"},

    # LEVEL 4: Simplicity (5 books)
    {"title": "Draft No. 4: On the Writing Process", "author": "John McPhee", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Simplicity", "slug": "Draft-No-4"},
    {"title": "Writing Tools: 55 Essential Strategies for Every Writer", "author": "Roy Peter Clark", "first_published": "2006", "latest_published": "2024", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Simplicity", "slug": "Writing-Tools"},
    {"title": "The Art and Craft of Feature Writing", "author": "William E. Blundell", "first_published": "1988", "latest_published": "1988", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Simplicity", "slug": "The-Art-and-Craft-of-Feature-Writing"},
    {"title": "Smart Brevity: The Power of Saying More with Less", "author": "Jim VandeHei; Mike Allen; Roy Schwartz", "first_published": "2022", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Simplicity", "slug": "Smart-Brevity"},
    {"title": "How to Write a Sentence: And How to Read One", "author": "Stanley Fish", "first_published": "2011", "latest_published": "2012", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Simplicity", "slug": "How-to-Write-a-Sentence"},

    # LEVEL 4: Editing (5 books)
    {"title": "Self-Editing for Fiction Writers", "author": "Renni Browne; Dave King", "first_published": "1993", "latest_published": "2004", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Editing", "slug": "Self-Editing-for-Fiction-Writers"},
    {"title": "The Subversive Copy Editor: Advice from Chicago", "author": "Carol Fisher Saller", "first_published": "2009", "latest_published": "2016", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Editing", "slug": "The-Subversive-Copy-Editor"},
    {"title": "Line by Line: How to Edit Your Own Writing", "author": "Claire Kehrwald Cook", "first_published": "1985", "latest_published": "1986", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Editing", "slug": "Line-by-Line"},
    {"title": "Copyediting and Headline Writing", "author": "Arthur Wimer; Dale Brix", "first_published": "1972", "latest_published": "1985", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Editing", "slug": "Copyediting-Headline-Writing"},
    {"title": "Sin and Syntax: How to Craft Wicked Good Prose", "author": "Constance Hale", "first_published": "1999", "latest_published": "2013", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Editing", "slug": "Sin-and-Syntax"},

    # LEVEL 3: PROFESSIONAL WRITING (15 books)
    # LEVEL 4: Technical Writing (5 books)
    {"title": "Technical Writing, Presentational Skills, and Online Communication", "author": "Raymond Greenlaw", "first_published": "2012", "latest_published": "2012", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technical Writing", "slug": "Technical-Writing-Greenlaw"},
    {"title": "Handbook of Technical Writing", "author": "Gerald J. Alred; Charles T. Brusaw; Walter E. Oliu", "first_published": "1976", "latest_published": "2020", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technical Writing", "slug": "Handbook-of-Technical-Writing"},
    {"title": "Developing Quality Technical Information: A Handbook for Writers and Editors", "author": "Gretchen Hargis", "first_published": "1998", "latest_published": "2014", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technical Writing", "slug": "Developing-Quality-Technical-Information"},
    {"title": "The Insider's Guide to Technical Writing", "author": "Krista Van Laan", "first_published": "2012", "latest_published": "2022", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technical Writing", "slug": "The-Insiders-Guide-to-Technical-Writing"},
    {"title": "Docs for Developers: An Engineer's Field Guide to Technical Writing", "author": "Jared Bhatti; Sarah Corleissen", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technical Writing", "slug": "Docs-for-Developers"},

    # LEVEL 4: Business Writing (5 books)
    {"title": "HBR Guide to Better Business Writing", "author": "Bryan A. Garner", "first_published": "2012", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Writing", "slug": "HBR-Guide-to-Better-Business-Writing"},
    {"title": "The Pyramid Principle: Logic in Writing and Thinking", "author": "Barbara Minto", "first_published": "1987", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Writing", "slug": "The-Pyramid-Principle"},
    {"title": "Strategic Storytelling: How to Create Persuasive Business Presentations", "author": "Dave McKinsey", "first_published": "2014", "latest_published": "2014", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Writing", "slug": "Strategic-Storytelling"},
    {"title": "Business Writing Done Right", "author": "Jane Watson", "first_published": "2020", "latest_published": "2020", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Writing", "slug": "Business-Writing-Done-Right"},
    {"title": "Writing for Business: The New York Times Guide", "author": "The New York Times", "first_published": "2010", "latest_published": "2010", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Writing", "slug": "Writing-for-Business-NYT"},

    # LEVEL 4: Documentation (5 books)
    {"title": "Every Page is Page One: Topic-Based Writing for Technical Communication and the Web", "author": "Mark Baker", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Documentation", "slug": "Every-Page-is-Page-One"},
    {"title": "Managing Your Documentation Projects", "author": "JoAnn T. Hackos", "first_published": "1994", "latest_published": "1994", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Documentation", "slug": "Managing-Your-Documentation-Projects"},
    {"title": "Documenting APIs: A Guide for Technical Writers", "author": "Tom Johnson", "first_published": "2020", "latest_published": "2023", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Documentation", "slug": "Documenting-APIs"},
    {"title": "Letting Go of the Words: Writing Web Content that Works", "author": "Janice Redish", "first_published": "2007", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Documentation", "slug": "Letting-Go-of-the-Words"},
    {"title": "Writing That Works: How to Communicate Effectively in Business", "author": "Kenneth Roman; Joel Raphaelson", "first_published": "1981", "latest_published": "2000", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Documentation", "slug": "Writing-That-Works"},

    # LEVEL 3: PERSUASIVE WRITING (10 books)
    # LEVEL 4: Argumentation (5 books)
    {"title": "Thank You for Arguing: What Aristotle, Lincoln, and Homer Simpson Can Teach Us About the Art of Persuasion", "author": "Jay Heinrichs", "first_published": "2007", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Argumentation", "slug": "Thank-You-for-Arguing"},
    {"title": "Rhetoric", "author": "Aristotle", "first_published": "-350", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Argumentation", "slug": "Rhetoric-Aristotle"},
    {"title": "The Uses of Argument", "author": "Stephen E. Toulmin", "first_published": "1958", "latest_published": "2003", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Argumentation", "slug": "The-Uses-of-Argument"},
    {"title": "Crucial Arguments: How to Frame and Defend Your Point", "author": "Robert A. Burton", "first_published": "2015", "latest_published": "2015", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Argumentation", "slug": "Crucial-Arguments"},
    {"title": "The Craft of Research", "author": "Wayne C. Booth; Gregory G. Colomb; Joseph M. Williams", "first_published": "1995", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Argumentation", "slug": "The-Craft-of-Research"},

    # LEVEL 4: Copywriting Concepts (5 books)
    {"title": "The Adweek Copywriting Handbook", "author": "Joseph Sugarman", "first_published": "2006", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Copywriting Concepts", "slug": "The-Adweek-Copywriting-Handbook"},
    {"title": "Tested Advertising Methods", "author": "John Caples; Fred E. Hahn", "first_published": "1932", "latest_published": "1997", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Copywriting Concepts", "slug": "Tested-Advertising-Methods"},
    {"title": "Scientific Advertising", "author": "Claude C. Hopkins", "first_published": "1923", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Copywriting Concepts", "slug": "Scientific-Advertising"},
    {"title": "Ogilvy on Advertising", "author": "David Ogilvy", "first_published": "1983", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Copywriting Concepts", "slug": "Ogilvy-on-Advertising"},
    {"title": "Breakthrough Advertising", "author": "Eugene M. Schwartz", "first_published": "1966", "latest_published": "2004", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Copywriting Concepts", "slug": "Breakthrough-Advertising"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 02. COMMUNICATION (35 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: SPEAKING (15 books)
    # LEVEL 4: Public Speaking (5 books)
    {"title": "Talk Like TED: The 9 Public-Speaking Secrets of the World's Top Minds", "author": "Carmine Gallo", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Public Speaking", "slug": "Talk-Like-TED"},
    {"title": "TED Talks: The Official TED Guide to Public Speaking", "author": "Chris Anderson", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Public Speaking", "slug": "TED-Talks-Anderson"},
    {"title": "Confessions of a Public Speaker", "author": "Scott Berkun", "first_published": "2009", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Public Speaking", "slug": "Confessions-of-a-Public-Speaker"},
    {"title": "Speak Like a CEO: Secrets for Commanding Attention and Getting Results", "author": "Suzanne Bates", "first_published": "2005", "latest_published": "2005", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Public Speaking", "slug": "Speak-Like-a-CEO"},
    {"title": "Steal the Show: How to Guarantee a Standing Ovation for All the Performances in Your Life", "author": "Michael Port", "first_published": "2015", "latest_published": "2016", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Public Speaking", "slug": "Steal-the-Show"},

    # LEVEL 4: Presentations (5 books)
    {"title": "Resonate: Present Visual Stories that Transform Audiences", "author": "Nancy Duarte", "first_published": "2010", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Presentations", "slug": "Resonate"},
    {"title": "Slide:ology: The Art and Science of Creating Great Presentations", "author": "Nancy Duarte", "first_published": "2008", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Presentations", "slug": "Slide-ology"},
    {"title": "Presentation Zen: Simple Ideas on Presentation Design and Delivery", "author": "Garr Reynolds", "first_published": "2008", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Presentations", "slug": "Presentation-Zen"},
    {"title": "The Visual Display of Quantitative Information", "author": "Edward R. Tufte", "first_published": "1983", "latest_published": "2001", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Presentations", "slug": "The-Visual-Display-of-Quantitative-Information"},
    {"title": "Envisioning Information", "author": "Edward R. Tufte", "first_published": "1990", "latest_published": "1990", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Presentations", "slug": "Envisioning-Information"},

    # LEVEL 4: Explaining Complex Ideas (5 books)
    {"title": "Made to Stick: Why Some Ideas Survive and Others Die", "author": "Chip Heath; Dan Heath", "first_published": "2007", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Explaining Complex Ideas", "slug": "Made-to-Stick"},
    {"title": "The Art of Explanation: Making Your Ideas, Products, and Services Easier to Understand", "author": "Lee LeFever", "first_published": "2012", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Explaining Complex Ideas", "slug": "The-Art-of-Explanation"},
    {"title": "Thing Explainer: Complicated Stuff in Simple Words", "author": "Randall Munroe", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Explaining Complex Ideas", "slug": "Thing-Explainer"},
    {"title": "Don't Be Such a Scientist: Talking Substance in an Age of Style", "author": "Randy Olson", "first_published": "2009", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Explaining Complex Ideas", "slug": "Dont-Be-Such-a-Scientist"},
    {"title": "Houston, We Have a Narrative: Why Science Needs Story", "author": "Randy Olson", "first_published": "2015", "latest_published": "2015", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Explaining Complex Ideas", "slug": "Houston-We-Have-a-Narrative"},

    # LEVEL 3: CONVERSATION (10 books)
    # LEVEL 4: Listening (5 books)
    {"title": "You're Not Listening: What You're Missing and Why It Matters", "author": "Kate Murphy", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Listening", "slug": "Youre-Not-Listening"},
    {"title": "The Lost Art of Listening: How Learning to Listen Can Improve Relationships", "author": "Michael P. Nichols; Martha B. Straus", "first_published": "1995", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Listening", "slug": "The-Lost-Art-of-Listening"},
    {"title": "Listen Like You Mean It: Reclaiming the Lost Art of True Connection", "author": "Ximena Vengoechea", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Listening", "slug": "Listen-Like-You-Mean-It"},
    {"title": "Active Listening: Improve Your Ability to Listen and Lead", "author": "Michael H. Hoppe", "first_published": "2006", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Listening", "slug": "Active-Listening-Hoppe"},
    {"title": "Just Listen: Discover the Secret to Getting Through to Absolutely Anyone", "author": "Mark Goulston", "first_published": "2009", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Listening", "slug": "Just-Listen"},

    # LEVEL 4: Difficult Conversations (5 books)
    {"title": "Difficult Conversations: How to Discuss What Matters Most", "author": "Douglas Stone; Bruce Patton; Sheila Heen", "first_published": "1999", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Difficult Conversations", "slug": "Difficult-Conversations"},
    {"title": "Crucial Conversations: Tools for Talking When Stakes Are High", "author": "Kerry Patterson; Joseph Grenny; Ron McMillan", "first_published": "2002", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Difficult Conversations", "slug": "Crucial-Conversations"},
    {"title": "Crucial Accountability: Tools for Resolving Violated Expectations, Broken Commitments, and Bad Behavior", "author": "Kerry Patterson; Joseph Grenny; David Maxfield", "first_published": "2004", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Difficult Conversations", "slug": "Crucial-Accountability"},
    {"title": "Fierce Conversations: Achieving Success at Work and in Life One Conversation at a Time", "author": "Susan Scott", "first_published": "2002", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Difficult Conversations", "slug": "Fierce-Conversations"},
    {"title": "Nonviolent Communication: A Language of Life", "author": "Marshall B. Rosenberg", "first_published": "1999", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Difficult Conversations", "slug": "Nonviolent-Communication"},

    # LEVEL 3: TEACHING & EXPLAINING (10 books)
    # LEVEL 4: Explanation (5 books)
    {"title": "What the Best College Teachers Do", "author": "Ken Bain", "first_published": "2004", "latest_published": "2004", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Explanation", "slug": "What-the-Best-College-Teachers-Do"},
    {"title": "The Courage to Teach: Exploring the Inner Landscape of a Teacher's Life", "author": "Parker J. Palmer", "first_published": "1998", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Explanation", "slug": "The-Courage-to-Teach"},
    {"title": "Teach Like a Champion 3.0: 63 Techniques that Put Students on the Path to College", "author": "Doug Lemov", "first_published": "2010", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Explanation", "slug": "Teach-Like-a-Champion"},
    {"title": "Visible Learning: A Synthesis of Over 800 Meta-Analyses Relating to Achievement", "author": "John Hattie", "first_published": "2008", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Explanation", "slug": "Visible-Learning"},
    {"title": "Teaching What You Don't Know", "author": "Therese Huston", "first_published": "2009", "latest_published": "2012", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Explanation", "slug": "Teaching-What-You-Dont-Know"},

    # LEVEL 4: Teaching Others (5 books)
    {"title": "The Pedagogy of the Oppressed", "author": "Paulo Freire", "first_published": "1968", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Teaching Others", "slug": "Pedagogy-of-the-Oppressed"},
    {"title": "Experience and Education", "author": "John Dewey", "first_published": "1938", "latest_published": "1997", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Teaching Others", "slug": "Experience-and-Education"},
    {"title": "The End of Education: Redefining the Value of School", "author": "Neil Postman", "first_published": "1995", "latest_published": "1996", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Teaching Others", "slug": "The-End-of-Education"},
    {"title": "The One World Schoolhouse: Education Reimagined", "author": "Salman Khan", "first_published": "2012", "latest_published": "2013", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Teaching Others", "slug": "The-One-World-Schoolhouse"},
    {"title": "Make Just One Change: Teach Students to Ask Their Own Questions", "author": "Dan Rothstein; Luz Santana", "first_published": "2011", "latest_published": "2011", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Teaching Others", "slug": "Make-Just-One-Change"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 03. SOCIAL INTELLIGENCE (30 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: RELATIONSHIPS (10 books)
    # LEVEL 4: Building Trust (5 books)
    {"title": "The Speed of Trust: The One Thing That Changes Everything", "author": "Stephen M.R. Covey; Rebecca R. Merrill", "first_published": "2006", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Trust", "slug": "The-Speed-of-Trust"},
    {"title": "The Thin Book of Trust: An Essential Primer for Building Trust at Work", "author": "Charles Feltman", "first_published": "2008", "latest_published": "2021", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Trust", "slug": "The-Thin-Book-of-Trust"},
    {"title": "Trust and Betrayal in the Workplace", "author": "Dennis S. Reina; Michelle L. Reina", "first_published": "2006", "latest_published": "2015", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Trust", "slug": "Trust-and-Betrayal-in-the-Workplace"},
    {"title": "The Trusted Advisor", "author": "David H. Maister; Charles H. Green; Robert M. Galford", "first_published": "2000", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Trust", "slug": "The-Trusted-Advisor"},
    {"title": "Building Trust: In Business, Politics, Relationships, and Life", "author": "Robert C. Solomon; Fernando Flores", "first_published": "2001", "latest_published": "2003", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Trust", "slug": "Building-Trust-Solomon"},

    # LEVEL 4: Social Connection (5 books)
    {"title": "How to Win Friends and Influence People", "author": "Dale Carnegie", "first_published": "1936", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Connection", "slug": "How-to-Win-Friends-and-Influence-People"},
    {"title": "Never Eat Alone: And Other Secrets to Success, One Relationship at a Time", "author": "Keith Ferrazzi; Tahl Raz", "first_published": "2005", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Connection", "slug": "Never-Eat-Alone"},
    {"title": "Captivate: The Science of Succeeding with People", "author": "Vanessa Van Edwards", "first_published": "2017", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Connection", "slug": "Captivate"},
    {"title": "The Like Switch: An Ex-FBI Agent's Guide to Influencing, Attracting, and Winning People Over", "author": "Jack Schafer; Marvin Karlins", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Connection", "slug": "The-Like-Switch"},
    {"title": "Friendship: The Evolution, Biology, and Extraordinary Power of Life's Fundamental Bond", "author": "Lydia Denworth", "first_published": "2020", "latest_published": "2021", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Connection", "slug": "Friendship-Denworth"},

    # LEVEL 3: EMOTIONAL INTELLIGENCE (10 books)
    # LEVEL 4: Self-Awareness (5 books)
    {"title": "Emotional Intelligence: Why It Can Matter More Than IQ", "author": "Daniel Goleman", "first_published": "1995", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Self-Awareness", "slug": "Emotional-Intelligence"},
    {"title": "Insight: The Surprising Truth About How Others See Us, How We See Ourselves, and Why the Answers Matter More Than We Think", "author": "Tasha Eurich", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Self-Awareness", "slug": "Insight-Eurich"},
    {"title": "Emotional Intelligence 2.0", "author": "Travis Bradberry; Jean Greaves", "first_published": "2009", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Self-Awareness", "slug": "Emotional-Intelligence-2-0"},
    {"title": "Self-Awareness (HBR Emotional Intelligence Series)", "author": "Harvard Business Review", "first_published": "2018", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Self-Awareness", "slug": "Self-Awareness-HBR"},
    {"title": "Permission to Feel: Unlocking the Power of Emotions to Help Our Kids, Ourselves, and Our Society Thrive", "author": "Marc Brackett", "first_published": "2019", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Self-Awareness", "slug": "Permission-to-Feel"},

    # LEVEL 4: Empathy (5 books)
    {"title": "Social Intelligence: The New Science of Human Relationships", "author": "Daniel Goleman", "first_published": "2006", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Empathy", "slug": "Social-Intelligence-Goleman"},
    {"title": "The War for Kindness: Building Empathy in a Fractured World", "author": "Jamil Zaki", "first_published": "2019", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Empathy", "slug": "The-War-for-Kindness"},
    {"title": "Against Empathy: The Case for Rational Compassion", "author": "Paul Bloom", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Empathy", "slug": "Against-Empathy"},
    {"title": "Empathy: Why It Matters, and How to Get It", "author": "Roman Krznaric", "first_published": "2014", "latest_published": "2015", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Empathy", "slug": "Empathy-Krznaric"},
    {"title": "The Age of Empathy: Nature's Lessons for a Kinder Society", "author": "Frans de Waal", "first_published": "2009", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Empathy", "slug": "The-Age-of-Empathy"},

    # LEVEL 3: CONFLICT (10 books)
    # LEVEL 4: Conflict Resolution (5 books)
    {"title": "The Anatomy of Peace: Resolving the Heart of Conflict", "author": "The Arbinger Institute", "first_published": "2006", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conflict Resolution", "slug": "The-Anatomy-of-Peace"},
    {"title": "High Conflict: Why We Get Trapped and How We Get Out", "author": "Amanda Ripley", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conflict Resolution", "slug": "High-Conflict"},
    {"title": "The Joy of Conflict Resolution: Transforming Victims, Villains and Heroes in the Workplace and at Home", "author": "Gary Harper", "first_published": "2004", "latest_published": "2004", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conflict Resolution", "slug": "The-Joy-of-Conflict-Resolution"},
    {"title": "Conflict Management: A Practical Guide to Developing Negotiation Strategies", "author": "Barbara A. Budjac Corvette", "first_published": "2006", "latest_published": "2014", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conflict Resolution", "slug": "Conflict-Management-Corvette"},
    {"title": "Everything Is Workable: A Mindful Guide to Conflict Resolution", "author": "Diane Musho Hamilton", "first_published": "2013", "latest_published": "2013", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conflict Resolution", "slug": "Everything-Is-Workable"},

    # LEVEL 4: Difficult People (5 books)
    {"title": "Dealing with People You Can't Stand: How to Bring Out the Best in People at Their Worst", "author": "Rick Brinkman; Rick Kirschner", "first_published": "1994", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Difficult People", "slug": "Dealing-with-People-You-Cant-Stand"},
    {"title": "The No Asshole Rule: Building a Civilized Workplace and Surviving One That Isn't", "author": "Robert I. Sutton", "first_published": "2007", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Difficult People", "slug": "The-No-Asshole-Rule"},
    {"title": "The Asshole Survival Guide: How to Deal with People Who Treat You Like Dirt", "author": "Robert I. Sutton", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Difficult People", "slug": "The-Asshole-Survival-Guide"},
    {"title": "Surrounded by Idiots: The Four Types of Human Behavior and How to Effectively Communicate with Each in Business (and in Life)", "author": "Thomas Erikson", "first_published": "2014", "latest_published": "2019", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Difficult People", "slug": "Surrounded-by-Idiots"},
    {"title": "Jerks at Work: Toxic Coworkers and What to Do About Them", "author": "Tessa West", "first_published": "2022", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Difficult People", "slug": "Jerks-at-Work"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 04. NEGOTIATION & INFLUENCE (25 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: NEGOTIATION (15 books)
    # LEVEL 4: Principled Negotiation (5 books)
    {"title": "Getting to Yes: Negotiating Agreement Without Giving In", "author": "Roger Fisher; William Ury; Bruce Patton", "first_published": "1981", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Principled Negotiation", "slug": "Getting-to-Yes"},
    {"title": "Getting Past No: Negotiating in Difficult Situations", "author": "William Ury", "first_published": "1991", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Principled Negotiation", "slug": "Getting-Past-No"},
    {"title": "The Power of a Positive No: How to Say No and Still Get to Yes", "author": "William Ury", "first_published": "2007", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Principled Negotiation", "slug": "The-Power-of-a-Positive-No"},
    {"title": "Beyond Reason: Using Emotions as You Negotiate", "author": "Roger Fisher; Daniel Shapiro", "first_published": "2005", "latest_published": "2006", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Principled Negotiation", "slug": "Beyond-Reason"},
    {"title": "Negotiating the Nonnegotiable: How to Resolve Your Most Emotionally Charged Conflicts", "author": "Daniel Shapiro", "first_published": "2016", "latest_published": "2017", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Principled Negotiation", "slug": "Negotiating-the-Nonnegotiable"},

    # LEVEL 4: Business Negotiation (5 books)
    {"title": "Bargaining for Advantage: Negotiation Strategies for Reasonable People", "author": "G. Richard Shell", "first_published": "1999", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Negotiation", "slug": "Bargaining-for-Advantage"},
    {"title": "Negotiation Genius: How to Overcome Obstacles and Achieve Brilliant Results at the Bargaining Table and Beyond", "author": "Deepak Malhotra; Max H. Bazerman", "first_published": "2007", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Negotiation", "slug": "Negotiation-Genius"},
    {"title": "The Art of Negotiation: How to Improvise Agreement in a Chaotic World", "author": "Michael Wheeler", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Negotiation", "slug": "The-Art-of-Negotiation"},
    {"title": "3-D Negotiation: Powerful Tools to Change the Game in Your Most Important Deals", "author": "David A. Lax; James K. Sebenius", "first_published": "2006", "latest_published": "2006", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Negotiation", "slug": "3-D-Negotiation"},
    {"title": "Start with NO... The Negotiating Tools That the Pros Don't Want You to Know", "author": "Jim Camp", "first_published": "2002", "latest_published": "2002", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Negotiation", "slug": "Start-with-NO"},

    # LEVEL 4: High-Stakes Negotiation (5 books)
    {"title": "Never Split the Difference: Negotiating As If Your Life Depended On It", "author": "Chris Voss; Tahl Raz", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "High-Stakes Negotiation", "slug": "Never-Split-the-Difference"},
    {"title": "Stalling for Time: My Life as an FBI Hostage Negotiator", "author": "Gary Noesner", "first_published": "2010", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "High-Stakes Negotiation", "slug": "Stalling-for-Time"},
    {"title": "Hostage at the Table: How Leaders Can Overcome Conflict, Influence Others, and Raise Performance", "author": "George Kohlrieser", "first_published": "2006", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "High-Stakes Negotiation", "slug": "Hostage-at-the-Table"},
    {"title": "Care to Dare: Unleashing Astonishing Potential Through Secure Base Leadership", "author": "George Kohlrieser; Susan Goldsworthy; Duncan Coombe", "first_published": "2012", "latest_published": "2012", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "High-Stakes Negotiation", "slug": "Care-to-Dare"},
    {"title": "Negotiating with the Devil: When to Resolve and When to Fight", "author": "Robert Mnookin", "first_published": "2010", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "High-Stakes Negotiation", "slug": "Negotiating-with-the-Devil"},

    # LEVEL 3: INFLUENCE (10 books)
    # LEVEL 4: Persuasion (5 books)
    {"title": "Influence: The Psychology of Persuasion", "author": "Robert B. Cialdini", "first_published": "1984", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Persuasion", "slug": "Influence-Cialdini"},
    {"title": "Pre-Suasion: A Revolutionary Way to Influence and Persuade", "author": "Robert B. Cialdini", "first_published": "2016", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Persuasion", "slug": "Pre-Suasion"},
    {"title": "To Sell Is Human: The Surprising Truth About Moving Others", "author": "Daniel H. Pink", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Persuasion", "slug": "To-Sell-Is-Human"},
    {"title": "Yes!: 50 Scientifically Proven Ways to Be Persuasive", "author": "Noah J. Goldstein; Steve J. Martin; Robert B. Cialdini", "first_published": "2008", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Persuasion", "slug": "Yes-50-Proven-Ways"},
    {"title": "The Soul of Influence: How to Create Deep Connection and Lasting Impact", "author": "Ken Druck", "first_published": "2000", "latest_published": "2000", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Persuasion", "slug": "The-Soul-of-Influence"},

    # LEVEL 4: Social Influence (5 books)
    {"title": "Invisible Influence: The Hidden Forces that Shape Behavior", "author": "Jonah Berger", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Influence", "slug": "Invisible-Influence"},
    {"title": "Contagious: Why Things Catch On", "author": "Jonah Berger", "first_published": "2013", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Influence", "slug": "Contagious"},
    {"title": "The Tipping Point: How Little Things Can Make a Big Difference", "author": "Malcolm Gladwell", "first_published": "2000", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Influence", "slug": "The-Tipping-Point"},
    {"title": "The Catalyst: How to Change Anyone's Mind", "author": "Jonah Berger", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Influence", "slug": "The-Catalyst"},
    {"title": "Influence Is Your Superpower: The Science of Winning Hearts, Sparking Change, and Making Good Things Happen", "author": "Zoe Chance", "first_published": "2022", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Social Influence", "slug": "Influence-Is-Your-Superpower"},
]
