from __future__ import annotations

# Domain 08: Artificial Intelligence & Future Technology (130 books: #1201–#1330)
BOOKS_08 = [
    # -------------------------------------------------------------------------
    # LEVEL 2: 01. AI CONCEPTS (35 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: ARTIFICIAL INTELLIGENCE (15 books)
    # LEVEL 4: History of AI (5 books)
    {"title": "Genius Makers: The Mavericks Who Brought AI to Google, Facebook, and the World", "author": "Cade Metz", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of AI", "slug": "Genius-Makers"},
    {"title": "The Quest for Artificial Intelligence: A History of Ideas and Achievements", "author": "Nils J. Nilsson", "first_published": "2009", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of AI", "slug": "The-Quest-for-Artificial-Intelligence"},
    {"title": "Machines of Loving Grace: The Quest for Common Ground Between Humans and Robots", "author": "John Markoff", "first_published": "2015", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of AI", "slug": "Machines-of-Loving-Grace"},
    {"title": "Artificial Intelligence: A Guide for Thinking Humans", "author": "Melanie Mitchell", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of AI", "slug": "Artificial-Intelligence-Mitchell"},
    {"title": "Empire of AI: Dreams and Nightmares in Sam Altman's OpenAI", "author": "Karen Hao", "first_published": "2025", "latest_published": "2025", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of AI", "slug": "Empire-of-AI-Hao"},

    # LEVEL 4: AI Concepts (5 books)
    {"title": "Artificial Intelligence: A Modern Approach", "author": "Stuart Russell; Peter Norvig", "first_published": "1995", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Concepts", "slug": "Artificial-Intelligence-A-Modern-Approach"},
    {"title": "The Master Algorithm: How the Quest for the Ultimate Learning Machine Will Remake Our World", "author": "Pedro Domingos", "first_published": "2015", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Concepts", "slug": "The-Master-Algorithm-AI"},
    {"title": "Deep Learning", "author": "Ian Goodfellow; Yoshua Bengio; Aaron Courville", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Concepts", "slug": "Deep-Learning-Goodfellow"},
    {"title": "Deep Learning with Python", "author": "François Chollet", "first_published": "2017", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Concepts", "slug": "Deep-Learning-with-Python"},
    {"title": "Rebooting AI: Building Artificial Intelligence We Can Trust", "author": "Gary Marcus; Ernest Davis", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Concepts", "slug": "Rebooting-AI"},

    # LEVEL 4: Intelligent Systems (5 books)
    {"title": "The Book of Why: The New Science of Cause and Effect", "author": "Judea Pearl; Dana Mackenzie", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligent Systems", "slug": "The-Book-of-Why"},
    {"title": "Causality: Models, Reasoning, and Inference", "author": "Judea Pearl", "first_published": "2000", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligent Systems", "slug": "Causality-Pearl"},
    {"title": "A Thousand Brains: A New Theory of Intelligence", "author": "Jeff Hawkins", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligent Systems", "slug": "A-Thousand-Brains"},
    {"title": "On Intelligence: How a New Understanding of the Brain Will Lead to the Creation of Truly Intelligent Machines", "author": "Jeff Hawkins; Sandra Blakeslee", "first_published": "2004", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligent Systems", "slug": "On-Intelligence"},
    {"title": "Society of Mind", "author": "Marvin Minsky", "first_published": "1986", "latest_published": "1988", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligent Systems", "slug": "Society-of-Mind"},

    # LEVEL 3: MACHINE LEARNING CONCEPTS (10 books)
    # LEVEL 4: Machine Learning Ideas (5 books)
    {"title": "The Hundred-Page Machine Learning Book", "author": "Andriy Burkov", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Machine Learning Ideas", "slug": "The-Hundred-Page-Machine-Learning-Book"},
    {"title": "Machine Learning Yearning", "author": "Andrew Ng", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Machine Learning Ideas", "slug": "Machine-Learning-Yearning"},
    {"title": "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow", "author": "Aurélien Géron", "first_published": "2017", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Machine Learning Ideas", "slug": "Hands-On-Machine-Learning-Geron"},
    {"title": "Interpretable Machine Learning: A Guide for Making Black Box Models Explainable", "author": "Christoph Molnar", "first_published": "2019", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Machine Learning Ideas", "slug": "Interpretable-Machine-Learning"},
    {"title": "Pattern Recognition and Machine Learning", "author": "Christopher M. Bishop", "first_published": "2006", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Machine Learning Ideas", "slug": "Pattern-Recognition-and-Machine-Learning"},

    # LEVEL 4: Data & Learning Systems (5 books)
    {"title": "Designing Machine Learning Systems: An Iterative Process for Production-Ready Applications", "author": "Chip Huyen", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data & Learning Systems", "slug": "Designing-Machine-Learning-Systems"},
    {"title": "AI Engineering: Building Applications with Foundation Models", "author": "Chip Huyen", "first_published": "2024", "latest_published": "2024", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data & Learning Systems", "slug": "AI-Engineering-Huyen"},
    {"title": "Reliable Machine Learning: Applying SRE Principles to ML in Production", "author": "Cathy Chen; Niall Richard Murphy; Kranti Parisa; D. Sculley", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data & Learning Systems", "slug": "Reliable-Machine-Learning"},
    {"title": "Machine Learning Engineering in Action", "author": "Ben Wilson", "first_published": "2022", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data & Learning Systems", "slug": "Machine-Learning-Engineering-in-Action"},
    {"title": "Building Machine Learning Powered Applications: Going from Idea to Product", "author": "Emmanuel Ameisen", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data & Learning Systems", "slug": "Building-Machine-Learning-Powered-Applications"},

    # LEVEL 3: GENERATIVE AI (10 books)
    # LEVEL 4: Language Models (5 books)
    {"title": "Build a Large Language Model (from Scratch)", "author": "Sebastian Raschka", "first_published": "2024", "latest_published": "2024", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Language Models", "slug": "Build-a-Large-Language-Model-from-Scratch"},
    {"title": "The LLM Engineering Handbook", "author": "Paul Iusztin; Maxime Labonne", "first_published": "2024", "latest_published": "2024", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Language Models", "slug": "The-LLM-Engineering-Handbook"},
    {"title": "Natural Language Processing with Transformers: Building Language Applications with Hugging Face", "author": "Lewis Tunstall; Leandro von Werra; Thomas Wolf", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Language Models", "slug": "Natural-Language-Processing-with-Transformers"},
    {"title": "Speech and Language Processing", "author": "Daniel Jurafsky; James H. Martin", "first_published": "2000", "latest_published": "2024", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Language Models", "slug": "Speech-and-Language-Processing"},
    {"title": "Generative Deep Learning: Teaching Machines to Paint, Write, Compose, and Play", "author": "David Foster", "first_published": "2019", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Language Models", "slug": "Generative-Deep-Learning"},

    # LEVEL 4: Generative Systems (5 books)
    {"title": "Co-Intelligence: Living and Working with AI", "author": "Ethan Mollick", "first_published": "2024", "latest_published": "2024", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Generative Systems", "slug": "Co-Intelligence-Mollick"},
    {"title": "The Coming Wave: Technology, Power, and the Twenty-first Century's Greatest Dilemma", "author": "Mustafa Suleyman; Michael Bhaskar", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Generative Systems", "slug": "The-Coming-Wave-Suleyman"},
    {"title": "Nexus: A Brief History of Information Networks from the Stone Age to AI", "author": "Yuval Noah Harari", "first_published": "2024", "latest_published": "2024", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Generative Systems", "slug": "Nexus-Harari"},
    {"title": "Impromptu: Amplifying Our Humanity Through AI", "author": "Reid Hoffman", "first_published": "2023", "latest_published": "2023", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Generative Systems", "slug": "Impromptu-Hoffman"},
    {"title": "All-in On AI: How Smart Companies Win Big with Artificial Intelligence", "author": "Thomas H. Davenport; Nitin Mittal", "first_published": "2023", "latest_published": "2023", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Generative Systems", "slug": "All-in-On-AI"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 02. AI & SOCIETY (35 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: AI SAFETY (10 books)
    # LEVEL 4: AI Alignment (5 books)
    {"title": "Human Compatible: Artificial Intelligence and the Problem of Control", "author": "Stuart Russell", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Alignment", "slug": "Human-Compatible"},
    {"title": "The Alignment Problem: Machine Learning and Human Values", "author": "Brian Christian", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Alignment", "slug": "The-Alignment-Problem"},
    {"title": "Superintelligence: Paths, Dangers, Strategies", "author": "Nick Bostrom", "first_published": "2014", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Alignment", "slug": "Superintelligence"},
    {"title": "Life 3.0: Being Human in the Age of Artificial Intelligence", "author": "Max Tegmark", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Alignment", "slug": "Life-3-0"},
    {"title": "If Then: How the Simulmatics Corporation Invented the Future", "author": "Jill Lepore", "first_published": "2020", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Alignment", "slug": "If-Then-Lepore"},

    # LEVEL 4: AI Risk (5 books)
    {"title": "The Precipice: Existential Risk and the Future of Humanity", "author": "Toby Ord", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Risk", "slug": "The-Precipice-Ord"},
    {"title": "Our Final Invention: Artificial Intelligence and the End of the Human Era", "author": "James Barrat", "first_published": "2013", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Risk", "slug": "Our-Final-Invention"},
    {"title": "Scary Smart: The Future of Artificial Intelligence and How You Can Save Our World", "author": "Mo Gawdat", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Risk", "slug": "Scary-Smart"},
    {"title": "Surviving AI: The Promise and Peril of Artificial Intelligence", "author": "Calum Chace", "first_published": "2015", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Risk", "slug": "Surviving-AI"},
    {"title": "Global Catastrophic Risks", "author": "Nick Bostrom; Milan M. Cirkovic", "first_published": "2008", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "AI Risk", "slug": "Global-Catastrophic-Risks"},

    # LEVEL 3: AI ETHICS (10 books)
    # LEVEL 4: Responsible AI (5 books)
    {"title": "Weapons of Math Destruction: How Big Data Increases Inequality and Threatens Democracy", "author": "Cathy O'Neil", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Responsible AI", "slug": "Weapons-of-Math-Destruction"},
    {"title": "Algorithms of Oppression: How Search Engines Reinforce Racism", "author": "Safiya Umoja Noble", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Responsible AI", "slug": "Algorithms-of-Oppression"},
    {"title": "Automating Inequality: How High-Tech Tools Profile, Police, and Punish the Poor", "author": "Virginia Eubanks", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Responsible AI", "slug": "Automating-Inequality"},
    {"title": "Race After Technology: Abolitionist Tools for the New Jim Code", "author": "Ruha Benjamin", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Responsible AI", "slug": "Race-After-Technology"},
    {"title": "Atlas of AI: Power, Politics, and the Planetary Costs of Artificial Intelligence", "author": "Kate Crawford", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Responsible AI", "slug": "Atlas-of-AI"},

    # LEVEL 4: Algorithmic Society (5 books)
    {"title": "The Ethical Algorithm: The Science of Socially Aware Algorithm Design", "author": "Michael Kearns; Aaron Roth", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Algorithmic Society", "slug": "The-Ethical-Algorithm"},
    {"title": "Hello World: Being Human in the Age of Algorithms", "author": "Hannah Fry", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Algorithmic Society", "slug": "Hello-World-Fry"},
    {"title": "The Black Box Society: The Secret Algorithms That Control Money and Information", "author": "Frank Pasquale", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Algorithmic Society", "slug": "The-Black-Box-Society"},
    {"title": "New Dark Age: Technology and the End of the Future", "author": "James Bridle", "first_published": "2018", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Algorithmic Society", "slug": "New-Dark-Age"},
    {"title": "Ways of Being: Animals, Plants, Machines: The Search for a Planetary Intelligence", "author": "James Bridle", "first_published": "2022", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Algorithmic Society", "slug": "Ways-of-Being"},

    # LEVEL 3: FUTURE OF WORK (15 books)
    # LEVEL 4: Automation & Jobs (5 books)
    {"title": "Rise of the Robots: Technology and the Threat of a Jobless Future", "author": "Martin Ford", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation & Jobs", "slug": "Rise-of-the-Robots"},
    {"title": "Rule of the Robots: How Artificial Intelligence Will Transform Everything", "author": "Martin Ford", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation & Jobs", "slug": "Rule-of-the-Robots"},
    {"title": "A World Without Work: Technology, Automation, and How We Should Respond", "author": "Daniel Susskind", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation & Jobs", "slug": "A-World-Without-Work"},
    {"title": "The Future of the Professions: How Technology Will Transform the Work of Human Experts", "author": "Richard Susskind; Daniel Susskind", "first_published": "2015", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation & Jobs", "slug": "The-Future-of-the-Professions"},
    {"title": "Humans Need Not Apply: A Guide to Wealth and Work in the Age of Artificial Intelligence", "author": "Jerry Kaplan", "first_published": "2015", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation & Jobs", "slug": "Humans-Need-Not-Apply"},

    # LEVEL 4: Human-AI Collaboration (5 books)
    {"title": "Human + Machine: Reimagining Work in the Age of AI", "author": "Paul R. Daugherty; H. James Wilson", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human-AI Collaboration", "slug": "Human-Plus-Machine"},
    {"title": "Radically Human: How New Technology Is Transforming Business and Shaping Our Future", "author": "Paul R. Daugherty; H. James Wilson", "first_published": "2022", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human-AI Collaboration", "slug": "Radically-Human"},
    {"title": "Deep Thinking: Where Machine Intelligence Ends and Human Creativity Begins", "author": "Garry Kasparov; Mig Greengard", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human-AI Collaboration", "slug": "Deep-Thinking-Kasparov"},
    {"title": "Only Humans Need Apply: Winners and Losers in the Age of Smart Machines", "author": "Thomas H. Davenport; Julia Kirby", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human-AI Collaboration", "slug": "Only-Humans-Need-Apply"},
    {"title": "Competing in the Age of AI: Strategy and Leadership When Algorithms and Networks Run the World", "author": "Marco Iansiti; Karim R. Lakhani", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human-AI Collaboration", "slug": "Competing-in-the-Age-of-AI"},

    # LEVEL 4: Future Skills (5 books)
    {"title": "Futureproof: 9 Rules for Humans in the Age of Automation", "author": "Kevin Roose", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Future Skills", "slug": "Futureproof-Roose"},
    {"title": "Robot-Proof: Higher Education in the Age of Artificial Intelligence", "author": "Joseph E. Aoun", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Future Skills", "slug": "Robot-Proof"},
    {"title": "21 Lessons for the 21st Century", "author": "Yuval Noah Harari", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Future Skills", "slug": "21-Lessons-for-the-21st-Century"},
    {"title": "Homo Deus: A Brief History of Tomorrow", "author": "Yuval Noah Harari", "first_published": "2015", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Future Skills", "slug": "Homo-Deus"},
    {"title": "AI 2041: Ten Visions for Our Future", "author": "Kai-Fu Lee; Chen Qiufan", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Future Skills", "slug": "AI-2041"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 03. EMERGING TECHNOLOGY (35 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: ROBOTICS (10 books)
    # LEVEL 4: Intelligent Machines (5 books)
    {"title": "AI Superpowers: China, Silicon Valley, and the New World Order", "author": "Kai-Fu Lee", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligent Machines", "slug": "AI-Superpowers"},
    {"title": "Probabilistic Robotics", "author": "Sebastian Thrun; Wolfram Burgard; Dieter Fox", "first_published": "2005", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligent Machines", "slug": "Probabilistic-Robotics"},
    {"title": "Introduction to Autonomous Mobile Robots", "author": "Roland Siegwart; Illah R. Nourbakhsh; Davide Scaramuzza", "first_published": "2004", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligent Machines", "slug": "Introduction-to-Autonomous-Mobile-Robots"},
    {"title": "Robot: Mere Machine to Transcendent Mind", "author": "Hans Moravec", "first_published": "1998", "latest_published": "2000", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligent Machines", "slug": "Robot-Moravec"},
    {"title": "Mind Children: The Future of Robot and Human Intelligence", "author": "Hans Moravec", "first_published": "1988", "latest_published": "1990", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligent Machines", "slug": "Mind-Children"},

    # LEVEL 4: Automation (5 books)
    {"title": "The Fourth Industrial Revolution", "author": "Klaus Schwab", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation", "slug": "The-Fourth-Industrial-Revolution"},
    {"title": "Shaping the Future of the Fourth Industrial Revolution", "author": "Klaus Schwab; Nicholas Davis", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation", "slug": "Shaping-the-Future-of-the-Fourth-Industrial-Revolution"},
    {"title": "The Lights in the Tunnel: Automation, Accelerating Technology and the Economy of the Future", "author": "Martin Ford", "first_published": "2009", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation", "slug": "The-Lights-in-the-Tunnel"},
    {"title": "Race Against the Machine: How the Digital Revolution is Accelerating Innovation, Driving Productivity, and Irreversibly Transforming Employment and the Economy", "author": "Erik Brynjolfsson; Andrew McAfee", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation", "slug": "Race-Against-the-Machine"},
    {"title": "Autonomous Driving: Technical, Legal and Social Aspects", "author": "Markus Maurer; J. Christian Gerdes; Barbara Lenz; Hermann Winner", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation", "slug": "Autonomous-Driving-Maurer"},

    # LEVEL 3: QUANTUM TECHNOLOGY (5 books)
    # LEVEL 4: Quantum Computing Concepts (5 books)
    {"title": "Quantum Computing Since Democritus", "author": "Scott Aaronson", "first_published": "2013", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Quantum Computing Concepts", "slug": "Quantum-Computing-Since-Democritus"},
    {"title": "Quantum Computation and Quantum Information", "author": "Michael A. Nielsen; Isaac L. Chuang", "first_published": "2000", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Quantum Computing Concepts", "slug": "Quantum-Computation-and-Quantum-Information"},
    {"title": "Programming Quantum Computers: Essential Algorithms and Code Samples", "author": "Eric R. Johnston; Nic Harrigan; Mercedes Gimeno-Segovia", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Quantum Computing Concepts", "slug": "Programming-Quantum-Computers"},
    {"title": "Quantum Computing: An Applied Approach", "author": "Jack D. Hidary", "first_published": "2019", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Quantum Computing Concepts", "slug": "Quantum-Computing-Hidary"},
    {"title": "Quantum Supremacy: How the Quantum Computer Revolution Will Change Everything", "author": "Michio Kaku", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Quantum Computing Concepts", "slug": "Quantum-Supremacy-Kaku"},

    # LEVEL 3: BIOTECHNOLOGY (10 books)
    # LEVEL 4: Biotechnology (5 books)
    {"title": "The Code Breaker: Jennifer Doudna, Gene Editing, and the Future of the Human Race", "author": "Walter Isaacson", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Biotechnology", "slug": "The-Code-Breaker"},
    {"title": "A Crack in Creation: Gene Editing and the Unthinkable Power to Control Evolution", "author": "Jennifer A. Doudna; Samuel H. Sternberg", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Biotechnology", "slug": "A-Crack-in-Creation"},
    {"title": "The Genesis Machine: Our Quest to Rewrite Life in the Age of Synthetic Biology", "author": "Amy Webb; Andrew Hessel", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Biotechnology", "slug": "The-Genesis-Machine"},
    {"title": "Regenesis: How Synthetic Biology Will Reinvent Nature and Ourselves", "author": "George M. Church; Ed Regis", "first_published": "2012", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Biotechnology", "slug": "Regenesis-Church"},
    {"title": "Synthetic: How Life Got Made", "author": "Sophia Roosth", "first_published": "2017", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Biotechnology", "slug": "Synthetic-Roosth"},

    # LEVEL 4: Genetic Technology (5 books)
    {"title": "The Gene: An Intimate History", "author": "Siddhartha Mukherjee", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Genetic Technology", "slug": "The-Gene-Mukherjee"},
    {"title": "The Song of the Cell: An Exploration of Medicine and the New Human", "author": "Siddhartha Mukherjee", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Genetic Technology", "slug": "The-Song-of-the-Cell"},
    {"title": "Hacking Darwin: Genetic Engineering and the Future of Humanity", "author": "Jamie Metzl", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Genetic Technology", "slug": "Hacking-Darwin"},
    {"title": "She Has Her Mother's Laugh: The Powers, Perversions, and Potential of Heredity", "author": "Carl Zimmer", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Genetic Technology", "slug": "She-Has-Her-Mothers-Laugh"},
    {"title": "Asimov's Guide to Science", "author": "Isaac Asimov", "first_published": "1972", "latest_published": "1984", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Genetic Technology", "slug": "Asimovs-Guide-to-Science"},

    # LEVEL 3: FUTURE TECHNOLOGY (10 books)
    # LEVEL 4: Technology Forecasting (5 books)
    {"title": "The Singularity Is Near: When Humans Transcend Biology", "author": "Ray Kurzweil", "first_published": "2005", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technology Forecasting", "slug": "The-Singularity-Is-Near"},
    {"title": "The Singularity Is Nearer: When We Merge with AI", "author": "Ray Kurzweil", "first_published": "2024", "latest_published": "2024", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technology Forecasting", "slug": "The-Singularity-Is-Nearer"},
    {"title": "How to Create a Mind: The Secret of Human Thought Revealed", "author": "Ray Kurzweil", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technology Forecasting", "slug": "How-to-Create-a-Mind"},
    {"title": "Abundance: The Future Is Better Than You Think", "author": "Peter H. Diamandis; Steven Kotler", "first_published": "2012", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technology Forecasting", "slug": "Abundance-Diamandis"},
    {"title": "The Future Is Faster Than You Think: How Converging Technologies Are Transforming Business, Industries, and Our Lives", "author": "Peter H. Diamandis; Steven Kotler", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technology Forecasting", "slug": "The-Future-Is-Faster-Than-You-Think"},

    # LEVEL 4: Emerging Technologies (5 books)
    {"title": "Physics of the Future: How Science Will Shape Human Destiny and Our Daily Lives by the Year 2100", "author": "Michio Kaku", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Emerging Technologies", "slug": "Physics-of-the-Future"},
    {"title": "The Future of Humanity: Terraforming Mars, Interstellar Travel, Immortality, and Our Destiny Beyond Earth", "author": "Michio Kaku", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Emerging Technologies", "slug": "The-Future-of-Humanity-Kaku"},
    {"title": "Soonish: Ten Emerging Technologies That'll Improve and/or Ruin Everything", "author": "Kelly Weinersmith; Zach Weinersmith", "first_published": "2017", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Emerging Technologies", "slug": "Soonish"},
    {"title": "A City on Mars: Can We Settle Space, Should We Settle Space, and Have We Really Thought This Through?", "author": "Kelly Weinersmith; Zach Weinersmith", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Emerging Technologies", "slug": "A-City-on-Mars"},
    {"title": "The Extreme Future: The Top Trends That Will Reshape the World in the Next 20 Years", "author": "James Canton", "first_published": "2006", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Emerging Technologies", "slug": "The-Extreme-Future"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 04. FUTURES & LONG-TERM THINKING (25 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: FUTURES STUDIES (10 books)
    # LEVEL 4: Forecasting (5 books)
    {"title": "The Signals Are Talking: Why Today's Fringe Is Tomorrow's Mainstream", "author": "Amy Webb", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Forecasting", "slug": "The-Signals-Are-Talking"},
    {"title": "The Big Nine: How the Tech Titans and Their Thinking Machines Could Warp Humanity", "author": "Amy Webb", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Forecasting", "slug": "The-Big-Nine"},
    {"title": "Thinking About the Future: Guidelines for Strategic Foresight", "author": "Peter C. Bishop; Andy Hines", "first_published": "2007", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Forecasting", "slug": "Thinking-About-the-Future-Bishop"},
    {"title": "Future Savvy: Quality Anticipation, Responsible Planning, and Robust Decision-Making", "author": "Adam Gordon", "first_published": "2008", "latest_published": "2008", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Forecasting", "slug": "Future-Savvy"},
    {"title": "The Art of the Long View: Planning for the Future in an Uncertain World", "author": "Peter Schwartz", "first_published": "1991", "latest_published": "1996", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Forecasting", "slug": "The-Art-of-the-Long-View"},

    # LEVEL 4: Scenario Thinking (5 books)
    {"title": "Scenario Planning: The Link Between Future and Strategy", "author": "Mats Lindgren; Hans Bandhold", "first_published": "2003", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Scenario Thinking", "slug": "Scenario-Planning-Lindgren"},
    {"title": "Learning from the Future: Competitive Foresight Scenarios", "author": "Liam Fahey; Robert M. Randall", "first_published": "1997", "latest_published": "1997", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Scenario Thinking", "slug": "Learning-from-the-Future"},
    {"title": "Scenarios: The Art of Strategic Conversation", "author": "Kees van der Heijden", "first_published": "1996", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Scenario Thinking", "slug": "Scenarios-van-der-Heijden"},
    {"title": "Strategic Reframing: The Oxford Scenario Planning Approach", "author": "Rafael Ramirez; Angela Wilkinson", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Scenario Thinking", "slug": "Strategic-Reframing"},
    {"title": "Future Shock", "author": "Alvin Toffler", "first_published": "1970", "latest_published": "1984", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Scenario Thinking", "slug": "Future-Shock"},

    # LEVEL 3: LONG-TERM FUTURE (15 books)
    # LEVEL 4: Civilization Futures (5 books)
    {"title": "The Third Wave", "author": "Alvin Toffler", "first_published": "1980", "latest_published": "1984", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civilization Futures", "slug": "The-Third-Wave"},
    {"title": "Powershift: Knowledge, Wealth, and Power at the Edge of the 21st Century", "author": "Alvin Toffler", "first_published": "1990", "latest_published": "1991", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civilization Futures", "slug": "Powershift-Toffler"},
    {"title": "What We Owe the Future", "author": "William MacAskill", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civilization Futures", "slug": "What-We-Owe-the-Future"},
    {"title": "Doing Good Better: How Effective Altruism Can Help You Make a Difference", "author": "William MacAskill", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civilization Futures", "slug": "Doing-Good-Better"},
    {"title": "The Good Ancestor: A Radical Prescription for Long-Term Thinking", "author": "Roman Krznaric", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civilization Futures", "slug": "The-Good-Ancestor"},

    # LEVEL 4: Existential Risk (5 books)
    {"title": "Our Final Hour: A Scientist's Warning: How Terror, Error, and Environmental Disaster Threaten Humankind's Future in This Century—On Earth and Beyond", "author": "Martin Rees", "first_published": "2003", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Existential Risk", "slug": "Our-Final-Hour"},
    {"title": "On the Future: Prospects for Humanity", "author": "Martin Rees", "first_published": "2018", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Existential Risk", "slug": "On-the-Future-Rees"},
    {"title": "End Times: A Brief Guide to the End of the World", "author": "Bryan Walsh", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Existential Risk", "slug": "End-Times-Walsh"},
    {"title": "X-Risk: How Humanity Discovered Its Own Extinction", "author": "Thomas Moynihan", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Existential Risk", "slug": "X-Risk-Moynihan"},
    {"title": "Engines of Creation: The Coming Era of Nanotechnology", "author": "K. Eric Drexler", "first_published": "1986", "latest_published": "1990", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Existential Risk", "slug": "Engines-of-Creation"},

    # LEVEL 4: Long-Term Human Progress (5 books)
    {"title": "Enlightenment Now: The Case for Reason, Science, Humanism, and Progress", "author": "Steven Pinker", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Human Progress", "slug": "Enlightenment-Now"},
    {"title": "The Better Angels of Our Nature: Why Violence Has Declined", "author": "Steven Pinker", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Human Progress", "slug": "The-Better-Angels-of-Our-Nature"},
    {"title": "Factfulness: Ten Reasons We're Wrong About the World—and Why Things Are Better Than You Think", "author": "Hans Rosling; Ola Rosling; Anna Rosling Rönnlund", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Human Progress", "slug": "Factfulness"},
    {"title": "The Rational Optimist: How Prosperity Evolves", "author": "Matt Ridley", "first_published": "2010", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Human Progress", "slug": "The-Rational-Optimist"},
    {"title": "Progress: Ten Reasons to Look Forward to the Future", "author": "Johan Norberg", "first_published": "2016", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Human Progress", "slug": "Progress-Norberg"},
]
