from __future__ import annotations

# Domain 07: Computer Science & Technology Concepts (160 books: #1041–#1200)
BOOKS_07 = [
    # -------------------------------------------------------------------------
    # LEVEL 2: 01. COMPUTING FUNDAMENTALS (35 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: HISTORY & PHILOSOPHY OF COMPUTING (10 books)
    # LEVEL 4: History of Computing (5 books)
    {"title": "The Innovators: How a Group of Hackers, Geniuses, and Geeks Created the Digital Revolution", "author": "Walter Isaacson", "first_published": "2014", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Computing", "slug": "The-Innovators-Isaacson"},
    {"title": "Hackers: Heroes of the Computer Revolution", "author": "Steven Levy", "first_published": "1984", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Computing", "slug": "Hackers-Levy"},
    {"title": "The Soul of a New Machine", "author": "Tracy Kidder", "first_published": "1981", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Computing", "slug": "The-Soul-of-a-New-Machine"},
    {"title": "Where Wizards Stay Up Late: The Origins of the Internet", "author": "Katie Hafner; Matthew Lyon", "first_published": "1996", "latest_published": "1998", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Computing", "slug": "Where-Wizards-Stay-Up-Late"},
    {"title": "Dealers of Lightning: Xerox PARC and the Dawn of the Computer Age", "author": "Michael A. Hiltzik", "first_published": "1999", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Computing", "slug": "Dealers-of-Lightning"},

    # LEVEL 4: Computing Concepts (5 books)
    {"title": "Code: The Hidden Language of Computer Hardware and Software", "author": "Charles Petzold", "first_published": "1999", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Computing Concepts", "slug": "Code-Petzold"},
    {"title": "The Elements of Computing Systems: Building a Modern Computer from First Principles (Nand to Tetris)", "author": "Noam Nisan; Shimon Schocken", "first_published": "2005", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Computing Concepts", "slug": "The-Elements-of-Computing-Systems"},
    {"title": "Structure and Interpretation of Computer Programs", "author": "Harold Abelson; Gerald Jay Sussman; Julie Sussman", "first_published": "1984", "latest_published": "1996", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Computing Concepts", "slug": "Structure-and-Interpretation-of-Computer-Programs"},
    {"title": "Turing's Cathedral: The Origins of the Digital Universe", "author": "George Dyson", "first_published": "2012", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Computing Concepts", "slug": "Turings-Cathedral"},
    {"title": "The Pattern On The Stone: The Simple Ideas That Make Computers Work", "author": "W. Daniel Hillis", "first_published": "1998", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Computing Concepts", "slug": "The-Pattern-On-The-Stone"},

    # LEVEL 3: COMPUTER SYSTEMS (15 books)
    # LEVEL 4: Operating System Concepts (5 books)
    {"title": "Operating Systems: Three Easy Pieces", "author": "Remzi H. Arpaci-Dusseau; Andrea C. Arpaci-Dusseau", "first_published": "2014", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Operating System Concepts", "slug": "Operating-Systems-Three-Easy-Pieces"},
    {"title": "Modern Operating Systems", "author": "Andrew S. Tanenbaum; Herbert Bos", "first_published": "1992", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Operating System Concepts", "slug": "Modern-Operating-Systems-Tanenbaum"},
    {"title": "The Design of the UNIX Operating System", "author": "Maurice J. Bach", "first_published": "1986", "latest_published": "1986", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Operating System Concepts", "slug": "The-Design-of-the-UNIX-Operating-System"},
    {"title": "The Linux Programming Interface: A Linux and UNIX System Programming Handbook", "author": "Michael Kerrisk", "first_published": "2010", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Operating System Concepts", "slug": "The-Linux-Programming-Interface"},
    {"title": "Computer Systems: A Programmer's Perspective", "author": "Randal E. Bryant; David R. O'Hallaron", "first_published": "2002", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Operating System Concepts", "slug": "Computer-Systems-A-Programmers-Perspective"},

    # LEVEL 4: Networks & Internet (5 books)
    {"title": "Computer Networking: A Top-Down Approach", "author": "James F. Kurose; Keith W. Ross", "first_published": "2000", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Networks & Internet", "slug": "Computer-Networking-A-Top-Down-Approach"},
    {"title": "TCP/IP Illustrated, Volume 1: The Protocols", "author": "W. Richard Stevens; Kevin R. Fall", "first_published": "1994", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Networks & Internet", "slug": "TCP-IP-Illustrated"},
    {"title": "High Performance Browser Networking: What Every Web Developer Should Know About Networking and Web Performance", "author": "Ilya Grigorik", "first_published": "2013", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Networks & Internet", "slug": "High-Performance-Browser-Networking"},
    {"title": "HTTP: The Definitive Guide", "author": "David Gourley; Brian Totty; Marjorie Sayer; Sailu Reddy; Anshu Aggarwal", "first_published": "2002", "latest_published": "2002", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Networks & Internet", "slug": "HTTP-The-Definitive-Guide"},
    {"title": "Computer Networks", "author": "Andrew S. Tanenbaum; David J. Wetherall; Nick Feamster", "first_published": "1981", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Networks & Internet", "slug": "Computer-Networks-Tanenbaum"},

    # LEVEL 4: Distributed Systems Concepts (5 books)
    {"title": "Designing Data-Intensive Applications: The Big Ideas Behind Reliable, Scalable, and Maintainable Systems", "author": "Martin Kleppmann", "first_published": "2017", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distributed Systems Concepts", "slug": "Designing-Data-Intensive-Applications"},
    {"title": "Distributed Systems: Principles and Paradigms", "author": "Andrew S. Tanenbaum; Maarten van Steen", "first_published": "2002", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distributed Systems Concepts", "slug": "Distributed-Systems-Tanenbaum"},
    {"title": "Understanding Distributed Systems: What Every Developer Should Know About Large Distributed Applications", "author": "Roberto Vitillo", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distributed Systems Concepts", "slug": "Understanding-Distributed-Systems-Vitillo"},
    {"title": "Database Internals: A Deep Dive into How Distributed Data Systems Work", "author": "Alex Petrov", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distributed Systems Concepts", "slug": "Database-Internals-Petrov"},
    {"title": "Patterns of Distributed Systems", "author": "Unmesh Joshi", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Distributed Systems Concepts", "slug": "Patterns-of-Distributed-Systems"},

    # LEVEL 3: ALGORITHMIC THINKING (10 books)
    # LEVEL 4: Computational Thinking (5 books)
    {"title": "Computational Thinking", "author": "Peter J. Denning; Matti Tedre", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Computational Thinking", "slug": "Computational-Thinking-Denning"},
    {"title": "Nine Algorithms That Changed the Future: The Ingenious Ideas That Drive Today's Computers", "author": "John MacCormick", "first_published": "2011", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Computational Thinking", "slug": "Nine-Algorithms-That-Changed-the-Future"},
    {"title": "Grokking Algorithms: An Illustrated Guide for Programmers and Other Curious People", "author": "Aditya Y. Bhargava", "first_published": "2016", "latest_published": "2024", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Computational Thinking", "slug": "Grokking-Algorithms"},
    {"title": "Once Upon an Algorithm: How Stories Explain Computing", "author": "Martin Erwig", "first_published": "2017", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Computational Thinking", "slug": "Once-Upon-an-Algorithm"},
    {"title": "Think Like a Programmer: An Introduction to Creative Problem Solving", "author": "V. Anton Spraul", "first_published": "2012", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Computational Thinking", "slug": "Think-Like-a-Programmer"},

    # LEVEL 4: Algorithmic Thinking (5 books)
    {"title": "Introduction to Algorithms", "author": "Thomas H. Cormen; Charles E. Leiserson; Ronald L. Rivest; Clifford Stein", "first_published": "1990", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Algorithmic Thinking", "slug": "Introduction-to-Algorithms-CLRS"},
    {"title": "The Algorithm Design Manual", "author": "Steven S. Skiena", "first_published": "1997", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Algorithmic Thinking", "slug": "The-Algorithm-Design-Manual"},
    {"title": "Algorithms", "author": "Robert Sedgewick; Kevin Wayne", "first_published": "1983", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Algorithmic Thinking", "slug": "Algorithms-Sedgewick"},
    {"title": "Algorithms Unlocked", "author": "Thomas H. Cormen", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Algorithmic Thinking", "slug": "Algorithms-Unlocked"},
    {"title": "Algorithm Design", "author": "Jon Kleinberg; Éva Tardos", "first_published": "2005", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Algorithmic Thinking", "slug": "Algorithm-Design-Kleinberg-Tardos"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 02. SOFTWARE ENGINEERING (45 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: SOFTWARE DESIGN (15 books)
    # LEVEL 4: Design Principles (5 books)
    {"title": "Design Patterns: Elements of Reusable Object-Oriented Software", "author": "Erich Gamma; Richard Helm; Ralph Johnson; John Vlissides", "first_published": "1994", "latest_published": "1994", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Design Principles", "slug": "Design-Patterns-GoF"},
    {"title": "Head First Design Patterns: A Brain-Friendly Guide", "author": "Eric Freeman; Elisabeth Robson", "first_published": "2004", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Design Principles", "slug": "Head-First-Design-Patterns"},
    {"title": "A Philosophy of Software Design", "author": "John Ousterhout", "first_published": "2018", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Design Principles", "slug": "A-Philosophy-of-Software-Design"},
    {"title": "Clean Architecture: A Craftsman's Guide to Software Structure and Design", "author": "Robert C. Martin", "first_published": "2017", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Design Principles", "slug": "Clean-Architecture"},
    {"title": "Domain-Driven Design: Tackling Complexity in the Heart of Software", "author": "Eric Evans", "first_published": "2003", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Design Principles", "slug": "Domain-Driven-Design-Evans"},

    # LEVEL 4: Architecture Concepts (5 books)
    {"title": "Software Architecture in Practice", "author": "Len Bass; Paul Clements; Rick Kazman", "first_published": "1998", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Architecture Concepts", "slug": "Software-Architecture-in-Practice"},
    {"title": "Fundamentals of Software Architecture: An Engineering Approach", "author": "Mark Richards; Neal Ford", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Architecture Concepts", "slug": "Fundamentals-of-Software-Architecture"},
    {"title": "Software Architecture: The Hard Parts: Modern Trade-Off Analyses for Distributed Architectures", "author": "Neal Ford; Mark Richards; Pramod Sadalage; Zhamak Dehghani", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Architecture Concepts", "slug": "Software-Architecture-The-Hard-Parts"},
    {"title": "Building Evolutionary Architectures: Automated Software Governance", "author": "Neal Ford; Rebecca Parsons; Patrick Kua; Pramod Sadalage", "first_published": "2017", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Architecture Concepts", "slug": "Building-Evolutionary-Architectures"},
    {"title": "Building Microservices: Designing Fine-Grained Systems", "author": "Sam Newman", "first_published": "2015", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Architecture Concepts", "slug": "Building-Microservices-Newman"},

    # LEVEL 4: System Design Thinking (5 books)
    {"title": "System Design Interview – An Insider's Guide: Volume 1", "author": "Alex Xu", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "System Design Thinking", "slug": "System-Design-Interview-Vol-1"},
    {"title": "System Design Interview – An Insider's Guide: Volume 2", "author": "Alex Xu; Sahn Lam", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "System Design Thinking", "slug": "System-Design-Interview-Vol-2"},
    {"title": "Release It!: Design and Deploy Production-Ready Software", "author": "Michael T. Nygard", "first_published": "2007", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "System Design Thinking", "slug": "Release-It-Nygard"},
    {"title": "Enterprise Integration Patterns: Designing, Building, and Deploying Messaging Solutions", "author": "Gregor Hohpe; Bobby Woolf", "first_published": "2003", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "System Design Thinking", "slug": "Enterprise-Integration-Patterns"},
    {"title": "The Software Architect Elevator: Redefining the Architect's Role in the Digital Enterprise", "author": "Gregor Hohpe", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "System Design Thinking", "slug": "The-Software-Architect-Elevator"},

    # LEVEL 3: SOFTWARE QUALITY (15 books)
    # LEVEL 4: Clean Code Concepts (5 books)
    {"title": "Clean Code: A Handbook of Agile Software Craftsmanship", "author": "Robert C. Martin", "first_published": "2008", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Clean Code Concepts", "slug": "Clean-Code"},
    {"title": "The Pragmatic Programmer: Your Journey to Mastery", "author": "David Thomas; Andrew Hunt", "first_published": "1999", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Clean Code Concepts", "slug": "The-Pragmatic-Programmer"},
    {"title": "The Clean Coder: A Code of Conduct for Professional Programmers", "author": "Robert C. Martin", "first_published": "2011", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Clean Code Concepts", "slug": "The-Clean-Coder"},
    {"title": "Code Complete: A Practical Handbook of Software Construction", "author": "Steve McConnell", "first_published": "1993", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Clean Code Concepts", "slug": "Code-Complete"},
    {"title": "The Art of Readable Code", "author": "Dustin Boswell; Trevor Foucher", "first_published": "2011", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Clean Code Concepts", "slug": "The-Art-of-Readable-Code"},

    # LEVEL 4: Refactoring (5 books)
    {"title": "Refactoring: Improving the Design of Existing Code", "author": "Martin Fowler; Kent Beck", "first_published": "1999", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Refactoring", "slug": "Refactoring-Fowler"},
    {"title": "Working Effectively with Legacy Code", "author": "Michael C. Feathers", "first_published": "2004", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Refactoring", "slug": "Working-Effectively-with-Legacy-Code"},
    {"title": "Refactoring to Patterns", "author": "Joshua Kerievsky", "first_published": "2004", "latest_published": "2004", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Refactoring", "slug": "Refactoring-to-Patterns"},
    {"title": "Modernizing Legacy Systems: Software Technologies, Engineering Processes and Business Practices", "author": "Robert C. Seacord; Daniel Plakosh; Grace A. Lewis", "first_published": "2003", "latest_published": "2003", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Refactoring", "slug": "Modernizing-Legacy-Systems"},
    {"title": "Software Systems Architecture: Working with Stakeholders Using Viewpoints and Perspectives", "author": "Nick Rozanski; Eóin Woods", "first_published": "2005", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Refactoring", "slug": "Software-Systems-Architecture"},

    # LEVEL 4: Testing Philosophy (5 books)
    {"title": "Test Driven Development: By Example", "author": "Kent Beck", "first_published": "2002", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Testing Philosophy", "slug": "Test-Driven-Development-Beck"},
    {"title": "Growing Object-Oriented Software, Guided by Tests", "author": "Steve Freeman; Nat Pryce", "first_published": "2009", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Testing Philosophy", "slug": "Growing-Object-Oriented-Software-Guided-by-Tests"},
    {"title": "Unit Testing Principles, Practices, and Patterns", "author": "Vladimir Khorikov", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Testing Philosophy", "slug": "Unit-Testing-Khorikov"},
    {"title": "The Art of Software Testing", "author": "Glenford J. Myers; Corey Sandler; Tom Badgett", "first_published": "1979", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Testing Philosophy", "slug": "The-Art-of-Software-Testing"},
    {"title": "Software Engineering at Google: Lessons Learned from Programming Over Time", "author": "Titus Winters; Tom Manshreck; Hyrum Wright", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Testing Philosophy", "slug": "Software-Engineering-at-Google"},

    # LEVEL 3: SOFTWARE DELIVERY (15 books)
    # LEVEL 4: Agile Concepts (5 books)
    {"title": "Continuous Delivery: Reliable Software Releases through Build, Test, and Deployment Automation", "author": "Jez Humble; David Farley", "first_published": "2010", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Agile Concepts", "slug": "Continuous-Delivery-Humble"},
    {"title": "Extreme Programming Explained: Embrace Change", "author": "Kent Beck; Cynthia Andres", "first_published": "1999", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Agile Concepts", "slug": "Extreme-Programming-Explained"},
    {"title": "User Story Mapping: Discover the Whole Story, Build the Right Product", "author": "Jeff Patton; Peter Economy", "first_published": "2014", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Agile Concepts", "slug": "User-Story-Mapping"},
    {"title": "Scrum: The Art of Doing Twice the Work in Half the Time", "author": "Jeff Sutherland", "first_published": "2014", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Agile Concepts", "slug": "Scrum-Sutherland"},
    {"title": "Modern Software Engineering: Doing What Works to Build Better Software Faster", "author": "David Farley", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Agile Concepts", "slug": "Modern-Software-Engineering-Farley"},

    # LEVEL 4: DevOps & Reliability (5 books)
    {"title": "Site Reliability Engineering: How Google Runs Production Systems", "author": "Niall Richard Murphy; Betsy Beyer; Chris Jones; Jennifer Petoff", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "DevOps & Reliability", "slug": "Site-Reliability-Engineering"},
    {"title": "The Site Reliability Workbook: Practical Ways to Implement SRE", "author": "Betsy Beyer; Niall Richard Murphy; David K. Rensin; Kent Kawahara; Stephen Thorne", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "DevOps & Reliability", "slug": "The-Site-Reliability-Workbook"},
    {"title": "The DevOps Handbook: How to Create World-Class Agility, Reliability, and Security in Technology Organizations", "author": "Gene Kim; Jez Humble; Patrick Debois; John Willis", "first_published": "2016", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "DevOps & Reliability", "slug": "The-DevOps-Handbook"},
    {"title": "Accelerate: The Science of Lean Software and DevOps: Building and Scaling High Performing Technology Organizations", "author": "Nicole Forsgren; Jez Humble; Gene Kim", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "DevOps & Reliability", "slug": "Accelerate-Forsgren"},
    {"title": "Chaos Engineering: System Resiliency in Practice", "author": "Casey Rosenthal; Nora Jones", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "DevOps & Reliability", "slug": "Chaos-Engineering-Rosenthal"},

    # LEVEL 4: Engineering Organizations (5 books)
    {"title": "Team Topologies: Organizing Business and Technology Teams for Fast Flow", "author": "Matthew Skelton; Manuel Pais", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Engineering Organizations", "slug": "Team-Topologies"},
    {"title": "The Mythical Man-Month: Essays on Software Engineering", "author": "Frederick P. Brooks Jr.", "first_published": "1975", "latest_published": "1995", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Engineering Organizations", "slug": "The-Mythical-Man-Month"},
    {"title": "An Elegant Puzzle: Systems of Engineering Management", "author": "Will Larson", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Engineering Organizations", "slug": "An-Elegant-Puzzle"},
    {"title": "Staff Engineer: Leadership Beyond the Management Track", "author": "Will Larson", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Engineering Organizations", "slug": "Staff-Engineer-Larson"},
    {"title": "The Manager's Path: A Guide for Tech Leaders Navigating Growth and Change", "author": "Camille Fournier", "first_published": "2017", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Engineering Organizations", "slug": "The-Managers-Path"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 03. DATA & DIGITAL SYSTEMS (35 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: DATA (15 books)
    # LEVEL 4: Data Systems (5 books)
    {"title": "Fundamentals of Data Engineering: Plan and Build Robust Data Systems", "author": "Joe Reis; Matt Housley", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data Systems", "slug": "Fundamentals-of-Data-Engineering"},
    {"title": "Data Mesh: Delivering Data-Driven Value at Scale", "author": "Zhamak Dehghani", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data Systems", "slug": "Data-Mesh-Dehghani"},
    {"title": "Streaming Systems: The What, Where, When, and How of Large-Scale Data Processing", "author": "Tyler Akidau; Slava Chernyak; Reuven Lax", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data Systems", "slug": "Streaming-Systems"},
    {"title": "Making Data Talk: Communicating Public Health Data to the Public, Policy Makers, and the Press", "author": "David E. Nelson", "first_published": "2009", "latest_published": "2009", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data Systems", "slug": "Making-Data-Talk"},
    {"title": "Big Data: A Revolution That Will Transform How We Live, Work, and Think", "author": "Viktor Mayer-Schönberger; Kenneth Cukier", "first_published": "2013", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data Systems", "slug": "Big-Data-Mayer-Schonberger"},

    # LEVEL 4: Databases Concepts (5 books)
    {"title": "Database System Concepts", "author": "Abraham Silberschatz; Henry F. Korth; S. Sudarshan", "first_published": "1986", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Databases Concepts", "slug": "Database-System-Concepts"},
    {"title": "Seven Databases in Seven Weeks: A Guide to Modern Databases and the NoSQL Movement", "author": "Luc Perkins; Eric Redmond; Jim Wilson", "first_published": "2012", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Databases Concepts", "slug": "Seven-Databases-in-Seven-Weeks"},
    {"title": "Readings in Database Systems (The Red Book)", "author": "Peter Bailis; Joseph M. Hellerstein; Michael Stonebraker", "first_published": "1988", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Databases Concepts", "slug": "Readings-in-Database-Systems"},
    {"title": "NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence", "author": "Pramod J. Sadalage; Martin Fowler", "first_published": "2012", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Databases Concepts", "slug": "NoSQL-Distilled"},
    {"title": "SQL and Relational Theory: How to Write Accurate SQL Code", "author": "C.J. Date", "first_published": "2009", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Databases Concepts", "slug": "SQL-and-Relational-Theory"},

    # LEVEL 4: Data Engineering Concepts (5 books)
    {"title": "The Data Warehouse Toolkit: The Definitive Guide to Dimensional Modeling", "author": "Ralph Kimball; Margy Ross", "first_published": "1996", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data Engineering Concepts", "slug": "The-Data-Warehouse-Toolkit"},
    {"title": "Building a Scalable Data Warehouse with Data Vault 2.0", "author": "Dan Linstedt; Michael Olschimke", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data Engineering Concepts", "slug": "Building-a-Scalable-Data-Warehouse-Data-Vault"},
    {"title": "Kafka: The Definitive Guide: Real-Time Data and Stream Processing at Scale", "author": "Gwen Shapira; Todd Palino; Rajini Sivaram; Krit Petty", "first_published": "2017", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data Engineering Concepts", "slug": "Kafka-The-Definitive-Guide"},
    {"title": "Learning Spark: Lightning-Fast Data Analytics", "author": "Jules S. Damji; Brooke Wenig; Tathagata Das; Denny Lee", "first_published": "2015", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data Engineering Concepts", "slug": "Learning-Spark"},
    {"title": "Data Pipelines Pocket Reference: Moving and Processing Data for Analytics", "author": "James Densmore", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Data Engineering Concepts", "slug": "Data-Pipelines-Pocket-Reference"},

    # LEVEL 3: INTERNET & DIGITAL INFRASTRUCTURE (10 books)
    # LEVEL 4: Internet Architecture (5 books)
    {"title": "Tubes: A Journey to the Center of the Internet", "author": "Andrew Blum", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Internet Architecture", "slug": "Tubes-Blum"},
    {"title": "The Master Switch: The Rise and Fall of Information Empires", "author": "Tim Wu", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Internet Architecture", "slug": "The-Master-Switch"},
    {"title": "The Undersea Network", "author": "Nicole Starosielski", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Internet Architecture", "slug": "The-Undersea-Network"},
    {"title": "The Internet: A Very Short Introduction", "author": "Subrata Dasgupta", "first_published": "2014", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Internet Architecture", "slug": "The-Internet-A-Very-Short-Introduction"},
    {"title": "Code and Other Laws of Cyberspace", "author": "Lawrence Lessig", "first_published": "1999", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Internet Architecture", "slug": "Code-and-Other-Laws-of-Cyberspace"},

    # LEVEL 4: Cloud Computing Concepts (5 books)
    {"title": "Cloud Strategy: A Decision-Based Approach to Successful Cloud Migration", "author": "Gregor Hohpe", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cloud Computing Concepts", "slug": "Cloud-Strategy-Hohpe"},
    {"title": "Cloud Native Patterns: Designing change-tolerant software", "author": "Cornelia Davis", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cloud Computing Concepts", "slug": "Cloud-Native-Patterns"},
    {"title": "Kubernetes: Up and Running: Dive into the Future of Infrastructure", "author": "Brendan Burns; Joe Beda; Kelsey Hightower; Lachlan Evenson", "first_published": "2017", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cloud Computing Concepts", "slug": "Kubernetes-Up-and-Running"},
    {"title": "Serverless Architectures on AWS", "author": "Peter Sbarski; Yan Cui", "first_published": "2017", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cloud Computing Concepts", "slug": "Serverless-Architectures-on-AWS"},
    {"title": "Infrastructure as Code: Dynamic Systems for the Cloud Age", "author": "Kief Morris", "first_published": "2016", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cloud Computing Concepts", "slug": "Infrastructure-as-Code-Morris"},

    # LEVEL 3: DIGITAL SECURITY & PRIVACY (10 books)
    # LEVEL 4: Cybersecurity Concepts (5 books)
    {"title": "Countdown to Zero Day: Stuxnet and the Launch of the World's First Digital Weapon", "author": "Kim Zetter", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cybersecurity Concepts", "slug": "Countdown-to-Zero-Day"},
    {"title": "Sandworm: A New Era of Cyberwar and the Hunt for the Kremlin's Most Dangerous Hackers", "author": "Andy Greenberg", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cybersecurity Concepts", "slug": "Sandworm-Greenberg"},
    {"title": "This Is How They Tell Me the World Ends: The Cyberweapons Arms Race", "author": "Nicole Perlroth", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cybersecurity Concepts", "slug": "This-Is-How-They-Tell-Me-the-World-Ends"},
    {"title": "The Cuckoo's Egg: Tracking a Spy Through the Maze of Computer Espionage", "author": "Cliff Stoll", "first_published": "1989", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cybersecurity Concepts", "slug": "The-Cuckoos-Egg"},
    {"title": "Ghost in the Wires: My Adventures as the World's Most Wanted Hacker", "author": "Kevin Mitnick; William L. Simon", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cybersecurity Concepts", "slug": "Ghost-in-the-Wires"},

    # LEVEL 4: Digital Privacy (5 books)
    {"title": "The Age of Surveillance Capitalism: The Fight for a Human Future at the New Frontier of Power", "author": "Shoshana Zuboff", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Privacy", "slug": "The-Age-of-Surveillance-Capitalism"},
    {"title": "Data and Goliath: The Hidden Battles to Collect Your Data and Control Your World", "author": "Bruce Schneier", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Privacy", "slug": "Data-and-Goliath"},
    {"title": "A Hacker's Mind: How the Powerful Bend Society's Rules, and How to Bend Them Back", "author": "Bruce Schneier", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Privacy", "slug": "A-Hackers-Mind"},
    {"title": "Secrets and Lies: Digital Security in a Networked World", "author": "Bruce Schneier", "first_published": "2000", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Privacy", "slug": "Secrets-and-Lies-Schneier"},
    {"title": "Permanent Record", "author": "Edward Snowden", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Privacy", "slug": "Permanent-Record-Snowden"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 04. TECHNOLOGY & SOCIETY (45 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: DIGITAL TRANSFORMATION (15 books)
    # LEVEL 4: Digital Business (5 books)
    {"title": "The Second Machine Age: Work, Progress, and Prosperity in a Time of Brilliant Technologies", "author": "Erik Brynjolfsson; Andrew McAfee", "first_published": "2014", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Business", "slug": "The-Second-Machine-Age"},
    {"title": "Machine, Platform, Crowd: Harnessing Our Digital Future", "author": "Andrew McAfee; Erik Brynjolfsson", "first_published": "2017", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Business", "slug": "Machine-Platform-Crowd"},
    {"title": "Leading Digital: Turning Technology into Business Transformation", "author": "George Westerman; Didier Bonnet; Andrew McAfee", "first_published": "2014", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Business", "slug": "Leading-Digital"},
    {"title": "The Digital Transformation Playbook: Rethink Your Business for the Digital Age", "author": "David L. Rogers", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Business", "slug": "The-Digital-Transformation-Playbook"},
    {"title": "The Geek Way: The Radical Mindset that Drives Extraordinary Results", "author": "Andrew McAfee", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Digital Business", "slug": "The-Geek-Way"},

    # LEVEL 4: Platform Economies (5 books)
    {"title": "Platform Leadership: How Intel, Microsoft, and Cisco Drive Industry Innovation", "author": "Annabelle Gawer; Michael A. Cusumano", "first_published": "2002", "latest_published": "2002", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Platform Economies", "slug": "Platform-Leadership"},
    {"title": "The Sharing Economy: The End of Employment and the Rise of Crowd-Based Capitalism", "author": "Arun Sundararajan", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Platform Economies", "slug": "The-Sharing-Economy"},
    {"title": "Chokepoint Capitalism: How Big Tech and Big Content Captured Creative Labor Markets and How We'll Win Them Back", "author": "Cory Doctorow; Rebecca Giblin", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Platform Economies", "slug": "Chokepoint-Capitalism"},
    {"title": "The Internet Con: How to Seize the Means of Computation", "author": "Cory Doctorow", "first_published": "2023", "latest_published": "2023", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Platform Economies", "slug": "The-Internet-Con"},
    {"title": "Move Fast and Break Things: How Facebook, Google, and Amazon Cornered Culture and Undermined Democracy", "author": "Jonathan Taplin", "first_published": "2017", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Platform Economies", "slug": "Move-Fast-and-Break-Things"},

    # LEVEL 4: Technological Change (5 books)
    {"title": "What Technology Wants", "author": "Kevin Kelly", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technological Change", "slug": "What-Technology-Wants"},
    {"title": "The Inevitable: Understanding the 12 Technological Forces That Will Shape Our Future", "author": "Kevin Kelly", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technological Change", "slug": "The-Inevitable-Kelly"},
    {"title": "Technology and the Character of Contemporary Life: A Philosophical Inquiry", "author": "Albert Borgmann", "first_published": "1984", "latest_published": "1987", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technological Change", "slug": "Technology-and-the-Character-of-Contemporary-Life"},
    {"title": "Understanding Media: The Extensions of Man", "author": "Marshall McLuhan", "first_published": "1964", "latest_published": "1994", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technological Change", "slug": "Understanding-Media-McLuhan"},
    {"title": "Amusing Ourselves to Death: Public Discourse in the Age of Show Business", "author": "Neil Postman", "first_published": "1985", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Technological Change", "slug": "Amusing-Ourselves-to-Death"},

    # LEVEL 3: OPEN SOURCE & INTERNET CULTURE (10 books)
    # LEVEL 4: Open Source (5 books)
    {"title": "The Cathedral & the Bazaar: Musings on Linux and Open Source by an Accidental Revolutionary", "author": "Eric S. Raymond", "first_published": "1999", "latest_published": "2001", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Open Source", "slug": "The-Cathedral-and-the-Bazaar"},
    {"title": "Working in Public: The Making and Maintenance of Open Source Software", "author": "Nadia Eghbal", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Open Source", "slug": "Working-in-Public"},
    {"title": "Just for Fun: The Story of an Accidental Revolutionary", "author": "Linus Torvalds; David Diamond", "first_published": "2001", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Open Source", "slug": "Just-for-Fun"},
    {"title": "Free as in Freedom: Richard Stallman's Crusade for Free Software", "author": "Sam Williams", "first_published": "2002", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Open Source", "slug": "Free-as-in-Freedom"},
    {"title": "Producing Open Source Software: How to Run a Successful Free Software Project", "author": "Karl Fogel", "first_published": "2005", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Open Source", "slug": "Producing-Open-Source-Software"},

    # LEVEL 4: Internet Culture (5 books)
    {"title": "Because Internet: Understanding the New Rules of Language", "author": "Gretchen McCulloch", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Internet Culture", "slug": "Because-Internet"},
    {"title": "Weaving the Web: The Original Design and Ultimate Destiny of the World Wide Web", "author": "Tim Berners-Lee; Mark Fischetti", "first_published": "1999", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Internet Culture", "slug": "Weaving-the-Web"},
    {"title": "The Net Delusion: The Dark Side of Internet Freedom", "author": "Evgeny Morozov", "first_published": "2011", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Internet Culture", "slug": "The-Net-Delusion"},
    {"title": "You Are Not a Gadget: A Manifesto", "author": "Jaron Lanier", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Internet Culture", "slug": "You-Are-Not-a-Gadget"},
    {"title": "Who Owns the Future?", "author": "Jaron Lanier", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Internet Culture", "slug": "Who-Owns-the-Future"},

    # LEVEL 3: FUTURE OF SOFTWARE (20 books)
    # LEVEL 4: Future of Programming (5 books)
    {"title": "The Nature of Software Development: Keep It Simple, Make It Valuable, Build It Piece by Piece", "author": "Ron Jeffries", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Future of Programming", "slug": "The-Nature-of-Software-Development"},
    {"title": "Coders at Work: Reflections on the Craft of Programming", "author": "Peter Seibel", "first_published": "2009", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Future of Programming", "slug": "Coders-at-Work"},
    {"title": "Masterminds of Programming: Conversations with the Creators of Major Programming Languages", "author": "Federico Biancuzzi; Shane Warden", "first_published": "2009", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Future of Programming", "slug": "Masterminds-of-Programming"},
    {"title": "Seven Languages in Seven Weeks: A Pragmatic Guide to Learning Programming Languages", "author": "Bruce A. Tate", "first_published": "2010", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Future of Programming", "slug": "Seven-Languages-in-Seven-Weeks"},
    {"title": "Seven More Languages in Seven Weeks: Languages That Are Shaping the Future", "author": "Bruce A. Tate; Ian Dees; Frederic Daoud; Jack Moffitt", "first_published": "2014", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Future of Programming", "slug": "Seven-More-Languages-in-Seven-Weeks"},

    # LEVEL 4: Developer Productivity (5 books)
    {"title": "Peopleware: Productive Projects and Teams", "author": "Tom DeMarco; Timothy Lister", "first_published": "1987", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Developer Productivity", "slug": "Peopleware"},
    {"title": "Rethinking Productivity in Software Engineering", "author": "Caitlin Sadowski; Thomas Zimmermann", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Developer Productivity", "slug": "Rethinking-Productivity-in-Software-Engineering"},
    {"title": "The Effective Engineer: How to Leverage Your Efforts In Software Engineering to Make a Disproportionate and Meaningful Impact", "author": "Edmond Lau", "first_published": "2015", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Developer Productivity", "slug": "The-Effective-Engineer"},
    {"title": "Apprenticeship Patterns: Guidance for the Aspiring Software Craftsman", "author": "Adewale Oshineye; Dave Hoover", "first_published": "2009", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Developer Productivity", "slug": "Apprenticeship-Patterns"},
    {"title": "The Passionate Programmer: Creating a Remarkable Career in Software Development", "author": "Chad Fowler", "first_published": "2009", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Developer Productivity", "slug": "The-Passionate-Programmer"},

    # LEVEL 4: Software Industry (5 books)
    {"title": "Coders: The Making of a New Tribe and the Remaking of the World", "author": "Clive Thompson", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Software Industry", "slug": "Coders-Thompson"},
    {"title": "Dreaming in Code: Two Dozen Programmers, Four Years, 4,732 Bugs, and One Quest for Transcendent Software", "author": "Scott Rosenberg", "first_published": "2007", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Software Industry", "slug": "Dreaming-in-Code"},
    {"title": "Showstopper!: The Breakneck Race to Create Windows NT and the Next Generation at Microsoft", "author": "G. Pascal Zachary", "first_published": "1994", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Software Industry", "slug": "Showstopper"},
    {"title": "Hard Drive: Bill Gates and the Making of the Microsoft Empire", "author": "James Wallace; Jim Erickson", "first_published": "1992", "latest_published": "1993", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Software Industry", "slug": "Hard-Drive-Gates"},
    {"title": "Empire of the Air: The Men Who Made Radio", "author": "Tom Lewis", "first_published": "1991", "latest_published": "1993", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Software Industry", "slug": "Empire-of-the-Air"},

    # LEVEL 4: Automation (5 books)
    {"title": "Automate the Boring Stuff with Python: Practical Programming for Total Beginners", "author": "Al Sweigart", "first_published": "2015", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation", "slug": "Automate-the-Boring-Stuff-with-Python"},
    {"title": "The Pragmatic Starter Kit: Pragmatic Unit Testing", "author": "Andy Hunt; Dave Thomas", "first_published": "2003", "latest_published": "2006", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation", "slug": "Pragmatic-Unit-Testing"},
    {"title": "Continuous Integration: Improving Software Quality and Reducing Risk", "author": "Paul M. Duvall; Steve Matyas; Andrew Glover", "first_published": "2007", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation", "slug": "Continuous-Integration-Duvall"},
    {"title": "Modern Infrastructure as Code", "author": "Sam Guckenheimer", "first_published": "2019", "latest_published": "2019", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation", "slug": "Modern-Infrastructure-as-Code"},
    {"title": "Software Engineering: A Practitioner's Approach", "author": "Roger S. Pressman; Bruce R. Maxim", "first_published": "1982", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Automation", "slug": "Software-Engineering-Pressman"},
]
