from __future__ import annotations

# Domain 10: History, Civilization & Geopolitics (220 books: #1461–#1680)
BOOKS_10 = [
    # -------------------------------------------------------------------------
    # LEVEL 2: 01. WORLD HISTORY (60 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: ANCIENT CIVILIZATIONS (15 books)
    # LEVEL 4: Origins of Civilization (5 books)
    {"title": "Sapiens: A Brief History of Humankind", "author": "Yuval Noah Harari", "first_published": "2011", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origins of Civilization", "slug": "Sapiens-Harari"},
    {"title": "Guns, Germs, and Steel: The Fates of Human Societies", "author": "Jared Diamond", "first_published": "1997", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origins of Civilization", "slug": "Guns-Germs-and-Steel"},
    {"title": "The Dawn of Everything: A New History of Humanity", "author": "David Graeber; David Wengrow", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origins of Civilization", "slug": "The-Dawn-of-Everything"},
    {"title": "Against the Grain: A Deep History of the Earliest States", "author": "James C. Scott", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origins of Civilization", "slug": "Against-the-Grain-Scott"},
    {"title": "1177 B.C.: The Year Civilization Collapsed", "author": "Eric H. Cline", "first_published": "2014", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origins of Civilization", "slug": "1177-BC-Cline"},

    # LEVEL 4: Ancient Mediterranean (5 books)
    {"title": "The Histories", "author": "Herodotus", "first_published": "-440", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient Mediterranean", "slug": "The-Histories-Herodotus"},
    {"title": "History of the Peloponnesian War", "author": "Thucydides", "first_published": "-400", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient Mediterranean", "slug": "History-of-the-Peloponnesian-War"},
    {"title": "SPQR: A History of Ancient Rome", "author": "Mary Beard", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient Mediterranean", "slug": "SPQR-Mary-Beard"},
    {"title": "The History of the Decline and Fall of the Roman Empire", "author": "Edward Gibbon", "first_published": "1776", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient Mediterranean", "slug": "The-Decline-and-Fall-of-the-Roman-Empire"},
    {"title": "Rubicon: The Last Years of the Roman Republic", "author": "Tom Holland", "first_published": "2003", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient Mediterranean", "slug": "Rubicon-Tom-Holland"},

    # LEVEL 4: Ancient Asian Civilizations (5 books)
    {"title": "Records of the Grand Historian", "author": "Sima Qian (Burton Watson Trans.)", "first_published": "-94", "latest_published": "1993", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient Asian Civilizations", "slug": "Records-of-the-Grand-Historian"},
    {"title": "The Early Chinese Empires: Qin and Han", "author": "Mark Edward Lewis", "first_published": "2007", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient Asian Civilizations", "slug": "The-Early-Chinese-Empires"},
    {"title": "India: A History", "author": "John Keay", "first_published": "2000", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient Asian Civilizations", "slug": "India-A-History-Keay"},
    {"title": "China: A History", "author": "John Keay", "first_published": "2008", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient Asian Civilizations", "slug": "China-A-History-Keay"},
    {"title": "The Wonder That Was India", "author": "A.L. Basham", "first_published": "1954", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ancient Asian Civilizations", "slug": "The-Wonder-That-Was-India"},

    # LEVEL 3: MEDIEVAL & EARLY MODERN (15 books)
    # LEVEL 4: Medieval World (5 books)
    {"title": "Powers and Thrones: A New History of the Middle Ages", "author": "Dan Jones", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Medieval World", "slug": "Powers-and-Thrones-Dan-Jones"},
    {"title": "The Plantagenets: The Warrior Kings and Queens Who Made England", "author": "Dan Jones", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Medieval World", "slug": "The-Plantagenets-Dan-Jones"},
    {"title": "The Templars: The Rise and Spectacular Fall of God's Holy Warriors", "author": "Dan Jones", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Medieval World", "slug": "The-Templars-Dan-Jones"},
    {"title": "The Crusades: The Authoritative History of the War for the Holy Land", "author": "Thomas Asbridge", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Medieval World", "slug": "The-Crusades-Asbridge"},
    {"title": "Genghis Khan and the Making of the Modern World", "author": "Jack Weatherford", "first_published": "2004", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Medieval World", "slug": "Genghis-Khan-and-the-Making-of-the-Modern-World"},

    # LEVEL 4: Age of Discovery (5 books)
    {"title": "1491: New Revelations of the Americas Before Columbus", "author": "Charles C. Mann", "first_published": "2005", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Age of Discovery", "slug": "1491-Charles-Mann"},
    {"title": "1493: Uncovering the New World Columbus Created", "author": "Charles C. Mann", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Age of Discovery", "slug": "1493-Charles-Mann"},
    {"title": "Conquerors: How Portugal Forged the First Global Empire", "author": "Roger Crowley", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Age of Discovery", "slug": "Conquerors-Roger-Crowley"},
    {"title": "City of Fortune: How Venice Ruled the Seas", "author": "Roger Crowley", "first_published": "2011", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Age of Discovery", "slug": "City-of-Fortune-Crowley"},
    {"title": "Empires of the Sea: The Siege of Malta, the Battle of Lepanto, and the Contest for the Center of the World", "author": "Roger Crowley", "first_published": "2008", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Age of Discovery", "slug": "Empires-of-the-Sea-Crowley"},

    # LEVEL 4: Enlightenment & Revolution (5 books)
    {"title": "The French Revolution: From Enlightenment to Tyranny", "author": "Ian Davidson", "first_published": "2016", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Enlightenment & Revolution", "slug": "The-French-Revolution-Davidson"},
    {"title": "Citizens: A Chronicle of the French Revolution", "author": "Simon Schama", "first_published": "1989", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Enlightenment & Revolution", "slug": "Citizens-Simon-Schama"},
    {"title": "The Age of Revolution: 1789-1848", "author": "Eric Hobsbawm", "first_published": "1962", "latest_published": "1996", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Enlightenment & Revolution", "slug": "The-Age-of-Revolution-Hobsbawm"},
    {"title": "The Age of Capital: 1848-1875", "author": "Eric Hobsbawm", "first_published": "1975", "latest_published": "1996", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Enlightenment & Revolution", "slug": "The-Age-of-Capital-Hobsbawm"},
    {"title": "The Age of Empire: 1875-1914", "author": "Eric Hobsbawm", "first_published": "1987", "latest_published": "1989", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Enlightenment & Revolution", "slug": "The-Age-of-Empire-Hobsbawm"},

    # LEVEL 3: MODERN HISTORY (15 books)
    # LEVEL 4: Industrial Revolution (5 books)
    {"title": "The British Industrial Revolution in Global Perspective", "author": "Robert C. Allen", "first_published": "2009", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industrial Revolution", "slug": "The-British-Industrial-Revolution-Allen"},
    {"title": "The Lever of Riches: Technological Creativity and Economic Progress", "author": "Joel Mokyr", "first_published": "1990", "latest_published": "1992", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industrial Revolution", "slug": "The-Lever-of-Riches"},
    {"title": "The Gifts of Athena: Historical Origins of the Knowledge Economy", "author": "Joel Mokyr", "first_published": "2002", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industrial Revolution", "slug": "The-Gifts-of-Athena"},
    {"title": "A Culture of Growth: The Origins of the Modern Economy", "author": "Joel Mokyr", "first_published": "2016", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industrial Revolution", "slug": "A-Culture-of-Growth"},
    {"title": "Empire of Cotton: A Global History", "author": "Sven Beckert", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Industrial Revolution", "slug": "Empire-of-Cotton"},

    # LEVEL 4: 20th Century (5 books)
    {"title": "The Age of Extremes: A History of the World, 1914-1991", "author": "Eric Hobsbawm", "first_published": "1994", "latest_published": "1996", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "20th Century", "slug": "The-Age-of-Extremes-Hobsbawm"},
    {"title": "The Sleepwalkers: How Europe Went to War in 1914", "author": "Christopher Clark", "first_published": "2012", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "20th Century", "slug": "The-Sleepwalkers-Clark"},
    {"title": "The Guns of August", "author": "Barbara W. Tuchman", "first_published": "1962", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "20th Century", "slug": "The-Guns-of-August"},
    {"title": "The Second World War", "author": "Antony Beevor", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "20th Century", "slug": "The-Second-World-War-Beevor"},
    {"title": "Postwar: A History of Europe Since 1945", "author": "Tony Judt", "first_published": "2005", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "20th Century", "slug": "Postwar-Tony-Judt"},

    # LEVEL 4: Cold War (5 books)
    {"title": "The Cold War: A New History", "author": "John Lewis Gaddis", "first_published": "2005", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cold War", "slug": "The-Cold-War-Gaddis"},
    {"title": "The Cold War: A World History", "author": "Odd Arne Westad", "first_published": "2017", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cold War", "slug": "The-Cold-War-Westad"},
    {"title": "The Global Cold War: Third World Interventions and the Making of Our Times", "author": "Odd Arne Westad", "first_published": "2005", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cold War", "slug": "The-Global-Cold-War-Westad"},
    {"title": "Strategies of Containment: A Critical Appraisal of American National Security Policy During the Cold War", "author": "John Lewis Gaddis", "first_published": "1982", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cold War", "slug": "Strategies-of-Containment"},
    {"title": "Armageddon and Paranoia: The Cold War Nuclear Confrontation", "author": "Rodric Braithwaite", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cold War", "slug": "Armageddon-and-Paranoia"},

    # LEVEL 3: GLOBAL HISTORY (15 books)
    # LEVEL 4: Big History (5 books)
    {"title": "Maps of Time: An Introduction to Big History", "author": "David Christian", "first_published": "2004", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Big History", "slug": "Maps-of-Time-Christian"},
    {"title": "Origin Story: A Big History of Everything", "author": "David Christian", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Big History", "slug": "Origin-Story-Christian"},
    {"title": "A Short History of Nearly Everything", "author": "Bill Bryson", "first_published": "2003", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Big History", "slug": "A-Short-History-of-Nearly-Everything"},
    {"title": "The Human Web: A Bird's-Eye View of World History", "author": "J.R. McNeill; William H. McNeill", "first_published": "2003", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Big History", "slug": "The-Human-Web"},
    {"title": "A History of the World in 100 Objects", "author": "Neil MacGregor", "first_published": "2010", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Big History", "slug": "A-History-of-the-World-in-100-Objects"},

    # LEVEL 4: Transnational History (5 books)
    {"title": "The Anarchy: The Relentless Rise of the East India Company", "author": "William Dalrymple", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Transnational History", "slug": "The-Anarchy-Dalrymple"},
    {"title": "The Golden Road: How Ancient India Transformed the World", "author": "William Dalrymple", "first_published": "2024", "latest_published": "2024", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Transnational History", "slug": "The-Golden-Road-Dalrymple"},
    {"title": "Return of a King: The Battle for Afghanistan, 1839-42", "author": "William Dalrymple", "first_published": "2012", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Transnational History", "slug": "Return-of-a-King-Dalrymple"},
    {"title": "White Mughals: Love and Betrayal in Eighteenth-Century India", "author": "William Dalrymple", "first_published": "2002", "latest_published": "2004", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Transnational History", "slug": "White-Mughals-Dalrymple"},
    {"title": "The Last Mughal: The Fall of a Dynasty, Delhi, 1857", "author": "William Dalrymple", "first_published": "2006", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Transnational History", "slug": "The-Last-Mughal-Dalrymple"},

    # LEVEL 4: Environmental History (5 books)
    {"title": "Something New Under the Sun: An Environmental History of the Twentieth-Century World", "author": "J.R. McNeill", "first_published": "2000", "latest_published": "2001", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environmental History", "slug": "Something-New-Under-the-Sun"},
    {"title": "The Great Acceleration: An Environmental History of the Anthropocene since 1945", "author": "J.R. McNeill; Peter Engelke", "first_published": "2014", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environmental History", "slug": "The-Great-Acceleration"},
    {"title": "The Earth Transformed: An Untold History", "author": "Peter Frankopan", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environmental History", "slug": "The-Earth-Transformed-Frankopan"},
    {"title": "Plagues and Peoples", "author": "William H. McNeill", "first_published": "1976", "latest_published": "1998", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environmental History", "slug": "Plagues-and-Peoples"},
    {"title": "The Columbian Exchange: Biological and Cultural Consequences of 1492", "author": "Alfred W. Crosby", "first_published": "1972", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environmental History", "slug": "The-Columbian-Exchange-Crosby"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 02. CIVILIZATION & CULTURE (50 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: RISE & FALL (15 books)
    # LEVEL 4: Collapse & Renewal (5 books)
    {"title": "Collapse: How Societies Choose to Fail or Succeed", "author": "Jared Diamond", "first_published": "2005", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Collapse & Renewal", "slug": "Collapse-Jared-Diamond"},
    {"title": "Upheaval: Turning Points for Nations in Crisis", "author": "Jared Diamond", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Collapse & Renewal", "slug": "Upheaval-Jared-Diamond"},
    {"title": "The Collapse of Complex Societies", "author": "Joseph A. Tainter", "first_published": "1988", "latest_published": "1988", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Collapse & Renewal", "slug": "The-Collapse-of-Complex-Societies"},
    {"title": "War and Peace and War: The Rise and Fall of Empires", "author": "Peter Turchin", "first_published": "2006", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Collapse & Renewal", "slug": "War-and-Peace-and-War-Turchin"},
    {"title": "End Times: Elites, Counter-Elites, and the Path of Political Disintegration", "author": "Peter Turchin", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Collapse & Renewal", "slug": "End-Times-Turchin"},

    # LEVEL 4: Imperial Systems (5 books)
    {"title": "The Rise and Fall of the Great Powers: Economic Change and Military Conflict from 1500 to 2000", "author": "Paul Kennedy", "first_published": "1987", "latest_published": "1989", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Imperial Systems", "slug": "The-Rise-and-Fall-of-the-Great-Powers"},
    {"title": "Empires in World History: Power and the Politics of Difference", "author": "Jane Burbank; Frederick Cooper", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Imperial Systems", "slug": "Empires-in-World-History"},
    {"title": "Empire: How Britain Made the Modern World", "author": "Niall Ferguson", "first_published": "2002", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Imperial Systems", "slug": "Empire-Ferguson"},
    {"title": "Colossus: The Rise and Fall of the American Empire", "author": "Niall Ferguson", "first_published": "2004", "latest_published": "2005", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Imperial Systems", "slug": "Colossus-Ferguson"},
    {"title": "Civilization: The West and the Rest", "author": "Niall Ferguson", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Imperial Systems", "slug": "Civilization-Ferguson"},

    # LEVEL 4: Civilizational Dynamics (5 books)
    {"title": "The Clash of Civilizations and the Remaking of World Order", "author": "Samuel P. Huntington", "first_published": "1996", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civilizational Dynamics", "slug": "The-Clash-of-Civilizations"},
    {"title": "Why the West Rules—For Now: The Patterns of History, and What They Reveal About the Future", "author": "Ian Morris", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civilizational Dynamics", "slug": "Why-the-West-Rules-For-Now"},
    {"title": "Foragers, Farmers, and Fossil Fuels: How Human Values Evolve", "author": "Ian Morris", "first_published": "2015", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civilizational Dynamics", "slug": "Foragers-Farmers-and-Fossil-Fuels"},
    {"title": "Geography Is Destiny: Britain and the World, a 10,000-Year History", "author": "Ian Morris", "first_published": "2022", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civilizational Dynamics", "slug": "Geography-Is-Destiny-Morris"},
    {"title": "A Study of History", "author": "Arnold J. Toynbee", "first_published": "1934", "latest_published": "1987", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Civilizational Dynamics", "slug": "A-Study-of-History-Toynbee"},

    # LEVEL 3: IDEAS & SCIENCE (15 books)
    # LEVEL 4: History of Science (5 books)
    {"title": "The Structure of Scientific Revolutions", "author": "Thomas S. Kuhn", "first_published": "1962", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Science", "slug": "The-Structure-of-Scientific-Revolutions"},
    {"title": "The Invention of Science: A New History of the Scientific Revolution", "author": "David Wootton", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Science", "slug": "The-Invention-of-Science-Wootton"},
    {"title": "To Explain the World: The Discovery of Modern Science", "author": "Steven Weinberg", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Science", "slug": "To-Explain-the-World-Weinberg"},
    {"title": "The Scientific Revolution: A Very Short Introduction", "author": "Lawrence M. Principe", "first_published": "2011", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Science", "slug": "The-Scientific-Revolution-Principe"},
    {"title": "Leviathan and the Air-Pump: Hobbes, Boyle, and the Experimental Life", "author": "Steven Shapin; Simon Schaffer", "first_published": "1985", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Science", "slug": "Leviathan-and-the-Air-Pump"},

    # LEVEL 4: History of Ideas (5 books)
    {"title": "The Swerve: How the World Became Modern", "author": "Stephen Greenblatt", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Ideas", "slug": "The-Swerve-Greenblatt"},
    {"title": "The Cave and the Light: Plato Versus Aristotle, and the Struggle for the Soul of Western Civilization", "author": "Arthur Herman", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Ideas", "slug": "The-Cave-and-the-Light"},
    {"title": "How the Scots Invented the Modern World", "author": "Arthur Herman", "first_published": "2001", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Ideas", "slug": "How-the-Scots-Invented-the-Modern-World"},
    {"title": "The Closing of the Western Mind: The Rise of Faith and the Fall of Reason", "author": "Charles Freeman", "first_published": "2002", "latest_published": "2005", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Ideas", "slug": "The-Closing-of-the-Western-Mind"},
    {"title": "The Awakening: A History of the Western Mind, AD 500-1700", "author": "Charles Freeman", "first_published": "2020", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Ideas", "slug": "The-Awakening-Freeman"},

    # LEVEL 4: Cultural Evolution (5 books)
    {"title": "The WEIRDest People in the World: How the West Became Psychologically Peculiar and Particularly Prosperous", "author": "Joseph Henrich", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cultural Evolution", "slug": "The-WEIRDest-People-in-the-World"},
    {"title": "The Secret of Our Success: How Culture Is Driving Human Evolution, Domesticating Our Species, and Making Us Smarter", "author": "Joseph Henrich", "first_published": "2015", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cultural Evolution", "slug": "The-Secret-of-Our-Success"},
    {"title": "Ultrasocial: The Evolution of Human Nature and the Rise of Civilizations", "author": "John M. Gowdy", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cultural Evolution", "slug": "Ultrasocial-Gowdy"},
    {"title": "Darwin's Unfinished Symphony: How Culture Made the Human Mind", "author": "Kevin N. Laland", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cultural Evolution", "slug": "Darwins-Unfinished-Symphony"},
    {"title": "Not by Genes Alone: How Culture Transformed Human Evolution", "author": "Peter J. Richerson; Robert Boyd", "first_published": "2005", "latest_published": "2006", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cultural Evolution", "slug": "Not-by-Genes-Alone"},

    # LEVEL 3: GLOBAL CONNECTIONS (20 books)
    # LEVEL 4: Silk Roads (5 books)
    {"title": "The Silk Roads: A New History of the World", "author": "Peter Frankopan", "first_published": "2015", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Silk Roads", "slug": "The-Silk-Roads-Frankopan"},
    {"title": "The New Silk Roads: The Present and Future of the World", "author": "Peter Frankopan", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Silk Roads", "slug": "The-New-Silk-Roads-Frankopan"},
    {"title": "Empires of the Silk Road: A History of Central Eurasia from the Bronze Age to the Present", "author": "Christopher I. Beckwith", "first_published": "2009", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Silk Roads", "slug": "Empires-of-the-Silk-Road"},
    {"title": "The Silk Road: A Very Short Introduction", "author": "James A. Millward", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Silk Roads", "slug": "The-Silk-Road-Millward"},
    {"title": "Shadow of the Silk Road", "author": "Colin Thubron", "first_published": "2006", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Silk Roads", "slug": "Shadow-of-the-Silk-Road"},

    # LEVEL 4: Maritime History (5 books)
    {"title": "The Boundless Sea: A Human History of the Oceans", "author": "David Abulafia", "first_published": "2019", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Maritime History", "slug": "The-Boundless-Sea-Abulafia"},
    {"title": "The Great Sea: A Human History of the Mediterranean", "author": "David Abulafia", "first_published": "2011", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Maritime History", "slug": "The-Great-Sea-Abulafia"},
    {"title": "The Mediterranean in the Ancient World", "author": "Fernand Braudel", "first_published": "1998", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Maritime History", "slug": "The-Mediterranean-in-the-Ancient-World-Braudel"},
    {"title": "The Sea and Civilization: A Maritime History of the World", "author": "Lincoln Paine", "first_published": "2013", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Maritime History", "slug": "The-Sea-and-Civilization-Paine"},
    {"title": "To Rule the Waves: How the British Navy Shaped the Modern World", "author": "Arthur Herman", "first_published": "2004", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Maritime History", "slug": "To-Rule-the-Waves-Herman"},

    # LEVEL 4: Migration History (5 books)
    {"title": "The Warmth of Other Suns: The Epic Story of America's Great Migration", "author": "Isabel Wilkerson", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Migration History", "slug": "The-Warmth-of-Other-Suns"},
    {"title": "Caste: The Origins of Our Discontents", "author": "Isabel Wilkerson", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Migration History", "slug": "Caste-Wilkerson"},
    {"title": "The Next Great Migration: The Beauty and Terror of Life on the Move", "author": "Sonia Shah", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Migration History", "slug": "The-Next-Great-Migration"},
    {"title": "Move: How Mass Migration Will Reshape the World -- and What It Means for You", "author": "Parag Khanna", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Migration History", "slug": "Move-Parag-Khanna"},
    {"title": "Nomad Century: How Climate Migration Will Reshape Our World", "author": "Gaia Vince", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Migration History", "slug": "Nomad-Century-Vince"},

    # LEVEL 4: Global Exchange (5 books)
    {"title": "A History of the World in 6 Glasses", "author": "Tom Standage", "first_published": "2005", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Exchange", "slug": "A-History-of-the-World-in-6-Glasses"},
    {"title": "An Edible History of Humanity", "author": "Tom Standage", "first_published": "2009", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Exchange", "slug": "An-Edible-History-of-Humanity"},
    {"title": "Writing on the Wall: Social Media - The First 2,000 Years", "author": "Tom Standage", "first_published": "2013", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Exchange", "slug": "Writing-on-the-Wall-Standage"},
    {"title": "The Victorian Internet: The Remarkable Story of the Telegraph and the Nineteenth Century's On-line Pioneers", "author": "Tom Standage", "first_published": "1998", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Exchange", "slug": "The-Victorian-Internet"},
    {"title": "Salt: A World History", "author": "Mark Kurlansky", "first_published": "2002", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Exchange", "slug": "Salt-Kurlansky"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 03. GEOPOLITICS & STRATEGY (60 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: GRAND STRATEGY (20 books)
    # LEVEL 4: Classical Strategy (5 books)
    {"title": "The Art of War", "author": "Sun Tzu", "first_published": "-500", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Classical Strategy", "slug": "The-Art-of-War-Sun-Tzu"},
    {"title": "On War", "author": "Carl von Clausewitz", "first_published": "1832", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Classical Strategy", "slug": "On-War-Clausewitz"},
    {"title": "Strategy", "author": "B.H. Liddell Hart", "first_published": "1954", "latest_published": "1991", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Classical Strategy", "slug": "Strategy-Liddell-Hart"},
    {"title": "The Book of Five Rings", "author": "Miyamoto Musashi", "first_published": "1645", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Classical Strategy", "slug": "The-Book-of-Five-Rings"},
    {"title": "The Arthashastra", "author": "Kautilya (L.N. Rangarajan Trans.)", "first_published": "-300", "latest_published": "1992", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Classical Strategy", "slug": "The-Arthashastra-Kautilya"},

    # LEVEL 4: Modern Strategy (5 books)
    {"title": "On Grand Strategy", "author": "John Lewis Gaddis", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Strategy", "slug": "On-Grand-Strategy-Gaddis"},
    {"title": "Makers of Modern Strategy from Machiavelli to the Nuclear Age", "author": "Peter Paret; Gordon A. Craig; Felix Gilbert", "first_published": "1986", "latest_published": "1986", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Strategy", "slug": "Makers-of-Modern-Strategy"},
    {"title": "Grand Strategies: Literature, Statecraft, and World Order", "author": "Charles Hill", "first_published": "2010", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Strategy", "slug": "Grand-Strategies-Charles-Hill"},
    {"title": "The Strategy of Conflict", "author": "Thomas C. Schelling", "first_published": "1960", "latest_published": "1980", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Strategy", "slug": "The-Strategy-of-Conflict"},
    {"title": "Arms and Influence", "author": "Thomas C. Schelling", "first_published": "1966", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Strategy", "slug": "Arms-and-Influence"},

    # LEVEL 4: Strategic Rivalry (5 books)
    {"title": "Destined for War: Can America and China Escape Thucydides's Trap?", "author": "Graham Allison", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Rivalry", "slug": "Destined-for-War-Graham-Allison"},
    {"title": "Essence of Decision: Explaining the Cuban Missile Crisis", "author": "Graham Allison; Philip Zelikow", "first_published": "1971", "latest_published": "1999", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Rivalry", "slug": "Essence-of-Decision"},
    {"title": "The Tragedy of Great Power Politics", "author": "John J. Mearsheimer", "first_published": "2001", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Rivalry", "slug": "The-Tragedy-of-Great-Power-Politics"},
    {"title": "The Great Delusion: Liberal Dreams and International Realities", "author": "John J. Mearsheimer", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Rivalry", "slug": "The-Great-Delusion-Mearsheimer"},
    {"title": "The Long Game: China's Grand Strategy to Displace American Order", "author": "Rush Doshi", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strategic Rivalry", "slug": "The-Long-Game-Doshi"},

    # LEVEL 4: Balance of Power (5 books)
    {"title": "Diplomacy", "author": "Henry Kissinger", "first_published": "1994", "latest_published": "1995", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Balance of Power", "slug": "Diplomacy-Kissinger"},
    {"title": "World Order", "author": "Henry Kissinger", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Balance of Power", "slug": "World-Order-Kissinger"},
    {"title": "A World Restored: Metternich, Castlereagh and the Problems of Peace, 1812-22", "author": "Henry Kissinger", "first_published": "1957", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Balance of Power", "slug": "A-World-Restored-Kissinger"},
    {"title": "The Grand Chessboard: American Primacy and Its Geostrategic Imperatives", "author": "Zbigniew Brzezinski", "first_published": "1997", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Balance of Power", "slug": "The-Grand-Chessboard"},
    {"title": "Strategic Vision: America and the Crisis of Global Power", "author": "Zbigniew Brzezinski", "first_published": "2012", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Balance of Power", "slug": "Strategic-Vision-Brzezinski"},

    # LEVEL 3: GEOPOLITICS (20 books)
    # LEVEL 4: Geographic Strategy (5 books)
    {"title": "Prisoners of Geography: Ten Maps That Explain Everything About the World", "author": "Tim Marshall", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Geographic Strategy", "slug": "Prisoners-of-Geography"},
    {"title": "The Power of Geography: Ten Maps That Reveal the Future of Our World", "author": "Tim Marshall", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Geographic Strategy", "slug": "The-Power-of-Geography"},
    {"title": "The Revenge of Geography: What the Map Tells Us About Coming Conflicts and the Battle Against Fate", "author": "Robert D. Kaplan", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Geographic Strategy", "slug": "The-Revenge-of-Geography"},
    {"title": "The Loom of Time: Between Empire and Anarchy, from the Mediterranean to China", "author": "Robert D. Kaplan", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Geographic Strategy", "slug": "The-Loom-of-Time-Kaplan"},
    {"title": "Monsoon: The Indian Ocean and the Future of American Power", "author": "Robert D. Kaplan", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Geographic Strategy", "slug": "Monsoon-Kaplan"},

    # LEVEL 4: Regional Dynamics (5 books)
    {"title": "Asia's Cauldron: The South China Sea and the End of a Stable Pacific", "author": "Robert D. Kaplan", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Regional Dynamics", "slug": "Asias-Cauldron-Kaplan"},
    {"title": "The Future Is Asian: Commerce, Conflict, and Culture in the 21st Century", "author": "Parag Khanna", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Regional Dynamics", "slug": "The-Future-Is-Asian"},
    {"title": "Connectography: Mapping the Future of Global Civilization", "author": "Parag Khanna", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Regional Dynamics", "slug": "Connectography"},
    {"title": "The Second World: Empires and Influence in the New Global Order", "author": "Parag Khanna", "first_published": "2008", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Regional Dynamics", "slug": "The-Second-World-Khanna"},
    {"title": "The European Union: A Very Short Introduction", "author": "John Pinder; Simon Usherwood", "first_published": "2001", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Regional Dynamics", "slug": "The-European-Union-Pinder"},

    # LEVEL 4: Sea & Land Power (5 books)
    {"title": "The Influence of Sea Power Upon History, 1660-1783", "author": "Alfred Thayer Mahan", "first_published": "1890", "latest_published": "1987", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Sea & Land Power", "slug": "The-Influence-of-Sea-Power-Upon-History"},
    {"title": "The Geographical Pivot of History", "author": "Halford J. Mackinder", "first_published": "1904", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Sea & Land Power", "slug": "The-Geographical-Pivot-of-History"},
    {"title": "Democratic Ideals and Reality: A Study in the Politics of Reconstruction", "author": "Halford J. Mackinder", "first_published": "1919", "latest_published": "1996", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Sea & Land Power", "slug": "Democratic-Ideals-and-Reality"},
    {"title": "The Geography of the Peace", "author": "Nicholas J. Spykman", "first_published": "1944", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Sea & Land Power", "slug": "The-Geography-of-the-Peace"},
    {"title": "America's Strategy in World Politics: The United States and the Balance of Power", "author": "Nicholas J. Spykman", "first_published": "1942", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Sea & Land Power", "slug": "Americas-Strategy-in-World-Politics"},

    # LEVEL 4: Global Order (5 books)
    {"title": "The Jungle Grows Back: America and Our Imperiled World", "author": "Robert Kagan", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Order", "slug": "The-Jungle-Grows-Back"},
    {"title": "The World America Made", "author": "Robert Kagan", "first_published": "2012", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Order", "slug": "The-World-America-Made"},
    {"title": "The Ghost at the Feast: America and the Collapse of World Order, 1900-1941", "author": "Robert Kagan", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Order", "slug": "The-Ghost-at-the-Feast"},
    {"title": "A Foreign Policy for the Left", "author": "Michael Walzer", "first_published": "2018", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Order", "slug": "A-Foreign-Policy-for-the-Left"},
    {"title": "The End of the Myth: From the Frontier to the Border Wall in the Mind of America", "author": "Greg Grandin", "first_published": "2019", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Global Order", "slug": "The-End-of-the-Myth"},

    # LEVEL 3: WAR & CONFLICT (20 books)
    # LEVEL 4: History of Warfare (5 books)
    {"title": "A History of Warfare", "author": "John Keegan", "first_published": "1993", "latest_published": "1994", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Warfare", "slug": "A-History-of-Warfare-Keegan"},
    {"title": "The Face of Battle: A Study of Agincourt, Waterloo, and the Somme", "author": "John Keegan", "first_published": "1976", "latest_published": "1983", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Warfare", "slug": "The-Face-of-Battle"},
    {"title": "The Mask of Command", "author": "John Keegan", "first_published": "1987", "latest_published": "1988", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Warfare", "slug": "The-Mask-of-Command"},
    {"title": "War in European History", "author": "Michael Howard", "first_published": "1976", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Warfare", "slug": "War-in-European-History"},
    {"title": "The Pursuit of Power: Technology, Armed Force, and Society since A.D. 1000", "author": "William H. McNeill", "first_published": "1982", "latest_published": "1984", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Warfare", "slug": "The-Pursuit-of-Power-McNeill"},

    # LEVEL 4: Modern Conflict (5 books)
    {"title": "LikeWar: The Weaponization of Social Media", "author": "P.W. Singer; Emerson T. Brooking", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Conflict", "slug": "LikeWar-Singer"},
    {"title": "Wired for War: The Robotics Revolution and Conflict in the 21st Century", "author": "P.W. Singer", "first_published": "2009", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Conflict", "slug": "Wired-for-War"},
    {"title": "The Utility of Force: The Art of War in the Modern World", "author": "Rupert Smith", "first_published": "2005", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Conflict", "slug": "The-Utility-of-Force"},
    {"title": "The New Rules of War: How America Can Win--Against Russia, China, and Other Threats", "author": "Sean McFate", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Conflict", "slug": "The-New-Rules-of-War"},
    {"title": "The Accidental Guerrilla: Fighting Small Wars in the Midst of a Big One", "author": "David Kilcullen", "first_published": "2009", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Modern Conflict", "slug": "The-Accidental-Guerrilla"},

    # LEVEL 4: Intelligence & Espionage (5 books)
    {"title": "Legacy of Ashes: The History of the CIA", "author": "Tim Weiner", "first_published": "2007", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligence & Espionage", "slug": "Legacy-of-Ashes"},
    {"title": "Enemies: A History of the FBI", "author": "Tim Weiner", "first_published": "2012", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligence & Espionage", "slug": "Enemies-Weiner"},
    {"title": "The Spy and the Traitor: The Greatest Espionage Story of the Cold War", "author": "Ben Macintyre", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligence & Espionage", "slug": "The-Spy-and-the-Traitor"},
    {"title": "Agent Zigzag: A True Story of Nazi Espionage, Love, and Betrayal", "author": "Ben Macintyre", "first_published": "2007", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligence & Espionage", "slug": "Agent-Zigzag"},
    {"title": "Operation Mincemeat: How a Dead Man and a Bizarre Plan Fooled the Nazis and Assured an Allied Victory", "author": "Ben Macintyre", "first_published": "2010", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intelligence & Espionage", "slug": "Operation-Mincemeat"},

    # LEVEL 4: Nuclear Strategy (5 books)
    {"title": "Command and Control: Nuclear Weapons, the Damascus Accident, and the Illusion of Safety", "author": "Eric Schlosser", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nuclear Strategy", "slug": "Command-and-Control-Schlosser"},
    {"title": "The Doomsday Machine: Confessions of a Nuclear War Planner", "author": "Daniel Ellsberg", "first_published": "2017", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nuclear Strategy", "slug": "The-Doomsday-Machine-Ellsberg"},
    {"title": "The Making of the Atomic Bomb", "author": "Richard Rhodes", "first_published": "1986", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nuclear Strategy", "slug": "The-Making-of-the-Atomic-Bomb"},
    {"title": "Dark Sun: The Making of the Hydrogen Bomb", "author": "Richard Rhodes", "first_published": "1995", "latest_published": "1996", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nuclear Strategy", "slug": "Dark-Sun-Rhodes"},
    {"title": "Nuclear War: A Scenario", "author": "Annie Jacobsen", "first_published": "2024", "latest_published": "2024", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nuclear Strategy", "slug": "Nuclear-War-A-Scenario"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 04. NATIONS & EMPIRES (50 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: GREAT POWERS (20 books)
    # LEVEL 4: American Power (5 books)
    {"title": "These Truths: A History of the United States", "author": "Jill Lepore", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "American Power", "slug": "These-Truths-Lepore"},
    {"title": "Battle Cry of Freedom: The Civil War Era", "author": "James M. McPherson", "first_published": "1988", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "American Power", "slug": "Battle-Cry-of-Freedom"},
    {"title": "A Brilliant Solution: Inventing the American Constitution", "author": "Carol Berkin", "first_published": "2002", "latest_published": "2003", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "American Power", "slug": "A-Brilliant-Solution-Berkin"},
    {"title": "Founding Brothers: The Revolutionary Generation", "author": "Joseph J. Ellis", "first_published": "2000", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "American Power", "slug": "Founding-Brothers-Ellis"},
    {"title": "The Ideological Origins of the American Revolution", "author": "Bernard Bailyn", "first_published": "1967", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "American Power", "slug": "The-Ideological-Origins-of-the-American-Revolution"},

    # LEVEL 4: European History (5 books)
    {"title": "The Pursuit of Glory: Europe 1648-1815", "author": "Tim Blanning", "first_published": "2007", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "European History", "slug": "The-Pursuit-of-Glory-Blanning"},
    {"title": "The Pursuit of Power: Europe 1815-1914", "author": "Richard J. Evans", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "European History", "slug": "The-Pursuit-of-Power-Evans"},
    {"title": "The Coming of the Third Reich", "author": "Richard J. Evans", "first_published": "2003", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "European History", "slug": "The-Coming-of-the-Third-Reich"},
    {"title": "The Third Reich in Power", "author": "Richard J. Evans", "first_published": "2005", "latest_published": "2006", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "European History", "slug": "The-Third-Reich-in-Power"},
    {"title": "The Third Reich at War", "author": "Richard J. Evans", "first_published": "2008", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "European History", "slug": "The-Third-Reich-at-War"},

    # LEVEL 4: Russian History (5 books)
    {"title": "The Romanovs: 1613-1918", "author": "Simon Sebag Montefiore", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Russian History", "slug": "The-Romanovs-Montefiore"},
    {"title": "Stalin: The Court of the Red Tsar", "author": "Simon Sebag Montefiore", "first_published": "2003", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Russian History", "slug": "Stalin-The-Court-of-the-Red-Tsar"},
    {"title": "Young Stalin", "author": "Simon Sebag Montefiore", "first_published": "2007", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Russian History", "slug": "Young-Stalin-Montefiore"},
    {"title": "A People's Tragedy: The Russian Revolution: 1891-1924", "author": "Orlando Figes", "first_published": "1996", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Russian History", "slug": "A-Peoples-Tragedy-Figes"},
    {"title": "The Story of Russia", "author": "Orlando Figes", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Russian History", "slug": "The-Story-of-Russia-Figes"},

    # LEVEL 4: Asian Powers (5 books)
    {"title": "The Search for Modern China", "author": "Jonathan D. Spence", "first_published": "1990", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Asian Powers", "slug": "The-Search-for-Modern-China"},
    {"title": "Mao's Great Famine: The History of China's Most Devastating Catastrophe, 1958-1962", "author": "Frank Dikötter", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Asian Powers", "slug": "Maos-Great-Famine"},
    {"title": "The Tragedy of Liberation: A History of the Chinese Revolution 1945-1957", "author": "Frank Dikötter", "first_published": "2013", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Asian Powers", "slug": "The-Tragedy-of-Liberation"},
    {"title": "The Cultural Revolution: A People's History, 1962-1976", "author": "Frank Dikötter", "first_published": "2016", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Asian Powers", "slug": "The-Cultural-Revolution-Dikotter"},
    {"title": "Embracing Defeat: Japan in the Wake of World War II", "author": "John W. Dower", "first_published": "1999", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Asian Powers", "slug": "Embracing-Defeat-Dower"},

    # LEVEL 3: POSTCOLONIAL WORLD (15 books)
    # LEVEL 4: Decolonization (5 books)
    {"title": "The Wretched of the Earth", "author": "Frantz Fanon", "first_published": "1961", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decolonization", "slug": "The-Wretched-of-the-Earth"},
    {"title": "Orientalism", "author": "Edward W. Said", "first_published": "1978", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decolonization", "slug": "Orientalism-Said"},
    {"title": "King Leopold's Ghost: A Story of Greed, Terror, and Heroism in Colonial Africa", "author": "Adam Hochschild", "first_published": "1998", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decolonization", "slug": "King-Leopolds-Ghost"},
    {"title": "Inglorious Empire: What the British Did to India", "author": "Shashi Tharoor", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decolonization", "slug": "Inglorious-Empire-Tharoor"},
    {"title": "Midnight's Furies: The Deadly Legacy of India's Partition", "author": "Nisid Hajari", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Decolonization", "slug": "Midnights-Furies-Hajari"},

    # LEVEL 4: Middle Eastern History (5 books)
    {"title": "A Peace to End All Peace: The Fall of the Ottoman Empire and the Creation of the Modern Middle East", "author": "David Fromkin", "first_published": "1989", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Middle Eastern History", "slug": "A-Peace-to-End-All-Peace"},
    {"title": "The Arabs: A History", "author": "Eugene Rogan", "first_published": "2009", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Middle Eastern History", "slug": "The-Arabs-Rogan"},
    {"title": "The Fall of the Ottomans: The Great War in the Middle East", "author": "Eugene Rogan", "first_published": "2015", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Middle Eastern History", "slug": "The-Fall-of-the-Ottomans-Rogan"},
    {"title": "All the Shah's Men: An American Coup and the Roots of Middle East Terror", "author": "Stephen Kinzer", "first_published": "2003", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Middle Eastern History", "slug": "All-the-Shahs-Men"},
    {"title": "Black Wave: Saudi Arabia, Iran, and the Forty-Year Rivalry That Unraveled Culture, Religion, and Collective Memory in the Middle East", "author": "Kim Ghattas", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Middle Eastern History", "slug": "Black-Wave-Ghattas"},

    # LEVEL 4: African History (5 books)
    {"title": "The Fate of Africa: A History of the Continent Since Independence", "author": "Martin Meredith", "first_published": "2005", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "African History", "slug": "The-Fate-of-Africa-Meredith"},
    {"title": "Diamonds, Gold, and War: The British, the Boers, and the Making of South Africa", "author": "Martin Meredith", "first_published": "2007", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "African History", "slug": "Diamonds-Gold-and-War"},
    {"title": "The Scramble for Africa: White Man's Conquest of the Dark Continent from 1876 to 1912", "author": "Thomas Pakenham", "first_published": "1991", "latest_published": "1992", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "African History", "slug": "The-Scramble-for-Africa-Pakenham"},
    {"title": "Africa: A Biography of the Continent", "author": "John Reader", "first_published": "1997", "latest_published": "1999", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "African History", "slug": "Africa-A-Biography-of-the-Continent"},
    {"title": "Born in Blackness: Africa, Africans, and the Making of the Modern World, 1471 to the Second World War", "author": "Howard W. French", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "African History", "slug": "Born-in-Blackness-French"},

    # LEVEL 3: MODERN STATE (15 books)
    # LEVEL 4: State Formation (5 books)
    {"title": "The Origins of Political Order: From Prehuman Times to the French Revolution", "author": "Francis Fukuyama", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "State Formation", "slug": "The-Origins-of-Political-Order"},
    {"title": "Political Order and Political Decay: From the Industrial Revolution to the Globalization of Democracy", "author": "Francis Fukuyama", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "State Formation", "slug": "Political-Order-and-Political-Decay"},
    {"title": "The End of History and the Last Man", "author": "Francis Fukuyama", "first_published": "1992", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "State Formation", "slug": "The-End-of-History-and-the-Last-Man"},
    {"title": "Seeing Like a State: How Certain Schemes to Improve the Human Condition Have Failed", "author": "James C. Scott", "first_published": "1998", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "State Formation", "slug": "Seeing-Like-a-State"},
    {"title": "The Art of Not Being Governed: An Anarchist History of Upland Southeast Asia", "author": "James C. Scott", "first_published": "2009", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "State Formation", "slug": "The-Art-of-Not-Being-Governed"},

    # LEVEL 4: Nationalism (5 books)
    {"title": "Imagined Communities: Reflections on the Origin and Spread of Nationalism", "author": "Benedict Anderson", "first_published": "1983", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nationalism", "slug": "Imagined-Communities-Anderson"},
    {"title": "Nations and Nationalism", "author": "Ernest Gellner", "first_published": "1983", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nationalism", "slug": "Nations-and-Nationalism-Gellner"},
    {"title": "The Invention of Tradition", "author": "Eric Hobsbawm; Terence Ranger", "first_published": "1983", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nationalism", "slug": "The-Invention-of-Tradition"},
    {"title": "Identity: The Demand for Dignity and the Politics of Resentment", "author": "Francis Fukuyama", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nationalism", "slug": "Identity-Fukuyama"},
    {"title": "Nationalism: A Very Short Introduction", "author": "Steven Grosby", "first_published": "2005", "latest_published": "2005", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Nationalism", "slug": "Nationalism-Grosby"},

    # LEVEL 4: Constitutional History (5 books)
    {"title": "The Gun, the Ship, and the Pen: Warfare, Constitutions, and the Making of the Modern World", "author": "Linda Colley", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Constitutional History", "slug": "The-Gun-the-Ship-and-the-Pen"},
    {"title": "Britons: Forging the Nation 1707-1837", "author": "Linda Colley", "first_published": "1992", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Constitutional History", "slug": "Britons-Linda-Colley"},
    {"title": "The Rule of Law", "author": "Tom Bingham", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Constitutional History", "slug": "The-Rule-of-Law-Bingham"},
    {"title": "Magna Carta: The Birth of Liberty", "author": "Dan Jones", "first_published": "2014", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Constitutional History", "slug": "Magna-Carta-Dan-Jones"},
    {"title": "America's Constitution: A Biography", "author": "Akhil Reed Amar", "first_published": "2005", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Constitutional History", "slug": "Americas-Constitution-Amar"},
]
