from __future__ import annotations

# Domain 11: Science, Nature & the Universe (150 books: #1681–#1830)
BOOKS_11 = [
    # -------------------------------------------------------------------------
    # LEVEL 2: 01. PHYSICS & ASTRONOMY (45 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: FUNDAMENTAL PHYSICS (15 books)
    # LEVEL 4: Quantum Physics (5 books)
    {"title": "Six Easy Pieces: Essentials of Physics Explained by Its Most Brilliant Teacher", "author": "Richard P. Feynman", "first_published": "1994", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Quantum Physics", "slug": "Six-Easy-Pieces-Feynman"},
    {"title": "Six Not-So-Easy Pieces: Einstein's Relativity, Symmetry, and Space-Time", "author": "Richard P. Feynman", "first_published": "1997", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Quantum Physics", "slug": "Six-Not-So-Easy-Pieces-Feynman"},
    {"title": "QED: The Strange Theory of Light and Matter", "author": "Richard P. Feynman", "first_published": "1985", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Quantum Physics", "slug": "QED-Feynman"},
    {"title": "Something Deeply Hidden: Quantum Worlds and the Emergence of Spacetime", "author": "Sean Carroll", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Quantum Physics", "slug": "Something-Deeply-Hidden-Carroll"},
    {"title": "In Search of Schrödinger's Cat: Quantum Physics and Reality", "author": "John Gribbin", "first_published": "1984", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Quantum Physics", "slug": "In-Search-of-Schrodingers-Cat"},

    # LEVEL 4: Relativity & Space-Time (5 books)
    {"title": "Relativity: The Special and the General Theory", "author": "Albert Einstein", "first_published": "1916", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Relativity & Space-Time", "slug": "Relativity-Einstein"},
    {"title": "The Order of Time", "author": "Carlo Rovelli", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Relativity & Space-Time", "slug": "The-Order-of-Time-Rovelli"},
    {"title": "Seven Brief Lessons on Physics", "author": "Carlo Rovelli", "first_published": "2014", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Relativity & Space-Time", "slug": "Seven-Brief-Lessons-on-Physics"},
    {"title": "Reality Is Not What It Seems: The Journey to Quantum Gravity", "author": "Carlo Rovelli", "first_published": "2014", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Relativity & Space-Time", "slug": "Reality-Is-Not-What-It-Seems"},
    {"title": "Helgoland: Making Sense of the Quantum Revolution", "author": "Carlo Rovelli", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Relativity & Space-Time", "slug": "Helgoland-Rovelli"},

    # LEVEL 4: Particle Physics (5 books)
    {"title": "The Particle at the End of the Universe: How the Hunt for the Higgs Boson Leads Us to the Edge of a New World", "author": "Sean Carroll", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Particle Physics", "slug": "The-Particle-at-the-End-of-the-Universe"},
    {"title": "The God Particle: If the Universe Is the Answer, What Is the Question?", "author": "Leon M. Lederman; Dick Teresi", "first_published": "1993", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Particle Physics", "slug": "The-God-Particle-Lederman"},
    {"title": "Knocking on Heaven's Door: How Physics and Scientific Thinking Illuminate the Universe and the Modern World", "author": "Lisa Randall", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Particle Physics", "slug": "Knocking-on-Heavens-Door-Randall"},
    {"title": "Warped Passages: Unraveling the Mysteries of the Universe's Hidden Dimensions", "author": "Lisa Randall", "first_published": "2005", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Particle Physics", "slug": "Warped-Passages-Randall"},
    {"title": "Dark Matter and the Dinosaurs: The Astounding Interconnectedness of the Universe", "author": "Lisa Randall", "first_published": "2015", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Particle Physics", "slug": "Dark-Matter-and-the-Dinosaurs"},

    # LEVEL 3: COSMOLOGY & ASTROPHYSICS (15 books)
    # LEVEL 4: Origin of Universe (5 books)
    {"title": "A Brief History of Time", "author": "Stephen Hawking", "first_published": "1988", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origin of Universe", "slug": "A-Brief-History-of-Time"},
    {"title": "The Universe in a Nutshell", "author": "Stephen Hawking", "first_published": "2001", "latest_published": "2001", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origin of Universe", "slug": "The-Universe-in-a-Nutshell"},
    {"title": "The Grand Design", "author": "Stephen Hawking; Leonard Mlodinow", "first_published": "2010", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origin of Universe", "slug": "The-Grand-Design-Hawking"},
    {"title": "The First Three Minutes: A Modern View of the Origin of the Universe", "author": "Steven Weinberg", "first_published": "1977", "latest_published": "1993", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origin of Universe", "slug": "The-First-Three-Minutes-Weinberg"},
    {"title": "Cosmos", "author": "Carl Sagan", "first_published": "1980", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origin of Universe", "slug": "Cosmos-Carl-Sagan"},

    # LEVEL 4: Black Holes (5 books)
    {"title": "Black Holes and Time Warps: Einstein's Outrageous Legacy", "author": "Kip S. Thorne", "first_published": "1994", "latest_published": "1995", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Black Holes", "slug": "Black-Holes-and-Time-Warps"},
    {"title": "The Science of Interstellar", "author": "Kip S. Thorne", "first_published": "2014", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Black Holes", "slug": "The-Science-of-Interstellar"},
    {"title": "The Black Hole War: My Battle with Stephen Hawking to Make the World Safe for Quantum Mechanics", "author": "Leonard Susskind", "first_published": "2008", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Black Holes", "slug": "The-Black-Hole-War"},
    {"title": "Einstein's Shadow: A Black Hole, a Band of Astronomers, and the Quest to See the Unseeable", "author": "Seth Fletcher", "first_published": "2018", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Black Holes", "slug": "Einsteins-Shadow"},
    {"title": "Black Hole Survival Guide", "author": "Janna Levin", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Black Holes", "slug": "Black-Hole-Survival-Guide"},

    # LEVEL 4: Space Exploration (5 books)
    {"title": "Pale Blue Dot: A Vision of the Human Future in Space", "author": "Carl Sagan", "first_published": "1994", "latest_published": "1997", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Space Exploration", "slug": "Pale-Blue-Dot-Sagan"},
    {"title": "Astrophysics for People in a Hurry", "author": "Neil deGrasse Tyson", "first_published": "2017", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Space Exploration", "slug": "Astrophysics-for-People-in-a-Hurry"},
    {"title": "Origins: Fourteen Billion Years of Cosmic Evolution", "author": "Neil deGrasse Tyson; Donald Goldsmith", "first_published": "2004", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Space Exploration", "slug": "Origins-Neil-deGrasse-Tyson"},
    {"title": "The Right Stuff", "author": "Tom Wolfe", "first_published": "1979", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Space Exploration", "slug": "The-Right-Stuff-Wolfe"},
    {"title": "Carrying the Fire: An Astronaut's Journeys", "author": "Michael Collins", "first_published": "1974", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Space Exploration", "slug": "Carrying-the-Fire-Collins"},

    # LEVEL 3: CLASSICAL PHYSICS (15 books)
    # LEVEL 4: Mechanics & Motion (5 books)
    {"title": "The Character of Physical Law", "author": "Richard P. Feynman", "first_published": "1965", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mechanics & Motion", "slug": "The-Character-of-Physical-Law-Feynman"},
    {"title": "Thinking Physics: Understandable Practical Reality", "author": "Lewis Carroll Epstein", "first_published": "1979", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mechanics & Motion", "slug": "Thinking-Physics-Epstein"},
    {"title": "For the Love of Physics: From the End of the Rainbow to the Edge of Time", "author": "Walter Lewin; Warren Goldstein", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mechanics & Motion", "slug": "For-the-Love-of-Physics"},
    {"title": "The Flying Circus of Physics", "author": "Jearl Walker", "first_published": "1975", "latest_published": "2006", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mechanics & Motion", "slug": "The-Flying-Circus-of-Physics"},
    {"title": "Physics for Future Presidents: The Science Behind the Headlines", "author": "Richard A. Muller", "first_published": "2008", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mechanics & Motion", "slug": "Physics-for-Future-Presidents"},

    # LEVEL 4: Thermodynamics & Energy (5 books)
    {"title": "The Big Picture: On the Origins of Life, Meaning, and the Universe Itself", "author": "Sean Carroll", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Thermodynamics & Energy", "slug": "The-Big-Picture-Carroll"},
    {"title": "From Eternity to Here: The Quest for the Ultimate Theory of Time", "author": "Sean Carroll", "first_published": "2010", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Thermodynamics & Energy", "slug": "From-Eternity-to-Here-Carroll"},
    {"title": "Energy and Civilization: A History", "author": "Vaclav Smil", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Thermodynamics & Energy", "slug": "Energy-and-Civilization-Smil"},
    {"title": "How the World Really Works: The Science Behind How We Got Here and Where We're Going", "author": "Vaclav Smil", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Thermodynamics & Energy", "slug": "How-the-World-Really-Works-Smil"},
    {"title": "Numbers Don't Lie: 71 Things You Need to Know About the World", "author": "Vaclav Smil", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Thermodynamics & Energy", "slug": "Numbers-Dont-Lie-Smil"},

    # LEVEL 4: History of Physics (5 books)
    {"title": "The Road to Reality: A Complete Guide to the Laws of the Universe", "author": "Roger Penrose", "first_published": "2004", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Physics", "slug": "The-Road-to-Reality-Penrose"},
    {"title": "The Emperor's New Mind: Concerning Computers, Minds, and the Laws of Physics", "author": "Roger Penrose", "first_published": "1989", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Physics", "slug": "The-Emperors-New-Mind"},
    {"title": "Shadows of the Mind: A Search for the Missing Science of Consciousness", "author": "Roger Penrose", "first_published": "1994", "latest_published": "1996", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Physics", "slug": "Shadows-of-the-Mind"},
    {"title": "Subtle Is the Lord: The Science and the Life of Albert Einstein", "author": "Abraham Pais", "first_published": "1982", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Physics", "slug": "Subtle-Is-the-Lord"},
    {"title": "Einstein: His Life and Universe", "author": "Walter Isaacson", "first_published": "2007", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Physics", "slug": "Einstein-Walter-Isaacson"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 02. BIOLOGY & LIFE SCIENCES (45 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: EVOLUTIONARY BIOLOGY (15 books)
    # LEVEL 4: Natural Selection (5 books)
    {"title": "On the Origin of Species", "author": "Charles Darwin", "first_published": "1859", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Natural Selection", "slug": "On-the-Origin-of-Species-Darwin"},
    {"title": "Climbing Mount Improbable", "author": "Richard Dawkins", "first_published": "1996", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Natural Selection", "slug": "Climbing-Mount-Improbable-Dawkins"},
    {"title": "The Extended Phenotype: The Long Reach of the Gene", "author": "Richard Dawkins", "first_published": "1982", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Natural Selection", "slug": "The-Extended-Phenotype"},
    {"title": "The Blind Watchmaker: Why the Evidence of Evolution Reveals a Universe without Design", "author": "Richard Dawkins", "first_published": "1986", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Natural Selection", "slug": "The-Blind-Watchmaker"},
    {"title": "The Greatest Show on Earth: The Evidence for Evolution", "author": "Richard Dawkins", "first_published": "2009", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Natural Selection", "slug": "The-Greatest-Show-on-Earth"},

    # LEVEL 4: Origin of Life (5 books)
    {"title": "The Vital Question: Energy, Evolution, and the Origins of Complex Life", "author": "Nick Lane", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origin of Life", "slug": "The-Vital-Question-Nick-Lane"},
    {"title": "Oxygen: The Molecule that Made the World", "author": "Nick Lane", "first_published": "2002", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origin of Life", "slug": "Oxygen-Nick-Lane"},
    {"title": "Power, Sex, Suicide: Mitochondria and the Meaning of Life", "author": "Nick Lane", "first_published": "2005", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origin of Life", "slug": "Power-Sex-Suicide-Nick-Lane"},
    {"title": "Transformer: The Deep Chemistry of Life and Death", "author": "Nick Lane", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origin of Life", "slug": "Transformer-Nick-Lane"},
    {"title": "Life Ascending: The Ten Great Inventions of Evolution", "author": "Nick Lane", "first_published": "2009", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Origin of Life", "slug": "Life-Ascending-Nick-Lane"},

    # LEVEL 4: Human Evolution (5 books)
    {"title": "The Story of the Human Body: Evolution, Health, and Disease", "author": "Daniel E. Lieberman", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Evolution", "slug": "The-Story-of-the-Human-Body"},
    {"title": "Exercised: Why Something We Never Evolved to Do Is Healthy and Rewarding", "author": "Daniel E. Lieberman", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Evolution", "slug": "Exercised-Lieberman"},
    {"title": "The Goodness Paradox: The Strange Relationship Between Virtue and Violence in Human Evolution", "author": "Richard Wrangham", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Evolution", "slug": "The-Goodness-Paradox"},
    {"title": "Tree of Origin: What Primate Behavior Can Tell Us About Human Social Evolution", "author": "Frans de Waal", "first_published": "2001", "latest_published": "2002", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Evolution", "slug": "Tree-of-Origin-de-Waal"},
    {"title": "Demonic Males: Apes and the Origins of Human Violence", "author": "Richard Wrangham; Dale Peterson", "first_published": "1996", "latest_published": "1997", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Human Evolution", "slug": "Demonic-Males"},

    # LEVEL 3: GENETICS & MOLECULAR BIOLOGY (15 books)
    # LEVEL 4: DNA & Genetics (5 books)
    {"title": "The Double Helix: A Personal Account of the Discovery of the Structure of DNA", "author": "James D. Watson", "first_published": "1968", "latest_published": "2001", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "DNA & Genetics", "slug": "The-Double-Helix-Watson"},
    {"title": "The Language of God: A Scientist Presents Evidence for Belief", "author": "Francis S. Collins", "first_published": "2006", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "DNA & Genetics", "slug": "The-Language-of-God-Collins"},
    {"title": "Genome: The Autobiography of a Species in 23 Chapters", "author": "Matt Ridley", "first_published": "1999", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "DNA & Genetics", "slug": "Genome-Matt-Ridley"},
    {"title": "Nature Via Nurture: Genes, Experience, and What Makes Us Human", "author": "Matt Ridley", "first_published": "2003", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "DNA & Genetics", "slug": "Nature-Via-Nurture"},
    {"title": "The Evolution of Everything: How New Ideas Emerge", "author": "Matt Ridley", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "DNA & Genetics", "slug": "The-Evolution-of-Everything-Ridley"},

    # LEVEL 4: Cellular Biology (5 books)
    {"title": "Molecular Biology of the Cell", "author": "Bruce Alberts; Rebecca Heald; Alexander Johnson", "first_published": "1983", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cellular Biology", "slug": "Molecular-Biology-of-the-Cell"},
    {"title": "The Immortal Life of Henrietta Lacks", "author": "Rebecca Skloot", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cellular Biology", "slug": "The-Immortal-Life-of-Henrietta-Lacks"},
    {"title": "Life at the Speed of Light: From the Double Helix to the Dawn of Digital Life", "author": "J. Craig Venter", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cellular Biology", "slug": "Life-at-the-Speed-of-Light"},
    {"title": "A Life Decoded: My Genome: My Life", "author": "J. Craig Venter", "first_published": "2007", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cellular Biology", "slug": "A-Life-Decoded-Venter"},
    {"title": "What is Life?: With Mind and Matter and Autobiographical Sketches", "author": "Erwin Schrödinger", "first_published": "1944", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cellular Biology", "slug": "What-is-Life-Schrodinger"},

    # LEVEL 4: Epigenetics (5 books)
    {"title": "The Epigenetics Revolution: How Modern Biology Is Rewriting Our Understanding of Genetics, Disease, and Inheritance", "author": "Nessa Carey", "first_published": "2011", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Epigenetics", "slug": "The-Epigenetics-Revolution"},
    {"title": "Junk DNA: A Journey Through the Dark Matter of the Genome", "author": "Nessa Carey", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Epigenetics", "slug": "Junk-DNA-Carey"},
    {"title": "Hacking the Code of Life: How Gene Editing Will Rewrite Our Futures", "author": "Nessa Carey", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Epigenetics", "slug": "Hacking-the-Code-of-Life"},
    {"title": "The Developing Genome: An Introduction to Behavioral Epigenetics", "author": "David S. Moore", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Epigenetics", "slug": "The-Developing-Genome"},
    {"title": "Epigenetics: How Environment Shapes Our Genes", "author": "Richard C. Francis", "first_published": "2011", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Epigenetics", "slug": "Epigenetics-Francis"},

    # LEVEL 3: ECOLOGY & ANIMAL BEHAVIOR (15 books)
    # LEVEL 4: Ecosystems (5 books)
    {"title": "The Diversity of Life", "author": "Edward O. Wilson", "first_published": "1992", "latest_published": "1999", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ecosystems", "slug": "The-Diversity-of-Life-Wilson"},
    {"title": "Half-Earth: Our Planet's Fight for Life", "author": "Edward O. Wilson", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ecosystems", "slug": "Half-Earth-Wilson"},
    {"title": "The Social Conquest of Earth", "author": "Edward O. Wilson", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ecosystems", "slug": "The-Social-Conquest-of-Earth"},
    {"title": "Consilience: The Unity of Knowledge", "author": "Edward O. Wilson", "first_published": "1998", "latest_published": "1999", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ecosystems", "slug": "Consilience-Wilson"},
    {"title": "The Serengeti Rules: The Quest to Discover How Life Works and Why It Matters", "author": "Sean B. Carroll", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Ecosystems", "slug": "The-Serengeti-Rules"},

    # LEVEL 4: Animal Intelligence (5 books)
    {"title": "Other Minds: The Octopus, the Sea, and the Deep Origins of Consciousness", "author": "Peter Godfrey-Smith", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Animal Intelligence", "slug": "Other-Minds-Godfrey-Smith"},
    {"title": "Metazoa: Animal Life and the Birth of the Mind", "author": "Peter Godfrey-Smith", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Animal Intelligence", "slug": "Metazoa-Godfrey-Smith"},
    {"title": "Are We Smart Enough to Know How Smart Animals Are?", "author": "Frans de Waal", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Animal Intelligence", "slug": "Are-We-Smart-Enough-to-Know-How-Smart-Animals-Are"},
    {"title": "Mama's Last Hug: Animal Emotions and What They Tell Us about Ourselves", "author": "Frans de Waal", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Animal Intelligence", "slug": "Mamas-Last-Hug"},
    {"title": "Chimpanzee Politics: Power and Sex among Apes", "author": "Frans de Waal", "first_published": "1982", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Animal Intelligence", "slug": "Chimpanzee-Politics"},

    # LEVEL 4: Plant Science (5 books)
    {"title": "The Hidden Life of Trees: What They Feel, How They Communicate", "author": "Peter Wohlleben", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Plant Science", "slug": "The-Hidden-Life-of-Trees"},
    {"title": "Braiding Sweetgrass: Indigenous Wisdom, Scientific Knowledge and the Teachings of Plants", "author": "Robin Wall Kimmerer", "first_published": "2013", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Plant Science", "slug": "Braiding-Sweetgrass"},
    {"title": "Entangled Life: How Fungi Make Our Worlds, Change Our Minds & Shape Our Futures", "author": "Merlin Sheldrake", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Plant Science", "slug": "Entangled-Life"},
    {"title": "The Revolutionary Genius of Plants: A New Understanding of Plant Intelligence and Behavior", "author": "Stefano Mancuso", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Plant Science", "slug": "The-Revolutionary-Genius-of-Plants"},
    {"title": "Brilliant Green: The Surprising History and Science of Plant Intelligence", "author": "Stefano Mancuso; Alessandra Viola", "first_published": "2013", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Plant Science", "slug": "Brilliant-Green"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 03. EARTH & ENVIRONMENTAL SCIENCE (30 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: EARTH SYSTEMS (15 books)
    # LEVEL 4: Geology & Earth History (5 books)
    {"title": "Annals of the Former World", "author": "John McPhee", "first_published": "1998", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Geology & Earth History", "slug": "Annals-of-the-Former-World"},
    {"title": "The Control of Nature", "author": "John McPhee", "first_published": "1989", "latest_published": "1990", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Geology & Earth History", "slug": "The-Control-of-Nature"},
    {"title": "Origins: How Earth's History Shaped Human History", "author": "Lewis Dartnell", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Geology & Earth History", "slug": "Origins-Lewis-Dartnell"},
    {"title": "The Planet in a Pebble: A Journey into Earth's Deep History", "author": "Jan Zalasiewicz", "first_published": "2010", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Geology & Earth History", "slug": "The-Planet-in-a-Pebble"},
    {"title": "The Story of Earth: The First 4.5 Billion Years, from Stardust to Living Planet", "author": "Robert M. Hazen", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Geology & Earth History", "slug": "The-Story-of-Earth-Hazen"},

    # LEVEL 4: Oceanography (5 books)
    {"title": "The Sea Around Us", "author": "Rachel Carson", "first_published": "1951", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Oceanography", "slug": "The-Sea-Around-Us-Carson"},
    {"title": "Under the Sea Wind", "author": "Rachel Carson", "first_published": "1941", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Oceanography", "slug": "Under-the-Sea-Wind"},
    {"title": "The Edge of the Sea", "author": "Rachel Carson", "first_published": "1955", "latest_published": "1998", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Oceanography", "slug": "The-Edge-of-the-Sea"},
    {"title": "The Brilliant Abyss: True Tales of Exploring the Deep Sea, Discovering Hidden Life and the High Stakes of Save It", "author": "Helen Scales", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Oceanography", "slug": "The-Brilliant-Abyss-Scales"},
    {"title": "Eye of the Shoal: A Fishwatcher's Guide to Life, the Ocean and Everything", "author": "Helen Scales", "first_published": "2018", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Oceanography", "slug": "Eye-of-the-Shoal"},

    # LEVEL 4: Atmospheric Science (5 books)
    {"title": "The Cloudspotter's Guide: The Science, History, and Culture of the Clouds", "author": "Gavin Pretor-Pinney", "first_published": "2006", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Atmospheric Science", "slug": "The-Cloudspotters-Guide"},
    {"title": "An Ocean of Air: Why the Wind Blows and Other Mysteries of the Atmosphere", "author": "Gabrielle Walker", "first_published": "2007", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Atmospheric Science", "slug": "An-Ocean-of-Air"},
    {"title": "The Atmosphere: An Introduction to Meteorology", "author": "Frederick K. Lutgens; Edward J. Tarbuck", "first_published": "1979", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Atmospheric Science", "slug": "The-Atmosphere-Lutgens"},
    {"title": "Severe Storms: A Guide to the Science and Secrets of Extreme Weather", "author": "Michael Allaby", "first_published": "2009", "latest_published": "2009", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Atmospheric Science", "slug": "Severe-Storms-Allaby"},
    {"title": "The Weather Machine: A Journey Inside the Forecast", "author": "Andrew Blum", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Atmospheric Science", "slug": "The-Weather-Machine-Blum"},

    # LEVEL 3: CLIMATE & ENVIRONMENT (15 books)
    # LEVEL 4: Climate Science (5 books)
    {"title": "The Uninhabitable Earth: Life After Warming", "author": "David Wallace-Wells", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Climate Science", "slug": "The-Uninhabitable-Earth"},
    {"title": "How to Avoid a Climate Disaster: The Solutions We Have and the Breakthroughs We Need", "author": "Bill Gates", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Climate Science", "slug": "How-to-Avoid-a-Climate-Disaster-Gates"},
    {"title": "Under the White Sky: The Nature of the Future", "author": "Elizabeth Kolbert", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Climate Science", "slug": "Under-the-White-Sky-Kolbert"},
    {"title": "Field Notes from a Catastrophe: Man, Nature, and Climate Change", "author": "Elizabeth Kolbert", "first_published": "2006", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Climate Science", "slug": "Field-Notes-from-a-Catastrophe"},
    {"title": "The Climate Book: The Facts and the Solutions", "author": "Greta Thunberg", "first_published": "2022", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Climate Science", "slug": "The-Climate-Book-Thunberg"},

    # LEVEL 4: Conservation & Biodiversity (5 books)
    {"title": "The Sixth Extinction: An Unnatural History", "author": "Elizabeth Kolbert", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conservation & Biodiversity", "slug": "The-Sixth-Extinction"},
    {"title": "Silent Spring", "author": "Rachel Carson", "first_published": "1962", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conservation & Biodiversity", "slug": "Silent-Spring-Carson"},
    {"title": "A Sand County Almanac and Sketches Here and There", "author": "Aldo Leopold", "first_published": "1949", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conservation & Biodiversity", "slug": "A-Sand-County-Almanac"},
    {"title": "Feral: Rewilding the Land, the Sea, and Human Life", "author": "George Monbiot", "first_published": "2013", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conservation & Biodiversity", "slug": "Feral-Monbiot"},
    {"title": "Regenesis: Feeding the World without Devouring the Planet", "author": "George Monbiot", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Conservation & Biodiversity", "slug": "Regenesis-Monbiot"},

    # LEVEL 4: Environmental Crisis (5 books)
    {"title": "This Changes Everything: Capitalism vs. The Climate", "author": "Naomi Klein", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environmental Crisis", "slug": "This-Changes-Everything-Klein"},
    {"title": "On Fire: The (Burning) Case for a Green New Deal", "author": "Naomi Klein", "first_published": "2019", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environmental Crisis", "slug": "On-Fire-Klein"},
    {"title": "Drawdown: The Most Comprehensive Plan Ever Proposed to Reverse Global Warming", "author": "Paul Hawken", "first_published": "2017", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environmental Crisis", "slug": "Drawdown-Hawken"},
    {"title": "Regeneration: Ending the Climate Crisis in One Generation", "author": "Paul Hawken", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environmental Crisis", "slug": "Regeneration-Hawken"},
    {"title": "Speed & Scale: An Action Plan for Solving Our Climate Crisis Now", "author": "John Doerr", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Environmental Crisis", "slug": "Speed-and-Scale-Doerr"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 04. NEUROSCIENCE & MIND (30 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: BRAIN & MIND (15 books)
    # LEVEL 4: Brain Architecture (5 books)
    {"title": "The Brain: The Story of You", "author": "David Eagleman", "first_published": "2015", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Brain Architecture", "slug": "The-Brain-The-Story-of-You"},
    {"title": "Incognito: The Secret Lives of the Brain", "author": "David Eagleman", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Brain Architecture", "slug": "Incognito-Eagleman"},
    {"title": "Livewired: The Inside Story of the Ever-Changing Brain", "author": "David Eagleman", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Brain Architecture", "slug": "Livewired-Eagleman"},
    {"title": "The Master and His Emissary: The Divided Brain and the Making of the Western World", "author": "Iain McGilchrist", "first_published": "2009", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Brain Architecture", "slug": "The-Master-and-His-Emissary"},
    {"title": "The Matter With Things: Our Brains, Our Delusions and the Unmaking of the World", "author": "Iain McGilchrist", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Brain Architecture", "slug": "The-Matter-With-Things"},

    # LEVEL 4: Consciousness (5 books)
    {"title": "Sweet Dreams: Philosophical Obstacles to a Science of Consciousness", "author": "Daniel C. Dennett", "first_published": "2005", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consciousness", "slug": "Sweet-Dreams-Dennett"},
    {"title": "From Bacteria to Bach and Back: The Evolution of Minds", "author": "Daniel C. Dennett", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consciousness", "slug": "From-Bacteria-to-Bach-and-Back"},
    {"title": "The Character of Consciousness", "author": "David J. Chalmers", "first_published": "2010", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consciousness", "slug": "The-Character-of-Consciousness-Chalmers"},
    {"title": "Reality+: Virtual Worlds and the Problems of Philosophy", "author": "David J. Chalmers", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consciousness", "slug": "Reality-Plus-Chalmers"},
    {"title": "Rethinking Consciousness: A Scientific Theory of Subjective Experience", "author": "Michael S. A. Graziano", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Consciousness", "slug": "Rethinking-Consciousness-Graziano"},

    # LEVEL 4: Perception & Senses (5 books)
    {"title": "An Immense World: How Animal Senses Reveal the Hidden Realms Around Us", "author": "Ed Yong", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Perception & Senses", "slug": "An-Immense-World-Ed-Yong"},
    {"title": "I Contain Multitudes: The Microbes Within Us and a Grander View of Life", "author": "Ed Yong", "first_published": "2016", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Perception & Senses", "slug": "I-Contain-Multitudes-Ed-Yong"},
    {"title": "Visual Intelligence: How We Create What We See", "author": "Donald D. Hoffman", "first_published": "1998", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Perception & Senses", "slug": "Visual-Intelligence-Hoffman"},
    {"title": "Deviate: The Science of Seeing Differently", "author": "Beau Lotto", "first_published": "2017", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Perception & Senses", "slug": "Deviate-Beau-Lotto"},
    {"title": "Hallucinations", "author": "Oliver Sacks", "first_published": "2012", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Perception & Senses", "slug": "Hallucinations-Sacks"},

    # LEVEL 3: NEUROBIOLOGY (15 books)
    # LEVEL 4: Neurochemistry (5 books)
    {"title": "Determined: A Science of Life without Free Will", "author": "Robert M. Sapolsky", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Neurochemistry", "slug": "Determined-Sapolsky"},
    {"title": "The Compass of Pleasure: How Our Brains Make Fatty Foods, Orgasm, Exercise, Marijuana, Generosity, and Vodka Feel So Good", "author": "David J. Linden", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Neurochemistry", "slug": "The-Compass-of-Pleasure-Linden"},
    {"title": "Never Enough: The Neuroscience and Experience of Addiction", "author": "Judith Grisel", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Neurochemistry", "slug": "Never-Enough-Grisel"},
    {"title": "This Is Your Brain on Parasites: How Tiny Creatures Manipulate Our Behavior and Shape Society", "author": "Kathleen McAuliffe", "first_published": "2016", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Neurochemistry", "slug": "This-Is-Your-Brain-on-Parasites"},
    {"title": "Molecules of Emotion: The Science Behind Mind-Body Medicine", "author": "Candace B. Pert", "first_published": "1997", "latest_published": "1999", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Neurochemistry", "slug": "Molecules-of-Emotion-Pert"},

    # LEVEL 4: Brain Development (5 books)
    {"title": "The Brain That Changes Itself: Stories of Personal Triumph from the Frontiers of Brain Science", "author": "Norman Doidge", "first_published": "2007", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Brain Development", "slug": "The-Brain-That-Changes-Itself-Doidge"},
    {"title": "The Brain's Way of Healing: Remarkable Discoveries and Recoveries from the Frontiers of Neuroplasticity", "author": "Norman Doidge", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Brain Development", "slug": "The-Brains-Way-of-Healing-Doidge"},
    {"title": "Soft-Wired: How the New Science of Brain Plasticity Can Change Your Life", "author": "Michael Merzenich", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Brain Development", "slug": "Soft-Wired-Merzenich"},
    {"title": "The Teenage Brain: A Neuroscientist's Survival Guide to Raising Adolescents and Young Adults", "author": "Frances E. Jensen; Amy Ellis Nutt", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Brain Development", "slug": "The-Teenage-Brain"},
    {"title": "Inventing Ourselves: The Secret Life of the Teenage Brain", "author": "Sarah-Jayne Blakemore", "first_published": "2018", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Brain Development", "slug": "Inventing-Ourselves-Blakemore"},

    # LEVEL 4: Mind-Body Connection (5 books)
    {"title": "The Mind-Gut Connection: How the Hidden Conversation Within Our Bodies Impacts Our Mood, Our Choices, and Our Overall Health", "author": "Emeran Mayer", "first_published": "2016", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mind-Body Connection", "slug": "The-Mind-Gut-Connection"},
    {"title": "Brain Maker: The Power of Gut Microbes to Heal and Protect Your Brain - for Life", "author": "David Perlmutter; Kristin Loberg", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mind-Body Connection", "slug": "Brain-Maker-Perlmutter"},
    {"title": "The Psychobiotic Revolution: Mood, Food, and the New Science of the Gut-Brain Connection", "author": "Scott C. Anderson; John F. Cryan; Ted Dinan", "first_published": "2017", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mind-Body Connection", "slug": "The-Psychobiotic-Revolution"},
    {"title": "Cure: A Journey into the Science of Mind Over Body", "author": "Jo Marchant", "first_published": "2016", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mind-Body Connection", "slug": "Cure-Jo-Marchant"},
    {"title": "The Expectation Effect: How Your Mindset Can Transform Your Life", "author": "David Robson", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Mind-Body Connection", "slug": "The-Expectation-Effect-Robson"},
]
