from __future__ import annotations

# Domain 05: Finance, Investing & Wealth (220 books: #0601–#0820)
BOOKS_05 = [
    # -------------------------------------------------------------------------
    # LEVEL 2: 01. PERSONAL FINANCE (50 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: MONEY MANAGEMENT (15 books)
    # LEVEL 4: Cash Flow (5 books)
    {"title": "Your Money or Your Life: 9 Steps to Transforming Your Relationship with Money and Achieving Financial Independence", "author": "Vicki Robin; Joe Dominguez; Vicki Robin", "first_published": "1992", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cash Flow", "slug": "Your-Money-or-Your-Life"},
    {"title": "I Will Teach You to Be Rich: No Guilt. No Excuses. Just a 6-Week Program That Works", "author": "Ramit Sethi", "first_published": "2009", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cash Flow", "slug": "I-Will-Teach-You-to-Be-Rich"},
    {"title": "The Total Money Makeover: A Proven Plan for Financial Fitness", "author": "Dave Ramsey", "first_published": "2003", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cash Flow", "slug": "The-Total-Money-Makeover"},
    {"title": "You Need a Budget: The Proven System for Breaking the Paycheck-to-Paycheck Cycle", "author": "Jesse Mecham", "first_published": "2017", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cash Flow", "slug": "You-Need-a-Budget"},
    {"title": "All the Money in the World: What the Happiest People Know About Getting and Spending", "author": "Laura Vanderkam", "first_published": "2012", "latest_published": "2013", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Cash Flow", "slug": "All-the-Money-in-the-World"},

    # LEVEL 4: Saving (5 books)
    {"title": "The Richest Man in Babylon", "author": "George S. Clason", "first_published": "1926", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Saving", "slug": "The-Richest-Man-in-Babylon"},
    {"title": "The Automatic Millionaire: A Powerful One-Step Plan to Live and Finish Rich", "author": "David Bach", "first_published": "2003", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Saving", "slug": "The-Automatic-Millionaire"},
    {"title": "Smart Women Finish Rich", "author": "David Bach", "first_published": "1998", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Saving", "slug": "Smart-Women-Finish-Rich"},
    {"title": "The Latte Factor: Why You Don't Have to Be Rich to Live Rich", "author": "David Bach; John David Mann", "first_published": "2019", "latest_published": "2019", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Saving", "slug": "The-Latte-Factor"},
    {"title": "Pound Foolish: Exposing the Dark Side of the Personal Finance Industry", "author": "Helaine Olen", "first_published": "2012", "latest_published": "2013", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Saving", "slug": "Pound-Foolish"},

    # LEVEL 4: Financial Planning (5 books)
    {"title": "The One-Page Financial Plan: A Simple Way to Be Smart About Your Money", "author": "Carl Richards", "first_published": "2015", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Planning", "slug": "The-One-Page-Financial-Plan"},
    {"title": "The Behavior Gap: Simple Ways to Stop Doing Dumb Things with Money", "author": "Carl Richards", "first_published": "2012", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Planning", "slug": "The-Behavior-Gap"},
    {"title": "Personal Finance for Dummies", "author": "Eric Tyson", "first_published": "1994", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Planning", "slug": "Personal-Finance-for-Dummies"},
    {"title": "Get a Financial Life: Personal Finance in Your Twenties and Thirties", "author": "Beth Kobliner", "first_published": "1996", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Planning", "slug": "Get-a-Financial-Life"},
    {"title": "The Financial Diet: A Beginner's Guide to Being Good with Money", "author": "Chelsea Fagan; Lauren Ver Hage", "first_published": "2018", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Planning", "slug": "The-Financial-Diet"},

    # LEVEL 3: BANKING & CREDIT (15 books)
    # LEVEL 4: Banking Systems (5 books)
    {"title": "Other People's Money: The Real Business of Finance", "author": "John Kay", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Banking Systems", "slug": "Other-Peoples-Money-Kay"},
    {"title": "The Alchemy of Banking: Making Money from Money", "author": "Perry Mehrling", "first_published": "2011", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Banking Systems", "slug": "The-Alchemy-of-Banking"},
    {"title": "Central Banking 101", "author": "Joseph Wang", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Banking Systems", "slug": "Central-Banking-101"},
    {"title": "The Bankers' New Clothes: What's Wrong with Banking and What to Do about It", "author": "Anat Admati; Martin Hellwig", "first_published": "2013", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Banking Systems", "slug": "The-Bankers-New-Clothes"},
    {"title": "Lombard Street: A Description of the Money Market", "author": "Walter Bagehot", "first_published": "1873", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Banking Systems", "slug": "Lombard-Street"},

    # LEVEL 4: Credit (5 books)
    {"title": "Credit Secrets: The Blueprint to Raising Your Credit Score Fast", "author": "Scott Hilton", "first_published": "2019", "latest_published": "2020", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Credit", "slug": "Credit-Secrets"},
    {"title": "Credit Repair Kit For Dummies", "author": "Steve Bucci", "first_published": "2005", "latest_published": "2014", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Credit", "slug": "Credit-Repair-Kit-For-Dummies"},
    {"title": "Your Score: An Insider's Secrets to Understanding, Controlling, and Protecting Your Credit Score", "author": "Anthony Davenport", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Credit", "slug": "Your-Score-Davenport"},
    {"title": "Hidden Credit Repair Secrets", "author": "Mark Clayborne", "first_published": "2012", "latest_published": "2016", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Credit", "slug": "Hidden-Credit-Repair-Secrets"},
    {"title": "Score: The Complete Guide to Credit Repair", "author": "Greg Wilson", "first_published": "2017", "latest_published": "2017", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Credit", "slug": "Score-Complete-Guide"},

    # LEVEL 4: Debt (5 books)
    {"title": "Debt: The First 5,000 Years", "author": "David Graeber", "first_published": "2011", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Debt", "slug": "Debt-The-First-5000-Years"},
    {"title": "The Spender's Guide to Debt-Free Living: How a Spending Fast Helped Me Get from Broke to Badass in Record Time", "author": "Anna Newell Jones", "first_published": "2016", "latest_published": "2016", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Debt", "slug": "The-Spenders-Guide-to-Debt-Free-Living"},
    {"title": "Zero Debt: The Ultimate Guide to Financial Freedom", "author": "Lynnette Khalfani-Cox", "first_published": "2004", "latest_published": "2009", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Debt", "slug": "Zero-Debt"},
    {"title": "House of Debt: How They (and You) Caused the Great Recession, and How We Can Prevent It from Happening Again", "author": "Atif Mian; Amir Sufi", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Debt", "slug": "House-of-Debt"},
    {"title": "Between Debt and the Devil: Money, Credit, and Fixing Global Finance", "author": "Adair Turner", "first_published": "2015", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Debt", "slug": "Between-Debt-and-the-Devil"},

    # LEVEL 3: FINANCIAL INDEPENDENCE (20 books)
    # LEVEL 4: Wealth Building (5 books)
    {"title": "The Millionaire Next Door: The Surprising Secrets of America's Wealthy", "author": "Thomas J. Stanley; William D. Danko", "first_published": "1996", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Wealth Building", "slug": "The-Millionaire-Next-Door"},
    {"title": "The Next Millionaire Next Door: Enduring Strategies for Building Wealth", "author": "Thomas J. Stanley; Sarah Stanley Fallaw", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Wealth Building", "slug": "The-Next-Millionaire-Next-Door"},
    {"title": "Rich Dad Poor Dad: What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not!", "author": "Robert T. Kiyosaki", "first_published": "1997", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Wealth Building", "slug": "Rich-Dad-Poor-Dad"},
    {"title": "The Simple Path to Wealth: Your Road Map to Financial Independence and a Rich, Free Life", "author": "JL Collins", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Wealth Building", "slug": "The-Simple-Path-to-Wealth"},
    {"title": "Just Keep Buying: Proven Ways to Save Money And Build Your Wealth", "author": "Nick Maggiulli", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Wealth Building", "slug": "Just-Keep-Buying"},

    # LEVEL 4: FIRE (5 books)
    {"title": "Early Retirement Extreme: A Philosophical and Practical Guide to Financial Independence", "author": "Jacob Lund Fisker", "first_published": "2010", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "FIRE", "slug": "Early-Retirement-Extreme"},
    {"title": "Quit Like a Millionaire: No Gimmicks, Luck, or Trust Fund Required", "author": "Kristy Shen; Bryce Leung", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "FIRE", "slug": "Quit-Like-a-Millionaire"},
    {"title": "Choose FI: Your Blueprint to Financial Independence", "author": "Chris Mamula; Brad Barrett; Jonathan Mendonsa", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "FIRE", "slug": "Choose-FI"},
    {"title": "Playing with FIRE (Financial Independence Retire Early): How Far Would You Go for Financial Freedom?", "author": "Scott Rieckens", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "FIRE", "slug": "Playing-with-FIRE"},
    {"title": "Work Optional: Retire Early the Non-Penny-Pinching Way", "author": "Tanja Hester", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "FIRE", "slug": "Work-Optional"},

    # LEVEL 4: Retirement (5 books)
    {"title": "Die with Zero: Getting All You Can from Your Money and Your Life", "author": "Bill Perkins", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Retirement", "slug": "Die-with-Zero"},
    {"title": "How Much Money Do I Need to Retire?: Uncommon Financial Planning Wisdom for a Stress Free Retirement", "author": "Todd Tresidder", "first_published": "2014", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Retirement", "slug": "How-Much-Money-Do-I-Need-to-Retire"},
    {"title": "The Bogleheads' Guide to Retirement Planning", "author": "Taylor Larimore; Mel Lindauer; Richard A. Ferri", "first_published": "2009", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Retirement", "slug": "The-Bogleheads-Guide-to-Retirement-Planning"},
    {"title": "Can I Retire Yet?: How to Make the Biggest Financial Decision of the Rest of Your Life", "author": "Darrow Kirkpatrick", "first_published": "2012", "latest_published": "2016", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Retirement", "slug": "Can-I-Retire-Yet"},
    {"title": "Retirement Planning Guidebook: Navigating the Important Decisions for Retirement Success", "author": "Wade Pfau", "first_published": "2021", "latest_published": "2023", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Retirement", "slug": "Retirement-Planning-Guidebook"},

    # LEVEL 4: Financial Risk (5 books)
    {"title": "Fixed: Why Personal Finance Is Broken and How to Make It Work for Everyone", "author": "John Y. Campbell; Tarun Ramadorai", "first_published": "2025", "latest_published": "2025", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Risk", "slug": "Fixed-Campbell-Ramadorai"},
    {"title": "Living with Risk: A Guide to Financial Security", "author": "Christian Gilles", "first_published": "2015", "latest_published": "2015", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Risk", "slug": "Living-with-Risk"},
    {"title": "The Only Guide to a Winning Investment Strategy You'll Ever Need", "author": "Larry E. Swedroe", "first_published": "1998", "latest_published": "2005", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Risk", "slug": "The-Only-Guide-to-a-Winning-Investment-Strategy"},
    {"title": "Risk and Asset Allocation", "author": "Attilio Meucci", "first_published": "2005", "latest_published": "2009", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Risk", "slug": "Risk-and-Asset-Allocation"},
    {"title": "The Flaw of Averages: Why We Underestimate Risk in the Face of Uncertainty", "author": "Sam L. Savage", "first_published": "2009", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Risk", "slug": "The-Flaw-of-Averages"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 02. INVESTING FOUNDATIONS (50 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: RISK & RETURN (15 books)
    # LEVEL 4: Investment Risk (5 books)
    {"title": "The Most Important Thing: Uncommon Sense for the Thoughtful Investor", "author": "Howard Marks", "first_published": "2011", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Investment Risk", "slug": "The-Most-Important-Thing"},
    {"title": "The Most Important Thing Illuminated: Uncommon Sense for the Thoughtful Investor", "author": "Howard Marks; Paul Johnson; Seth A. Klarman", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Investment Risk", "slug": "The-Most-Important-Thing-Illuminated"},
    {"title": "Mastering the Market Cycle: Getting the Odds on Your Side", "author": "Howard Marks", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Investment Risk", "slug": "Mastering-the-Market-Cycle"},
    {"title": "Capital Ideas: The Improbable Origins of Modern Wall Street", "author": "Peter L. Bernstein", "first_published": "1992", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Investment Risk", "slug": "Capital-Ideas"},
    {"title": "Capital Ideas Evolving", "author": "Peter L. Bernstein", "first_published": "2007", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Investment Risk", "slug": "Capital-Ideas-Evolving"},

    # LEVEL 4: Return (5 books)
    {"title": "Stocks for the Long Run: The Definitive Guide to Financial Market Returns & Long-Term Investment Strategies", "author": "Jeremy J. Siegel", "first_published": "1994", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Return", "slug": "Stocks-for-the-Long-Run"},
    {"title": "The Future for Investors: Why the Tried and the True Triumph Over the Bold and the New", "author": "Jeremy J. Siegel", "first_published": "2005", "latest_published": "2005", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Return", "slug": "The-Future-for-Investors"},
    {"title": "Triumph of the Optimists: 101 Years of Global Investment Returns", "author": "Elroy Dimson; Paul Marsh; Mike Staunton", "first_published": "2002", "latest_published": "2002", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Return", "slug": "Triumph-of-the-Optimists"},
    {"title": "Expected Returns: An Investor's Guide to Harvesting Market Rewards", "author": "Antti Ilmanen", "first_published": "2011", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Return", "slug": "Expected-Returns"},
    {"title": "Investing Amid Low Expected Returns: Making the Most When Markets Offer the Least", "author": "Antti Ilmanen", "first_published": "2022", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Return", "slug": "Investing-Amid-Low-Expected-Returns"},

    # LEVEL 4: Diversification (5 books)
    {"title": "A Random Walk Down Wall Street: The Time-Tested Strategy for Successful Investing", "author": "Burton G. Malkiel", "first_published": "1973", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Diversification", "slug": "A-Random-Walk-Down-Wall-Street"},
    {"title": "Common Sense on Mutual Funds: Fully Updated 10th Anniversary Edition", "author": "John C. Bogle", "first_published": "1999", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Diversification", "slug": "Common-Sense-on-Mutual-Funds"},
    {"title": "The Little Book of Common Sense Investing: The Only Way to Guarantee Your Fair Share of Stock Market Returns", "author": "John C. Bogle", "first_published": "2007", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Diversification", "slug": "The-Little-Book-of-Common-Sense-Investing"},
    {"title": "The Bogleheads' Guide to Investing", "author": "Taylor Larimore; Mel Lindauer; Michael LeBoeuf", "first_published": "2006", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Diversification", "slug": "The-Bogleheads-Guide-to-Investing"},
    {"title": "The Four Pillars of Investing: Lessons for Building a Winning Portfolio", "author": "William J. Bernstein", "first_published": "2002", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Diversification", "slug": "The-Four-Pillars-of-Investing"},

    # LEVEL 3: ASSET ALLOCATION (15 books)
    # LEVEL 4: Portfolio Construction (5 books)
    {"title": "The Intelligent Asset Allocator: How to Build Your Portfolio to Maximize Returns and Minimize Risk", "author": "William J. Bernstein", "first_published": "2000", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Portfolio Construction", "slug": "The-Intelligent-Asset-Allocator"},
    {"title": "All About Asset Allocation", "author": "Richard A. Ferri", "first_published": "2006", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Portfolio Construction", "slug": "All-About-Asset-Allocation"},
    {"title": "Asset Allocation: Balancing Financial Risk", "author": "Roger C. Gibson", "first_published": "1989", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Portfolio Construction", "slug": "Asset-Allocation-Gibson"},
    {"title": "Pioneering Portfolio Management: An Unconventional Approach to Institutional Investment", "author": "David F. Swensen", "first_published": "2000", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Portfolio Construction", "slug": "Pioneering-Portfolio-Management"},
    {"title": "Unconventional Success: A Fundamental Approach to Personal Investment", "author": "David F. Swensen", "first_published": "2005", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Portfolio Construction", "slug": "Unconventional-Success"},

    # LEVEL 4: Rebalancing (5 books)
    {"title": "Rebalance: The Modern Portfolio Theory Guide", "author": "William J. Bernstein", "first_published": "2014", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Rebalancing", "slug": "Rebalance-Bernstein"},
    {"title": "Dynamic Global Portfolio Management", "author": "Tony Bell", "first_published": "2015", "latest_published": "2015", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Rebalancing", "slug": "Dynamic-Global-Portfolio-Management"},
    {"title": "Portfolio Rebalancing", "author": "Edward E. Qian", "first_published": "2007", "latest_published": "2007", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Rebalancing", "slug": "Portfolio-Rebalancing-Qian"},
    {"title": "Global Asset Allocation: A Survey of the World's Top Asset Allocation Strategies", "author": "Mebane Faber", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Rebalancing", "slug": "Global-Asset-Allocation-Faber"},
    {"title": "The Ivy Portfolio: How to Invest Like the Top Endowments and Avoid Bear Markets", "author": "Mebane Faber; Eric W. Richardson", "first_published": "2009", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Rebalancing", "slug": "The-Ivy-Portfolio"},

    # LEVEL 4: Long-Term Allocation (5 books)
    {"title": "The Allocator's Edge: A Guide to Alternative Investments and the Future of Diversification", "author": "Phil Huber", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Allocation", "slug": "The-Allocators-Edge"},
    {"title": "Adaptive Markets: Financial Evolution at the Speed of Thought", "author": "Andrew W. Lo", "first_published": "2017", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Allocation", "slug": "Adaptive-Markets"},
    {"title": "In Pursuit of the Perfect Portfolio: The Stories, Voices, and Key Insights of the Pioneers Who Shaped the Way We Invest", "author": "Andrew W. Lo; Stephen R. Foerster", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Allocation", "slug": "In-Pursuit-of-the-Perfect-Portfolio"},
    {"title": "Efficient Asset Management: A Practical Guide to Stock Portfolio Optimization and Asset Allocation", "author": "Richard O. Michaud; Robert O. Michaud", "first_published": "1998", "latest_published": "2008", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Allocation", "slug": "Efficient-Asset-Management"},
    {"title": "Quantitative Risk and Portfolio Management", "author": "Attilio Meucci", "first_published": "2011", "latest_published": "2011", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Allocation", "slug": "Quantitative-Risk-Meucci"},

    # LEVEL 3: INVESTOR PSYCHOLOGY (20 books)
    # LEVEL 4: Behavioral Finance (5 books)
    {"title": "The Psychology of Money: Timeless Lessons on Wealth, Greed, and Happiness", "author": "Morgan Housel", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Finance", "slug": "The-Psychology-of-Money"},
    {"title": "Same as Ever: A Guide to What Never Changes", "author": "Morgan Housel", "first_published": "2023", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Finance", "slug": "Same-as-Ever"},
    {"title": "Beyond Greed and Fear: Understanding Behavioral Finance and the Psychology of Investing", "author": "Hersh Shefrin", "first_published": "2000", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Finance", "slug": "Beyond-Greed-and-Fear-Shefrin"},
    {"title": "Behavioral Finance: Understanding the Social, Cognitive, and Economic Debates", "author": "Burton G. Malkiel", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Finance", "slug": "Behavioral-Finance-Malkiel"},
    {"title": "Advances in Behavioral Finance", "author": "Richard H. Thaler", "first_published": "1993", "latest_published": "2005", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Behavioral Finance", "slug": "Advances-in-Behavioral-Finance"},

    # LEVEL 4: Market Psychology (5 books)
    {"title": "Irrational Exuberance", "author": "Robert J. Shiller", "first_published": "2000", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Psychology", "slug": "Irrational-Exuberance"},
    {"title": "Animal Spirits: How Human Psychology Drives the Economy, and Why It Matters for Global Capitalism", "author": "George A. Akerlof; Robert J. Shiller", "first_published": "2009", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Psychology", "slug": "Animal-Spirits"},
    {"title": "Narrative Economics: How Stories Go Viral and Drive Major Economic Events", "author": "Robert J. Shiller", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Psychology", "slug": "Narrative-Economics"},
    {"title": "Phishing for Phools: The Economics of Manipulation and Deception", "author": "George A. Akerlof; Robert J. Shiller", "first_published": "2015", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Psychology", "slug": "Phishing-for-Phools"},
    {"title": "How I Invest My Money: Finance Professionals Reveal How They Save, Spend, and Invest", "author": "Joshua Brown; Brian Portnoy", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Psychology", "slug": "How-I-Invest-My-Money"},

    # LEVEL 4: Bubbles & Crashes (5 books)
    {"title": "Manias, Panics, and Crashes: A History of Financial Crises", "author": "Charles P. Kindleberger; Robert Z. Aliber", "first_published": "1978", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bubbles & Crashes", "slug": "Manias-Panics-and-Crashes"},
    {"title": "This Time Is Different: Eight Centuries of Financial Folly", "author": "Carmen M. Reinhart; Kenneth S. Rogoff", "first_published": "2009", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bubbles & Crashes", "slug": "This-Time-Is-Different"},
    {"title": "Devil Take the Hindmost: A History of Financial Speculation", "author": "Edward Chancellor", "first_published": "1999", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bubbles & Crashes", "slug": "Devil-Take-the-Hindmost"},
    {"title": "The Price of Time: The Real Story of Interest", "author": "Edward Chancellor", "first_published": "2022", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bubbles & Crashes", "slug": "The-Price-of-Time"},
    {"title": "When Genius Failed: The Rise and Fall of Long-Term Capital Management", "author": "Roger Lowenstein", "first_published": "2000", "latest_published": "2001", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bubbles & Crashes", "slug": "When-Genius-Failed"},

    # LEVEL 4: Investment Decision Errors (5 books)
    {"title": "Why Smart People Make Big Money Mistakes and How to Correct Them", "author": "Gary Belsky; Thomas Gilovich", "first_published": "1999", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Investment Decision Errors", "slug": "Why-Smart-People-Make-Big-Money-Mistakes"},
    {"title": "Your Money and Your Brain: How the New Science of Neuroeconomics Can Help Make You Rich", "author": "Jason Zweig", "first_published": "2007", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Investment Decision Errors", "slug": "Your-Money-and-Your-Brain"},
    {"title": "The Little Book of Behavioral Investing: How Not to Be Your Own Worst Enemy", "author": "James Montier", "first_published": "2010", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Investment Decision Errors", "slug": "The-Little-Book-of-Behavioral-Investing"},
    {"title": "Behavioural Investing: A Practitioner's Guide to Applying Behavioural Finance", "author": "James Montier", "first_published": "2007", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Investment Decision Errors", "slug": "Behavioural-Investing-Montier"},
    {"title": "What Investors Really Want: Discover What Drives Investor Behavior and Make Smarter Financial Decisions", "author": "Meir Statman", "first_published": "2010", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Investment Decision Errors", "slug": "What-Investors-Really-Want"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 03. EQUITY & BUSINESS INVESTING (45 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: VALUE INVESTING (15 books)
    # LEVEL 4: Value Principles (5 books)
    {"title": "The Intelligent Investor: The Definitive Book on Value Investing", "author": "Benjamin Graham", "first_published": "1949", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Value Principles", "slug": "The-Intelligent-Investor"},
    {"title": "Security Analysis: Principles and Technique", "author": "Benjamin Graham; David L. Dodd", "first_published": "1934", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Value Principles", "slug": "Security-Analysis"},
    {"title": "The Essays of Warren Buffett: Lessons for Corporate America", "author": "Warren E. Buffett; Lawrence A. Cunningham", "first_published": "1997", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Value Principles", "slug": "The-Essays-of-Warren-Buffett"},
    {"title": "Value Investing: From Graham to Buffett and Beyond", "author": "Bruce C.N. Greenwald; Judd Kahn; Paul D. Sonkin", "first_published": "2001", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Value Principles", "slug": "Value-Investing-Greenwald"},
    {"title": "The Dhandho Investor: The Low-Risk Value Method to High Returns", "author": "Mohnish Pabrai", "first_published": "2007", "latest_published": "2007", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Value Principles", "slug": "The-Dhandho-Investor"},

    # LEVEL 4: Business Analysis (5 books)
    {"title": "Common Stocks and Uncommon Profits and Other Writings", "author": "Philip A. Fisher", "first_published": "1958", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Analysis", "slug": "Common-Stocks-and-Uncommon-Profits"},
    {"title": "One Up On Wall Street: How to Use What You Already Know to Make Money in the Market", "author": "Peter Lynch; John Rothchild", "first_published": "1989", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Analysis", "slug": "One-Up-On-Wall-Street"},
    {"title": "Beating the Street", "author": "Peter Lynch; John Rothchild", "first_published": "1993", "latest_published": "1994", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Analysis", "slug": "Beating-the-Street"},
    {"title": "Learn to Earn: A Beginner's Guide to the Basics of Investing and Business", "author": "Peter Lynch; John Rothchild", "first_published": "1995", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Analysis", "slug": "Learn-to-Earn"},
    {"title": "Quality Investing: Owning the Best Companies for the Long Term", "author": "Lawrence A. Cunningham; Torkell T. Eide; Patrick Hargreaves", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Business Analysis", "slug": "Quality-Investing"},

    # LEVEL 4: Margin of Safety (5 books)
    {"title": "Margin of Safety: Risk-Averse Value Investing Strategies for the Thoughtful Investor", "author": "Seth A. Klarman", "first_published": "1991", "latest_published": "1991", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Margin of Safety", "slug": "Margin-of-Safety"},
    {"title": "The Little Book That Beats the Market", "author": "Joel Greenblatt", "first_published": "2005", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Margin of Safety", "slug": "The-Little-Book-That-Beats-the-Market"},
    {"title": "You Can Be a Stock Market Genius: Uncover the Secret Hiding Places of Stock Market Profits", "author": "Joel Greenblatt", "first_published": "1997", "latest_published": "1999", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Margin of Safety", "slug": "You-Can-Be-a-Stock-Market-Genius"},
    {"title": "The Big Secret for the Small Investor: A New Route to Long-Term Investment Success", "author": "Joel Greenblatt", "first_published": "2011", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Margin of Safety", "slug": "The-Big-Secret-for-the-Small-Investor"},
    {"title": "Deep Value: Why Activist Investors and Other Contrarians Battle for Control of Losing Corporations", "author": "Tobias E. Carlisle", "first_published": "2014", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Margin of Safety", "slug": "Deep-Value"},

    # LEVEL 3: COMPANY ANALYSIS (15 books)
    # LEVEL 4: Financial Statements (5 books)
    {"title": "Financial Intelligence: A Manager's Guide to Knowing What the Numbers Really Mean", "author": "Karen Berman; Joe Knight; John Case", "first_published": "2006", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Statements", "slug": "Financial-Intelligence"},
    {"title": "Warren Buffett and the Interpretation of Financial Statements", "author": "Mary Buffett; David Clark", "first_published": "2008", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Statements", "slug": "Warren-Buffett-and-the-Interpretation-of-Financial-Statements"},
    {"title": "Financial Shenanigans: How to Detect Accounting Gimmicks & Fraud in Financial Reports", "author": "Howard M. Schilit; Jeremy Perler; Yoni Engelhart", "first_published": "1993", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Statements", "slug": "Financial-Shenanigans"},
    {"title": "How to Read a Financial Report: Wringing Vital Signs Out of the Numbers", "author": "John A. Tracy; Tage C. Tracy", "first_published": "1979", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Statements", "slug": "How-to-Read-a-Financial-Report"},
    {"title": "The Interpretation of Financial Statements", "author": "Benjamin Graham; Spencer B. Meredith", "first_published": "1937", "latest_published": "1998", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Statements", "slug": "The-Interpretation-of-Financial-Statements"},

    # LEVEL 4: Competitive Advantage (5 books)
    {"title": "Competitive Advantage: Creating and Sustaining Superior Performance", "author": "Michael E. Porter", "first_published": "1985", "latest_published": "1998", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competitive Advantage", "slug": "Competitive-Advantage"},
    {"title": "Competitive Strategy: Techniques for Analyzing Industries and Competitors", "author": "Michael E. Porter", "first_published": "1980", "latest_published": "1998", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competitive Advantage", "slug": "Competitive-Strategy"},
    {"title": "The Little Book That Builds Wealth: The Knockout Formula for Finding Great Investments", "author": "Pat Dorsey", "first_published": "2008", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competitive Advantage", "slug": "The-Little-Book-That-Builds-Wealth"},
    {"title": "7 Powers: The Foundations of Business Strategy", "author": "Hamilton Helmer", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competitive Advantage", "slug": "7-Powers"},
    {"title": "Understanding Michael Porter: The Essential Guide to Competition and Strategy", "author": "Joan Magretta", "first_published": "2011", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Competitive Advantage", "slug": "Understanding-Michael-Porter"},

    # LEVEL 4: Management & Capital Allocation (5 books)
    {"title": "The Outsiders: Eight Unconventional CEOs and Their Radically Rational Blueprint for Success", "author": "William N. Thorndike Jr.", "first_published": "2012", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Management & Capital Allocation", "slug": "The-Outsiders-Thorndike"},
    {"title": "Dear Chairman: Boardroom Battles and the Rise of Shareholder Activism", "author": "Jeff Gramm", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Management & Capital Allocation", "slug": "Dear-Chairman"},
    {"title": "Capital Allocation: Principles, Strategies, and Processes for Creating Long-Term Shareholder Value", "author": "David Giroux", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Management & Capital Allocation", "slug": "Capital-Allocation-Giroux"},
    {"title": "Excess Returns: A Comparative Study of the Methods of the World's Greatest Investors", "author": "Frederik Vanhaverbeke", "first_published": "2014", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Management & Capital Allocation", "slug": "Excess-Returns"},
    {"title": "Richer, Wiser, Happier: How the World's Greatest Investors Win in Markets and Life", "author": "William Green", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Management & Capital Allocation", "slug": "Richer-Wiser-Happier"},

    # LEVEL 3: MARKET THINKING (15 books)
    # LEVEL 4: Market Efficiency (5 books)
    {"title": "Efficient Capital Markets: A Review of Theory and Empirical Work", "author": "Eugene F. Fama", "first_published": "1970", "latest_published": "1991", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Efficiency", "slug": "Efficient-Capital-Markets-Fama"},
    {"title": "Inefficient Markets: An Introduction to Behavioral Finance", "author": "Andrei Shleifer", "first_published": "2000", "latest_published": "2000", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Efficiency", "slug": "Inefficient-Markets-Shleifer"},
    {"title": "The Myth of the Rational Market: A History of Risk, Reward, and Delusion on Wall Street", "author": "Justin Fox", "first_published": "2009", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Efficiency", "slug": "The-Myth-of-the-Rational-Market"},
    {"title": "Market Wizards: Interviews with Top Traders", "author": "Jack D. Schwager", "first_published": "1989", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Efficiency", "slug": "Market-Wizards"},
    {"title": "The New Market Wizards: Conversations with America's Top Traders", "author": "Jack D. Schwager", "first_published": "1992", "latest_published": "2008", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Efficiency", "slug": "The-New-Market-Wizards"},

    # LEVEL 4: Market Cycles (5 books)
    {"title": "Principles for Navigating Big Debt Crises", "author": "Ray Dalio", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Cycles", "slug": "Principles-for-Navigating-Big-Debt-Crises"},
    {"title": "Principles for Dealing with the Changing World Order: Why Nations Succeed and Fail", "author": "Ray Dalio", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Cycles", "slug": "Principles-for-Dealing-with-the-Changing-World-Order"},
    {"title": "The Alchemy of Finance", "author": "George Soros", "first_published": "1987", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Cycles", "slug": "The-Alchemy-of-Finance"},
    {"title": "Soros on Soros: Staying Ahead of the Curve", "author": "George Soros; Byron Wien; Krisztina Koenen", "first_published": "1995", "latest_published": "1995", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Cycles", "slug": "Soros-on-Soros"},
    {"title": "My Investment Technique: Who Does the Market Smile Upon?", "author": "Tatsuro Kiyohara", "first_published": "2024", "latest_published": "2024", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Market Cycles", "slug": "My-Investment-Technique-Kiyohara"},

    # LEVEL 4: Long-Term Compounding (5 books)
    {"title": "100 Baggers: Stocks That Return 100-to-1 and How to Find Them", "author": "Christopher Mayer", "first_published": "2015", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Compounding", "slug": "100-Baggers"},
    {"title": "100 to 1 in the Stock Market: A Distinguished Security Analyst Tells How to Make More of Your Investment Opportunities", "author": "Thomas William Phelps", "first_published": "1972", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Compounding", "slug": "100-to-1-in-the-Stock-Market"},
    {"title": "Invested: How Warren Buffett and Charlie Munger Taught Me to Master My Mind, My Emotions, and My Money", "author": "Danielle Town; Phil Town", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Compounding", "slug": "Invested-Town"},
    {"title": "Rule #1: The Simple Strategy for Successful Investing in Only 15 Minutes a Week", "author": "Phil Town", "first_published": "2006", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Compounding", "slug": "Rule-1-Phil-Town"},
    {"title": "Payback Time: Making Big Money Is the Best Revenge!", "author": "Phil Town", "first_published": "2010", "latest_published": "2010", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Compounding", "slug": "Payback-Time-Phil-Town"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 04. FINANCIAL MARKETS & ASSETS (40 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: FIXED INCOME (10 books)
    # LEVEL 4: Bonds & Interest Rates (5 books)
    {"title": "The Bond Book: Everything Investors Need to Know About Treasuries, Municipals, GNMAs, Corporates, Zeros, Bond Funds, and More", "author": "Annette Thau", "first_published": "1992", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bonds & Interest Rates", "slug": "The-Bond-Book"},
    {"title": "Handbook of Fixed Income Securities", "author": "Frank J. Fabozzi", "first_published": "1983", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bonds & Interest Rates", "slug": "Handbook-of-Fixed-Income-Securities"},
    {"title": "Fixed Income Analysis", "author": "Barbara S. Petitt; Jerald E. Pinto; Wendy L. Pirie", "first_published": "2000", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bonds & Interest Rates", "slug": "Fixed-Income-Analysis-CFA"},
    {"title": "Interest Rate Markets: A Practical Approach to Fixed Income", "author": "Siddhartha Jha", "first_published": "2011", "latest_published": "2011", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bonds & Interest Rates", "slug": "Interest-Rate-Markets-Jha"},
    {"title": "Inside the Yield Book: The Classic Foundation of Runaway Fixed Income Portfolio Returns", "author": "Sidney Homer; Martin L. Leibowitz", "first_published": "1972", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Bonds & Interest Rates", "slug": "Inside-the-Yield-Book"},

    # LEVEL 4: Credit Markets (5 books)
    {"title": "Corporate Credit Analysis", "author": "Brian Coyle", "first_published": "2000", "latest_published": "2004", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Credit Markets", "slug": "Corporate-Credit-Analysis"},
    {"title": "Credit Risk Management: Basic Concepts", "author": "Tony Van Gestel; Bart Baesens", "first_published": "2008", "latest_published": "2009", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Credit Markets", "slug": "Credit-Risk-Management"},
    {"title": "Distressed Debt Analysis: Strategies for Speculative Investors", "author": "Stephen G. Moyer", "first_published": "2004", "latest_published": "2005", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Credit Markets", "slug": "Distressed-Debt-Analysis"},
    {"title": "Creating Value Through Corporate Restructuring: Case Studies in Bankruptcies, Buyouts, and Breakups", "author": "Stuart C. Gilson", "first_published": "2001", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Credit Markets", "slug": "Creating-Value-Through-Corporate-Restructuring"},
    {"title": "Corporate Financial Distress, Restructuring, and Bankruptcy", "author": "Edward I. Altman; Edith Hotchkiss; Wei Wang", "first_published": "1983", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Credit Markets", "slug": "Corporate-Financial-Distress-Altman"},

    # LEVEL 3: REAL ASSETS (10 books)
    # LEVEL 4: Real Estate (5 books)
    {"title": "The Book on Rental Property Investing: How to Create Wealth and Passive Income Through Smart Buy & Hold Real Estate Investing", "author": "Brandon Turner", "first_published": "2015", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Real Estate", "slug": "The-Book-on-Rental-Property-Investing"},
    {"title": "The Millionaire Real Estate Investor", "author": "Gary Keller; Dave Jenks; Jay Papasan", "first_published": "2005", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Real Estate", "slug": "The-Millionaire-Real-Estate-Investor"},
    {"title": "What Every Real Estate Investor Needs to Know About Cash Flow... And 36 Other Key Financial Measures", "author": "Frank Gallinelli", "first_published": "2004", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Real Estate", "slug": "What-Every-Real-Estate-Investor-Needs-to-Know"},
    {"title": "Real Estate Finance and Investments", "author": "William B. Brueggeman; Jeffrey D. Fisher", "first_published": "1970", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Real Estate", "slug": "Real-Estate-Finance-and-Investments"},
    {"title": "Long-Distance Real Estate Investing: How to Buy, Rehab, and Manage Out-of-State Rental Properties", "author": "David Greene", "first_published": "2017", "latest_published": "2017", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Real Estate", "slug": "Long-Distance-Real-Estate-Investing"},

    # LEVEL 4: Commodities & Gold (5 books)
    {"title": "The World for Sale: Money, Power, and the Traders Who Barter the Earth's Resources", "author": "Javier Blas; Jack Farchy", "first_published": "2021", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Commodities & Gold", "slug": "The-World-for-Sale"},
    {"title": "Hot Commodities: How Anyone Can Invest Profitably in the World's Best Market", "author": "Jim Rogers", "first_published": "2004", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Commodities & Gold", "slug": "Hot-Commodities"},
    {"title": "The King of Oil: The Secret Lives of Marc Rich", "author": "Daniel Ammann", "first_published": "2009", "latest_published": "2010", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Commodities & Gold", "slug": "The-King-of-Oil"},
    {"title": "The Power of Gold: The History of an Obsession", "author": "Peter L. Bernstein", "first_published": "2000", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Commodities & Gold", "slug": "The-Power-of-Gold"},
    {"title": "The Prize: The Epic Quest for Oil, Money, and Power", "author": "Daniel Yergin", "first_published": "1991", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Commodities & Gold", "slug": "The-Prize"},

    # LEVEL 3: ALTERNATIVE FINANCE (10 books)
    # LEVEL 4: Private Markets (5 books)
    {"title": "The Power Law: Venture Capital and the Art of Disruption", "author": "Sebastian Mallaby", "first_published": "2022", "latest_published": "2023", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Private Markets", "slug": "The-Power-Law-Mallaby"},
    {"title": "Secrets of Sand Hill Road: Venture Capital and How to Get It", "author": "Scott Kupor", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Private Markets", "slug": "Secrets-of-Sand-Hill-Road"},
    {"title": "Venture Deals: Be Smarter Than Your Lawyer and Venture Capitalist", "author": "Brad Feld; Jason Mendelson", "first_published": "2011", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Private Markets", "slug": "Venture-Deals"},
    {"title": "King of Capital: The Remarkable Rise, Fall, and Rise Again of Steve Schwarzman and Blackstone", "author": "David Carey; John E. Morris", "first_published": "2010", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Private Markets", "slug": "King-of-Capital"},
    {"title": "Barbarians at the Gate: The Fall of RJR Nabisco", "author": "Bryan Burrough; John Helyar", "first_published": "1989", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Private Markets", "slug": "Barbarians-at-the-Gate"},

    # LEVEL 4: Alternative Investments (5 books)
    {"title": "More Money Than God: Hedge Funds and the Making of a New Elite", "author": "Sebastian Mallaby", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Alternative Investments", "slug": "More-Money-Than-God"},
    {"title": "The Man Who Solved the Market: How Jim Simons Launched the Quant Revolution", "author": "Gregory Zuckerman", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Alternative Investments", "slug": "The-Man-Who-Solved-the-Market"},
    {"title": "The Quants: How a New Breed of Math Whizzes Conquered Wall Street and Nearly Destroyed It", "author": "Scott Patterson", "first_published": "2010", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Alternative Investments", "slug": "The-Quants"},
    {"title": "Dark Pools: High-Speed Traders, A.I. Bandits, and the Threat to the Global Financial System", "author": "Scott Patterson", "first_published": "2012", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Alternative Investments", "slug": "Dark-Pools"},
    {"title": "Flash Boys: A Wall Street Revolt", "author": "Michael Lewis", "first_published": "2014", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Alternative Investments", "slug": "Flash-Boys"},

    # LEVEL 3: MARKET HISTORY (10 books)
    # LEVEL 4: Financial Crises (5 books)
    {"title": "Too Big to Fail: The Inside Story of How Wall Street and Washington Fought to Save the Financial System—and Themselves", "author": "Andrew Ross Sorkin", "first_published": "2009", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Crises", "slug": "Too-Big-to-Fail"},
    {"title": "The Big Short: Inside the Doomsday Machine", "author": "Michael Lewis", "first_published": "2010", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Crises", "slug": "The-Big-Short"},
    {"title": "Liar's Poker: Rising Through the Wreckage on Wall Street", "author": "Michael Lewis", "first_published": "1989", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Crises", "slug": "Liars-Poker"},
    {"title": "Crashed: How a Decade of Financial Crises Changed the World", "author": "Adam Tooze", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Crises", "slug": "Crashed-Tooze"},
    {"title": "The Great Crash 1929", "author": "John Kenneth Galbraith", "first_published": "1954", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Financial Crises", "slug": "The-Great-Crash-1929"},

    # LEVEL 4: History of Markets (5 books)
    {"title": "The Ascent of Money: A Financial History of the World", "author": "Niall Ferguson", "first_published": "2008", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Markets", "slug": "The-Ascent-of-Money"},
    {"title": "The House of Morgan: An American Banking Dynasty and the Rise of Modern Finance", "author": "Ron Chernow", "first_published": "1990", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Markets", "slug": "The-House-of-Morgan"},
    {"title": "The House of Rothschild: Money's Prophets 1798-1848", "author": "Niall Ferguson", "first_published": "1998", "latest_published": "1999", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Markets", "slug": "The-House-of-Rothschild"},
    {"title": "Lords of Finance: The Bankers Who Broke the World", "author": "Liaquat Ahamed", "first_published": "2009", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Markets", "slug": "Lords-of-Finance"},
    {"title": "A History of Interest Rates", "author": "Sidney Homer; Richard Sylla", "first_published": "1963", "latest_published": "2005", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "History of Markets", "slug": "A-History-of-Interest-Rates"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 05. WEALTH CREATION (35 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: INCOME (10 books)
    # LEVEL 4: Career Income (5 books)
    {"title": "The Millionaire Fastlane: Crack the Code to Wealth and Live Rich for a Lifetime", "author": "M.J. DeMarco", "first_published": "2011", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Career Income", "slug": "The-Millionaire-Fastlane"},
    {"title": "UNSCRIPTED: Life, Liberty, and the Pursuit of Entrepreneurship", "author": "M.J. DeMarco", "first_published": "2017", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Career Income", "slug": "UNSCRIPTED-DeMarco"},
    {"title": "The Great Rat Race Escape: From Wage Slavery to Wealth", "author": "M.J. DeMarco", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Career Income", "slug": "The-Great-Rat-Race-Escape"},
    {"title": "The Almanack of Naval Ravikant: A Guide to Wealth and Happiness", "author": "Eric Jorgenson; Naval Ravikant", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Career Income", "slug": "The-Almanack-of-Naval-Ravikant"},
    {"title": "The Personal MBA: Master the Art of Business", "author": "Josh Kaufman", "first_published": "2010", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Career Income", "slug": "The-Personal-MBA"},

    # LEVEL 4: Multiple Income Streams (5 books)
    {"title": "Multiple Streams of Income: How to Generate a Lifetime of Unlimited Wealth", "author": "Robert G. Allen", "first_published": "2000", "latest_published": "2005", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Multiple Income Streams", "slug": "Multiple-Streams-of-Income"},
    {"title": "Side Hustle: From Idea to Income in 27 Days", "author": "Chris Guillebeau", "first_published": "2017", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Multiple Income Streams", "slug": "Side-Hustle-Guillebeau"},
    {"title": "The $100 Startup: Reinvent the Way You Make a Living, Do What You Love, and Create a New Future", "author": "Chris Guillebeau", "first_published": "2012", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Multiple Income Streams", "slug": "The-100-Startup"},
    {"title": "Company of One: Why Staying Small Is the Next Big Thing for Business", "author": "Paul Jarvis", "first_published": "2019", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Multiple Income Streams", "slug": "Company-of-One"},
    {"title": "The Minimalist Entrepreneur: How Great Founders Do More with Less", "author": "Sahil Lavingia", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Multiple Income Streams", "slug": "The-Minimalist-Entrepreneur"},

    # LEVEL 3: OWNERSHIP (10 books)
    # LEVEL 4: Equity & Ownership (5 books)
    {"title": "Zero to One: Notes on Startups, or How to Build the Future", "author": "Peter Thiel; Blake Masters", "first_published": "2014", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Equity & Ownership", "slug": "Zero-to-One"},
    {"title": "The Hard Thing About Hard Things: Building a Business When There Are No Easy Answers", "author": "Ben Horowitz", "first_published": "2014", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Equity & Ownership", "slug": "The-Hard-Thing-About-Hard-Things"},
    {"title": "What It Takes: Lessons in the Pursuit of Excellence", "author": "Stephen A. Schwarzman", "first_published": "2019", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Equity & Ownership", "slug": "What-It-Takes-Schwarzman"},
    {"title": "Shoe Dog: A Memoir by the Creator of Nike", "author": "Phil Knight", "first_published": "2016", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Equity & Ownership", "slug": "Shoe-Dog"},
    {"title": "The Snowball: Warren Buffett and the Business of Life", "author": "Alice Schroeder", "first_published": "2008", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Equity & Ownership", "slug": "The-Snowball"},

    # LEVEL 4: Building Assets (5 books)
    {"title": "Buy Then Build: How Acquisition Entrepreneurs Outsmart the Startup Game", "author": "Walker Deibel", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Assets", "slug": "Buy-Then-Build"},
    {"title": "HBR Guide to Buying a Small Business: Think Big, Buy Small, Own Your Own Company", "author": "Richard S. Ruback; Royce Yudkoff", "first_published": "2017", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Assets", "slug": "HBR-Guide-to-Buying-a-Small-Business"},
    {"title": "Built to Sell: Creating a Business That Can Thrive Without You", "author": "John Warrillow", "first_published": "2010", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Assets", "slug": "Built-to-Sell"},
    {"title": "The Automatic Customer: Creating a Subscription Business in Any Industry", "author": "John Warrillow", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Assets", "slug": "The-Automatic-Customer"},
    {"title": "The Art of Selling Your Business: Winning Strategies & Secret Hacks for Exiting on Top", "author": "John Warrillow", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Building Assets", "slug": "The-Art-of-Selling-Your-Business"},

    # LEVEL 3: LONG-TERM WEALTH (15 books)
    # LEVEL 4: Compounding (5 books)
    {"title": "The Art of Invisibility: The World's Most Famous Hacker Teaches You How to Be Safe in the Age of Big Brother and Big Data", "author": "Kevin Mitnick; Robert Vamosi", "first_published": "2017", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Compounding", "slug": "The-Art-of-Invisibility"},
    {"title": "The Joys of Compounding: The Passionate Pursuit of Lifelong Learning, Investing, and Living", "author": "Gautam Baid", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Compounding", "slug": "The-Joys-of-Compounding"},
    {"title": "The Education of a Value Investor: My Transformative Quest for Wealth, Wisdom, and Enlightenment", "author": "Guy Spier", "first_published": "2014", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Compounding", "slug": "The-Education-of-a-Value-Investor"},
    {"title": "Investing for Growth: How to Make Money by Investing in Only the Best Companies", "author": "Terry Smith", "first_published": "2020", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Compounding", "slug": "Investing-for-Growth-Terry-Smith"},
    {"title": "The Sacred Truths of Investing: Finding Stocks That Will Make You Rich", "author": "Louis Navellier", "first_published": "2025", "latest_published": "2025", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Compounding", "slug": "The-Sacred-Truths-of-Investing"},

    # LEVEL 4: Intergenerational Wealth (5 books)
    {"title": "Family Wealth: Keeping It in the Family—How Family Systems and Family Governance Ensure Multigenerational Success", "author": "James E. Hughes Jr.", "first_published": "1997", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intergenerational Wealth", "slug": "Family-Wealth-Hughes"},
    {"title": "Complete Family Wealth: Wealth as Well-Being", "author": "James E. Hughes Jr.; Susan E. Massenzio; Keith Whitaker", "first_published": "2017", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intergenerational Wealth", "slug": "Complete-Family-Wealth"},
    {"title": "Wealth in Families", "author": "Charles W. Collier", "first_published": "2003", "latest_published": "2006", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intergenerational Wealth", "slug": "Wealth-in-Families"},
    {"title": "Borrowed Intellect: Strategic Philanthropy and Dynasty", "author": "Peter Karoff", "first_published": "2012", "latest_published": "2012", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intergenerational Wealth", "slug": "Borrowed-Intellect"},
    {"title": "Family Business: Governance and Succession", "author": "Ernesto J. Poza", "first_published": "2003", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Intergenerational Wealth", "slug": "Family-Business-Poza"},

    # LEVEL 4: Capital Preservation (5 books)
    {"title": "Safe Haven: Investing for Financial Storms", "author": "Mark Spitznagel", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Capital Preservation", "slug": "Safe-Haven-Spitznagel"},
    {"title": "The Dao of Capital: Austrian Investing in a Distorted World", "author": "Mark Spitznagel", "first_published": "2013", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Capital Preservation", "slug": "The-Dao-of-Capital"},
    {"title": "The Permanent Portfolio: Harry Browne's Long-Term Investment Strategy", "author": "Craig Rowland; J. M. Lawson", "first_published": "2012", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Capital Preservation", "slug": "The-Permanent-Portfolio"},
    {"title": "Fail-Safe Investing: Lifelong Financial Security in 30 Minutes", "author": "Harry Browne", "first_published": "1999", "latest_published": "1999", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Capital Preservation", "slug": "Fail-Safe-Investing"},
    {"title": "In This Economy? How Money and Markets Really Work", "author": "Kyla Scanlon", "first_published": "2024", "latest_published": "2025", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Capital Preservation", "slug": "In-This-Economy-Scanlon"},
]
