from __future__ import annotations

# Domain 04: Personal Development & Life Skills (110 books: #0491–#0600)
BOOKS_04 = [
    # -------------------------------------------------------------------------
    # LEVEL 2: 01. SELF-DEVELOPMENT (30 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: SELF-AWARENESS (10 books)
    # LEVEL 4: Strengths & Weaknesses (5 books)
    {"title": "StrengthsFinder 2.0", "author": "Tom Rath", "first_published": "2007", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strengths & Weaknesses", "slug": "StrengthsFinder-2-0"},
    {"title": "Now, Discover Your Strengths", "author": "Marcus Buckingham; Donald O. Clifton", "first_published": "2001", "latest_published": "2005", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strengths & Weaknesses", "slug": "Now-Discover-Your-Strengths"},
    {"title": "StandOut 2.0: Assess Your Strengths, Find Your Edge, Win at Work", "author": "Marcus Buckingham", "first_published": "2015", "latest_published": "2015", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strengths & Weaknesses", "slug": "StandOut-2-0"},
    {"title": "What You're Good At", "author": "Richard Leider", "first_published": "2010", "latest_published": "2010", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strengths & Weaknesses", "slug": "What-Youre-Good-At"},
    {"title": "Know Your Strengths and Be Confident", "author": "Patrick Lencioni", "first_published": "2016", "latest_published": "2016", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Strengths & Weaknesses", "slug": "Know-Your-Strengths"},

    # LEVEL 4: Personal Reflection (5 books)
    {"title": "The Daily Stoic: 366 Meditations on Wisdom, Perseverance, and the Art of Living", "author": "Ryan Holiday; Stephen Hanselman", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Reflection", "slug": "The-Daily-Stoic-Holiday"},
    {"title": "Letters from a Stoic", "author": "Seneca", "first_published": "65", "latest_published": "2015", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Reflection", "slug": "Letters-from-a-Stoic"},
    {"title": "Essays", "author": "Michel de Montaigne", "first_published": "1580", "latest_published": "2003", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Reflection", "slug": "Essays-Montaigne"},
    {"title": "Walden", "author": "Henry David Thoreau", "first_published": "1854", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Reflection", "slug": "Walden"},
    {"title": "The Examined Life: Philosophical Meditations", "author": "Robert Nozick", "first_published": "1989", "latest_published": "1990", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Reflection", "slug": "The-Examined-Life-Nozick"},

    # LEVEL 3: IDENTITY & VALUES (10 books)
    # LEVEL 4: Personal Values (5 books)
    {"title": "Man's Search for Meaning", "author": "Viktor E. Frankl", "first_published": "1946", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Values", "slug": "Mans-Search-for-Meaning"},
    {"title": "Principles: Life and Work", "author": "Ray Dalio", "first_published": "2017", "latest_published": "2017", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Values", "slug": "Principles-Life-and-Work"},
    {"title": "The Road to Character", "author": "David Brooks", "first_published": "2015", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Values", "slug": "The-Road-to-Character"},
    {"title": "The Second Mountain: The Quest for a Moral Life", "author": "David Brooks", "first_published": "2019", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Values", "slug": "The-Second-Mountain"},
    {"title": "Living an Examined Life: Wisdom for the Second Half of the Journey", "author": "James Hollis", "first_published": "2018", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Values", "slug": "Living-an-Examined-Life"},

    # LEVEL 4: Personal Direction (5 books)
    {"title": "Start with Why: How Great Leaders Inspire Everyone to Take Action", "author": "Simon Sinek", "first_published": "2009", "latest_published": "2011", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Direction", "slug": "Start-with-Why"},
    {"title": "Find Your Why: A Practical Guide for Discovering Purpose for You and Your Team", "author": "Simon Sinek; David Mead; Peter Docker", "first_published": "2017", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Direction", "slug": "Find-Your-Why"},
    {"title": "The Crossroads of Should and Must: Find and Follow Your Passion", "author": "Elle Luna", "first_published": "2015", "latest_published": "2015", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Direction", "slug": "The-Crossroads-of-Should-and-Must"},
    {"title": "The Element: How Finding Your Passion Changes Everything", "author": "Ken Robinson; Lou Aronica", "first_published": "2009", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Direction", "slug": "The-Element"},
    {"title": "Mastery", "author": "George Leonard", "first_published": "1992", "latest_published": "1992", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Direction", "slug": "Mastery-Leonard-Path"},

    # LEVEL 3: GROWTH (10 books)
    # LEVEL 4: Growth Mindset (5 books)
    {"title": "Mindset: The New Psychology of Success", "author": "Carol S. Dweck", "first_published": "2006", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Growth Mindset", "slug": "Mindset-Dweck"},
    {"title": "Mathematical Mindsets: Unleashing Students' Potential through Creative Math, Inspiring Messages and Innovative Teaching", "author": "Jo Boaler", "first_published": "2015", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Growth Mindset", "slug": "Mathematical-Mindsets"},
    {"title": "Limitless Mind: Learn, Lead, and Live Without Barriers", "author": "Jo Boaler", "first_published": "2019", "latest_published": "2019", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Growth Mindset", "slug": "Limitless-Mind-Boaler"},
    {"title": "The Growth Mindset Coach", "author": "Annie Brock; Heather Hundley", "first_published": "2016", "latest_published": "2016", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Growth Mindset", "slug": "The-Growth-Mindset-Coach"},
    {"title": "Smarter Faster Better: The Transformative Power of Real Productivity", "author": "Charles Duhigg", "first_published": "2016", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Growth Mindset", "slug": "Smarter-Faster-Better"},

    # LEVEL 4: Adaptation & Reinvention (5 books)
    {"title": "Adapt: Why Success Always Starts with Failure", "author": "Tim Harford", "first_published": "2011", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Adaptation & Reinvention", "slug": "Adapt-Harford"},
    {"title": "Reinventing You: Define Your Brand, Imagine Your Future", "author": "Dorie Clark", "first_published": "2013", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Adaptation & Reinvention", "slug": "Reinventing-You"},
    {"title": "The Long Game: How to Be a Long-Term Thinker in a Short-Term World", "author": "Dorie Clark", "first_published": "2021", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Adaptation & Reinvention", "slug": "The-Long-Game-Clark"},
    {"title": "Stand Out: How to Find Your Breakthrough Idea and Build a Following Around It", "author": "Dorie Clark", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Adaptation & Reinvention", "slug": "Stand-Out-Clark"},
    {"title": "Who Moved My Cheese?: An A-Mazing Way to Deal with Change in Your Work and in Your Life", "author": "Spencer Johnson", "first_published": "1998", "latest_published": "2002", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Adaptation & Reinvention", "slug": "Who-Moved-My-Cheese"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 02. RESILIENCE (25 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: ADVERSITY (10 books)
    # LEVEL 4: Resilience (5 books)
    {"title": "Antifragile: Things That Gain from Disorder", "author": "Nassim Nicholas Taleb", "first_published": "2012", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Resilience", "slug": "Antifragile"},
    {"title": "Option B: Facing Adversity, Building Resilience, and Finding Joy", "author": "Sheryl Sandberg; Adam Grant", "first_published": "2017", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Resilience", "slug": "Option-B"},
    {"title": "Resilience: Hard-Won Wisdom for Living a Better Life", "author": "Eric Greitens", "first_published": "2015", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Resilience", "slug": "Resilience-Greitens"},
    {"title": "The Obstacle Is the Way: The Timeless Art of Turning Trials into Triumph", "author": "Ryan Holiday", "first_published": "2014", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Resilience", "slug": "The-Obstacle-Is-the-Way"},
    {"title": "Ego Is the Enemy", "author": "Ryan Holiday", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Resilience", "slug": "Ego-Is-the-Enemy"},

    # LEVEL 4: Recovery (5 books)
    {"title": "Can't Hurt Me: Master Your Mind and Defy the Odds", "author": "David Goggins", "first_published": "2018", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Recovery", "slug": "Cant-Hurt-Me"},
    {"title": "Never Finished: Unshackle Your Mind and Win the War Within", "author": "David Goggins", "first_published": "2022", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Recovery", "slug": "Never-Finished"},
    {"title": "Touching the Void: The True Story of One Man's Miraculous Survival", "author": "Joe Simpson", "first_published": "1988", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Recovery", "slug": "Touching-the-Void-Simpson"},
    {"title": "Unbroken: A World War II Story of Survival, Resilience, and Redemption", "author": "Laura Hillenbrand", "first_published": "2010", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Recovery", "slug": "Unbroken"},
    {"title": "Deep Survival: Who Lives, Who Dies, and Why", "author": "Laurence Gonzales", "first_published": "2003", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Recovery", "slug": "Deep-Survival"},

    # LEVEL 3: STRESS & PRESSURE (10 books)
    # LEVEL 4: Stress Management (5 books)
    {"title": "Why Zebras Don't Get Ulcers", "author": "Robert M. Sapolsky", "first_published": "1994", "latest_published": "2004", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Stress Management", "slug": "Why-Zebras-Dont-Get-Ulcers"},
    {"title": "The Upside of Stress: Why Stress Is Good for You, and How to Get Good at It", "author": "Kelly McGonigal", "first_published": "2015", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Stress Management", "slug": "The-Upside-of-Stress"},
    {"title": "Burnout: The Secret to Unlocking the Stress Cycle", "author": "Emily Nagoski; Amelia Nagoski", "first_published": "2019", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Stress Management", "slug": "Burnout-Nagoski"},
    {"title": "The Stress-Proof Brain: Master Your Emotional Response to Stress Using Mindfulness and Neuroplasticity", "author": "Melanie Greenberg", "first_published": "2017", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Stress Management", "slug": "The-Stress-Proof-Brain"},
    {"title": "Full Catastrophe Living: Using the Wisdom of Your Body and Mind to Face Stress, Pain, and Illness", "author": "Jon Kabat-Zinn", "first_published": "1990", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Stress Management", "slug": "Full-Catastrophe-Living"},

    # LEVEL 4: Pressure & Performance (5 books)
    {"title": "Performing Under Pressure: The Science of Doing Your Best When It Matters Most", "author": "Hendrie Weisinger; J.P. Pawliw-Fry", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pressure & Performance", "slug": "Performing-Under-Pressure"},
    {"title": "Clutch: Why Some People Excel Under Pressure and Others Don't", "author": "Paul Sullivan", "first_published": "2010", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pressure & Performance", "slug": "Clutch-Sullivan"},
    {"title": "The Pressure Principle: Handle Stress, Harness Energy, and Perform When It Counts", "author": "Dave Alred", "first_published": "2016", "latest_published": "2016", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pressure & Performance", "slug": "The-Pressure-Principle"},
    {"title": "10-Minute Toughness: The Mental Training Program for Winning Before the Game Begins", "author": "Jason Selk", "first_published": "2008", "latest_published": "2008", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pressure & Performance", "slug": "10-Minute-Toughness"},
    {"title": "Mind Gym: An Athlete's Guide to Inner Excellence", "author": "Gary Mack; David Casstevens", "first_published": "2001", "latest_published": "2002", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Pressure & Performance", "slug": "Mind-Gym"},

    # LEVEL 3: ADAPTABILITY (5 books)
    # LEVEL 4: Adapting to Change (5 books)
    {"title": "The Practice of Adaptive Leadership: Tools and Tactics for Changing Your Organization and the World", "author": "Ronald A. Heifetz; Alexander Grashow; Marty Linsky", "first_published": "2009", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Adapting to Change", "slug": "The-Practice-of-Adaptive-Leadership"},
    {"title": "Immunity to Change: How to Overcome It and Unlock the Potential in Yourself and Your Organization", "author": "Robert Kegan; Lisa Laskow Lahey", "first_published": "2009", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Adapting to Change", "slug": "Immunity-to-Change"},
    {"title": "An Everyone Culture: Becoming a Deliberately Developmental Organization", "author": "Robert Kegan; Lisa Laskow Lahey", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Adapting to Change", "slug": "An-Everyone-Culture"},
    {"title": "Change: How Organizations Achieve Hard-to-Imagine Results in Uncertain and Volatile Times", "author": "John P. Kotter; Vanessa Akhtar; Gaurav Gupta", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Adapting to Change", "slug": "Change-Kotter"},
    {"title": "Our Iceberg Is Melting: Changing and Succeeding Under Any Conditions", "author": "John P. Kotter; Holger Rathgeber", "first_published": "2005", "latest_published": "2016", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Adapting to Change", "slug": "Our-Iceberg-Is-Melting"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 03. MEANING & LIFE DESIGN (25 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: PURPOSE (10 books)
    # LEVEL 4: Meaning (5 books)
    {"title": "The Power of Meaning: Finding Fulfillment in a World Obsessed with Happiness", "author": "Emily Esfahani Smith", "first_published": "2017", "latest_published": "2018", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Meaning", "slug": "The-Power-of-Meaning"},
    {"title": "Ikigai: The Japanese Secret to a Long and Happy Life", "author": "Héctor García; Francesc Miralles", "first_published": "2016", "latest_published": "2017", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Meaning", "slug": "Ikigai"},
    {"title": "Life Is Tremendous", "author": "Charlie Tremendous Jones", "first_published": "1968", "latest_published": "1998", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Meaning", "slug": "Life-Is-Tremendous"},
    {"title": "The Anatomy of Hope: How People Prevail in the Face of Illness", "author": "Jerome Groopman", "first_published": "2004", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Meaning", "slug": "The-Anatomy-of-Hope-Groopman"},
    {"title": "A Year to Live: How to Live This Year as If It Were Your Last", "author": "Stephen Levine", "first_published": "1997", "latest_published": "1998", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Meaning", "slug": "A-Year-to-Live-Levine"},

    # LEVEL 4: Purpose (5 books)
    {"title": "The Purpose Driven Life: What on Earth Am I Here For?", "author": "Rick Warren", "first_published": "2002", "latest_published": "2012", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Purpose", "slug": "The-Purpose-Driven-Life"},
    {"title": "The Art of Work: A Proven Path to Discovering What You Were Meant to Do", "author": "Jeff Goins", "first_published": "2015", "latest_published": "2015", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Purpose", "slug": "The-Art-of-Work"},
    {"title": "Let Your Life Speak: Listening for the Voice of Vocation", "author": "Parker J. Palmer", "first_published": "1999", "latest_published": "2000", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Purpose", "slug": "Let-Your-Life-Speak"},
    {"title": "Callings: Finding and Following an Authentic Life", "author": "Gregg Levoy", "first_published": "1997", "latest_published": "1998", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Purpose", "slug": "Callings-Levoy"},
    {"title": "The On-Purpose Person: Making Your Life Make Sense", "author": "Kevin W. McCarthy", "first_published": "1992", "latest_published": "2009", "priority": "P3", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Purpose", "slug": "The-On-Purpose-Person"},

    # LEVEL 3: HAPPINESS & WELL-BEING (10 books)
    # LEVEL 4: Well-Being (5 books)
    {"title": "The Happiness Advantage: How a Positive Brain Fuels Success in Work and Life", "author": "Shawn Achor", "first_published": "2010", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Well-Being", "slug": "The-Happiness-Advantage"},
    {"title": "Before Happiness: The 5 Actionable Steps to Create a Positive Path to Success", "author": "Shawn Achor", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Well-Being", "slug": "Before-Happiness"},
    {"title": "Hardwiring Happiness: The New Brain Science of Contentment, Calm, and Confidence", "author": "Rick Hanson", "first_published": "2013", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Well-Being", "slug": "Hardwiring-Happiness"},
    {"title": "Buddha's Brain: The Practical Neuroscience of Happiness, Love, and Wisdom", "author": "Rick Hanson; Richard Mendius", "first_published": "2009", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Well-Being", "slug": "Buddhas-Brain"},
    {"title": "The Book of Joy: Lasting Happiness in a Changing World", "author": "Dalai Lama; Desmond Tutu; Douglas Abrams", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Well-Being", "slug": "The-Book-of-Joy"},

    # LEVEL 4: Flourishing (5 books)
    {"title": "Happier: Learn the Secrets to Daily Joy and Lasting Fulfillment", "author": "Tal Ben-Shahar", "first_published": "2007", "latest_published": "2008", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Flourishing", "slug": "Happier-Ben-Shahar"},
    {"title": "The Sweet Spot: The Pleasures of Suffering and the Search for Meaning", "author": "Paul Bloom", "first_published": "2021", "latest_published": "2022", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Flourishing", "slug": "The-Sweet-Spot-Bloom"},
    {"title": "Positivity: Top-Notch Research Reveals the 3 to 1 Ratio That Will Change Your Life", "author": "Barbara L. Fredrickson", "first_published": "2009", "latest_published": "2009", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Flourishing", "slug": "Positivity-Fredrickson"},
    {"title": "Love 2.0: Finding Happiness and Health in Moments of Connection", "author": "Barbara L. Fredrickson", "first_published": "2013", "latest_published": "2014", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Flourishing", "slug": "Love-2-0"},
    {"title": "Learned Optimism: How to Change Your Mind and Your Life", "author": "Martin E.P. Seligman", "first_published": "1990", "latest_published": "2006", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Flourishing", "slug": "Learned-Optimism"},

    # LEVEL 3: LIFE DESIGN (5 books)
    # LEVEL 4: Designing a Life (5 books)
    {"title": "Designing Your Life: How to Build a Well-Lived, Joyful Life", "author": "Bill Burnett; Dave Evans", "first_published": "2016", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Designing a Life", "slug": "Designing-Your-Life"},
    {"title": "Designing Your Work Life: How to Thrive and Change and Find Happiness at Work", "author": "Bill Burnett; Dave Evans", "first_published": "2020", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Designing a Life", "slug": "Designing-Your-Work-Life"},
    {"title": "Essentialism: The Disciplined Pursuit of Less", "author": "Greg McKeown", "first_published": "2014", "latest_published": "2020", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Designing a Life", "slug": "Essentialism"},
    {"title": "Effortless: Make It Easier to Do What Matters Most", "author": "Greg McKeown", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Designing a Life", "slug": "Effortless"},
    {"title": "The 4-Hour Workweek: Escape 9-5, Live Anywhere, and Join the New Rich", "author": "Timothy Ferriss", "first_published": "2007", "latest_published": "2009", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Designing a Life", "slug": "The-4-Hour-Workweek"},

    # -------------------------------------------------------------------------
    # LEVEL 2: 04. PRACTICAL LIFE SKILLS (30 books)
    # -------------------------------------------------------------------------
    # LEVEL 3: CAREER NAVIGATION (10 books)
    # LEVEL 4: Career Strategy (5 books)
    {"title": "What Color Is Your Parachute? 2023: Your Guide to a Lifetime of Meaningful Work and Career Success", "author": "Richard N. Bolles", "first_published": "1970", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Career Strategy", "slug": "What-Color-Is-Your-Parachute"},
    {"title": "The Start-up of You: Adapt to the Future, Invest in Yourself, and Transform Your Career", "author": "Reid Hoffman; Ben Casnocha", "first_published": "2012", "latest_published": "2022", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Career Strategy", "slug": "The-Start-up-of-You"},
    {"title": "The Alliance: Managing Talent in the Networked Age", "author": "Reid Hoffman; Casnocha; Chris Yeh", "first_published": "2014", "latest_published": "2014", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Career Strategy", "slug": "The-Alliance"},
    {"title": "Pivot: The Only Move That Matters Is Your Next One", "author": "Jenny Blake", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Career Strategy", "slug": "Pivot-Blake"},
    {"title": "Do Over: Rescue Monday, Reinvent Your Work, and Never Get Stuck", "author": "Jon Acuff", "first_published": "2015", "latest_published": "2015", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Career Strategy", "slug": "Do-Over-Acuff"},

    # LEVEL 4: Professional Growth (5 books)
    {"title": "How to Be a Star at Work: 9 Breakthrough Strategies You Need to Succeed", "author": "Robert E. Kelley", "first_published": "1998", "latest_published": "1999", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Professional Growth", "slug": "How-to-Be-a-Star-at-Work"},
    {"title": "The Unspoken Rules: Secrets to Starting Your Career Off Right", "author": "Gorick Ng", "first_published": "2021", "latest_published": "2021", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Professional Growth", "slug": "The-Unspoken-Rules"},
    {"title": "What Got You Here Won't Get You There: How Successful People Become Even More Successful", "author": "Marshall Goldsmith; Mark Reiter", "first_published": "2007", "latest_published": "2014", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Professional Growth", "slug": "What-Got-You-Here-Wont-Get-You-There"},
    {"title": "The First 90 Days: Proven Strategies for Getting Up to Speed Faster and Smarter", "author": "Michael D. Watkins", "first_published": "2003", "latest_published": "2013", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Professional Growth", "slug": "The-First-90-Days"},
    {"title": "Your Next Five Moves: Master the Art of Business Strategy", "author": "Patrick Bet-David; Greg Dinkin", "first_published": "2020", "latest_published": "2020", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Professional Growth", "slug": "Your-Next-Five-Moves"},

    # LEVEL 3: LIFE DECISIONS (10 books)
    # LEVEL 4: Major Life Choices (5 books)
    {"title": "Life Is in the Transitions: Mastering Change at Any Age", "author": "Bruce Feiler", "first_published": "2020", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Major Life Choices", "slug": "Life-Is-in-the-Transitions-Feiler"},
    {"title": "The Defining Decade: Why Your Twenties Matter—And How to Make the Most of Them Now", "author": "Meg Jay", "first_published": "2012", "latest_published": "2021", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Major Life Choices", "slug": "The-Defining-Decade"},
    {"title": "How Will You Measure Your Life?", "author": "Clayton M. Christensen; James Allworth; Karen Dillon", "first_published": "2012", "latest_published": "2012", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Major Life Choices", "slug": "How-Will-You-Measure-Your-Life"},
    {"title": "The Dip: A Little Book That Teaches You When to Quit (and When to Stick)", "author": "Seth Godin", "first_published": "2007", "latest_published": "2007", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Major Life Choices", "slug": "The-Dip"},
    {"title": "The Top Five Regrets of the Dying: A Life Transformed by the Dearly Departing", "author": "Bronnie Ware", "first_published": "2011", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Major Life Choices", "slug": "The-Top-Five-Regrets-of-the-Dying"},

    # LEVEL 4: Personal Risk Management (5 books)
    {"title": "Skin in the Game: Hidden Asymmetries in Daily Life", "author": "Nassim Nicholas Taleb", "first_published": "2018", "latest_published": "2019", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Risk Management", "slug": "Skin-in-the-Game"},
    {"title": "Fooled by Randomness: The Hidden Role of Chance in Life and in the Markets", "author": "Nassim Nicholas Taleb", "first_published": "2001", "latest_published": "2005", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Risk Management", "slug": "Fooled-by-Randomness"},
    {"title": "The Black Swan: The Impact of the Highly Improbable", "author": "Nassim Nicholas Taleb", "first_published": "2007", "latest_published": "2010", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Risk Management", "slug": "The-Black-Swan"},
    {"title": "The Bed of Procrustes: Philosophical and Practical Aphorisms", "author": "Nassim Nicholas Taleb", "first_published": "2010", "latest_published": "2016", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Risk Management", "slug": "The-Bed-of-Procrustes-Taleb"},
    {"title": "Against the Gods: The Remarkable Story of Risk", "author": "Peter L. Bernstein", "first_published": "1996", "latest_published": "1998", "priority": "P0", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Risk Management", "slug": "Against-the-Gods"},

    # LEVEL 3: LONG-TERM PLANNING (10 books)
    # LEVEL 4: Personal Organization (5 books)
    {"title": "Organizing from the Inside Out: The Foolproof System For Organizing Your Home, Your Office and Your Life", "author": "Julie Morgenstern", "first_published": "1998", "latest_published": "2004", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Organization", "slug": "Organizing-from-the-Inside-Out"},
    {"title": "Time Management from the Inside Out: The Foolproof System for Taking Control of Your Schedule—and Your Life", "author": "Julie Morgenstern", "first_published": "2000", "latest_published": "2004", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Organization", "slug": "Time-Management-from-the-Inside-Out"},
    {"title": "Never Check Email In the Morning: And Other Unexpected Strategies for Making Your Work Life Work", "author": "Julie Morgenstern", "first_published": "2004", "latest_published": "2005", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Organization", "slug": "Never-Check-Email-In-the-Morning"},
    {"title": "Decluttering at the Speed of Life: Winning Your Never-Ending Battle with Stuff", "author": "Dana K. White", "first_published": "2018", "latest_published": "2018", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Organization", "slug": "Decluttering-at-the-Speed-of-Life"},
    {"title": "Remodel Your Life", "author": "Bruce Feiler", "first_published": "2020", "latest_published": "2020", "priority": "P2", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Personal Organization", "slug": "Remodel-Your-Life"},

    # LEVEL 4: Long-Term Planning (5 books)
    {"title": "The Council of Dads: My Daughters, My Illness, and the Men Who Could Be Me", "author": "Bruce Feiler", "first_published": "2010", "latest_published": "2011", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Planning", "slug": "The-Council-of-Dads-Feiler"},
    {"title": "The Secrets of Happy Families: Improve Your Mornings, Rethink Family Dinner, Fight Smarter, Go Out and Play, and Much More", "author": "Bruce Feiler", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Planning", "slug": "The-Secrets-of-Happy-Families"},
    {"title": "Living Forward: A Proven Plan to Stop Drifting and Get the Life You Want", "author": "Michael Hyatt; Daniel Harkavy", "first_published": "2016", "latest_published": "2016", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Planning", "slug": "Living-Forward"},
    {"title": "Your Best Year Ever: A 5-Step Plan for Achieving Your Most Important Goals", "author": "Michael Hyatt", "first_published": "2018", "latest_published": "2018", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Planning", "slug": "Your-Best-Year-Ever"},
    {"title": "The 12 Week Year: Get More Done in 12 Weeks than Others Do in 12 Months", "author": "Brian P. Moran; Michael Lennington", "first_published": "2013", "latest_published": "2013", "priority": "P1", "type": "nonfiction", "reading_mode": "summary", "summary_depth": "detailed", "topic": "Long-Term Planning", "slug": "The-12-Week-Year"},
]
