from __future__ import annotations

import csv
import functools
import re
from pathlib import Path

from .config import ROOT
from .taxonomy import PILLAR_DIRS

# All book notes live under the md/ folder at the repository root.
MD_ROOT = "md"


def _pillar_dirs() -> dict[str, str]:
    """Pillar display name -> md folder, generated by curriculum.py."""
    return {name: f"md/{folder}" for name, folder in PILLAR_DIRS.items()}


# Columns that must always be present and non-empty. Fields the generator
# fills in from research (published year, learning_stage, prerequisites,
# primary_source) are allowed to be blank in a planned row.
REQUIRED_COLUMNS = {
    "number",
    "priority",
    "title",
    "author",
    "pillar",
    "category",
    "subcategory",
    "slug",
    "difficulty",
    "status",
    "path",
}
ALLOWED_BLANK = {"published", "learning_stage", "prerequisites", "primary_source"}


class ManifestError(ValueError):
    """Raised when the canonical manifest is invalid."""


@functools.lru_cache(maxsize=1)
def _taxonomy() -> dict[str, list[str]]:
    taxonomy: dict[str, list[str]] = {}
    manifest_path = ROOT / "automation" / "manifest.csv"
    if not manifest_path.exists():
        return {}
    with manifest_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            p = row.get("pillar", "").strip()
            c = row.get("category", "").strip()
            if p and c:
                if p not in taxonomy:
                    taxonomy[p] = []
                if c not in taxonomy[p]:
                    taxonomy[p].append(c)
    return taxonomy


@functools.lru_cache(maxsize=1)
def _manifest_category_folders() -> dict[tuple[str, str], str]:
    cat_folders: dict[tuple[str, str], str] = {}
    manifest_path = ROOT / "automation" / "manifest.csv"
    if not manifest_path.exists():
        return {}
    with manifest_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            p = row.get("pillar", "").strip()
            c = row.get("category", "").strip()
            if p and c and (p, c) not in cat_folders:
                parts = row.get("path", "").replace("\\", "/").split("/")
                if len(parts) >= 3:
                    cat_folders[(p, c)] = parts[2]
    return cat_folders


def category_folder(pillar: str, category: str) -> str:
    """Level-2 category folder name inside a pillar folder."""
    cached = _manifest_category_folders().get((pillar, category))
    if cached:
        return cached
    return re.sub(r"[^A-Za-z0-9]+", "-", category).strip("-")


def load_manifest(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise ManifestError(f"Manifest is empty: {path}")
    missing = REQUIRED_COLUMNS - set(rows[0])
    if missing:
        raise ManifestError(f"Manifest is missing columns: {', '.join(sorted(missing))}")

    seen_slugs: set[str] = set()
    seen_keys: set[tuple[str, str]] = set()
    pillar_dirs = _pillar_dirs()
    tax = _taxonomy()

    for row in rows:
        for column in REQUIRED_COLUMNS:
            if not row.get(column, "").strip():
                raise ManifestError(f"Manifest row has empty {column}: {row}")
        slug = row["slug"].strip()
        key = (row["title"].strip().casefold(), row["author"].strip().casefold())
        if slug in seen_slugs:
            raise ManifestError(f"Duplicate slug in manifest: {slug}")
        if key in seen_keys:
            raise ManifestError(f"Duplicate title/author in manifest: {row['title']} / {row['author']}")
        allowed_categories = tax.get(row["pillar"], [])
        if row["category"] not in allowed_categories:
            raise ManifestError(
                f"Invalid category '{row['category']}' for pillar '{row['pillar']}'."
            )
        expected_path = "/".join(
            [
                pillar_dirs.get(row["pillar"], ""),
                category_folder(row["pillar"], row["category"]),
                f"{row['slug']}.md",
            ]
        )
        if row["path"].replace("\\", "/") != expected_path:
            raise ManifestError(f"Manifest path mismatch for {row['title']}: expected {expected_path}")
        seen_slugs.add(slug)
        seen_keys.add(key)
    return [{key: value.strip() for key, value in row.items()} for row in rows]
