from __future__ import annotations

# Generated by automation/curriculum/build_curriculum_2000.py
"""Domain folder mappings derived from the 2,000-book canonical curriculum."""

DOMAINS_13 = {
    "01": ("01-Learning-Thinking-and-Knowledge", "Learning, Thinking & Knowledge"),
    "02": ("02-Communication-Writing-and-Social-Intelligence", "Communication, Writing & Social Intelligence"),
    "03": ("03-Psychology-and-Human-Behavior", "Psychology & Human Behavior"),
    "04": ("04-Personal-Development-and-Life-Skills", "Personal Development & Life Skills"),
    "05": ("05-Finance-Investing-and-Wealth", "Finance, Investing & Wealth"),
    "06": ("06-Economics-Business-and-Entrepreneurship", "Economics, Business & Entrepreneurship"),
    "07": ("07-Computer-Science-and-Technology-Concepts", "Computer Science & Technology Concepts"),
    "08": ("08-Artificial-Intelligence-and-Future-Technology", "Artificial Intelligence & Future Technology"),
    "09": ("09-Philosophy-Ethics-and-Decision-Making", "Philosophy, Ethics & Decision-Making"),
    "10": ("10-History-Civilization-and-Geopolitics", "History, Civilization & Geopolitics"),
    "11": ("11-Science-Nature-and-the-Universe", "Science, Nature & the Universe"),
    "12": ("12-Society-Politics-Law-and-Public-Policy", "Society, Politics, Law & Public Policy"),
    "13": ("13-Biography-Memoir-and-Lives", "Biography, Memoir & Lives"),
}

DOMAIN_DIRS = {display: folder for code, (folder, display) in DOMAINS_13.items()}
# Backwards-compatible alias for existing code
PILLAR_DIRS = DOMAIN_DIRS
