# Generated by automation/curriculum.py — do not hand-edit; re-run the builder.
"""Pillar folder mappings derived from the canonical curriculum."""

PILLAR_DIRS = {
    "Learning, Cognition & Meta-Skills": "01-Learning-Cognition-and-Meta-Skills",
    "Thinking, Rationality & Mental Models": "02-Thinking-Rationality-and-Mental-Models",
    "Psychology, Behavior & Neuroscience": "03-Psychology-Behavior-and-Neuroscience",
    "Mathematics, Statistics & Quantitative Logic": "04-Mathematics-Statistics-and-Quantitative-Logic",
    "Computer Science & Software Engineering": "05-Computer-Science-and-Software-Engineering",
    "Artificial Intelligence & Data Systems": "06-Artificial-Intelligence-and-Data-Systems",
    "Economics, Markets & Investing": "07-Economics-Markets-and-Investing",
    "Business, Strategy & Enterprise": "08-Business-Strategy-and-Enterprise",
    "Leadership, Organizations & Management": "09-Leadership-Organizations-and-Management",
    "Natural Sciences, Health & Biology": "10-Natural-Sciences-Health-and-Biology",
    "History, Geopolitics & Civilization": "11-History-Geopolitics-and-Civilization",
    "Philosophy, Ethics & Human Society": "12-Philosophy-Ethics-and-Human-Society",
}

